import { Lesson } from '../models/lesson.model';

export const BROWSER_LESSONS: Lesson[] = [
  {
    id: 960, slug: 'browser-rendering', title: 'Browser Rendering Pipeline',
    description: 'Understand how browsers render pages — from HTML parsing to painting pixels, and how to optimize each stage.',
    level: 'intermediate', duration: '45 min',
    objectives: ['Explain the browser rendering pipeline stages', 'Identify what triggers layout, paint, and composite', 'Minimize forced reflows and repaints', 'Optimize animations for GPU compositing'],
    quiz: [
      { id: 1, question: 'What is the correct order of the rendering pipeline?', options: ['Parse > Paint > Layout > Composite', 'Parse > Style > Layout > Paint > Composite', 'Style > Parse > Layout > Composite > Paint', 'Layout > Parse > Style > Paint > Composite'], correctIndex: 1, explanation: 'The browser pipeline: HTML parsing > Style calculation > Layout (geometry) > Paint (pixels) > Composite (layers).' },
      { id: 2, question: 'Which CSS property triggers a layout recalculation?', options: ['color', 'transform', 'width', 'opacity'], correctIndex: 2, explanation: 'Changing width triggers layout because it affects element geometry. Color, transform, and opacity only trigger paint or composite.' },
      { id: 3, question: 'What is compositing?', options: ['Combining multiple CSS files', 'Combining multiple pages', 'Drawing multiple layers into the final screen output', 'Merging JavaScript bundles'], correctIndex: 2, explanation: 'Compositing is the final step where the browser draws all painted layers onto the screen in the correct order.' }
    ],
    topics: [
      {
        id: 'pipeline-overview', title: 'Rendering Pipeline Overview',
        content: 'The browser rendering pipeline transforms HTML, CSS, and JavaScript into pixels on screen through several sequential stages. First, HTML parsing builds the DOM (Document Object Model) tree by tokenizing and constructing nodes. Simultaneously, CSS parsing builds the CSSOM (CSS Object Model) tree from stylesheets. These two trees merge into the Render Tree, which includes only visible elements (excludes display:none, head elements, and elements outside the viewport). The Layout stage (also called Reflow) calculates the exact position and size of every element in the render tree using box model rules. Paint fills in pixels — text colors, borders, shadows, gradients — creating one or more layers. Finally, Composite arranges all layers in the correct z-order and draws them to screen using the GPU. Each stage can be triggered by different operations: DOM manipulation triggers parsing, CSS changes trigger style recalculation, geometry changes trigger layout, appearance changes trigger paint, and only transform/opacity changes skip straight to composite.'
      },
      {
        id: 'reflow-repaint', title: 'Reflow and Repaint',
        content: 'Reflow (layout) is the most expensive rendering step. It recalculates positions and sizes for all or part of the render tree. Triggers include: changing width, height, margin, padding, border-width, position, display, font-size, or text-align; adding or removing DOM elements; reading geometry properties like offsetWidth, offsetHeight, getBoundingClientRect(), or getComputedStyle(). Repaint (paint) is cheaper — it redraws pixels for visual changes. Triggers include: changing color, background-color, box-shadow, text-shadow, visibility, or opacity. Composite (cheapest) only happens with transform and opacity changes. Batching DOM reads and writes minimizes reflows: read all needed geometry values first, then write all style changes. Never read geometry properties immediately after writing styles — this forces a synchronous reflow. The browser batches reflows when possible — multiple style changes in a single JavaScript execution context trigger only one reflow at the end.'
      },
      {
        id: 'gpu-compositing', title: 'GPU Compositing and Layers',
        content: 'GPU compositing promotes elements to separate layers that are composited on the GPU instead of the CPU, dramatically improving animation performance. Promote elements to layers with will-change: transform or transform: translateZ(0) / will-change: opacity. The browser creates layers for elements with 3D transforms, video, canvas, opacity transitions, and elements with will-change. Each layer consumes GPU memory — excessive layer promotion wastes resources. Use Chrome DevTools Layers panel to inspect layer count and size. Animations using transform (translate, rotate, scale) and opacity are GPU-composited and run at 60fps without triggering layout or paint. Avoid animating with top, left, width, or height — these trigger expensive reflows. will-change should be added before animation starts and removed after it ends. The browser automatically removes compositing layers when they are no longer needed. Maximum recommended layers: keep under 1000 for smooth performance on mobile devices.'
      },
      {
        id: 'critical-rendering-path', title: 'Critical Rendering Path',
        content: 'The Critical Rendering Path (CRP) is the sequence of steps to render the initial viewport content. Optimizing the CRP delivers faster First Contentful Paint (FCP) and Largest Contentful Paint (LCP). Inline critical CSS — the styles needed for above-the-fold content — directly in the HTML <style> tag. Defer non-critical CSS with <link rel="preload" href="full.css" as="style" onload="this.rel=\'stylesheet\'">. Use defer for non-critical JavaScript (executes after HTML parsing) and async for independent scripts (executes as soon as downloaded). Resource hints optimize resource loading: preconnect establishes early connections to important origins, dns-prefetch resolves DNS early, preload fetches critical resources immediately, prefetch fetches resources for next navigation. Render-blocking resources (CSS in <head>, synchronous scripts) delay rendering — minimize them. Server-Side Rendering (SSR) with Angular Universal sends pre-rendered HTML, reducing CRP time. Dynamic imports and lazy loading split the CRP into multiple paths — one per route.'
      }
    ]
  },
  {
    id: 961, slug: 'browser-event-loop', title: 'Event Loop Deep Dive',
    description: 'Understand the JavaScript event loop — call stack, Web APIs, callback queues, and microtask vs macrotask execution.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Explain how the event loop processes different task types', 'Distinguish between microtasks and macrotasks', 'Predict the execution order of async operations', 'Use queueMicrotask and requestAnimationFrame effectively'],
    quiz: [
      { id: 1, question: 'What is the difference between microtasks and macrotasks?', options: ['Microtasks run first, then macrotasks', 'Macrotasks run first, then microtasks', 'They run in parallel', 'They are identical'], correctIndex: 0, explanation: 'After each macrotask, all microtasks in the microtask queue are processed before the next macrotask. Microtasks have higher priority.' },
      { id: 2, question: 'Which of these is a macrotask?', options: ['Promise.then callback', 'queueMicrotask callback', 'setTimeout callback', 'MutationObserver callback'], correctIndex: 2, explanation: 'setTimeout, setInterval, I/O, and UI rendering are macrotasks. Promise.then, queueMicrotask, and MutationObserver are microtasks.' },
      { id: 3, question: 'What is the output order of: console.log("1"), setTimeout(() => console.log("2")), Promise.resolve().then(() => console.log("3"))?', options: ['1, 2, 3', '1, 3, 2', '3, 2, 1', '2, 1, 3'], correctIndex: 1, explanation: 'Synchronous code runs first (1), then microtasks (3), then macrotasks (2). Promise.then is a microtask, setTimeout is a macrotask.' }
    ],
    topics: [
      {
        id: 'call-stack', title: 'Call Stack',
        content: 'The call stack is a LIFO (Last In, First Out) data structure that tracks function execution. When a function is called, a new frame is pushed onto the stack. When it returns, the frame is popped. JavaScript is single-threaded — only one function executes at a time. The call stack has a maximum size (varies by browser, typically 10,000-25,000 frames). Stack overflow occurs with excessive recursion: function recurse() { recurse(); } — this throws "Maximum call stack size exceeded". The call stack is visualized in Chrome DevTools Sources panel. Long-running functions block the stack and freeze the UI — break them into smaller chunks using setTimeout or requestIdleCallback. The call stack is synchronous — async callbacks (Promises, setTimeout) are handled by the Web API environment and placed in the task queue, not on the stack.'
      },
      {
        id: 'web-apis', title: 'Web APIs',
        content: 'Web APIs are browser-provided interfaces that run outside the JavaScript engine. They are not part of the ECMAScript specification — they are defined by the Web platform. Common Web APIs: setTimeout/setInterval (timer), fetch (HTTP requests), DOM manipulation (addEventListener, querySelector), IntersectionObserver, MutationObserver, Web Workers, localStorage, and IndexedDB. When you call fetch(), the browser creates a network request on a separate thread, suspends the JavaScript execution, and resumes when the response arrives. The Web API environment manages the callback — when the timer expires or the fetch completes, the callback is placed in the appropriate task queue (macrotask for setTimeout/fetch, microtask for Promise). Web APIs do not block the call stack — they run on separate browser threads (network, timer, rendering). This is why async operations do not freeze the UI while waiting for network responses or timer callbacks.'
      },
      {
        id: 'task-queues', title: 'Callback Queues',
        content: 'Two task queues manage async callback execution: the macrotask queue and the microtask queue. Macrotasks include: setTimeout, setInterval, I/O callbacks, UI rendering, requestAnimationFrame. Microtasks include: Promise.then/catch/finally, queueMicrotask, MutationObserver. The event loop processes one macrotask at a time from the macrotask queue, then drains all microtasks from the microtask queue before processing the next macrotask. This means microtasks always execute before the next macrotask. requestAnimationFrame is neither — it runs before the browser paints, between macrotasks and rendering. Execution order: synchronous code > all microtasks > requestAnimationFrame > macrotask > paint. Multiple setTimeout(0) callbacks do not all execute before rendering — each is a separate macrotask processed one at a time. queueMicrotask(() => {}) schedules a microtask that runs before the next macrotask. This guarantees execution order: Promise.resolve().then() and queueMicrotask() run in the order they were queued.'
      },
      {
        id: 'micro-macro', title: 'Microtask vs Macrotask',
        content: 'The microtask queue has absolute priority over the macrotask queue. After each macrotask completes, the event loop processes ALL microtasks before picking the next macrotask. This can starve macrotasks if microtasks generate more microtasks infinitely. Example: Promise.resolve().then(function self() { Promise.resolve().then(self); }) creates an infinite microtask loop that blocks macrotasks and UI rendering. Promise callbacks are microtasks: fetch().then(callback) — the callback runs as a microtask. async/await creates microtasks: await expression pauses the function and resumes it as a microtask. setTimeout and setInterval are macrotasks — their callbacks wait for all microtasks to complete. MutationObserver callbacks are microtasks, making DOM observations synchronous with the microtask checkpoint. In Angular, zone.js patches async APIs to trigger change detection. Understanding the event loop helps predict change detection timing — microtasks complete before Angular checks for changes, while macrotasks may trigger change detection separately.'
      }
    ]
  },
  {
    id: 962, slug: 'browser-storage', title: 'Browser Storage',
    description: 'Explore browser storage mechanisms — localStorage, sessionStorage, IndexedDB, Cache API, and cookies.',
    level: 'beginner', duration: '35 min',
    objectives: ['Compare different browser storage mechanisms', 'Use localStorage and sessionStorage appropriately', 'Implement IndexedDB for structured data storage', 'Choose the right storage for different use cases'],
    quiz: [
      { id: 1, question: 'What is the main difference between localStorage and sessionStorage?', options: ['localStorage is faster', 'localStorage persists across sessions, sessionStorage is per-tab', 'localStorage has more capacity', 'sessionStorage is encrypted'], correctIndex: 1, explanation: 'localStorage persists data until explicitly cleared. sessionStorage is scoped to the current browser tab and cleared when the tab closes.' },
      { id: 2, question: 'Which storage option is best for storing large structured datasets?', options: ['localStorage', 'Cookies', 'IndexedDB', 'Session storage'], correctIndex: 2, explanation: 'IndexedDB supports large datasets (hundreds of MB), structured data with indexes, and transactions — ideal for complex client-side storage.' },
      { id: 3, question: 'What is the storage limit for localStorage?', options: ['No limit', '5MB per origin', '100KB per domain', '64KB total'], correctIndex: 1, explanation: 'localStorage has a ~5MB limit per origin (protocol + domain + port). This limit varies slightly between browsers but is typically 5-10MB.' }
    ],
    topics: [
      {
        id: 'local-session', title: 'localStorage and sessionStorage',
        content: 'localStorage and sessionStorage provide key-value string storage with the Web Storage API. localStorage persists data across browser sessions — it survives tab closures, browser restarts, and page reloads. sessionStorage is scoped to the current tab — data is cleared when the tab closes. Both share the same API: getItem(key), setItem(key, value), removeItem(key), clear(), key(index). Data is stored as strings — use JSON.stringify() and JSON.parse() for objects. Both are synchronous and block the main thread. Limit: ~5MB per origin (protocol + domain + port). Data is shared across same-origin tabs — changes in one tab trigger Storage events in others (localStorage only). Never store sensitive data (tokens, passwords) — storage is accessible to any JavaScript on the page. Angular patterns: create a StorageService that abstracts the API, handles JSON serialization, and provides type safety: getItem<T>(key: string): T | null. Use for user preferences, UI state, and non-sensitive cache data.'
      },
      {
        id: 'indexeddb', title: 'IndexedDB',
        content: 'IndexedDB is a transactional, asynchronous database for large structured data. It supports storing objects, arrays, Blobs, and any structured-clonable data. Schema is defined through object stores (tables) with indexes for efficient querying. Opening a database: const request = indexedDB.open("MyDB", 1); request.onupgradeneeded defines the schema. Transaction modes: readonly (default), readwrite, and versionchange. Object stores support put (insert/update), get (by key), delete, getAll, and cursor-based iteration. Indexes enable efficient queries: store.createIndex("email", "email", { unique: true }). IndexedDB is asynchronous and event-driven — no async/await without a Promise wrapper. Libraries like idb (by Jake Archibald) provide a Promise-based API. Angular patterns: create an IndexedDBService using the idb library for type-safe operations. Capacity: much larger than localStorage (hundreds of MB to GB, varies by browser). Use IndexedDB for offline data, large caches, and complex queries. Chrome DevTools Application panel provides IndexedDB inspection and editing.'
      },
      {
        id: 'cache-api', title: 'Cache API',
        content: 'The Cache API stores Request/Response pairs, primarily used by service workers for offline caching. Unlike other storage APIs, Cache stores entire HTTP responses including headers and body. Cache instances are named: await caches.open("my-cache-v1"). Store responses: cache.put(request, response). Retrieve: const response = await cache.match(request). The Cache API is asynchronous and Promise-based. Common patterns: cache-first (serve from cache, fallback to network), network-first (try network, fallback to cache), stale-while-revalidate (serve cache, update in background). Cache storage is separate from browser cache — you have full control over what is cached and when. Angular Service Workers use the Cache API internally for PWA caching strategies defined in ngsw-config.json. Cache names should be versioned (v1, v2) — old caches are cleaned up in the service worker activate event. Cache storage is queryable: caches.keys() returns all cache names, cache.keys() returns all stored requests. Storage limits are generous but vary by browser — typically at least 50MB, often much more.'
      },
      {
        id: 'cookies', title: 'Cookies',
        content: 'Cookies are small text data stored by the browser and sent with every HTTP request to the domain that set them. They serve multiple purposes: session management (session IDs), personalization (preferences), and tracking (analytics). Cookie attributes control behavior: expires/max-age sets lifetime, path limits scope, domain extends scope to subdomains, secure requires HTTPS, HttpOnly prevents JavaScript access (document.cookie), and SameSite controls cross-site behavior (Strict, Lax, None). SameSite=Strict prevents sending cookies with cross-site requests (most secure but breaks legitimate cross-site navigation). SameSite=Lax allows cookies with top-level navigation (GET requests from other sites). SameSite=None requires Secure — allows cross-site requests for embedded content. Size limit: ~4KB per cookie, ~50 cookies per domain. In Angular, HttpOnly cookies are automatically sent with HttpClient requests when withCredentials: true is set. Cookies are the only storage mechanism that survives all navigation types and is sent automatically — this makes them essential for authentication but also vulnerable to CSRF attacks.'
      }
    ]
  },
  {
    id: 963, slug: 'browser-dom', title: 'DOM Manipulation',
    description: 'Master DOM manipulation — traversal, MutationObserver, virtual DOM concepts, and DOM performance optimization.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Efficiently traverse and query the DOM', 'Use MutationObserver to watch for DOM changes', 'Understand virtual DOM concepts and their benefits', 'Optimize DOM operations for performance'],
    quiz: [
      { id: 1, question: 'Which query method is fastest for finding elements by class?', options: ['document.getElementsByClassName()', 'document.querySelector()', 'document.querySelectorAll()', 'For loop with className check'], correctIndex: 0, explanation: 'getElementsByClassName returns a live HTMLCollection and is faster than querySelectorAll because it does not need to parse a CSS selector.' },
      { id: 2, question: 'What is MutationObserver used for?', options: ['Observing network requests', 'Watching for DOM changes in real-time', 'Monitoring memory usage', 'Tracking user interactions'], correctIndex: 1, explanation: 'MutationObserver watches for DOM tree changes — added/removed nodes, attribute changes, and text content modifications.' },
      { id: 3, question: 'What is the main performance benefit of virtual DOM?', options: ['Eliminates all DOM manipulation', 'Reduces unnecessary DOM updates through diffing', 'Makes DOM queries faster', 'Increases DOM element count'], correctIndex: 1, explanation: 'Virtual DOM diffs the current and new state, then applies only the minimal necessary changes to the real DOM.' }
    ],
    topics: [
      {
        id: 'dom-traversal', title: 'DOM Traversal',
        content: 'DOM traversal navigates the tree structure of elements. Parent traversal: element.parentElement (closest Element parent), element.parentNode (any node type). Child traversal: element.children (Element children only), element.childNodes (all node types including text), element.firstElementChild, element.lastElementChild. Sibling traversal: element.nextElementSibling, element.previousElementSibling. Query methods: getElementById (fastest, single element), getElementsByClassName (live HTMLCollection), getElementsByTagName (live HTMLCollection), querySelector (first match, CSS selector), querySelectorAll (all matches, static NodeList). querySelector is flexible but slower for large DOMs because it parses CSS selectors. For performance-critical code, prefer element-specific methods. TreeWalker and NodeIterator provide efficient traversal of large DOM subtrees. Angular handles DOM manipulation internally through its change detection and rendering engine — direct DOM manipulation in Angular should be minimal, using ElementRef only when necessary and preferably through renderer2 for cross-platform compatibility.'
      },
      {
        id: 'mutation-observer', title: 'MutationObserver',
        content: 'MutationObserver watches for DOM tree changes asynchronously. Create an observer: const observer = new MutationObserver(callback). Observe a target: observer.observe(target, { childList: true, attributes: true, characterData: true, subtree: true, attributeOldValue: true }). The callback receives an array of MutationRecord objects describing each change. MutationRecord properties: type (childList, attributes, characterData), target (affected node), addedNodes/removedNodes, attributeName, oldValue. Disconnect to stop observing: observer.disconnect(). MutationObserver is batched — multiple rapid changes produce one callback with multiple records, not one callback per change. It runs as a microtask, ensuring DOM consistency. Use cases: detecting dynamic content changes, implementing reactive components, monitoring attribute changes for custom elements, lazy loading content, and infinite scroll detection. In Angular, zone.js uses MutationObserver internally to trigger change detection when the DOM changes. Never use MutationObserver for simple event handling — use addEventListener for click, input, and other user events.'
      },
      {
        id: 'virtual-dom', title: 'Virtual DOM Concepts',
        content: 'Virtual DOM is a lightweight JavaScript representation of the real DOM. Instead of directly manipulating the DOM (expensive), you create a virtual tree, diff it against the previous virtual tree, and apply only the minimal changes to the real DOM. The process: render the new state into a virtual tree (JavaScript objects), diff the new tree against the previous tree to find changes, and patch the real DOM with the minimal set of operations. React popularized this approach with its reconciliation algorithm — it uses heuristics (component type, key prop) to minimize diffing complexity from O(n^3) to O(n). Angular uses incremental DOM (Ivy) — it does not create a full virtual tree but tracks dynamic parts of templates and updates only what changed. Benefits: declarative UI (describe what the UI should look like), efficient updates (minimal DOM operations), and cross-platform (virtual tree can be rendered to DOM, server, or native). Overhead: creating virtual objects has cost — for very simple updates, direct DOM manipulation may be faster. Virtual DOM is best for complex, frequently-updating UIs.'
      },
      {
        id: 'dom-performance', title: 'DOM Performance',
        content: 'DOM operations are expensive — minimize them. Batch DOM reads and writes: read all needed properties first, then write all changes. Never read a layout property (offsetWidth, getBoundingClientRect) after writing styles — this forces a synchronous reflow. Use DocumentFragment to batch DOM insertions: const fragment = document.createDocumentFragment(); add elements to fragment; container.appendChild(fragment) — one reflow instead of N. Use CSS class toggling instead of individual style changes: element.classList.toggle("active") instead of element.style.display = "block". Use requestAnimationFrame for visual updates — it ensures the browser has completed layout and paint before your callback runs. Virtual scrolling (windowing) renders only visible items — libraries like @angular/cdk/virtual-scroll-viewport handle this. Debounce rapid DOM updates (typing, resizing) to avoid excessive reflows. Avoid layout thrashing — reading and writing layout properties in a loop. Chrome DevTools Performance panel identifies layout thrashing with "Forced synchronous layout" warnings.'
      }
    ]
  },
  {
    id: 964, slug: 'browser-devtools', title: 'Browser DevTools Mastery',
    description: 'Master Chrome DevTools — Elements, Network, Performance, and Memory panels for debugging and optimization.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Navigate and use the Elements panel for DOM debugging', 'Analyze network requests with the Network panel', 'Profile application performance with the Performance panel', 'Identify memory leaks with the Memory profiler'],
    quiz: [
      { id: 1, question: 'Which DevTools panel shows the waterfall of network requests?', options: ['Elements panel', 'Network panel', 'Performance panel', 'Sources panel'], correctIndex: 1, explanation: 'The Network panel shows all network requests with timing, headers, response data, and a waterfall visualization.' },
      { id: 2, question: 'What does the Performance panel record?', options: ['Network requests only', 'CPU, memory, and rendering performance during a recorded session', 'JavaScript errors only', 'DOM element count'], correctIndex: 1, explanation: 'The Performance panel records CPU usage, rendering, painting, compositing, and JavaScript execution over time.' },
      { id: 3, question: 'How do you detect memory leaks in DevTools?', options: ['Check the Console tab', 'Take heap snapshots and compare them over time', 'Use the Network panel', 'Check the Elements panel'], correctIndex: 1, explanation: 'Take heap snapshots in the Memory panel, perform actions, take another snapshot, and compare — objects that grow indicate leaks.' }
    ],
    topics: [
      {
        id: 'elements-panel', title: 'Elements Panel',
        content: 'The Elements panel inspects and modifies the DOM and CSS in real-time. The DOM tree shows all elements with their nesting — click an element to see its properties, computed styles, and event listeners. The Styles pane shows all CSS rules applied to the selected element, including inherited styles and user agent styles. Changes are live — modify any property to see instant visual feedback. The Computed pane shows the final computed values after all CSS cascade, specificity, and inheritance. The box model visualization shows margin, border, padding, and content dimensions. The Event Listeners pane shows all attached event handlers — useful for debugging Angular event bindings. The Properties pane shows JavaScript properties of the DOM element. The Accessibility pane shows the element tree as screen readers see it — essential for a11y debugging. Right-click any element to: Edit as HTML, Copy selector, Force state (:hover, :active), Break on modifications, and more. In Angular, component styles are encapsulated — look for _nghost and _ngcontent attributes to identify Angular components.'
      },
      {
        id: 'network-panel', title: 'Network Panel',
        content: 'The Network panel monitors all HTTP requests made by the page. The waterfall shows request timing: DNS lookup, connection, TLS handshake, request, response, and download. Key columns: Status (HTTP status code), Type (document, script, xhr, fetch), Size (response body size), and Time (total duration). Filter by type: XHR/Fetch for API calls, CSS for stylesheets, JS for scripts, Img for images. Click a request to see Headers (request and response), Preview (formatted response body), Response (raw response), Cookies, and Timing breakdown. Preserve log across navigations to debug redirects. Throttle network to simulate slow connections (Slow 3G, offline). Disable cache to test cold loading performance. The Initiator column shows what triggered each request — hover the waterfall to see the call stack. Search requests by URL, header values, or response content. Export HAR files for sharing performance data. Use the Blocking feature to simulate request blocking for testing error handling. WebSocket connections show a separate Messages tab with real-time data.'
      },
      {
        id: 'performance-panel', title: 'Performance Panel',
        content: 'The Performance panel records runtime performance to identify bottlenecks. Start recording, interact with the page, stop recording — the panel shows a timeline with CPU, Network, and Frames tracks. The Summary tab shows where time was spent: Scripting, Rendering, Painting, System, Idle. The call tree shows function call hierarchy with self-time and total-time. The flame chart visualizes JavaScript execution — wide bars indicate long-running functions. Long tasks (bars > 50ms) indicate jank — look for nested functions that can be broken up. The Main track shows the call stack for each task. The Frames track shows frame rate — dropped frames indicate jank. Use "Screenshots" checkbox to see visual snapshots. Layout/Paint/Composite tracks show rendering performance. Forced synchronous layout warnings indicate layout thrashing. Identify script evaluation time, garbage collection pauses, and long-running event handlers. Angular-specific: look for excessive change detection cycles (ngZone stability events). Use the "Record DevTools Activity" to profile with less overhead. Compare recordings before and after optimizations.'
      },
      {
        id: 'memory-profiler', title: 'Memory Profiler',
        content: 'The Memory panel identifies memory leaks and high memory usage. Heap Snapshots capture the state of JavaScript objects at a point in time. Take a snapshot, perform actions, take another snapshot, and compare — objects that only appear in the later snapshot are potential leaks. The Summary view groups objects by constructor name with count and size. The Comparison view shows differences between two snapshots — objects added (red), removed (blue), or changed. The Containment view shows the object graph starting from GC roots. The Statistics view shows total memory by category. Allocation Timeline records memory allocations over time — spikes indicate heavy allocations. Look for detached DOM elements — they remain in memory if JavaScript holds references. Retainers show why objects are not garbage collected — follow the chain to find the reference keeping them alive. Common Angular leaks: subscriptions not unsubscribed, event listeners not removed, destroyed components still referenced. Force garbage collection (trash icon) before snapshots to get accurate results. Use "Allocation instrumentation on timeline" to see what code allocates the most memory.'
      }
    ]
  },
  {
    id: 965, slug: 'browser-workers', title: 'Web Workers',
    description: 'Use Web Workers for background processing — dedicated workers, shared workers, service workers, and message passing.',
    level: 'advanced', duration: '40 min',
    objectives: ['Create and communicate with dedicated Web Workers', 'Understand shared workers for cross-tab communication', 'Implement service workers for offline functionality', 'Design message passing patterns for worker communication'],
    quiz: [
      { id: 1, question: 'What is the main limitation of Web Workers?', options: ['Cannot access the DOM', 'Cannot make network requests', 'Cannot use JavaScript', 'Cannot communicate with the main thread'], correctIndex: 0, explanation: 'Web Workers run in a separate thread and cannot access the DOM, window, or document objects — they communicate via message passing.' },
      { id: 2, question: 'What is the difference between a dedicated worker and a shared worker?', options: ['Dedicated workers are faster', 'A dedicated worker is used by one page, a shared worker can be accessed by multiple pages', 'Shared workers cannot use network requests', 'Dedicated workers cannot use postMessage'], correctIndex: 1, explanation: 'Dedicated workers are bound to a single page/tab. Shared workers can be accessed by multiple pages/tabs on the same origin.' },
      { id: 3, question: 'What data cannot be sent via postMessage?', options: ['Strings', 'Numbers', 'DOM elements', 'Plain objects'], correctIndex: 2, explanation: 'postMessage uses structured cloning — DOM elements, functions, and Error objects cannot be cloned. Use transferable objects for large binary data.' }
    ],
    topics: [
      {
        id: 'dedicated-workers', title: 'Dedicated Workers',
        content: 'A dedicated worker runs in a background thread with its own global scope (no window, document, or DOM access). Create one: const worker = new Worker("worker.js"). The worker script receives messages with self.onmessage = (e) => { const result = process(e.data); self.postMessage(result); }. Send data: worker.postMessage({ data: largeArray }). Receive results: worker.onmessage = (e) => console.log(e.data). Terminate a worker: worker.terminate() — the thread is killed immediately, no cleanup. Workers support importScripts("lib.js") for loading external scripts synchronously. For ES modules: const worker = new Worker("worker.js", { type: "module" }). Transferable objects (ArrayBuffer, ImageData, etc.) are transferred to the worker without copying — the sender loses access: worker.postMessage(buffer, [buffer]). Structured cloning copies data — use for objects. Error handling: worker.onerror = (e) => console.error(e.message). Angular patterns: create a WorkerService that manages worker lifecycle, provides typed message channels, and handles worker errors. Use workers for CPU-intensive tasks: image processing, data parsing, cryptographic operations, and complex calculations.'
      },
      {
        id: 'shared-workers', title: 'Shared Workers',
        content: 'A shared worker can be accessed by multiple browser tabs, windows, or iframes on the same origin. Unlike dedicated workers, the worker script runs once and serves multiple connections. Create: const shared = new SharedWorker("shared.js"). The worker script listens for connections: self.onconnect = (e) => { const port = e.ports[0]; port.onmessage = handler; port.start(); }. Each connecting page gets its own port for communication. Use cases: cross-tab communication, shared state management, centralized WebSocket connections, and shared caching. BroadcastChannel is a simpler alternative for basic cross-tab messaging: const channel = new BroadcastChannel("my-channel"); channel.postMessage(data); channel.onmessage = handler. Shared workers are not supported in all browsers (not in mobile Safari). For Angular, create a SharedWorkerService that wraps the port communication. The worker can maintain shared state that all connected pages read from — this is more efficient than each tab maintaining its own state. Shared workers are terminated when all connecting pages close.'
      },
      {
        id: 'service-workers', title: 'Service Workers',
        content: 'Service workers are a specialized type of worker that acts as a proxy between the browser and network. They enable offline functionality, push notifications, and background sync. A service worker intercepts fetch events: self.addEventListener("fetch", (e) => { e.respondWith(cacheFirst(e.request)); }). The lifecycle: register (navigator.serviceWorker.register("sw.js")), install (cache app shell), activate (clean old caches), and idle. Angular PWAs use @angular/pwa which generates ngsw-config.json for declarative caching strategies. The Cache API stores request-response pairs for offline use. Service workers are killable — browsers terminate idle workers to save resources. They must be served over HTTPS (except localhost). Update detection: when the browser detects a new service worker, it installs it and waits for existing tabs to close before activating. Navigation API can notify users of updates. Push notifications use the Push API: self.addEventListener("push", handler). Background Sync: self.addEventListener("sync", handler) queues operations for when the network returns. Service workers are the foundation of Progressive Web Apps (PWAs).'
      },
      {
        id: 'message-passing', title: 'Message Passing',
        content: 'Workers communicate exclusively via message passing using postMessage and onmessage. The structured cloning algorithm copies data between threads — it handles most JavaScript types but not functions, DOM nodes, Error objects, or WeakMap/WeakSet. Transferable objects (ArrayBuffer, MessagePort, ImageBitmap, ReadableStream) are moved to the recipient without copying — the sender can no longer use them: worker.postMessage(arrayBuffer, [arrayBuffer]). Named channels organize communication: const channel = new MessageChannel(); worker.postMessage({ port: channel.port2 }, [channel.port2]); channel.port1.onmessage = handler. Request-response pattern: include a unique ID with each message and match responses to their requests. For complex communication, create a typed message protocol: type WorkerMessage = { type: "process", data: number } | { type: "stop" }. In Angular, use a centralized WorkerService that exposes observables for each message type. Error handling: wrap postMessage in try-catch for transferable objects, and handle onerror on the worker. Memory management: nullify references to transferred objects, clean up MessageChannel ports, and terminate workers when no longer needed.'
      }
    ]
  },
  {
    id: 966, slug: 'browser-security', title: 'Browser Security Model',
    description: 'Understand browser security — same-origin policy, sandboxing, CSP, and the Permissions API.',
    level: 'advanced', duration: '35 min',
    objectives: ['Explain the same-origin policy and its implications', 'Understand iframe sandboxing and restrictions', 'Configure Content Security Policy for defense in depth', 'Use the Permissions API for feature access control'],
    quiz: [
      { id: 1, question: 'What does the Same-Origin Policy restrict?', options: ['JavaScript errors', 'Access to DOM and network requests across different origins', 'CSS styling', 'HTML parsing'], correctIndex: 1, explanation: 'SOP prevents a script from one origin from accessing DOM data or making requests to a different origin without permission.' },
      { id: 2, question: 'What does an iframe with sandbox="allow-scripts" allow?', options: ['Full iframe functionality', 'JavaScript execution only (no forms, popups, or same-origin access)', 'Scripts and form submission', 'Scripts and same-origin access'], correctIndex: 1, explanation: 'The sandbox attribute restricts iframe capabilities. allow-scripts enables JavaScript but without other capabilities unless also specified.' },
      { id: 3, question: 'What is the purpose of the Permissions API?', options: ['To check if a user is logged in', 'To query the status of browser permissions (camera, location, etc.)', 'To request API access tokens', 'To manage localStorage permissions'], correctIndex: 1, explanation: 'The Permissions API lets you check if permission has been granted, denied, or is promptable for features like camera, microphone, and geolocation.' }
    ],
    topics: [
      {
        id: 'same-origin', title: 'Same-Origin Policy',
        content: 'The Same-Origin Policy (SOP) is the browser\'s fundamental security mechanism. Two URLs share an origin if they have the same protocol, host, and port. SOP restricts: DOM access (a script from origin A cannot read document.cookie or DOM of origin B), network requests (fetch/XHR to a different origin requires CORS), and storage access (cookies, localStorage are origin-scoped). Cross-origin img, video, script, and link tags are allowed (can load resources, but scripts cannot read their content). CORS relaxes SOP for network requests — the server sends Access-Control-Allow-Origin header to permit specific origins. JSONP was a pre-CORS workaround using script tags (insecure, deprecated). CORS with credentials (cookies) requires specific headers and cannot use wildcard origin. SOP applies to iframes — a cross-origin iframe cannot be accessed by the parent frame. Angular\'s HttpClient handles CORS automatically — the server must return appropriate headers. Never bypass SOP with hacks — it exists to prevent malicious cross-origin data access.'
      },
      {
        id: 'sandboxing', title: 'Iframe Sandboxing',
        content: 'The sandbox attribute on iframes restricts capabilities for untrusted content. By default, sandbox applies all restrictions: no scripts, no forms, no popups, no same-origin access, no top-level navigation. Allow specific capabilities: sandbox="allow-scripts" enables JavaScript, allow-forms enables form submission, allow-same-origin allows same-origin access (use cautiously — combined with allow-scripts it can bypass sandbox), allow-popups allows window.open, allow-top-navigation allows navigation of the parent frame. Multiple permissions: sandbox="allow-scripts allow-forms". Sandboxed iframes cannot access the parent frame\'s DOM, storage, or network requests (without CORS). The sandboxed iframe can still make cross-origin requests (if allowed by CORS). Use sandbox for: embedding third-party widgets, user-generated content (iframes from external sites), and ads. Always pair allow-scripts with allow-same-origin cautiously — it effectively disables sandboxing. CSP frame-src directive adds another layer of control over which origins can be embedded in iframes. Content-Security-Policy: frame-src \'self\' https://trusted.com restricts embedding to specific origins.'
      },
      {
        id: 'csp-security', title: 'Content Security Policy',
        content: 'CSP is an HTTP header that restricts which resources the browser can load, providing defense in depth against XSS, clickjacking, and data injection. Core directives: default-src sets the fallback for all resource types, script-src controls JavaScript (the most critical for XSS prevention), style-src controls CSS, img-src controls images, connect-src controls XHR/fetch/WebSocket, frame-src controls iframes, and frame-ancestors controls who can embed your page. Start with Content-Security-Policy-Report-Only to test without breaking functionality. Replace unsafe-inline with nonces: script-src \'self\' \'nonce-abc123\' — generate a unique nonce per request. Use strict-dynamic to trust scripts loaded by trusted scripts. Report violations with report-uri or report-to directives. CSP is not a substitute for input validation and output encoding — it is an additional layer. Modern CSP level 3 supports stricter policies: require-trusted-types-for script prevents DOM XSS. Combine CSP with other headers: X-Content-Type-Options (prevent MIME sniffing), X-Frame-Options (legacy clickjacking prevention), and Permissions-Policy (feature restrictions).'
      },
      {
        id: 'permissions-api', title: 'Permissions API',
        content: 'The Permissions API queries the status of browser permissions without prompting the user. Check permission status: const status = await navigator.permissions.query({ name: "camera" }). Status values: "granted" (user approved), "denied" (user denied), "prompt" (user has not decided). Supported permissions: camera, microphone, geolocation, notifications, persistent-storage, and more. Watch for permission changes: status.onchange = () => console.log(status.state). The Permissions API does not request permission — it only queries status. To actually request permission, use the feature\'s API: navigator.mediaDevices.getUserMedia({ video: true }) for camera. The Permissions API provides a consistent interface across different features. In Angular, create a PermissionsService: async canAccessCamera(): Promise<boolean> { const status = await navigator.permissions.query({ name: "camera" }); return status.state !== "denied"; }. Useful for feature detection before requesting permission. The Permissions API is not supported in all browsers (limited support in Safari). For broader compatibility, use try-catch around the specific API calls. Permissions can be changed by the user in browser settings at any time — always check before assuming access.'
      }
    ]
  },
  {
    id: 967, slug: 'browser-apis', title: 'Modern Browser APIs',
    description: 'Explore modern browser APIs — Intersection Observer, Resize Observer, Performance Observer, and the Navigation API.',
    level: 'advanced', duration: '40 min',
    objectives: ['Implement lazy loading with Intersection Observer', 'Track element size changes with Resize Observer', 'Monitor performance metrics with Performance Observer', 'Use Navigation API for modern routing patterns'],
    quiz: [
      { id: 1, question: 'What is Intersection Observer used for?', options: ['Tracking element visibility in the viewport', 'Monitoring network requests', 'Observing DOM mutations', 'Measuring element dimensions'], correctIndex: 0, explanation: 'Intersection Observer asynchronously observes changes in intersection (visibility) of a target element with an ancestor element or viewport.' },
      { id: 2, question: 'What does Resize Observer provide?', options: ['Window resize events only', 'Callbacks when an element\'s content size changes', 'Element position tracking', 'Viewport size measurement'], correctIndex: 1, explanation: 'Resize Observer fires callbacks when an element\'s content rectangle changes — useful for responsive components without window.resize listeners.' },
      { id: 3, question: 'What does the Performance Observer entryType "largest-contentful-paint" track?', options: ['Total page weight', 'When the largest content element becomes visible', 'Number of DOM elements', 'Network request count'], correctIndex: 1, explanation: 'Largest Contentful Paint (LCP) entries track when the largest visible content element renders — a Core Web Vital metric.' }
    ],
    topics: [
      {
        id: 'intersection-observer', title: 'Intersection Observer',
        content: 'Intersection Observer asynchronously detects when an element enters or exits the viewport or another root element. Create an observer: const observer = new IntersectionObserver(callback, { root: null (viewport), rootMargin: "100px" (trigger early), threshold: 0 (any visibility) or [0, 0.25, 0.5, 0.75, 1] for percentage-based). The callback receives IntersectionObserverEntry objects: isIntersecting (boolean), intersectionRatio (0-1), target (the element). Unobserve when done: observer.unobserve(element). Use cases: lazy loading images (trigger load when entering viewport), infinite scroll (load more content at bottom), ad viewability tracking (report when ads are visible), scroll animations (trigger CSS animations on visibility), and tab panels (load content only when tab is active). In Angular, create an Angular directive: @Directive({ selector: "[appLazyLoad]" }) that uses Intersection Observer to detect when the host element enters the viewport and emits an event. rootMargin allows triggering before the element enters the viewport — useful for preloading content just before the user scrolls to it.'
      },
      {
        id: 'resize-observer', title: 'Resize Observer',
        content: 'Resize Observer fires callbacks when an element\'s content box size changes. Unlike window.onresize (which only fires for viewport changes), Resize Observer tracks individual element size changes. Create: const observer = new ResizeObserver(entries => { entries.forEach(entry => { const { width, height } = entry.contentRect; }); }); observer.observe(element). Disconnect: observer.disconnect(). The contentRect property provides: x, y (position), width, height (content box dimensions). The borderBoxSize and contentBoxSize properties provide box sizes for more complex use cases. Use cases: responsive components that adapt to their container size (not viewport), chart libraries that resize with their parent element, text truncation detection, and responsive images. In Angular, create a ResizeObserverDirective that wraps the API: @Directive({ selector: "[appResizeObserver]" }) with an output EventEmitter<{ width: number, height: number }>. This replaces the anti-pattern of listening to window.resize for element-specific responsiveness. Resize Observer is throttled by the browser — callbacks fire at most once per animation frame. It is more efficient than polling or window resize listeners for element-specific sizing.'
      },
      {
        id: 'performance-observer', title: 'Performance Observer',
        content: 'Performance Observer subscribes to browser performance events (paint, resource loading, layout shifts, etc.). Create: const observer = new PerformanceObserver(list => { list.getEntries().forEach(entry => { console.log(entry.name, entry.startTime, entry.duration); }); }); observer.observe({ entryTypes: ["paint", "largest-contentful-paint", "layout-shift", "resource"] }). Key entry types: "paint" (first-paint, first-contentful-paint), "largest-contentful-paint" (LCP), "layout-shift" (CLS shifts), "resource" (network request timing), "longtask" (tasks > 50ms blocking main thread), "navigation" (page navigation timing). Disconnect: observer.disconnect(). PerformanceObserver is the modern replacement for performance.getEntriesByType() — it provides real-time notifications instead of polling. Use it to implement Core Web Vitals monitoring: observe "largest-contentful-paint" for LCP, "layout-shift" for CLS, and "longtask" for jank detection. Angular patterns: inject PerformanceObserver in a service, observe relevant entry types, and report metrics to analytics. The buffered option: observer.observe({ type: "paint", buffered: true }) includes entries that occurred before the observer was created.'
      },
      {
        id: 'navigation-api', title: 'Navigation API',
        content: 'The Navigation API provides modern client-side navigation with fine-grained control. It replaces popstate and pushState with a cleaner interface. Check if supported: if ("navigation" in navigator). Get current entry: const entry = navigation.currentEntry; Navigate: navigation.navigate("/new-url", { state: { data: "value" }, info: "extra" }). Listen to navigations: navigation.addEventListener("navigate", (e) => { e.intercept({ handler: async () => { /* custom navigation logic */ } }); }). The NavigateEvent provides: navigationType ("push", "replace", "reload", "traverse"), destination (target URL and state), canIntercept (boolean), intercept (function to handle the navigation), preventDefault (cancel navigation), and scroll (scroll behavior). The Navigation API supports prerendering with the prerender attribute. Use cases: custom routing logic, prefetching on hover, intercepting navigation for auth checks, and fine-grained scroll restoration. In Angular, the Router internally handles navigation — the Navigation API complements it for browser-level control. Back/forward navigation: navigation.addEventListener("currententrychange", handler) tracks all navigation type changes. The Navigation API is not yet supported in all browsers — check compatibility before production use.'
      }
    ]
  },
  {
    id: 968, slug: 'browser-intro', title: 'What is a Browser?',
    description: 'Explore the fundamentals of web browsers — their history, architecture, and how they process and render web content.',
    level: 'beginner', duration: '30 min',
    objectives: ['Trace the evolution of web browsers from early text-based browsers to modern engines', 'Understand the high-level architecture of a modern browser', 'Explain how browsers process HTML, CSS, and JavaScript to display pages'],
    quiz: [
      { id: 1, question: 'Which two major rendering engines power most modern browsers?', options: ['V8 and SpiderMonkey', 'Blink and Gecko', 'WebKit and V8', 'Trident and Gecko'], correctIndex: 1, explanation: 'Blink (used by Chrome, Edge, Opera) and Gecko (used by Firefox) are the two dominant rendering engines. WebKit is also significant (Safari) but Blink has the largest share.' },
      { id: 2, question: 'What is the role of the browser\'s networking layer?', options: ['Rendering HTML to screen', 'Parsing CSS stylesheets', 'Sending HTTP requests and receiving responses', 'Executing JavaScript code'], correctIndex: 2, explanation: 'The networking layer handles all HTTP/HTTPS requests, manages connections, handles caching headers, and receives responses from servers.' },
      { id: 3, question: 'Who is credited with creating the first web browser?', options: ['Linus Torvalds', 'Tim Berners-Lee', 'Brendan Eich', 'Vinton Cerf'], correctIndex: 1, explanation: 'Tim Berners-Lee created the first web browser called WorldWideWeb (later renamed Nexus) in 1990, along with the first web server and the foundational web protocols.' }
    ],
    topics: [
      {
        id: 'browser-history', title: 'Browser History',
        content: 'The web browser has evolved dramatically since its inception. In 1990, Tim Berners-Lee created WorldWideWeb, the first graphical web browser, which could only display text and was limited to NeXT computers. The mid-1990s saw the browser wars between Netscape Navigator and Internet Explorer, which drove rapid innovation but also introduced proprietary features and incompatible standards. Netscape eventually open-sourced its codebase, which became the Mozilla project and eventually Firefox (2004). Safari launched in 2003 with WebKit, and Google Chrome arrived in 2008 with the V8 JavaScript engine and the multi-process Chromium architecture. The V8 engine was revolutionary — it introduced just-in-time (JIT) compilation for JavaScript, making web applications dramatically faster. Modern browsers have converged on web standards compliance, largely due to the Web Standards Project and the WHATWG (Web Hypertext Application Technology Working Group). Today, Chrome dominates with roughly 65% market share, followed by Safari, Edge, and Firefox. Each browser contributes to open web standards through the W3C and WHATWG, ensuring interoperability and pushing the web platform forward with APIs for offline storage, push notifications, hardware access, and more.'
      },
      {
        id: 'how-browsers-work', title: 'How Browsers Work',
        content: 'When a user enters a URL, the browser performs a series of steps to display the page. First, the browser resolves the domain name through DNS lookup (checking cache, ISP, root servers). Next, it establishes a TCP connection using a three-way handshake, then upgrades to TLS for HTTPS. The browser sends an HTTP GET request and receives the HTML response. The HTML parser builds the DOM (Document Object Model) tree by tokenizing the raw bytes and constructing a tree of nodes. The browser then discovers linked resources — CSS, JavaScript, images, fonts — and fetches them. CSS is parsed into the CSSOM (CSS Object Model) tree. JavaScript is downloaded, parsed, compiled by the V8/SpiderMonkey engine, and executed. The DOM and CSSOM merge into a Render Tree, which includes only visible elements. The Layout stage calculates exact positions and sizes of each element using the box model. Paint fills in pixels — text, colors, borders, shadows — creating one or more layers. Composite arranges all layers in z-order and draws them to screen using the GPU. Each of these stages can be triggered independently or combined depending on what changes. The browser optimizes by batching work, deferring non-urgent tasks, and using caching at every level — from DNS to HTTP responses to compiled JavaScript bytecode.'
      },
      {
        id: 'browser-architecture', title: 'Browser Architecture',
        content: 'A modern browser is organized into several major components. The User Interface includes the address bar, back/forward buttons, bookmarks, and the viewport that displays content. The Browser Engine (like Chromium\'s Content module) coordinates between the UI and the rendering engine. The Rendering Engine parses HTML/CSS and displays content on screen — Blink and Gecko are the most common. The JavaScript Engine (V8 in Chrome, SpiderMonkey in Firefox, JavaScriptCore in Safari) compiles and executes JavaScript code, managing memory through garbage collection. The Networking component handles HTTP requests, manages connection pools, handles caching, and implements protocol details like HTTP/2 multiplexing and HTTP/3 QUIC. The UI Backend draws basic widgets like combo boxes and dialogs, using operating system primitives. The Data Persistence layer manages client-side storage including cookies, localStorage, IndexedDB, and Cache API. Modern browsers use a multi-process architecture — Chrome pioneered this with separate processes for the browser UI, each tab (renderer process), and utility processes for networking, GPU, and storage. This isolation prevents a crashed tab from affecting others and provides security through process-level sandboxing. Each renderer process runs in a sandboxed environment with limited system access, communicating with the privileged browser process through IPC (Inter-Process Communication) using the Mojo message system in Chromium.'
      }
    ]
  },
  {
    id: 969, slug: 'browser-networking', title: 'Browser Networking',
    description: 'Deep dive into browser networking — HTTP requests, connection management, resource loading strategies, and network optimization.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Understand how browsers manage HTTP connections and requests', 'Explain connection pooling and keep-alive mechanisms', 'Optimize resource loading order and priorities'],
    quiz: [
      { id: 1, question: 'How many simultaneous connections does a browser typically allow per origin for HTTP/1.1?', options: ['Unlimited', '6', '12', '24'], correctIndex: 1, explanation: 'Browsers typically limit to 6 simultaneous connections per origin for HTTP/1.1 to prevent server overload. HTTP/2 multiplexes requests over a single connection, removing this limit.' },
      { id: 2, question: 'What is the benefit of HTTP/2 multiplexing?', options: ['Larger response sizes', 'Multiple requests and responses over a single TCP connection in parallel', 'Simpler server implementation', 'Reduced header size only'], correctIndex: 1, explanation: 'HTTP/2 multiplexing allows multiple requests and responses to be sent simultaneously over a single TCP connection, eliminating head-of-line blocking at the HTTP layer.' },
      { id: 3, question: 'What does the browser do when it encounters a <link rel="preload"> tag?', options: ['Defers loading until page load completes', 'Immediately fetches the resource with high priority', 'Loads the resource in a background tab', 'Blocks rendering until the resource is loaded'], correctIndex: 1, explanation: 'Preload tells the browser to fetch the resource immediately with high priority, before the browser discovers it naturally through parsing. It helps eliminate the discovery delay.' }
    ],
    topics: [
      {
        id: 'http-requests', title: 'HTTP Requests',
        content: 'The browser\'s networking layer manages all HTTP communication with servers. When a request is made, the browser goes through DNS resolution (converting domain to IP address), establishes a TCP connection (three-way handshake), and optionally upgrades to TLS for HTTPS. The browser maintains a connection pool — a set of reusable TCP connections per origin to avoid repeated handshake overhead. Each request includes headers: User-Agent (browser identification), Accept (content types), Accept-Encoding (compression support), Cookie (stored credentials), and Cache-Control directives. Responses include status codes (200 OK, 304 Not Modified, 404 Not Found, 301 Redirect), headers (Content-Type, Cache-Control, Set-Cookie, ETag), and the response body. The browser\'s preload scanner parses HTML ahead of the main parser to discover resources early — it finds <link>, <script>, and <img> tags in the raw HTML bytes before the DOM is fully built. Resource loading has priorities: critical scripts and CSS are high priority, fonts are medium, images are low (unless decoded as Largest Contentful Paint candidates). The browser uses heuristics to determine load order — inline scripts block, defer scripts wait for parsing, async scripts execute when downloaded, and preload hints elevate priority.'
      },
      {
        id: 'connection-pooling', title: 'Connection Pooling',
        content: 'Connection pooling maintains reusable TCP connections to the same origin, avoiding the overhead of establishing new connections for each request. For HTTP/1.1, browsers limit to approximately 6 simultaneous connections per origin — additional requests are queued. The Connection: keep-alive header (default in HTTP/1.1) keeps the connection open after a request completes, allowing subsequent requests to reuse it without renegotiation. HTTP/2 fundamentally changes connection management — it uses a single TCP connection with multiplexed streams. Multiple requests and responses can be in flight simultaneously without blocking each other. The browser opens one connection per origin for HTTP/2 and distributes requests across streams. HTTP/3 uses QUIC (built on UDP), providing faster connection establishment (0-RTT or 1-RTT for new connections, 0-RTT for resuming), multiplexing without head-of-line blocking, and built-in TLS 1.3. Connection pooling behavior is visible in Chrome DevTools Network panel — the Protocol column shows h2 (HTTP/2), h3 (HTTP/3), or http/1.1. Preconnect hints (resource hints) establish early connections to third-party origins before they are needed: <link rel="preconnect" href="https://fonts.googleapis.com">. DNS prefetch (dns-prefetch) resolves DNS early for known third-party domains. Connection pooling strategies affect performance significantly — keeping connections warm reduces latency for repeated requests to the same API endpoints or CDN origins.'
      },
      {
        id: 'resource-loading', title: 'Resource Loading',
        content: 'Resource loading determines when and how the browser fetches CSS, JavaScript, images, fonts, and other resources. Scripts have several loading modes: synchronous (blocks parsing — legacy), defer (downloads during parsing, executes after HTML parsing completes, in order), async (downloads and executes as soon as available, order not guaranteed), and type="module" (deferred by default, supports ES modules). CSS loading: <link rel="stylesheet"> blocks rendering (not parsing) until the stylesheet is fully downloaded and parsed — this is the render-blocking behavior. Critical inline CSS avoids this delay for above-the-fold content. Images: <img> tags with src are fetched immediately; images below the fold waste bandwidth. Use loading="lazy" for below-the-fold images — the browser defers loading until the image nears the viewport. Intersection Observer can implement custom lazy loading. Fonts: @font-face with font-display controls fallback behavior — swap (show fallback immediately, swap when loaded), optional (use fallback only if font loads quickly), block (hide text until font loads). Resource Hints provide loading directives: preconnect (establish connection early), dns-prefetch (resolve DNS early), preload (fetch resource immediately with high priority), prefetch (fetch resource for next navigation), and prerender (render page in background). The Fetch API provides fine-grained control: fetch(url, { priority: "low" }) sets request priority. Service workers intercept fetch events to implement caching strategies, enabling offline functionality and faster repeat loads through cache-first or stale-while-revalidate patterns.'
      }
    ]
  },
  {
    id: 970, slug: 'browser-storage-deep-dive', title: 'Browser Storage Deep Dive',
    description: 'Master all browser storage mechanisms in depth — Web Storage API, IndexedDB internals, and the Cache API for service workers.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Understand the internals and limitations of localStorage and sessionStorage', 'Work with IndexedDB object stores, indexes, and transactions', 'Leverage the Cache API for offline-first strategies'],
    quiz: [
      { id: 1, question: 'Which storage API is fully asynchronous and supports structured data with indexes?', options: ['localStorage', 'sessionStorage', 'IndexedDB', 'Cookies'], correctIndex: 2, explanation: 'IndexedDB is asynchronous, transactional, and supports structured data with indexes for efficient querying. It is designed for large, complex client-side data storage.' },
      { id: 2, question: 'What event is fired when localStorage is changed in another tab?', options: ['storagechange', 'Storage', 'storage', 'localstorage'], correctIndex: 2, explanation: 'The Storage event fires on the window object in other tabs sharing the same origin when localStorage is modified. It provides key, oldValue, newValue, and url properties.' },
      { id: 3, question: 'What does the Cache API store?', options: ['Only response bodies', 'Request/Response pairs including headers', 'Only cookies', 'DOM elements'], correctIndex: 1, explanation: 'The Cache API stores complete Request/Response pairs, preserving both the original request and the full response with headers, body, and status code.' }
    ],
    topics: [
      {
        id: 'localstorage-sessionstorage', title: 'localStorage and sessionStorage',
        content: 'The Web Storage API provides synchronous key-value string storage through localStorage and sessionStorage. localStorage persists data across browser sessions — it survives tab closures, browser restarts, and page reloads until explicitly cleared. sessionStorage is scoped to the current browser tab — data persists during the tab session but is destroyed when the tab closes. Both provide the same synchronous API: getItem(key), setItem(key, value), removeItem(key), clear(), and key(index) to enumerate keys. Data is stored as strings — objects must be serialized with JSON.stringify() and deserialized with JSON.parse(). Both are limited to approximately 5MB per origin (protocol + domain + port). A critical limitation is that all operations are synchronous and block the main thread — large data operations can cause jank. The Storage event fires on the window object in other tabs when localStorage is modified, enabling cross-tab communication: window.addEventListener("storage", (e) => { console.log(e.key, e.oldValue, e.newValue); }). Angular patterns: create a type-safe StorageService that abstracts serialization and handles quota errors: try { localStorage.setItem(key, JSON.stringify(value)); } catch (e) { if (e.name === "QuotaExceededError") { /* handle storage limit */ } }. Never store sensitive data like authentication tokens — localStorage is accessible to any JavaScript on the page, making it vulnerable to XSS attacks. Use HttpOnly cookies instead for authentication credentials.'
      },
      {
        id: 'indexeddb', title: 'IndexedDB',
        content: 'IndexedDB is a transactional, asynchronous NoSQL database for large structured data storage. It supports storing JavaScript objects, arrays, Blobs, and any structured-clonable data types. The API is event-driven with request objects: const request = indexedDB.open("MyDatabase", 1); request.onupgradeneeded fires when the database is created or versioned — this is where you define the schema by creating object stores and indexes. request.onsuccess fires when the database is open. Transactions ensure data integrity — they are atomic (all or nothing) and support three modes: readonly (default, multiple readers), readwrite (single writer), and versionchange (schema modifications). Object stores support put (insert or update), get (by primary key), delete, getAll, and cursor-based iteration for complex queries. Indexes enable efficient queries without scanning the entire store: objectStore.createIndex("email", "email", { unique: true }) creates a lookup by email field. IndexedDB is asynchronous and request-based — libraries like idb (by Jake Archibald) provide a modern Promise-based wrapper. Capacity varies by browser but typically supports hundreds of megabytes to gigabytes. Chrome DevTools Application panel provides inspection and editing. Angular patterns: create an IndexedDBService using idb for type-safe operations with async/await, and handle database upgrades through versioned migration functions.'
      },
      {
        id: 'cache-api', title: 'Cache API',
        content: 'The Cache API stores Request/Response pairs, designed for service workers to enable offline caching and performance optimization. Unlike other storage APIs, Cache stores complete HTTP responses including status codes, headers, and bodies. Create named caches: const cache = await caches.open("my-cache-v1"). Store responses: await cache.put(request, response). Retrieve: const response = await cache.match(request). Delete: await cache.delete(request). List all caches: const names = await caches.keys(). Common caching strategies: cache-first (serve from cache, fall back to network), network-first (try network, fall back to cache), stale-while-revalidate (serve cache immediately, update in background), and cache-only (serve from cache only, fail if not cached). Cache storage is separate from browser HTTP cache — you have full programmatic control. Angular Service Workers (via @angular/pwa) use the Cache API internally, configured through ngsw-config.json. Cache names should be versioned (v1, v2) — clean up old caches in the service worker activate event: self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== currentVersion).map(k => caches.delete(k))))); }). The Cache API is asynchronous and Promise-based, making it naturally compatible with async/await. Storage limits are generous but vary by browser — typically at least 50MB. The Cache API is queryable: cache.keys() returns all stored Request objects, enabling inspection and selective cleanup. Cache entries survive page reloads but are cleared when the user clears site data.'
      }
    ]
  },
  {
    id: 971, slug: 'browser-performance-apis', title: 'Performance APIs',
    description: 'Master browser performance measurement APIs — Navigation Timing, Resource Timing, User Timing, and the Performance Observer interface.',
    level: 'advanced', duration: '40 min',
    objectives: ['Measure page load performance using Navigation Timing API', 'Track resource loading with Resource Timing and Performance Observer', 'Implement custom performance measurements with User Timing API'],
    quiz: [
      { id: 1, question: 'Which API provides detailed timing data for page navigation from DNS lookup to load complete?', options: ['Resource Timing API', 'Navigation Timing API', 'User Timing API', 'Performance Observer'], correctIndex: 1, explanation: 'The Navigation Timing API provides detailed timing metrics for the entire page lifecycle — from DNS lookup through connection, request, response, parsing, and load events.' },
      { id: 2, question: 'What does the Performance Observer entryType "largest-contentful-paint" measure?', options: ['Total page download size', 'Time when the largest visible content element finishes rendering', 'Time to first byte', 'Duration of all network requests'], correctIndex: 1, explanation: 'Largest Contentful Paint (LCP) is a Core Web Vital that measures when the largest visible content element (image, text block, or video) finishes rendering in the viewport.' },
      { id: 3, question: 'How do you create custom performance marks with the User Timing API?', options: ['performance.mark() and performance.measure()', 'performance.now() only', 'new PerformanceEntry()', 'PerformanceObserver.observe()'], correctIndex: 0, explanation: 'performance.mark("start") creates a timestamp marker, and performance.measure("duration", "start", "end") calculates the time between two marks. Both appear in the Performance timeline.' }
    ],
    topics: [
      {
        id: 'performance-timing', title: 'Navigation Timing and Resource Timing',
        content: 'The Navigation Timing API provides comprehensive timing data for page loads. Access through performance.getEntriesByType("navigation")[0], which returns a PerformanceNavigationTiming object with properties: domainLookupStart/End (DNS resolution), connectStart/End (TCP connection), secureConnectionStart (TLS handshake), requestStart/ResponseStart/ResponseEnd (HTTP timing), domLoading/DomInteractive/DomContentLoadedEventEnd/LoadEventEnd (DOM milestones), transferSize (bytes transferred), encodedBodySize, and decodedBodySize. These timestamps are relative to performance.timeOrigin (the moment the page started loading). Derived metrics: TTFB = responseStart - requestStart, domContentLoaded = domContentLoadedEventEnd - timeOrigin, fullLoad = loadEventEnd - timeOrigin. The Resource Timing API provides similar timing for individual resources: performance.getEntriesByType("resource") returns PerformanceResourceTiming objects for every CSS, JS, image, and XHR/fetch request. Each entry includes name (URL), initiatorType (script, link, img, css, xmlhttprequest), transferSize, duration, and all timing phases. Filter by initiatorType to analyze specific resource categories. Angular patterns: inject a TimingService that collects Navigation Timing metrics on page load and reports them to analytics. Use performance.getEntriesByType("resource") to identify slow resources and optimize loading. The Server-Timing header (serverTiming) lets servers communicate backend timing metrics to the frontend, visible in the Performance API entries.'
      },
      {
        id: 'performance-observer', title: 'Performance Observer',
        content: 'Performance Observer subscribes to the browser performance timeline and receives notifications when performance entries are recorded. Create an observer: const observer = new PerformanceObserver((list) => { list.getEntries().forEach(entry => { /* process entry */ }); }); observer.observe({ entryTypes: ["paint", "largest-contentful-paint", "layout-shift", "resource", "longtask", "navigation"] }). Each entry type provides specific metrics: "paint" entries include first-paint and first-contentful-paint; "largest-contentful-paint" tracks LCP (a Core Web Vital); "layout-shift" measures Cumulative Layout Shift (CLS); "resource" records all resource loading timing; "longtask" identifies tasks exceeding 50ms that block the main thread; "navigation" provides page load timing. The buffered option: observer.observe({ type: "paint", buffered: true }) includes entries that occurred before the observer was created — essential for metrics that fire before your JavaScript loads. Disconnect: observer.disconnect() stops receiving entries. PerformanceObserver is the modern replacement for polling with performance.getEntriesByType() — it provides push-based real-time notifications. Angular patterns: inject PerformanceObserver in an app-initialization service to collect Core Web Vitals (LCP, CLS, FID/INP). Report metrics to analytics endpoints. Combine with the web-vitals library for standardized metric collection. Use observe({ entryTypes: ["longtask"] }) to detect main thread jank in production. PerformanceObserver is supported in all modern browsers — use feature detection for older environments.'
      },
      {
        id: 'performance-navigation', title: 'Performance API Advanced Patterns',
        content: 'Advanced Performance API patterns combine multiple APIs for comprehensive monitoring. User Timing marks and measures enable custom performance tracking: performance.mark("dataFetchStart"); await fetchData(); performance.mark("dataFetchEnd"); performance.measure("dataFetchDuration", "dataFetchStart", "dataFetchEnd"); performance.getEntriesByType("measure") returns your custom metrics — this is invaluable for profiling application-specific operations. The Memory API (performance.memory) provides memory usage data in Chrome: usedJSHeapSize and totalJSHeapSize — useful for detecting memory pressure in production (not available in all browsers). Server-Timing API connects backend and frontend performance: the server sends Server-Timing: db;dur=53, api;dur=144 headers, and frontend reads them via serverTiming property on PerformanceResourceTiming entries. Performance Timeline (the foundation API) unifies all timing data — performance.getEntries() returns all entries sorted by startTime. For Angular applications, create a PerformanceMonitoringService that: collects Navigation Timing on app initialization, observes paint, LCP, CLS, and longtask entries, tracks custom measures for route transitions and data fetching, and reports aggregated metrics to analytics. Use the Atomics and SharedArrayBuffer for high-precision timing in Web Workers when sub-millisecond accuracy is needed. The Timing-Allow-Origin header enables cross-origin timing data sharing for third-party resources. Performance budgets can be enforced in CI using Lighthouse CI, which parses Performance API data to prevent regressions.'
      }
    ]
  }
];
