import { Lesson } from '../models/lesson.model';

export const DATABASE_LESSONS: Lesson[] = [
  {
    id: 990, slug: 'db-intro', title: 'Introduction to Databases',
    description: 'Learn database fundamentals, understand why databases matter, and explore different types of databases.',
    level: 'beginner', duration: '30 min',
    objectives: ['Understand what databases are and why they matter', 'Distinguish between SQL and NoSQL databases', 'Identify key database components and terminology', 'Choose the right database type for your use case'],
    quiz: [
      { id: 1, question: 'What is the primary purpose of a database?', options: ['Run web applications', 'Store, retrieve, and manage data efficiently', 'Design user interfaces', 'Handle network requests'], correctIndex: 1, explanation: 'Databases are designed for efficient data storage, retrieval, and management.' },
      { id: 2, question: 'What does ACID stand for in databases?', options: ['Atomicity, Consistency, Isolation, Durability', 'Access, Control, Integration, Data', 'Array, Class, Interface, Dynamic', 'Application, Connection, ID, Design'], correctIndex: 0, explanation: 'ACID properties ensure reliable database transactions.' },
      { id: 3, question: 'Which database type is best for flexible, unstructured data?', options: ['Relational (SQL)', 'Document (NoSQL)', 'Both are equally good', 'Neither'], correctIndex: 1, explanation: 'Document databases like MongoDB handle flexible, unstructured data well.' }
    ],
    topics: [
      { id: 'what-is-database', title: 'What is a Database', content: '**Definition:** A database is an organized collection of structured data stored electronically, designed for efficient retrieval, insertion, and deletion of data. Databases are managed by Database Management Systems (DBMS) like MySQL, PostgreSQL, or MongoDB.\n\n**Why Databases Matter:**\n- Centralized data storage eliminates duplication\n- Concurrent access by multiple users and applications\n- Data integrity and consistency guarantees\n- ACID properties ensure reliable transactions\n- Scalability from small apps to enterprise systems\n\n**Types of Databases:**\n- **Relational (SQL)**: MySQL, PostgreSQL, SQLite — structured tables with predefined schemas\n- **Document**: MongoDB, CouchDB — flexible JSON-like documents\n- **Key-Value**: Redis, DynamoDB — simple key-value pairs\n- **Graph**: Neo4j, ArangoDB — relationship-focused data\n- **Time-Series**: InfluxDB, TimescaleDB — optimized for timestamped data\n\n**Key Takeaways:**\n1. Databases provide structured, reliable storage for application data\n2. The DBMS handles concurrency, security, and data integrity\n3. Choose a database type based on your data structure and access patterns' },
      { id: 'sql-vs-nosql', title: 'SQL vs NoSQL', content: '**Relational Databases (SQL):**\nData is stored in tables with fixed schemas. Relationships are enforced through foreign keys.\n\n**Non-Relational Databases (NoSQL):**\nData is stored in flexible formats without rigid schemas. Models vary by database type.\n\n**Comparison:**\n| Feature | Relational | NoSQL |\n|---------|-----------|-------|\n| Schema | Fixed | Flexible |\n| Relationships | Foreign keys | Embedded or references |\n| Query Language | SQL | Varies (MongoDB query API) |\n| ACID Compliance | Yes | Varies |\n| Scaling | Vertical | Horizontal |\n\n**When to Use What:**\n- **Relational**: Complex queries, transactions, data consistency\n- **NoSQL**: Rapid development, large-scale distributed data, flexible schemas\n\n**Key Takeaways:**\n1. Relational databases excel at structured data with complex relationships\n2. NoSQL databases offer flexibility and horizontal scalability\n3. Many modern apps use both (polyglot persistence)' },
      { id: 'database-tables', title: 'Database Tables', content: '**Database Tables:** A table is the fundamental storage unit in a relational database, consisting of columns (fields) and rows (records).\n\n**Data Types:**\n- **INT / BIGINT**: Integer numbers\n- **VARCHAR / TEXT**: Variable-length strings\n- **DECIMAL / FLOAT / DOUBLE**: Numeric with decimals\n- **DATE / TIMESTAMP**: Date and time values\n- **BOOLEAN**: True/false values\n- **JSON / JSONB**: JSON data (PostgreSQL)\n\n**Column Constraints:**\n- `NOT NULL`: Column cannot be empty\n- `UNIQUE`: All values must be distinct\n- `DEFAULT`: Value used when none is provided\n- `CHECK`: Validates data against a condition\n\n**Row Operations:**\n```sql\nINSERT INTO products (name, price, category) VALUES (\'Widget\', 9.99, \'Tools\');\nSELECT * FROM products WHERE category = \'Tools\';\nUPDATE products SET price = 12.99 WHERE id = 1;\nDELETE FROM products WHERE id = 1;\n```\n\n**Key Takeaways:**\n1. Tables organize data into rows and columns with enforced structure\n2. Choose appropriate data types and constraints for data integrity\n3. CRUD operations (Create, Read, Update, Delete) are the foundation of data management' },
      { id: 'keys-relationships', title: 'Keys and Relationships', content: '**Primary Keys:** A primary key uniquely identifies each row in a table. It cannot be NULL and must be unique.\n\n**Foreign Keys:** A foreign key creates a link between two tables by referencing the primary key of another table.\n\n**Cascade Options:**\n- `ON DELETE CASCADE`: Delete child rows when parent is deleted\n- `ON DELETE SET NULL`: Set foreign key to NULL when parent is deleted\n- `ON DELETE RESTRICT`: Prevent deletion of parent if children exist\n- `ON UPDATE CASCADE`: Update foreign key when parent key changes\n\n**Composite Keys:**\n```sql\nCREATE TABLE enrollments (\n  student_id INT,\n  course_id INT,\n  enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n  PRIMARY KEY (student_id, course_id)\n);\n```\n\n**Key Takeaways:**\n1. Primary keys uniquely identify rows and are required for every table\n2. Foreign keys establish relationships and enforce referential integrity\n3. Cascade rules define what happens to child records when parent records change' }
    ]
  },
  {
    id: 991, slug: 'db-mysql', title: 'MySQL Deep Dive',
    description: 'Master MySQL architecture, storage engines, indexing strategies, and query optimization techniques.',
    level: 'intermediate', duration: '45 min',
    objectives: ['Understand MySQL server architecture', 'Choose between InnoDB and MyISAM storage engines', 'Design effective database indexes', 'Optimize slow queries using EXPLAIN'],
    quiz: [
      { id: 1, question: 'What is the default storage engine in modern MySQL?', options: ['MyISAM', 'InnoDB', 'MEMORY', 'CSV'], correctIndex: 1, explanation: 'InnoDB is the default storage engine since MySQL 5.5.' },
      { id: 2, question: 'What does an index do?', options: ['Speeds up data retrieval at the cost of storage and write overhead', 'Reduces database size', 'Improves data integrity', 'Enforces relationships'], correctIndex: 0, explanation: 'Indexes speed up reads but add storage overhead and slow down writes.' },
      { id: 3, question: 'When should you avoid indexing a column?', options: ['When it is used in WHERE clauses', 'When it has low cardinality (few distinct values)', 'When it is used in JOIN conditions', 'When it is the primary key'], correctIndex: 1, explanation: 'Low-cardinality columns do not benefit much from indexing.' }
    ],
    topics: [
      { id: 'mysql-architecture', title: 'MySQL Architecture', content: '**MySQL Server Architecture:**\n\nMySQL uses a client-server model with several layers:\n\n1. **Connection Layer** — Handles client connections, authentication, and thread management\n2. **SQL Layer** — Parses SQL, optimizes queries, manages caching\n3. **Storage Engine Layer** — Pluggable engines that handle actual data storage\n\n**Key Components:**\n- **Query Cache** (deprecated in 8.0) — Cached query results\n- **Buffer Pool** — In-memory cache for data and indexes (InnoDB)\n- **Redo Log** — Crash recovery for InnoDB\n- **Binary Log** — Replication and point-in-time recovery\n- **Query Optimizer** — Determines the best execution plan\n\n**Memory Management:**\n```sql\n-- Check buffer pool size\nSHOW VARIABLES LIKE \'innodb_buffer_pool_size\';\n\n-- Recommended: 70-80% of available RAM on dedicated DB server\nSET GLOBAL innodb_buffer_pool_size = 1073741824; -- 1GB\n```\n\n**Key Takeaways:**\n1. MySQL separates SQL processing from storage via pluggable engines\n2. The InnoDB buffer pool is critical for performance — size it appropriately\n3. Understanding the architecture helps diagnose performance bottlenecks' },
      { id: 'storage-engines', title: 'Storage Engines', content: '**InnoDB (Default):**\n- ACID-compliant transactions\n- Row-level locking for concurrent access\n- Foreign key support\n- Crash recovery via redo logs\n- Clustered index for primary key lookups\n\n**MyISAM:**\n- Table-level locking (not suitable for write-heavy workloads)\n- Full-text indexing (before MySQL 5.6 InnoDB got it)\n- Faster for read-heavy workloads with no updates\n- No transaction support\n- No foreign keys\n\n**Choosing Between Them:**\n```sql\n-- Check available engines\nSHOW ENGINES;\n\n-- Set default engine\nSET DEFAULT_STORAGE_ENGINE = InnoDB;\n\n-- Create table with specific engine\nCREATE TABLE logs (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  message TEXT\n) ENGINE=InnoDB;\n```\n\n**Other Engines:**\n- **MEMORY**: Data stored in RAM, ultra-fast but non-persistent\n- **ARCHIVE**: Optimized for inserting large amounts of data\n- **CSV**: Stores data in CSV format\n\n**Key Takeaways:**\n1. InnoDB is the right choice for almost all use cases in modern MySQL\n2. MyISAM is legacy — only use it for specific read-only analytics workloads\n3. Consider MEMORY engine for temporary tables and caching' },
      { id: 'mysql-indexing', title: 'MySQL Indexing', content: '**What is an Index?**\nAn index is a data structure that speeds up data retrieval at the cost of additional storage and write overhead.\n\n**B-Tree Index (Default):**\n```sql\n-- Single column index\nCREATE INDEX idx_email ON users(email);\n\n-- Composite index (column order matters!)\nCREATE INDEX idx_name_email ON users(last_name, first_name);\n```\n\n**Index Best Practices:**\n1. Index columns used in WHERE, JOIN, and ORDER BY clauses\n2. Put high-selectivity columns first in composite indexes\n3. Avoid over-indexing — each index slows down writes\n4. Use covering indexes to avoid table lookups\n\n**Covering Index Example:**\n```sql\n-- This index covers the query (no need to read the table)\nCREATE INDEX idx_covering ON orders(customer_id, order_date, total);\n\nSELECT order_date, total FROM orders WHERE customer_id = 100;\n```\n\n**Key Takeaways:**\n1. Composite index column order should match your most common query patterns\n2. Covering indexes eliminate table lookups for specific queries\n3. Monitor slow queries and add indexes strategically' },
      { id: 'query-optimization', title: 'Query Optimization', content: '**Using EXPLAIN:**\n```sql\nEXPLAIN SELECT u.name, o.total\nFROM users u\nJOIN orders o ON u.id = o.customer_id\nWHERE u.email = \'jane@example.com\';\n```\n\n**EXPLAIN Output Key Fields:**\n- **type**: Access type (system > const > eq_ref > ref > range > index > ALL)\n- **key**: Which index MySQL chose to use\n- **rows**: Estimated number of rows examined\n- **Extra**: Additional info (Using index, Using filesort, etc.)\n\n**Common Optimization Techniques:**\n```sql\n-- Avoid SELECT *\nSELECT id, name, email FROM users WHERE id = 1; -- Good\nSELECT * FROM users WHERE id = 1; -- Bad\n\n-- Use LIMIT for large result sets\nSELECT * FROM products ORDER BY created_at DESC LIMIT 20;\n\n-- Avoid functions on indexed columns (breaks index usage)\nWHERE YEAR(created_at) = 2024; -- Bad\nWHERE created_at >= \'2024-01-01\' AND created_at < \'2025-01-01\'; -- Good\n```\n\n**Key Takeaways:**\n1. Always use EXPLAIN to understand how MySQL executes your queries\n2. Avoid functions on indexed columns to maintain index usage\n3. SELECT specific columns instead of using SELECT *' }
    ]
  },
  {
    id: 992, slug: 'db-postgresql', title: 'PostgreSQL Essentials',
    description: 'Explore PostgreSQL features including JSONB support, full-text search, window functions, and advanced indexing.',
    level: 'intermediate', duration: '45 min',
    objectives: ['Understand PostgreSQL architecture and configuration', 'Work with JSONB data type effectively', 'Implement full-text search', 'Use window functions for advanced analytics'],
    quiz: [
      { id: 1, question: 'What is the key difference between JSON and JSONB in PostgreSQL?', options: ['No difference', 'JSONB is binary-optimized with indexing support', 'JSON is faster', 'JSONB does not support nested data'], correctIndex: 1, explanation: 'JSONB stores data in a decomposed binary format that supports indexing and is faster to process.' },
      { id: 2, question: 'What index type is best for JSONB columns?', options: ['B-tree', 'GIN', 'Hash', 'GiST'], correctIndex: 1, explanation: 'GIN indexes are designed for composite types like JSONB and arrays.' },
      { id: 3, question: 'What is a window function?', options: ['A function that opens a new window', 'A function that performs calculations across a set of rows', 'A function that only works with windows OS', 'A function that creates GUI windows'], correctIndex: 1, explanation: 'Window functions perform calculations across rows related to the current row without grouping.' }
    ],
    topics: [
      { id: 'pg-architecture', title: 'PostgreSQL Architecture', content: '**Process Architecture:**\n\nPostgreSQL uses a process-based architecture with a central postmaster process:\n\n1. **Postmaster** — Main process that handles incoming connections\n2. **Backend Processes** — One per client connection\n3. **Background Workers** — Handle tasks like autovacuum, WAL writing\n4. **Shared Memory** — Buffer cache, WAL buffers, lock tables\n\n**Memory Architecture:**\n- **Shared Buffers** — Main cache for data pages (typically 25% of RAM)\n- **Work Mem** — Memory for sorting and hash operations per query\n- **Maintenance Work Mem** — Memory for VACUUM, CREATE INDEX\n- **Effective Cache Size** — Planner hint for total OS cache\n\n**Key Configuration:**\n```sql\n-- Check current settings\nSHOW shared_buffers;\nSHOW work_mem;\n\n-- Recommended for a dedicated DB server (16GB RAM)\nALTER SYSTEM SET shared_buffers = \'4GB\';\nALTER SYSTEM SET work_mem = \'256MB\';\nALTER SYSTEM SET maintenance_work_mem = \'1GB\';\nALTER SYSTEM SET effective_cache_size = \'12GB\';\n```\n\n**Key Takeaways:**\n1. PostgreSQL spawns a new process per connection — connection pooling is essential\n2. Shared buffers are the primary cache — size to 25% of system RAM\n3. Work mem affects sort and hash operation performance per query' },
      { id: 'jsonb-support', title: 'JSONB Support', content: '**JSON vs JSONB:**\n- **JSON**: Stores raw text, validates JSON syntax, preserves formatting\n- **JSONB**: Stores binary representation, supports indexing, faster queries\n\n**Querying JSONB:**\n```sql\n-- Extract a value\nSELECT attributes->\'brand\' FROM products;\n\n-- Extract as text\nSELECT attributes->>\'brand\' FROM products;\n\n-- Filter by nested value\nSELECT * FROM products WHERE attributes->\'specs\'->>\'ram\' = \'16\';\n\n-- Check key existence\nSELECT * FROM products WHERE attributes ? \'brand\';\n\n-- Check containment\nSELECT * FROM products WHERE attributes @> \'{"tags": ["electronics"]}\'::jsonb;\n```\n\n**GIN Index for JSONB:**\n```sql\nCREATE INDEX idx_products_attrs ON products USING GIN (attributes);\n```\n\n**Key Takeaways:**\n1. Always use JSONB over JSON for query performance and indexing support\n2. Use GIN indexes on JSONB columns for fast containment and key-existence queries\n3. JSONB supports both dot-notation and arrow operators for data extraction' },
      { id: 'full-text-search', title: 'Full-Text Search', content: '**PostgreSQL FTS:**\n```sql\n-- Create a tsvector column\nALTER TABLE articles ADD COLUMN search_vector tsvector;\n\n-- Populate with content\nUPDATE articles SET search_vector =\n  to_tsvector(\'english\', coalesce(title, \'\') || \' \' || coalesce(body, \'\'));\n\n-- Create GIN index\nCREATE INDEX idx_search ON articles USING GIN(search_vector);\n\n-- Query\nSELECT * FROM articles\nWHERE search_vector @@ to_tsquery(\'english\', \'database & performance\');\n```\n\n**Key Takeaways:**\n1. tsvector stores normalized lexemes for fast searching\n2. GIN indexes accelerate full-text queries\n3. Use plainto_tsquery for user input (no syntax required)' },
      { id: 'window-functions', title: 'Window Functions', content: '**Window Functions:**\n```sql\n-- Ranking\nSELECT name, department, salary,\n  RANK() OVER (PARTITION BY department ORDER BY salary DESC) as rank,\n  PERCENT_RANK() OVER (PARTITION BY department ORDER BY salary DESC) as pct\nFROM employees;\n\n-- Running total\nSELECT date, amount,\n  SUM(amount) OVER (ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as running_total\nFROM transactions;\n\n-- Lag/Lead\nSELECT month, revenue,\n  LAG(revenue, 1) OVER (ORDER BY month) as prev_month,\n  revenue - LAG(revenue, 1) OVER (ORDER BY month) as growth\nFROM monthly_revenue;\n```\n\n**Key Takeaways:**\n1. Window functions compute across rows without collapsing them\n2. PARTITION BY defines groups, ORDER BY defines order within partitions\n3. Frame clause (ROWS BETWEEN) controls the window范围' }
    ]
  },
  {
    id: 993, slug: 'db-mongodb', title: 'MongoDB Fundamentals',
    description: 'Learn MongoDB document modeling, CRUD operations, aggregation pipeline, and indexing strategies.',
    level: 'beginner', duration: '40 min',
    objectives: ['Design effective MongoDB document schemas', 'Perform CRUD operations efficiently', 'Build aggregation pipelines for data analysis', 'Create indexes to optimize query performance'],
    quiz: [
      { id: 1, question: 'What is the MongoDB equivalent of a table?', options: ['Database', 'Collection', 'Document', 'Field'], correctIndex: 1, explanation: 'A collection is the MongoDB equivalent of a table in relational databases.' },
      { id: 2, question: 'What format does MongoDB store data in?', options: ['XML', 'JSON', 'BSON', 'CSV'], correctIndex: 2, explanation: 'MongoDB stores data as BSON (Binary JSON), which is more efficient than JSON.' },
      { id: 3, question: 'What is the aggregation pipeline?', options: ['A way to import data', 'A series of stages to process and transform data', 'A backup mechanism', 'A replication protocol'], correctIndex: 1, explanation: 'The aggregation pipeline processes documents through a series of stages.' }
    ],
    topics: [
      { id: 'document-modeling', title: 'Document Modeling', content: '**MongoDB Data Model:**\n- **Database**: Container for collections\n- **Collection**: Group of documents (like a table)\n- **Document**: Individual record (like a row)\n- **Field**: Key-value pair (like a column)\n\n**Design Principles:**\n1. Embed data that is accessed together\n2. Reference data that is accessed independently\n3. Avoid unbounded arrays\n4. Consider document size limits (16MB)\n\n**Embedding vs Referencing:**\n| Pattern | When to Use | Example |\n|---------|-------------|---------|\n| Embed | 1:1 or 1:few | Address in user document |\n| Reference | 1:many or many:many | Orders referencing users |\n\n**Key Takeaways:**\n1. Design schemas based on query patterns\n2. Embed for data accessed together\n3. Reference for independent data access' },
      { id: 'crud-operations', title: 'CRUD Operations', content: '**Insert:**\n```javascript\ndb.users.insertOne({ name: "Alice", email: "alice@example.com" });\ndb.users.insertMany([{ name: "Bob" }, { name: "Charlie" }]);\n```\n\n**Read:**\n```javascript\ndb.users.find({ age: { $gte: 18 } });\ndb.users.findOne({ _id: ObjectId("...") });\n```\n\n**Update:**\n```javascript\ndb.users.updateOne({ name: "Alice" }, { $set: { age: 30 } });\ndb.users.updateMany({ active: false }, { $set: { active: true } });\n```\n\n**Delete:**\n```javascript\ndb.users.deleteOne({ name: "Alice" });\ndb.users.deleteMany({ age: { $lt: 18 } });\n```\n\n**Key Takeaways:**\n1. Use insertOne/insertMany for new documents\n2. Use $set to update specific fields\n3. Use deleteMany carefully with proper filters' },
      { id: 'aggregation-pipeline', title: 'Aggregation Pipeline', content: '**Pipeline Stages:**\n```javascript\ndb.orders.aggregate([\n  { $match: { status: "completed" } },\n  { $group: {\n    _id: "$customerId",\n    totalSpent: { $sum: "$amount" },\n    orderCount: { $sum: 1 }\n  }},\n  { $sort: { totalSpent: -1 } },\n  { $limit: 10 }\n]);\n```\n\n**Common Stages:**\n- `$match`: Filter documents\n- `$group`: Group by key and accumulate\n- `$project`: Reshape documents\n- `$sort`: Sort results\n- `$limit` / `$skip`: Pagination\n- `$lookup`: Join collections (like LEFT JOIN)\n\n**Key Takeaways:**\n1. Pipeline processes documents in sequence\n2. Place $match early to reduce processing\n3. Use $lookup for joins between collections' },
      { id: 'mongodb-indexing', title: 'MongoDB Indexing', content: '**Index Types:**\n```javascript\n// Single field\nCREATE INDEX idx_email ON users(email);\n\n// Compound index\nCREATE INDEX idx_name_age ON users(name, age);\n\n// Text index\nCREATE INDEX idx_text ON articles(title, body);\n\n// TTL index (auto-expire)\nCREATE INDEX idx_session ON sessions(expireAt, { expireAfterSeconds: 0 });\n```\n\n**Index Best Practices:**\n1. Create indexes for frequently queried fields\n2. Use compound indexes for multi-field queries\n3. ESR Rule: Equality, Sort, Range for compound index order\n4. Use explain() to verify index usage\n\n**Key Takeaways:**\n1. Indexes improve read performance dramatically\n2. Compound index field order matters (ESR rule)\n3. Use explain() to verify your indexes are being used' }
    ]
  },
  {
    id: 994, slug: 'db-design', title: 'Database Design',
    description: 'Master database design principles, normalization, ER diagrams, and schema design best practices.',
    level: 'beginner', duration: '40 min',
    objectives: ['Apply database normalization principles', 'Create entity-relationship diagrams', 'Design efficient schemas for real-world applications', 'Avoid common design mistakes'],
    quiz: [
      { id: 1, question: 'What is the goal of normalization?', options: ['Make the database smaller', 'Eliminate data redundancy and improve integrity', 'Make queries faster', 'Simplify the schema'], correctIndex: 1, explanation: 'Normalization eliminates redundancy and ensures data integrity.' },
      { id: 2, question: 'What is denormalization?', options: ['Removing all redundancies', 'Adding controlled redundancy to improve read performance', 'Deleting unused tables', 'Adding more indexes'], correctIndex: 1, explanation: 'Denormalization trades write complexity for faster reads.' },
      { id: 3, question: 'What does an ER diagram show?', options: ['Database size', 'Entities, attributes, and relationships', 'Query performance', 'User permissions'], correctIndex: 1, explanation: 'ER diagrams visualize entities, their attributes, and relationships.' }
    ],
    topics: [
      { id: 'normalization', title: 'Normalization', content: '**Normal Forms:**\n\n1NF: Each cell contains atomic values\n2NF: 1NF + no partial dependencies\n3NF: 2NF + no transitive dependencies\nBCNF: 3NF + every determinant is a candidate key\n\n**Example - Denormalized:**\n| OrderID | Customer | CustomerEmail | Product | Price |\n|---------|----------|---------------|---------|-------|\n| 1 | Alice | alice@test.com | Widget | 9.99 |\n\n**Normalized (3NF):**\nCustomers: { id, name, email }\nProducts: { id, name, price }\nOrders: { id, customerId, productId }\n\n**Key Takeaways:**\n1. Normalize to at least 3NF for most applications\n2. Denormalize selectively for read-heavy workloads\n3. Always document your design decisions' },
      { id: 'er-diagrams', title: 'ER Diagrams', content: '**Components:**\n- **Entity**: Object or concept (rectangle)\n- **Attribute**: Property of entity (oval)\n- **Relationship**: Association between entities (diamond)\n\n**Cardinality:**\n- 1:1 - One-to-one\n- 1:N - One-to-many\n- M:N - Many-to-many\n\n**Example Schema:**\n```sql\nCREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(100) NOT NULL,\n  email VARCHAR(255) UNIQUE NOT NULL\n);\n\nCREATE TABLE orders (\n  id SERIAL PRIMARY KEY,\n  user_id INT REFERENCES users(id),\n  total DECIMAL(10,2),\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n```\n\n**Key Takeaways:**\n1. ER diagrams help visualize database structure\n2. Define cardinality correctly\n3. Use diagrams to communicate design decisions' },
      { id: 'schema-design', title: 'Schema Design', content: '**Design Principles:**\n1. Choose appropriate data types\n2. Use constraints (NOT NULL, UNIQUE, CHECK)\n3. Create indexes for common queries\n4. Plan for growth\n\n**Common Patterns:**\n- Audit columns (created_at, updated_at)\n- Soft deletes (deleted_at timestamp)\n- Status fields (ENUM or VARCHAR)\n- UUID vs Auto-increment IDs\n\n**Migration Strategy:**\n```sql\n-- Add new column safely\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- Backfill data\nUPDATE users SET bio = \'\' WHERE bio IS NULL;\n\n-- Add constraint\nALTER TABLE users ALTER COLUMN bio SET NOT NULL;\n```\n\n**Key Takeaways:**\n1. Use appropriate data types and constraints\n2. Plan migrations carefully\n3. Document your schema decisions' },
      { id: 'common-mistakes', title: 'Common Mistakes', content: '**Mistakes to Avoid:**\n1. Over-normalization (too many joins)\n2. Under-normalization (data redundancy)\n3. Missing indexes on foreign keys\n4. Using SELECT * in production\n5. Not planning for data growth\n6. Ignoring backup strategy\n\n**Best Practices:**\n- Name tables and columns clearly\n- Use singular table names (user, not users)\n- Always have a primary key\n- Add timestamps for auditing\n- Document your design decisions\n\n**Key Takeaways:**\n1. Balance normalization with performance\n2. Always index foreign keys\n3. Document design decisions for future developers' }
    ]
  },
  {
    id: 995, slug: 'db-migrations', title: 'Database Migrations',
    description: 'Implement safe database migrations with zero-downtime deployments and rollback strategies.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Create safe, reversible database migrations', 'Handle data migrations without downtime', 'Implement rollback strategies', 'Use migration tools effectively'],
    quiz: [
      { id: 1, question: 'What is the key principle of database migrations?', options: ['Make changes quickly', 'Be reversible and idempotent', 'Always backup first', 'Use transactions always'], correctIndex: 1, explanation: 'Migrations should be reversible and idempotent for safety.' },
      { id: 2, question: 'What is a zero-downtime migration?', options: ['Migration that runs instantly', 'Migration that does not require application restart', 'Migration that uses zero storage', 'Migration that affects zero rows'], correctIndex: 1, explanation: 'Zero-downtime migrations can be applied without stopping the application.' },
      { id: 3, question: 'When should you use data migrations?', options: ['Never', 'When you need to transform or backfill existing data', 'For every schema change', 'Only for new tables'], correctIndex: 1, explanation: 'Data migrations are needed when transforming or backfilling existing data.' }
    ],
    topics: [
      { id: 'migration-basics', title: 'Migration Basics', content: '**Migration Lifecycle:**\n1. Write migration\n2. Test locally\n3. Review and approve\n4. Deploy to staging\n5. Deploy to production\n6. Monitor and verify\n\n**Migration Types:**\n- Schema changes (DDL)\n- Data migrations (DML)\n- Configuration changes\n\n**Best Practices:**\n- One migration per change\n- Test rollback procedures\n- Use version control\n- Document changes\n- Monitor performance\n\n**Key Takeaways:**\n1. Migrations should be version controlled\n2. Always test rollback procedures\n3. Monitor performance during migration' },
      { id: 'safe-migrations', title: 'Safe Migrations', content: '**Safe Pattern:**\n```sql\n-- Add column (nullable first)\nALTER TABLE users ADD COLUMN bio TEXT;\n\n-- Backfill data\nUPDATE users SET bio = \'\' WHERE bio IS NULL;\n\n-- Add constraint after backfill\nALTER TABLE users ALTER COLUMN bio SET NOT NULL;\n```\n\n**Unsafe Patterns:**\n- Adding NOT NULL column without default\n- Renaming columns directly\n- Dropping columns without backup\n- Large batch updates without batching\n\n**Zero-Downtime Techniques:**\n1. Expand and contract pattern\n2. Feature flags\n3. Backfill before schema change\n4. Blue-green deployments\n\n**Key Takeaways:**\n1. Add columns as nullable first\n2. Backfill data before adding constraints\n3. Use expand-contract pattern' },
      { id: 'data-migrations', title: 'Data Migrations', content: '**Batch Processing:**\n```javascript\nasync function migrateData() {\n  const batchSize = 1000;\n  let offset = 0;\n  while (true) {\n    const batch = await db.query(\n      \'SELECT * FROM old_table LIMIT $1 OFFSET $2\',\n      [batchSize, offset]\n    );\n    if (batch.length === 0) break;\n    \n    await db.transaction(async (tx) => {\n      for (const row of batch) {\n        await tx.insert(\'new_table\', transform(row));\n      }\n    });\n    \n    offset += batchSize;\n  }\n}\n```\n\n**Verification:**\n```javascript\n// After migration, verify counts\nconst oldCount = await db.query(\'SELECT COUNT(*) FROM old_table\');\nconst newCount = await db.query(\'SELECT COUNT(*) FROM new_table\');\nif (oldCount !== newCount) throw new Error(\'Migration verification failed\');\n```\n\n**Key Takeaways:**\n1. Process data in batches\n2. Use transactions for consistency\n3. Always verify migration results' },
      { id: 'rollback-strategies', title: 'Rollback Strategies', content: '**Rollback Plan:**\n1. Before migration: backup database\n2. During migration: monitor for errors\n3. After migration: verify data integrity\n4. If issues: execute rollback script\n\n**Rollback Types:**\n- Immediate rollback (within transaction)\n- Deferred rollback (separate script)\n- Point-in-time recovery\n\n**Monitoring:**\n```sql\n-- Monitor long-running queries\nSELECT pid, now() - pg_stat_activity.query_start AS duration, query\nFROM pg_stat_activity\nWHERE (now() - pg_stat_activity.query_start) > interval \'5 minutes\';\n```\n\n**Key Takeaways:**\n1. Always have a rollback plan\n2. Test rollback procedures\n3. Monitor during and after migration' }
    ]
  },
  {
    id: 996, slug: 'db-security', title: 'Database Security',
    description: 'Implement database security best practices including access control, encryption, and audit logging.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Implement proper access control and user management', 'Configure encryption at rest and in transit', 'Set up audit logging for compliance', 'Protect against SQL injection attacks'],
    quiz: [
      { id: 1, question: 'What is the principle of least privilege?', options: ['Give all users admin access', 'Grant only the minimum permissions needed', 'Restrict all access', 'Use shared accounts'], correctIndex: 1, explanation: 'Least privilege means granting only the minimum permissions necessary.' },
      { id: 2, question: 'How do you prevent SQL injection?', options: ['Use longer passwords', 'Use parameterized queries/ORM', 'Encrypt the database', 'Use HTTPS'], correctIndex: 1, explanation: 'Parameterized queries and ORMs prevent SQL injection by separating code from data.' },
      { id: 3, question: 'What is encryption at rest?', options: ['Encrypting data during transfer', 'Encrypting data stored on disk', 'Encrypting data in memory', 'Encrypting backups only'], correctIndex: 1, explanation: 'Encryption at rest protects data stored on disk or in storage.' }
    ],
    topics: [
      { id: 'access-control', title: 'Access Control', content: '**User Management:**\n```sql\n-- Create role\nCREATE ROLE app_readonly;\nGRANT SELECT ON ALL TABLES IN SCHEMA public TO app_readonly;\n\n-- Create user with role\nCREATE USER app_user WITH PASSWORD \'secure_password\';\nGRANT app_readonly TO app_user;\n\n-- Revoke dangerous permissions\nREVOKE ALL ON DATABASE mydb FROM PUBLIC;\n```\n\n**Access Control Matrix:**\n| Role | SELECT | INSERT | UPDATE | DELETE | DROP |\n|------|--------|--------|--------|--------|------|\n| App Read | Y | N | N | N | N |\n| App Write | Y | Y | Y | Y | N |\n| Admin | Y | Y | Y | Y | Y |\n\n**Key Takeaways:**\n1. Use role-based access control\n2. Grant minimum required permissions\n3. Regularly audit user permissions' },
      { id: 'encryption', title: 'Encryption', content: '**Encryption at Rest:**\n```sql\n-- PostgreSQL: Enable SSL\nALTER SYSTEM SET ssl = on;\n\n-- MySQL: Encrypt tablespace\nCREATE TABLE encrypted_table (\n  id INT PRIMARY KEY,\n  data TEXT\n) ENCRYPTION=\'Y\';\n```\n\n**Encryption in Transit:**\n```\n# PostgreSQL connection string\npostgresql://user:pass@host:5432/db?sslmode=require\n\n# MySQL connection string\nmysql://user:pass@host:3306/db?ssl=true\n```\n\n**Key Management:**\n1. Rotate encryption keys regularly\n2. Use key management services (KMS)\n3. Never store keys in code\n4. Separate key access from data access\n\n**Key Takeaways:**\n1. Enable encryption at rest and in transit\n2. Use TLS for all connections\n3. Rotate encryption keys regularly' },
      { id: 'audit-logging', title: 'Audit Logging', content: '**PostgreSQL Audit:**\n```sql\n-- Enable pgAudit\nCREATE EXTENSION pgaudit;\n\n-- Log all DDL\nALTER SYSTEM SET pgaudit.log = \'ddl\';\n\n-- Log specific table access\nALTER SYSTEM SET pgaudit.log = \'read, write\';\nALTER SYSTEM SET pgaudit.log_parameter = on;\n```\n\n**MySQL Audit:**\n```sql\n-- Enable general log\nSET GLOBAL general_log = 1;\n\n-- Enable audit plugin\nINSTALL PLUGIN audit_log SONAME \'audit_log.so\';\n```\n\n**What to Log:**\n- Schema changes (DDL)\n- Data modifications (DML)\n- Authentication attempts\n- Permission changes\n- Query performance (slow queries)\n\n**Key Takeaways:**\n1. Enable audit logging for compliance\n2. Log schema changes and data modifications\n3. Monitor and alert on suspicious activity' },
      { id: 'sql-injection', title: 'SQL Injection Prevention', content: '**Vulnerable Code:**\n```javascript\n// NEVER do this\nconst query = `SELECT * FROM users WHERE id = ${userId}`;\n```\n\n**Safe Code:**\n```javascript\n// Parameterized query\nconst query = \'SELECT * FROM users WHERE id = $1\';\nconst result = await db.query(query, [userId]);\n\n// ORM (Prisma)\nconst user = await prisma.user.findUnique({ where: { id: userId } });\n```\n\n**Prevention Checklist:**\n1. Always use parameterized queries\n2. Use ORM when possible\n3. Validate and sanitize input\n4. Use least privilege database accounts\n5. Disable dangerous SQL functions\n\n**Key Takeaways:**\n1. Never concatenate user input into SQL\n2. Use parameterized queries or ORM\n3. Validate all input before processing' }
    ]
  },
  {
    id: 997, slug: 'db-performance', title: 'Database Performance',
    description: 'Optimize database performance through query tuning, caching strategies, connection pooling, and monitoring.',
    level: 'advanced', duration: '45 min',
    objectives: ['Identify and fix slow queries', 'Implement effective caching strategies', 'Configure connection pooling properly', 'Monitor database performance metrics'],
    quiz: [
      { id: 1, question: 'What is the first step in optimizing a slow query?', options: ['Add more indexes', 'Run EXPLAIN to understand the execution plan', 'Upgrade hardware', 'Rewrite the query'], correctIndex: 1, explanation: 'EXPLAIN shows how the database executes the query, identifying bottlenecks.' },
      { id: 2, question: 'What is connection pooling?', options: ['Caching query results', 'Reusing database connections to avoid overhead', 'Storing connections in memory', 'Encrypting connections'], correctIndex: 1, explanation: 'Connection pooling maintains a pool of reusable connections to avoid connection overhead.' },
      { id: 3, question: 'What is the N+1 query problem?', options: ['Running N queries plus one', 'Executing one query for a list and N queries for related data', 'A query that returns N+1 rows', 'A query with N joins'], correctIndex: 1, explanation: 'N+1 occurs when fetching a list triggers N additional queries for related data.' }
    ],
    topics: [
      { id: 'query-tuning', title: 'Query Tuning', content: '**Identifying Slow Queries:**\n```sql\n-- PostgreSQL: Enable slow query logging\nALTER SYSTEM SET log_min_duration_statement = 1000; -- 1 second\n\n-- MySQL: Enable slow query log\nSET GLOBAL slow_query_log = 1;\nSET GLOBAL long_query_time = 1;\n```\n\n**EXPLAIN Analysis:**\n```sql\nEXPLAIN ANALYZE SELECT u.name, COUNT(o.id)\nFROM users u\nJOIN orders o ON u.id = o.user_id\nGROUP BY u.id;\n```\n\n**Common Fixes:**\n1. Add missing indexes\n2. Rewrite subqueries as JOINs\n3. Use LIMIT for large result sets\n4. Avoid SELECT *\n5. Use covering indexes\n\n**Key Takeaways:**\n1. Always EXPLAIN before optimizing\n2. Focus on the most expensive operations\n3. Measure before and after changes' },
      { id: 'caching', title: 'Caching Strategies', content: '**Caching Layers:**\n1. Application-level (in-memory)\n2. Distributed cache (Redis/Memcached)\n3. Database query cache\n4. CDN for static data\n\n**Redis Example:**\n```javascript\n// Cache-aside pattern\nasync function getUser(id) {\n  let user = await redis.get(`user:${id}`);\n  if (!user) {\n    user = await db.query(\'SELECT * FROM users WHERE id = $1\', [id]);\n    await redis.setex(`user:${id}`, 3600, JSON.stringify(user));\n  }\n  return JSON.parse(user);\n}\n```\n\n**Cache Invalidation:**\n- TTL-based (time to live)\n- Event-based (write-through)\n- Version-based\n\n**Key Takeaways:**\n1. Use Redis/Memcached for distributed caching\n2. Implement cache invalidation strategy\n3. Monitor cache hit rate' },
      { id: 'connection-pooling', title: 'Connection Pooling', content: '**Why Connection Pooling?**\n- Connection creation is expensive\n- Limited database connections\n- Pooling reuses connections efficiently\n\n**Configuration:**\n```javascript\n// Node.js pg-pool\nconst pool = new Pool({\n  host: \'localhost\',\n  database: \'myapp\',\n  user: \'app_user\',\n  max: 20,           // max connections\n  idleTimeoutMillis: 30000,\n  connectionTimeoutMillis: 2000,\n});\n```\n\n**Pool Sizing:**\n- Formula: connections = (core_count * 2) + effective_spindle_count\n- Typical: 10-20 connections per app instance\n- Monitor connection usage\n\n**Key Takeaways:**\n1. Always use connection pooling\n2. Size pool based on workload\n3. Monitor connection usage and wait times' },
      { id: 'monitoring', title: 'Performance Monitoring', content: '**Key Metrics:**\n- Query response time\n- Connection count and usage\n- Cache hit rate\n- Replication lag\n- Disk I/O and space\n\n**PostgreSQL Monitoring:**\n```sql\n-- Active connections\nSELECT count(*) FROM pg_stat_activity;\n\n-- Slow queries\nSELECT pid, now() - pg_stat_activity.query_start AS duration, query\nFROM pg_stat_activity\nWHERE (now() - pg_stat_activity.query_start) > interval \'5 minutes\';\n\n-- Table bloat\nSELECT schemaname, tablename, pg_size_pretty(pg_total_relation_size(schemaname || \'.\' || tablename))\nFROM pg_tables ORDER BY pg_total_relation_size(schemaname || \'.\' || tablename) DESC;\n```\n\n**Key Takeaways:**\n1. Monitor query performance regularly\n2. Set up alerts for anomalies\n3. Use APM tools for comprehensive monitoring' }
    ]
  },
  {
    id: 998, slug: 'db-nosql-patterns', title: 'NoSQL Patterns',
    description: 'Master NoSQL design patterns including document modeling, graph databases, and key-value stores.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Design effective document schemas in MongoDB', 'Implement key-value patterns with Redis', 'Model relationships in graph databases', 'Choose the right NoSQL pattern for your use case'],
    quiz: [
      { id: 1, question: 'When should you use a document database?', options: ['For complex joins', 'For flexible, hierarchical data structures', 'For time-series data', 'For simple key-value pairs'], correctIndex: 1, explanation: 'Document databases excel at storing flexible, hierarchical data.' },
      { id: 2, question: 'What is a common Redis use case?', options: ['Primary data storage', 'Session caching and real-time leaderboards', 'Complex queries', 'File storage'], correctIndex: 1, explanation: 'Redis is commonly used for caching, sessions, and real-time data.' },
      { id: 3, question: 'What is the key advantage of graph databases?', options: ['Fast writes', 'Efficient traversal of connected data', 'Flexible schemas', 'High availability'], correctIndex: 1, explanation: 'Graph databases are optimized for traversing relationships between data.' }
    ],
    topics: [
      { id: 'document-patterns', title: 'Document Patterns', content: '**Subset Pattern:**\nEmbed only frequently accessed data, reference the rest.\n\n```javascript\n// Instead of embedding all orders\n{\n  _id: userId,\n  name: "Alice",\n  recentOrders: [/* last 10 orders */],\n  allOrdersRef: orderCollectionId\n}\n```\n\n**Computed Pattern:**\nPre-compute expensive aggregations.\n\n```javascript\n{\n  _id: productId,\n  name: "Widget",\n  stats: {\n    viewCount: 1234,\n    avgRating: 4.5,\n    totalSales: 5678\n  }\n}\n```\n\n**Bucket Pattern:**\nGroup time-series data into buckets.\n\n```javascript\n{\n  sensorId: "temp-001",\n  date: "2024-01-15",\n  readings: [\n    { time: "08:00", value: 22.5 },\n    { time: "08:01", value: 22.6 }\n  ]\n}\n```\n\n**Key Takeaways:**\n1. Subset pattern reduces document size\n2. Computed pattern trades write cost for read speed\n3. Bucket pattern optimizes time-series data' },
      { id: 'key-value-patterns', title: 'Key-Value Patterns', content: '**Session Management:**\n```javascript\n// Store session\nawait redis.setex(`session:${sessionId}`, 3600, JSON.stringify({\n  userId: 123,\n  role: \'admin\',\n  loginTime: Date.now()\n}));\n\n// Retrieve session\nconst session = await redis.get(`session:${sessionId}`);\n```\n\n**Rate Limiting:**\n```javascript\nasync function isRateLimited(userId, limit, window) {\n  const key = `rate:${userId}`;\n  const current = await redis.incr(key);\n  if (current === 1) {\n    await redis.expire(key, window);\n  }\n  return current > limit;\n}\n```\n\n**Distributed Locking:**\n```javascript\nasync function acquireLock(lockKey, ttl) {\n  const result = await redis.set(lockKey, \'1\', \'EX\', ttl, \'NX\');\n  return result === \'OK\';\n}\n```\n\n**Key Takeaways:**\n1. Redis excels at session management\n2. Use INCR for atomic counters\n3. SET NX for distributed locks' },
      { id: 'graph-patterns', title: 'Graph Patterns', content: '**Social Network:**\n```cypher\n// Create relationships\nCREATE (alice:Person {name: "Alice"})\nCREATE (bob:Person {name: "Bob"})\nCREATE (alice)-[:FRIENDS_WITH {since: 2020}]->(bob)\n\n// Find friends of friends\nMATCH (p:Person {name: "Alice"})-[:FRIENDS_WITH]->(f)-[:FRIENDS_WITH]->(fof)\nWHERE NOT (p)-[:FRIENDS_WITH]->(fof) AND p <> fof\nRETURN fof.name\n```\n\n**Recommendation Engine:**\n```cypher\n// Products bought together\nMATCH (p1:Product)<-[:PURCHASED]-(c:Customer)-[:PURCHASED]->(p2:Product)\nWHERE p1 <> p2\nRETURN p1.name, p2.name, COUNT(c) as frequency\nORDER BY frequency DESC\n```\n\n**Key Takeaways:**\n1. Graphs excel at relationship-heavy queries\n2. Cypher is the query language for Neo4j\n3. Use graphs for social networks and recommendations' },
      { id: 'choosing-nosql', title: 'Choosing NoSQL', content: '**Decision Matrix:**\n| Pattern | Best For | Examples |\n|---------|----------|----------|\n| Document | Flexible schemas, nested data | MongoDB, CouchDB |\n| Key-Value | Simple lookups, caching | Redis, DynamoDB |\n| Column-Family | Time-series, analytics | Cassandra, HBase |\n| Graph | Relationships, networks | Neo4j, ArangoDB |\n\n**When to Use:**\n- Document: CMS, user profiles, product catalogs\n- Key-Value: Sessions, caching, configuration\n- Column-Family: IoT data, event logging\n- Graph: Social networks, fraud detection, recommendations\n\n**Polyglot Persistence:**\nUse multiple database types for different needs:\n- Redis for caching\n- PostgreSQL for transactions\n- MongoDB for content\n- Neo4j for recommendations\n\n**Key Takeaways:**\n1. Choose based on data model and access patterns\n2. Consider polyglot persistence\n3. Evaluate operational complexity' }
    ]
  }
];
