import { Lesson } from '../models/lesson.model';

export const DESIGN_SYSTEMS_LESSONS: Lesson[] = [
  {
    id: 986, slug: 'dsys-intro', title: 'Introduction to Design Systems',
    description: 'Discover what a design system is, why teams need one, and the core benefits of adopting a shared design language across your organization.',
    level: 'beginner', duration: '25 min',
    objectives: [
      'Understand what a design system is and what it contains',
      'Explain why teams adopt design systems',
      'Identify the key benefits and challenges',
      'Recognize real-world design system examples'
    ],
    quiz: [
      { id: 1, question: 'What is a design system?', options: ['A CSS framework like Bootstrap', 'A collection of reusable components, guidelines, and standards for building UIs', 'A JavaScript library for animations', 'A project management tool'], correctIndex: 1, explanation: 'A design system is a comprehensive set of standards, reusable components, and documentation that helps teams build consistent user interfaces.' },
      { id: 2, question: 'Why do teams adopt design systems?', options: ['To write more code', 'To speed up hiring', 'To build consistent products faster with shared patterns', 'To replace their designers'], correctIndex: 2, explanation: 'Design systems provide shared building blocks and patterns so teams can ship consistent features without reinventing UI elements every sprint.' },
      { id: 3, question: 'Which of these is NOT typically part of a design system?', options: ['Component library', 'Design tokens', 'Company org chart', 'Usage guidelines'], correctIndex: 2, explanation: 'A design system focuses on UI components, tokens, patterns, and documentation - not organizational structure.' }
    ],
    topics: [
      { id: 'what-is-a-design-system', title: 'What is a Design System?', content: 'A design system is a collection of reusable components, guided by clear standards, that can be assembled to build any number of applications. Think of it as a single source of truth for your product team.\n\n**What a Design System Includes:**\n\n1. **Component Library** - Buttons, inputs, modals, cards, and every reusable UI piece\n2. **Design Tokens** - Named values for colors, spacing, typography, and shadows\n3. **Documentation** - Guidelines on when and how to use each component\n4. **Patterns** - Common layouts, interaction patterns, and page templates\n5. **Brand Guidelines** - Logos, voice, tone, and visual identity rules\n\n**What It is NOT:**\n- It is not just a style guide - it includes working code\n- It is not a one-time project - it evolves continuously\n- It is not just for designers - developers, QA, and PMs all contribute\n\n**How Components Flow:**\n\nDesigners create mockups using design tokens -> Developers build components from tokens -> Components are shared across all products -> Updates propagate everywhere\n\n**Key Takeaway:** A design system bridges design and development, creating a shared vocabulary and set of tools that accelerate product development while maintaining consistency.' },
      { id: 'why-teams-need-one', title: 'Why Teams Need Design Systems', content: 'As products grow, teams face recurring challenges that a design system directly addresses.\n\n**Common Pain Points Without a Design System:**\n\n1. **Inconsistency** - Different buttons on every page, varying color shades, mismatched spacing\n2. **Duplication** - Each developer builds their own version of common components\n3. **Slow onboarding** - New hires spend weeks learning team-specific patterns\n4. **Design-developer handoff gaps** - Designers and developers interpret specs differently\n5. **Hard to scale** - Adding a new product means rebuilding everything from scratch\n\n**How Design Systems Solve These:**\n\n- Consistency: One button component used everywhere\n- Duplication: Shared library eliminates rebuilds\n- Onboarding: New devs learn one system instead of a dozen approaches\n- Handoff: Components are the bridge between design and code\n- Scale: New products reuse existing components\n\n**Real-World Impact:**\n\nTeams that adopt design systems typically report 30-50% faster UI development, fewer visual bugs, and more consistent user experiences across products.\n\n**When You Need One:**\n- Multiple products or apps under one brand\n- More than 3-4 frontend developers\n- Frequent UI-related bugs\n- Slow feature delivery due to UI rebuilds\n\n**Key Takeaway:** Design systems are not just for large companies. Any team building multiple screens or products benefits from shared, reusable UI building blocks.' },
      { id: 'benefits-and-challenges', title: 'Benefits and Challenges', content: 'Design systems offer significant advantages but also come with real challenges to consider.\n\n**Benefits:**\n\n1. **Speed** - Pre-built components mean faster feature development\n2. **Consistency** - Every product looks and feels the same\n3. **Quality** - Components are tested and accessible once, reused everywhere\n4. **Collaboration** - Shared vocabulary between designers and developers\n5. **Scalability** - New products launch faster by reusing existing components\n6. **Accessibility** - Build a11y into components once, benefit everywhere\n7. **Reduced Debt** - Fewer one-off styles and duplicated code\n\n**Challenges:**\n\n1. **Initial Investment** - Building the system takes time before ROI\n2. **Adoption** - Getting teams to actually use the system\n3. **Maintenance** - Someone must keep the system updated\n4. **Flexibility vs Consistency** - Teams may feel restricted\n5. **Governance** - Deciding what goes into the system and when\n\n**Success Factors:**\n\n- Executive sponsorship and team buy-in\n- Start small with core components (buttons, inputs, typography)\n- Treat the design system as a product, not a side project\n- Measure adoption and gather feedback regularly\n\n**Key Takeaway:** The benefits of design systems compound over time. Start with high-impact components and grow the system based on actual team needs.' },
      { id: 'real-world-examples', title: 'Real-World Design Systems', content: 'Many successful companies have published their design systems, offering great learning resources.\n\n**Notable Public Design Systems:**\n\n1. **Material Design (Google)** - Comprehensive system with components, motion, and theming guidelines. Used across Android, web, and Flutter.\n\n2. **Carbon (IBM)** - Enterprise-focused system with strong accessibility and data visualization components.\n\n3. **Polaris (Shopify)** - E-commerce focused system with merchant-friendly patterns.\n\n4. **Spectrum (Adobe)** - Creative tool focused system with rich interaction patterns.\n\n5. **Fluent (Microsoft)** - Powers Microsoft 365 and Windows with cross-platform consistency.\n\n6. **Ant Design (Alibaba)** - Popular in Asia, strong enterprise component library.\n\n**What You Can Learn From Each:**\n\n- Material Design: How to structure tokens and theming at scale\n- Carbon: Accessibility-first design approach\n- Polaris: How to document usage guidelines clearly\n- Spectrum: Complex interaction patterns for creative tools\n\n**Building Your Own:**\n\nYou do not need to copy these systems. Study their structure, then build what your team needs:\n1. Start with your most-used components\n2. Document patterns you already use consistently\n3. Define tokens that match your brand\n\n**Key Takeaway:** Study public design systems for inspiration, but build your own system tailored to your team size, product needs, and brand identity.' }
    ]
  },
  {
    id: 987, slug: 'dsys-tokens-intro', title: 'Design Tokens Explained',
    description: 'Learn what design tokens are, how they represent colors, spacing, and typography, and why they are the foundation of every design system.',
    level: 'beginner', duration: '25 min',
    objectives: [
      'Define what design tokens are and their purpose',
      'Identify the main categories of design tokens',
      'Understand how tokens enable theming and consistency',
      'Apply basic token concepts in CSS'
    ],
    quiz: [
      { id: 1, question: 'What is a design token?', options: ['A login credential', 'A named value that represents a design decision', 'A React component prop', 'A database index'], correctIndex: 1, explanation: 'Design tokens are named entities that store visual design attributes like colors, spacing, typography, and shadows as reusable values.' },
      { id: 2, question: 'Which is an example of a semantic design token?', options: ['#FF5733', '--color-primary', 'rgb(255, 87, 51)', '16px'], correctIndex: 1, explanation: 'Semantic tokens describe purpose (like --color-primary) rather than raw values, making them more meaningful and maintainable.' },
      { id: 3, question: 'Why are design tokens better than hardcoding values?', options: ['They run faster', 'They allow one-place changes that update everywhere', 'They use less memory', 'They are required by Angular'], correctIndex: 1, explanation: 'Tokens centralize design decisions so changing a color or spacing value in one place updates it across your entire application.' }
    ],
    topics: [
      { id: 'what-are-tokens', title: 'What Are Design Tokens?', content: 'Design tokens are the smallest pieces of a design system - named variables that store visual design decisions. Instead of hardcoding colors, sizes, or fonts throughout your codebase, you reference tokens by name.\n\n**Without Tokens:**\n\n.button { background: #2196F3; padding: 12px 24px; font-size: 14px; }\n.card { background: #2196F3; padding: 12px 24px; font-size: 14px; }\n\n**With Tokens:**\n\n:root { --color-primary: #2196F3; --spacing-md: 12px; --text-sm: 14px; }\n.button { background: var(--color-primary); padding: var(--spacing-md); }\n.card { background: var(--color-primary); padding: var(--spacing-md); }\n\n**Why Tokens Matter:**\n\n1. **Single Source of Truth** - One definition, used everywhere\n2. **Easy Theming** - Swap token values to re-theme an entire app\n3. **Consistency** - Eliminates accidental variations\n4. **Maintainability** - Change a color once, update everywhere\n5. **Platform Agnostic** - Same tokens work in CSS, iOS, Android\n\n**Token Naming Convention:**\n\nUse descriptive, purpose-based names:\n- Good: --color-text-primary, --spacing-large, --font-heading\n- Bad: --blue-500, --px-16, --arial-bold\n\n**Key Takeaway:** Tokens transform hard-to-maintain magic numbers into a structured, maintainable system of named design decisions.' },
      { id: 'token-categories', title: 'Token Categories', content: 'Design tokens are organized into three main tiers, each serving a different purpose.\n\n**1. Primitive Tokens (Global):**\n\nRaw values with no semantic meaning. The complete palette of available values.\n\n:root {\n  --blue-50: #E3F2FD;\n  --blue-500: #2196F3;\n  --blue-700: #1565C0;\n  --gray-100: #F5F5F5;\n  --gray-900: #212121;\n  --spacing-1: 4px;\n  --spacing-2: 8px;\n  --spacing-4: 16px;\n}\n\n**2. Semantic Tokens (Alias):**\n\nReference primitive tokens and describe purpose or intent.\n\n:root {\n  --color-primary: var(--blue-500);\n  --color-text: var(--gray-900);\n  --color-bg: var(--gray-100);\n  --spacing-sm: var(--spacing-1);\n  --spacing-md: var(--spacing-2);\n  --spacing-lg: var(--spacing-4);\n}\n\n**3. Component Tokens:**\n\nSpecific to a single component, reference semantic tokens.\n\n:root {\n  --button-bg: var(--color-primary);\n  --button-padding: var(--spacing-md);\n  --card-bg: var(--color-bg);\n  --card-border: var(--color-border);\n}\n\n**Why Three Tiers:**\n\n- Primitives give you a consistent palette\n- Semantics let you re-theme by changing one layer\n- Component tokens isolate component-specific decisions\n\n**Key Takeaway:** The three-tier structure (primitive -> semantic -> component) makes theming and maintenance manageable at any scale.' },
      { id: 'color-and-spacing-tokens', title: 'Color and Spacing Tokens', content: 'Colors and spacing are the most commonly used tokens. Here is how to structure them effectively.\n\n**Color Tokens:**\n\nStart with a base palette, then create semantic layers.\n\n:root {\n  /* Brand palette */\n  --brand-50: #E8F5E9;\n  --brand-500: #4CAF50;\n  --brand-700: #388E3C;\n  --brand-900: #1B5E20;\n\n  /* Neutral palette */\n  --gray-50: #FAFAFA;\n  --gray-100: #F5F5F5;\n  --gray-300: #E0E0E0;\n  --gray-500: #9E9E9E;\n  --gray-700: #616161;\n  --gray-900: #212121;\n\n  /* Semantic colors */\n  --color-primary: var(--brand-500);\n  --color-text: var(--gray-900);\n  --color-text-muted: var(--gray-500);\n  --color-bg: #FFFFFF;\n  --color-bg-subtle: var(--gray-50);\n  --color-border: var(--gray-300);\n  --color-success: #4CAF50;\n  --color-error: #F44336;\n  --color-warning: #FF9800;\n}\n\n**Spacing Tokens:**\n\nUse a consistent scale (typically based on 4px or 8px increments).\n\n:root {\n  --space-0: 0px;\n  --space-1: 4px;\n  --space-2: 8px;\n  --space-3: 12px;\n  --space-4: 16px;\n  --space-6: 24px;\n  --space-8: 32px;\n  --space-12: 48px;\n  --space-16: 64px;\n}\n\n**Using Spacing Tokens:**\n\n.card { padding: var(--space-4); margin-bottom: var(--space-6); }\n.stack > * + * { margin-top: var(--space-3); }\n\n**Key Takeaway:** Color and spacing tokens form the visual foundation of your system. Define them early and reference them consistently.' },
      { id: 'typography-tokens', title: 'Typography Tokens', content: 'Typography tokens define your type system - font families, sizes, weights, line heights, and letter spacing.\n\n**Typography Token Structure:**\n\n:root {\n  /* Font families */\n  --font-sans: Inter, -apple-system, BlinkMacSystemFont, sans-serif;\n  --font-mono: JetBrains Mono, Fira Code, monospace;\n\n  /* Font sizes */\n  --text-xs: 0.75rem;\n  --text-sm: 0.875rem;\n  --text-base: 1rem;\n  --text-lg: 1.125rem;\n  --text-xl: 1.25rem;\n  --text-2xl: 1.5rem;\n  --text-3xl: 1.875rem;\n  --text-4xl: 2.25rem;\n\n  /* Font weights */\n  --font-normal: 400;\n  --font-medium: 500;\n  --font-semibold: 600;\n  --font-bold: 700;\n\n  /* Line heights */\n  --leading-tight: 1.25;\n  --leading-normal: 1.5;\n  --leading-relaxed: 1.75;\n}\n\n**Type Scale Ratios:**\n\nA modular scale creates visual harmony:\n- Major Third (1.25): xs, sm, base, lg, xl, 2xl, 3xl\n- Perfect Fourth (1.333): Slightly larger jumps\n- Golden Ratio (1.618): Dramatic hierarchy\n\n**Applying Typography Tokens:**\n\nh1 { font-size: var(--text-4xl); font-weight: var(--font-bold); line-height: var(--leading-tight); }\nh2 { font-size: var(--text-2xl); font-weight: var(--font-semibold); line-height: var(--leading-tight); }\np { font-size: var(--text-base); line-height: var(--leading-normal); }\n\n**Key Takeaway:** Typography tokens ensure consistent, readable text across your application. Choose a type scale and stick to it.' }
    ]
  },
  {
    id: 988, slug: 'dsys-components-intro', title: 'Component-Based Thinking',
    description: 'Learn why components are the building blocks of modern UIs, how to think in reusable patterns, and what atomic design means.',
    level: 'beginner', duration: '25 min',
    objectives: [
      'Understand why component-based architecture is valuable',
      'Learn to identify reusable UI patterns',
      'Apply atomic design thinking to your components',
      'Recognize the difference between components and pages'
    ],
    quiz: [
      { id: 1, question: 'What is the main benefit of building UIs with components?', options: ['They use less memory', 'They can be reused across pages and projects', 'They do not need testing', 'They write themselves'], correctIndex: 1, explanation: 'Components encapsulate UI logic and presentation, making them reusable across different parts of your application or even different projects.' },
      { id: 2, question: 'In atomic design, what is the smallest unit?', options: ['Pages', 'Organisms', 'Atoms', 'Templates'], correctIndex: 2, explanation: 'Atoms are the smallest building blocks - individual UI elements like buttons, inputs, labels, and icons.' },
      { id: 3, question: 'What makes a good reusable component?', options: ['It does many things at once', 'It has a single responsibility and flexible API', 'It depends on other components', 'It only works in one specific page'], correctIndex: 1, explanation: 'Good components do one thing well, accept flexible inputs, and can be composed together to build complex UIs.' }
    ],
    topics: [
      { id: 'why-components', title: 'Why Components Matter', content: 'Components are the foundation of modern frontend development. They let you break complex UIs into manageable, reusable pieces.\n\n**What is a Component?**\n\nA component is a self-contained piece of UI that:\n- Has its own template (what it looks like)\n- Has its own logic (how it behaves)\n- Can receive inputs (props/attributes)\n- Can emit outputs (events)\n- Can be composed with other components\n\n**Without Components:**\n\nEvery page is a monolithic block of HTML and CSS. Changes ripple unpredictably. Testing is nearly impossible.\n\n**With Components:**\n\nEach piece is isolated and testable. A ButtonComponent can be used on every page, tested once, and updated everywhere simultaneously.\n\n**Component Thinking Checklist:**\n\n- Can this be used elsewhere? If yes, make it a component\n- Does it have a clear responsibility? If not, split it\n- Is it too specific? Abstract common parts into options\n- Does it manage its own state? Keep state local when possible\n\n**Real-World Example:**\n\nA navigation bar component that works across your dashboard, settings page, and mobile app - defined once, reused everywhere.\n\n**Key Takeaway:** Thinking in components means looking at every UI and asking: what are the reusable building blocks here?' },
      { id: 'reusable-patterns', title: 'Reusable UI Patterns', content: 'Most UIs follow common patterns that can be extracted into reusable components.\n\n**Common Patterns:**\n\n1. **Card** - Content container with header, body, and footer\n2. **Modal/Dialog** - Overlay for focused interactions\n3. **Form Controls** - Input, select, checkbox, radio, toggle\n4. **Navigation** - Tabs, sidebar, breadcrumb, pagination\n5. **Data Display** - Table, list, grid, stats\n6. **Feedback** - Toast, alert, spinner, skeleton\n7. **Layout** - Stack, grid, sidebar layout, spacer\n\n**Identifying Patterns:**\n\nLook for repeated HTML structures across your app:\n- Same CSS class combinations appearing 3+ times = extract a component\n- Same form layout appearing in multiple places = extract a pattern\n- Same data display format = build a reusable component\n\n**The Input-Output Model:**\n\nEvery component can be understood through its interface:\n\nInput: What data does it need to render?\n- Button: label, variant, size, disabled\n- Card: title, content, footer\n\nOutput: What does it communicate back?\n- Button: click event\n- Modal: close, confirm events\n\n**Composition Over Configuration:**\n\nPrefer composable pieces over one giant configurable component:\n\nInstead: <Modal title="Delete" body="Are you sure?" confirmText="Yes" cancelText="No" />\n\nPrefer: <Modal><ModalHeader>Delete</ModalHeader><ModalBody>Are you sure?</ModalBody><ModalFooter><Button>Yes</Button><Button>No</Button></ModalFooter></Modal>\n\n**Key Takeaway:** Start by identifying repeated patterns in your existing code. Extract them into components with clear inputs and outputs.' },
      { id: 'atomic-design', title: 'Atomic Design Principles', content: 'Atomic design, created by Brad Frost, is a methodology for creating design systems using five distinct levels.\n\n**The Five Levels:**\n\n1. **Atoms** - Smallest building blocks\n   - Buttons, inputs, labels, icons, badges\n   - Cannot be broken down further without losing meaning\n\n2. **Molecules** - Groups of atoms working together\n   - Search form (input + button)\n   - Form field (label + input + error)\n   - Avatar group (multiple avatars)\n\n3. **Organisms** - Complex UI sections\n   - Navigation bar (logo + links + search)\n   - Product card (image + title + price + button)\n   - Footer (columns + social links)\n\n4. **Templates** - Page-level layouts\n   - Define where organisms go\n   - Structure without real content\n   - Reusable across similar pages\n\n5. **Pages** - Templates with real content\n   - Specific instances of templates\n   - Actual data filling the structure\n\n**Angular Mapping:**\n\nAtoms -> SharedComponent (ButtonComponent, InputComponent)\nMolecules -> FeatureComponent (SearchBarComponent)\nOrganisms -> LayoutComponent (NavBarComponent)\nTemplates -> Route layouts (DashboardLayoutComponent)\nPages -> Route components (DashboardPageComponent)\n\n**Applying Atomic Design:**\n\n1. Start with atoms (your design system foundation)\n2. Combine atoms into molecules\n3. Build organisms from molecules and atoms\n4. Create templates using organisms\n5. Fill templates with real data for pages\n\n**Key Takeaway:** Atomic design gives you a systematic way to break down complex UIs into manageable, hierarchical components.' },
      { id: 'components-vs-pages', title: 'Components vs Pages', content: 'Understanding the difference between components and pages helps you organize code better.\n\n**Components:**\n\n- Reusable across multiple pages\n- Receive data through inputs\n- Emit events for communication\n- Manage their own visual state\n- Have a clear, focused responsibility\n- Example: ButtonComponent, CardComponent, TableComponent\n\n**Pages (or Containers):**\n\n- Specific to one route or URL\n- Fetch and manage application data\n- Compose multiple components together\n- Handle navigation and routing\n- Usually not reused elsewhere\n\n**Example Structure:**\n\n/dashboard (Page)\n  -> DashboardLayoutComponent (Template)\n    -> StatsCardComponent (Organism)\n      -> IconComponent (Atom)\n    -> DataTableComponent (Organism)\n      -> TableRowComponent (Molecule)\n        -> TableCellComponent (Atom)\n\n**Why This Distinction Matters:**\n\n1. **Testability** - Components are easily unit tested, pages need integration tests\n2. **Reusability** - Components move between projects, pages do not\n3. **Maintainability** - Changes to components affect all pages, changes to pages are isolated\n4. **Performance** - Components can be lazy-loaded, pages are route-bound\n\n**Rule of Thumb:**\n\nIf it appears on only one screen, it might be a page concern. If it appears on two or more screens, it should be a component.\n\n**Key Takeaway:** Components are your reusable building blocks. Pages compose those blocks into complete screens with data and navigation.' }
    ]
  },
  {
    id: 980, slug: 'dsys-fundamentals', title: 'Design System Fundamentals',
    description: 'Learn what a design system is, how to create design tokens, build typography and color systems, and establish a consistent visual language across your applications.',
    level: 'intermediate', duration: '40 min',
    objectives: [
      'Understand the purpose and components of a design system',
      'Create and manage design tokens for consistent styling',
      'Build scalable typography and color systems',
      'Apply design system principles to Angular applications'
    ],
    quiz: [
      { id: 1, question: 'What is a design token?', options: ['A security credential', 'A named entity that stores visual design attributes like color and spacing', 'A TypeScript variable', 'An Angular input binding'], correctIndex: 1, explanation: 'Design tokens are the smallest pieces of a design system - named entities that store visual design attributes such as colors, spacing, typography, and shadows.' },
      { id: 2, question: 'Why use CSS custom properties for design tokens instead of Sass variables?', options: ['Sass variables are slower', 'CSS custom properties can be changed at runtime and cascade', 'Sass is being deprecated', 'CSS custom properties are more secure'], correctIndex: 1, explanation: 'CSS custom properties are dynamic - they can be changed at runtime via JavaScript, cascade down the DOM tree, and respond to media queries, unlike Sass variables which are compile-time only.' },
      { id: 3, question: 'What is the recommended approach for naming design tokens?', options: ['Use hex color values as names', 'Use semantic naming that describes purpose, not appearance', 'Use abbreviations to save space', 'Use random identifiers'], correctIndex: 1, explanation: 'Semantic naming (e.g., color-primary, spacing-large) describes the purpose of the token, making it easier to maintain and understand regardless of the actual value.' }
    ],
    topics: [
      { id: 'what-is-design-system', title: 'What is a Design System', content: 'A design system is a collection of reusable components, guided by clear standards, that can be assembled to build any number of applications.\n\n**Core Components of a Design System:**\n\n1. **Design Tokens** - The atomic values (colors, spacing, typography)\n2. **Component Library** - Reusable UI components\n3. **Pattern Library** - Common interaction patterns\n4. **Documentation** - Guidelines and usage instructions\n5. **Governance** - Processes for contribution and versioning\n\n**Benefits:**\n- Consistency across products and teams\n- Faster development with reusable building blocks\n- Reduced design debt and technical debt\n- Shared vocabulary between designers and developers\n- Easier onboarding for new team members\n\n**Popular Design Systems:**\n- Material Design (Google)\n- Carbon (IBM)\n- Polaris (Shopify)\n- Fluent (Microsoft)\n- Spectrum (Adobe)\n\n**Key Takeaways:**\n1. A design system is more than a component library\n2. Design tokens are the foundation of every design system\n3. Start small and evolve your system based on team needs' },
      { id: 'design-tokens', title: 'Design Tokens', content: '**What are Design Tokens?**\n\nDesign tokens are the visual design atoms of your system - named variables that represent design decisions.\n\n**Token Categories:**\n\nPrimitive tokens: Raw values like blue-500: #2196F3\nSemantic tokens: Purpose-based like color-primary: blue-500\nComponent tokens: Component-specific like button-bg: color-primary\n\n**Creating Tokens in CSS:**\n\n:root {\n  /* Primitive tokens */\n  --color-blue-500: #2196F3;\n  --spacing-4: 16px;\n\n  /* Semantic tokens */\n  --color-primary: var(--color-blue-500);\n  --spacing-md: var(--spacing-4);\n}\n\n**Token Structure in TypeScript:**\n\nexport const tokens = {\n  color: {\n    primary: { value: "#2196F3", dark: "#64B5F6" },\n    secondary: { value: "#9C27B0", dark: "#CE93D8" }\n  },\n  spacing: {\n    sm: { value: "8px" },\n    md: { value: "16px" },\n    lg: { value: "32px" }\n  }\n};\n\n**Key Takeaways:**\n1. Use three tiers: primitive, semantic, and component tokens\n2. Semantic tokens describe purpose, not appearance\n3. Tokens enable theming and dark mode support' },
      { id: 'typography-systems', title: 'Typography Systems', content: '**Building a Type Scale:**\n\nA consistent type scale creates visual hierarchy and readability.\n\n:root {\n  --font-family-primary: Inter, sans-serif;\n  --font-family-mono: JetBrains Mono, monospace;\n\n  --text-xs: 0.75rem;\n  --text-sm: 0.875rem;\n  --text-base: 1rem;\n  --text-lg: 1.125rem;\n  --text-xl: 1.25rem;\n  --text-2xl: 1.5rem;\n  --text-3xl: 1.875rem;\n  --text-4xl: 2.25rem;\n\n  --leading-tight: 1.25;\n  --leading-normal: 1.5;\n  --leading-relaxed: 1.75;\n}\n\n**Typography Component:**\n\n@Component({\n  selector: "app-typography",\n  template: `<h1 class="text-4xl font-bold">Heading 1</h1>\n    <p class="text-base leading-relaxed">Body text</p>`\n})\nexport class TypographyComponent {}\n\n**Font Loading Strategy:**\n\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preload" href="/fonts/inter-var.woff2" as="font" type="font/woff2" crossorigin>\n\n**Key Takeaways:**\n1. Define a modular type scale with consistent ratios\n2. Preload critical fonts to reduce FOIT/FOUT\n3. Use semantic token names for font sizes' },
      { id: 'color-systems', title: 'Color Systems', content: '**Building a Color Palette:**\n\nA robust color system starts with a base palette and creates semantic tokens from it.\n\n:root {\n  /* Brand colors */\n  --color-brand-50: #E3F2FD;\n  --color-brand-100: #BBDEFB;\n  --color-brand-500: #2196F3;\n  --color-brand-700: #1565C0;\n  --color-brand-900: #0D47A1;\n\n  /* Neutral scale */\n  --color-gray-50: #FAFAFA;\n  --color-gray-100: #F5F5F5;\n  --color-gray-500: #9E9E9E;\n  --color-gray-800: #424242;\n  --color-gray-900: #212121;\n\n  /* Semantic colors */\n  --color-primary: var(--color-brand-500);\n  --color-text: var(--color-gray-900);\n  --color-bg: var(--color-gray-50);\n  --color-error: #F44336;\n  --color-success: #4CAF50;\n}\n\n**Accessibility with Color:**\n\nfunction checkContrast(foreground: string, background: string): number {\n  // Returns ratio: >= 4.5:1 for normal text, >= 3:1 for large text\n}\n\n**Key Takeaways:**\n1. Use a consistent naming convention (50-900 scale)\n2. Always verify color contrast meets WCAG standards\n3. Create semantic tokens that reference primitive tokens' }
    ]
  },
  {
    id: 981, slug: 'dsys-components', title: 'Component Library Architecture',
    description: 'Design and build a scalable component library with well-defined APIs, composition patterns, variant systems, and comprehensive documentation.',
    level: 'advanced', duration: '45 min',
    objectives: [
      'Design clean and consistent component APIs',
      'Implement composition patterns for flexible component assembly',
      'Build variant systems for component customization',
      'Create effective documentation for component consumers'
    ],
    quiz: [
      { id: 1, question: 'What is the compound component pattern?', options: ['Combining multiple HTML elements into one', 'A pattern where parent components implicitly share state with children', 'Splitting components into smaller pieces', 'Using CSS to combine elements'], correctIndex: 1, explanation: 'The compound component pattern uses implicit state sharing between parent and child components, allowing flexible composition while maintaining internal consistency.' },
      { id: 2, question: 'Which principle best describes a well-designed component API?', options: ['Maximum flexibility with minimum props', 'Expose all internal functionality', 'Minimize the number of props', 'Use only string inputs'], correctIndex: 0, explanation: 'A good component API provides maximum flexibility with minimum props - the props API should be small, composable, and have sensible defaults.' },
      { id: 3, question: 'What is a variant system in component libraries?', options: ['A system for versioning components', 'A system that allows components to have different visual styles based on usage', 'A testing framework', 'A build system'], correctIndex: 1, explanation: 'A variant system defines the different visual styles a component can have (e.g., primary, secondary, outlined) and provides a consistent API for switching between them.' }
    ],
    topics: [
      { id: 'component-api-design', title: 'Component API Design', content: '**Principles of Good Component APIs:**\n\n1. **Minimal Surface Area** - Expose only what consumers need\n2. **Predictable Behavior** - Follow consistent patterns\n3. **Sensible Defaults** - Work out of the box\n4. **Composability** - Compose complex UIs from simple pieces\n\n**API Design Patterns:**\n\n@Component({\n  selector: "app-button",\n  template: `<button [class]="buttonClasses" [type]="type">\n      <ng-content></ng-content>\n    </button>`\n})\nexport class ButtonComponent {\n  @Input() variant: "primary" | "secondary" | "ghost" = "primary";\n  @Input() size: "sm" | "md" | "lg" = "md";\n  @Input() disabled = false;\n}\n\n**Compound Component Pattern:**\n\n@Component({\n  selector: "app-tabs",\n  template: `<ng-content></ng-content>`\n})\nexport class TabsComponent {\n  activeTab = signal<string | null>(null);\n  registerTab(id: string) { /* ... */ }\n}\n\n**Key Takeaways:**\n1. Keep the props API small with sensible defaults\n2. Use composition over configuration\n3. Support both template-driven and reactive patterns' },
      { id: 'composition-patterns', title: 'Composition Patterns', content: '**Content Projection:**\n\n@Component({\n  selector: "app-card",\n  template: `<div class="card">\n      <div class="card-header"><ng-content select="[card-header]"></ng-content></div>\n      <div class="card-body"><ng-content></ng-content></div>\n      <div class="card-footer"><ng-content select="[card-footer]"></ng-content></div>\n    </div>`\n})\nexport class CardComponent {}\n\n**Render Props Pattern:**\n\n@Component({\n  selector: "app-list",\n  template: `@for (item of items(); track item) {\n      <ng-container *ngTemplateOutlet="itemTemplate; context: { $implicit: item }"></ng-container>\n    }`\n})\nexport class ListComponent {\n  @ContentChild("itemTemplate") itemTemplate!: TemplateRef<any>;\n  items = signal<any[]>([]);\n}\n\n**Headless Components:**\n\n@Injectable({ providedIn: "root" })\nexport class UsePagination {\n  totalPages = computed(() => Math.ceil(this.total() / this.pageSize()));\n  nextPage = () => { /* ... */ };\n}\n\n**Key Takeaways:**\n1. Use content projection for flexible layouts\n2. Use templates for complex rendering logic\n3. Headless components separate logic from presentation' },
      { id: 'variant-systems', title: 'Variant Systems', content: '**Defining Variants:**\n\ntype ButtonVariant = "primary" | "secondary" | "outline" | "ghost";\ntype ButtonSize = "xs" | "sm" | "md" | "lg";\n\nconst variantStyles: Record<ButtonVariant, string> = {\n  primary: "bg-primary text-white hover:bg-primary-dark",\n  secondary: "bg-gray-200 text-gray-800 hover:bg-gray-300",\n  outline: "border-2 border-primary text-primary",\n  ghost: "text-primary hover:bg-primary-50"\n};\n\n**CVA (Class Variance Authority):**\n\nimport { cva } from "class-variance-authority";\n\nconst buttonVariants = cva(\n  "inline-flex items-center justify-center rounded-md font-medium",\n  {\n    variants: {\n      variant: {\n        primary: "bg-blue-600 text-white",\n        secondary: "bg-gray-200 text-gray-800",\n      },\n      size: {\n        sm: "text-sm px-3 py-1.5",\n        md: "text-base px-4 py-2",\n        lg: "text-lg px-6 py-3",\n      }\n    },\n    defaultVariants: { variant: "primary", size: "md" }\n  }\n);\n\n**Key Takeaways:**\n1. Use type-safe variants with TypeScript enums or unions\n2. CVA provides a clean API for managing variants\n3. Default variants should work out of the box' },
      { id: 'documentation', title: 'Component Documentation', content: '**Documentation Components:**\n\n@Component({\n  selector: "app-button-demo",\n  template: `<h2>Button</h2>\n    <p>{{ description }}</p>\n    <h3>Usage</h3>\n    <pre><code>{{ usageCode }}</code></pre>\n    <h3>Variants</h3>\n    <div class="flex gap-2">\n      <button app-button variant="primary">Primary</button>\n      <button app-button variant="secondary">Secondary</button>\n    </div>`\n})\nexport class ButtonDemoComponent {\n  description = "A versatile button component with multiple variants.";\n  usageCode = `<app-button variant="primary" size="md">Click me</app-button>`;\n}\n\n**Key Takeaways:**\n1. Include live examples with interactive controls\n2. Document all props with types and defaults\n3. Provide copy-paste code snippets' }
    ]
  },
  {
    id: 982, slug: 'dsys-storybook', title: 'Storybook and Documentation',
    description: 'Set up Storybook for your Angular project, write effective stories, configure addons for accessibility and controls, and implement visual testing.',
    level: 'intermediate', duration: '40 min',
    objectives: [
      'Set up and configure Storybook for an Angular project',
      'Write comprehensive stories for components',
      'Configure addons for accessibility testing and controls',
      'Implement visual regression testing'
    ],
    quiz: [
      { id: 1, question: 'What is Storybook primarily used for?', options: ['Unit testing Angular components', 'Isolated development and documentation of UI components', 'Building production bundles', 'Managing database schemas'], correctIndex: 1, explanation: 'Storybook provides an isolated environment for developing, testing, and documenting UI components independently from the main application.' },
      { id: 2, question: 'What does the a11y addon do?', options: ['Adds accessibility checks to your components', 'Automatically fixes accessibility issues', 'Generates accessibility documentation', 'Tests screen reader compatibility'], correctIndex: 0, explanation: 'The a11y addon integrates axe-core to automatically check your components for accessibility violations and highlights them in the Storybook UI.' },
      { id: 3, question: 'What is a Storybook story?', options: ['A narrative about component history', 'A function that defines how a component renders in different states', 'A test case', 'A CSS stylesheet'], correctIndex: 1, explanation: 'A story is a function that defines how a component renders in a specific state, allowing you to visualize and interact with different configurations.' }
    ],
    topics: [
      { id: 'storybook-setup', title: 'Storybook Setup', content: '**Installation:**\n\nnpx storybook@latest init\n\nThis will install Storybook dependencies, configure it for Angular, create example stories, and add scripts to package.json.\n\n**Configuration (preview.ts):**\n\nimport type { Preview } from "@storybook/angular";\n\nconst preview: Preview = {\n  parameters: {\n    controls: {\n      matchers: {\n        color: /(background|color)$/i,\n        date: /Date$/i,\n      },\n    },\n    backgrounds: {\n      default: "light",\n      values: [\n        { name: "light", value: "#ffffff" },\n        { name: "dark", value: "#1a1a2e" },\n      ],\n    },\n  },\n};\n\nexport default preview;\n\n**Angular-Specific Setup:**\n\nconst config: StorybookConfig = {\n  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],\n  addons: [\n    "@storybook/addon-links",\n    "@storybook/addon-essentials",\n    "@storybook/addon-interactions",\n    "@storybook/addon-a11y",\n  ],\n  framework: {\n    name: "@storybook/angular",\n    options: {},\n  },\n};\n\nexport default config;\n\n**Key Takeaways:**\n1. Use npx storybook@latest init for automatic setup\n2. Configure addons for controls, a11y, and backgrounds\n3. Storybook supports Angular standalone components' },
      { id: 'writing-stories', title: 'Writing Stories', content: '**Basic Story Structure:**\n\nimport type { Meta, StoryObj } from "@storybook/angular";\nimport { ButtonComponent } from "./button.component";\n\nconst meta: Meta<ButtonComponent> = {\n  title: "Components/Button",\n  component: ButtonComponent,\n  tags: ["autodocs"],\n  argTypes: {\n    variant: {\n      control: "select",\n      options: ["primary", "secondary", "ghost"],\n    },\n    size: {\n      control: "radio",\n      options: ["sm", "md", "lg"],\n    },\n  },\n};\n\nexport default meta;\ntype Story = StoryObj<ButtonComponent>;\n\nexport const Primary: Story = {\n  args: {\n    variant: "primary",\n    size: "md",\n    children: "Click me",\n  },\n};\n\n**Decorators:**\n\nimport { moduleMetadata } from "@storybook/angular";\nimport { CommonModule } from "@angular/common";\n\nexport default {\n  decorators: [\n    moduleMetadata({\n      imports: [CommonModule],\n      declarations: [],\n    }),\n  ],\n};\n\n**Key Takeaways:**\n1. Use TypeScript types for type-safe stories\n2. Use argTypes for interactive controls\n3. Tag stories with autodocs for automatic documentation' },
      { id: 'addons', title: 'Storybook Addons', content: '**Essential Addons:**\n\n1. **Controls** - Interactive prop editing\n\nexport const WithControls: Story = {\n  argTypes: {\n    label: { control: "text" },\n    onClick: { action: "clicked" },\n  },\n};\n\n2. **A11y** - Accessibility testing\n\nexport const Accessible: Story = {\n  parameters: {\n    a11y: {\n      config: {\n        rules: [\n          {\n            id: "color-contrast",\n            enabled: true,\n          },\n        ],\n      },\n    },\n  },\n};\n\n3. **Actions** - Event logging\n\nexport const WithActions: Story = {\n  play: async ({ canvasElement }) => {\n    const button = canvasElement.querySelector("button");\n    await userEvent.click(button);\n  },\n};\n\n4. **Docs** - Auto-generated documentation\n\nimport { Meta, Story } from "@storybook/addon-docs";\n\n<Meta title="Components/Button" />\n\n# Button Component\n\nDescription of the component...\n\n**Key Takeaways:**\n1. Use Controls for interactive prop editing\n2. Use a11y addon to catch accessibility violations\n3. Use play functions for interaction testing' },
      { id: 'visual-testing', title: 'Visual Testing', content: '**Visual Regression Testing:**\n\nVisual testing captures screenshots and compares them against baselines to detect visual changes.\n\n**Chromatic Setup:**\n\nnpm install chromatic\n\n"scripts": {\n  "storybook:chromatic": "chromatic --project-token=<your-token>"\n}\n\n**Local Visual Testing with Storybook:**\n\nimport { TestRunnerConfig } from "@storybook/test-runner";\n\nconst config: TestRunnerConfig = {\n  setup() {\n    // Setup code\n  },\n  async postRender(page, context) {\n    const screenshot = await page.screenshot();\n    expect(screenshot).toMatchSnapshot();\n  },\n};\n\nexport default config;\n\n**Interaction Tests:**\n\nexport const ClickInteraction: Story = {\n  play: async ({ canvasElement, args }) => {\n    const canvas = within(canvasElement);\n    const button = canvas.getByRole("button");\n    await userEvent.click(button);\n    expect(args.onClick).toHaveBeenCalled();\n  },\n};\n\n**Key Takeaways:**\n1. Use Chromatic for cloud-based visual testing\n2. Visual tests catch UI regressions that unit tests miss\n3. Combine visual and interaction tests for comprehensive coverage' }
    ]
  },
  {
    id: 983, slug: 'dsys-theming', title: 'Theming and Dark Mode',
    description: 'Implement comprehensive theming with CSS custom properties, Angular theme providers, dark mode support, and system preference detection.',
    level: 'intermediate', duration: '35 min',
    objectives: [
      'Create a themeable design system using CSS custom properties',
      'Build Angular theme providers for runtime theming',
      'Implement dark mode with smooth transitions',
      'Detect and respond to user system preferences'
    ],
    quiz: [
      { id: 1, question: 'How do CSS custom properties enable theming?', options: ['They cannot be changed after being set', 'They can be overridden at any level in the DOM tree', 'They only work with Sass', 'They require JavaScript to modify'], correctIndex: 1, explanation: 'CSS custom properties cascade and can be overridden at any DOM node, making them ideal for theming.' },
      { id: 2, question: 'What CSS media query detects dark mode preference?', options: ['@media (prefers-dark)', '@media (prefers-color-scheme: dark)', '@media (dark-mode: enabled)', '@media (theme: dark)'], correctIndex: 1, explanation: 'The (prefers-color-scheme: dark) media query detects when the user has requested dark mode through their OS settings.' },
      { id: 3, question: 'What is the benefit of CSS custom properties over Sass variables for theming?', options: ['Sass variables are not supported in Angular', 'CSS custom properties can change at runtime without recompilation', 'CSS custom properties are smaller in size', 'Sass variables do not support nesting'], correctIndex: 1, explanation: 'CSS custom properties are dynamic and can be changed at runtime via JavaScript, while Sass variables are compiled to static values.' }
    ],
    topics: [
      { id: 'css-custom-properties', title: 'CSS Custom Properties for Theming', content: '**Theme Definition with CSS Variables:**\n\n:root, [data-theme="light"] {\n  --color-bg-primary: #FFFFFF;\n  --color-bg-secondary: #F5F5F5;\n  --color-text-primary: #1A1A2E;\n  --color-text-secondary: #6B7280;\n  --color-border: #E5E7EB;\n  --color-primary: #3B82F6;\n  --shadow-sm: 0 1px 2px rgba(0,0,0,0.05);\n}\n\n[data-theme="dark"] {\n  --color-bg-primary: #1A1A2E;\n  --color-bg-secondary: #16213E;\n  --color-text-primary: #EAEAEA;\n  --color-text-secondary: #9CA3AF;\n  --color-border: #374151;\n  --color-primary: #60A5FA;\n}\n\n**Applying Theme Variables:**\n\n.card {\n  background: var(--color-bg-primary);\n  color: var(--color-text-primary);\n  border: 1px solid var(--color-border);\n}\n\n**Key Takeaways:**\n1. Define theme variables at the root level\n2. Use data attributes for theme switching\n3. All component styles should reference theme variables' },
      { id: 'theme-providers', title: 'Angular Theme Providers', content: '**Theme Service:**\n\n@Injectable({ providedIn: "root" })\nexport class ThemeService {\n  private theme = signal<"light" | "dark" | "system">("system");\n\n  readonly currentTheme = computed(() => {\n    if (this.theme() === "system") {\n      return window.matchMedia("(prefers-color-scheme: dark)").matches\n        ? "dark" : "light";\n    }\n    return this.theme();\n  });\n\n  setTheme(theme: "light" | "dark" | "system") {\n    this.theme.set(theme);\n    document.documentElement.setAttribute("data-theme", this.currentTheme());\n    localStorage.setItem("theme", this.currentTheme());\n  }\n}\n\n**Theme Toggle Component:**\n\n@Component({\n  selector: "app-theme-toggle",\n  template: `<button (click)="cycleTheme()">\n      {{ themeService.currentTheme() === "dark" ? "Sun" : "Moon" }}\n    </button>`,\n  changeDetection: ChangeDetectionStrategy.OnPush\n})\nexport class ThemeToggleComponent {\n  themeService = inject(ThemeService);\n\n  cycleTheme() {\n    const themes: Array<"light" | "dark" | "system"> = ["light", "dark", "system"];\n    const next = themes[(themes.indexOf(this.themeService.theme()) + 1) % 3];\n    this.themeService.setTheme(next);\n  }\n}\n\n**Key Takeaways:**\n1. Use signals for reactive theme state\n2. Persist theme preference to localStorage\n3. Provide a theme toggle in the application header' },
      { id: 'dark-mode-implementation', title: 'Dark Mode Implementation', content: '**Smooth Theme Transitions:**\n\n*, *::before, *::after {\n  transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;\n}\n\n**Per-Component Dark Mode:**\n\n.component {\n  background: var(--color-bg-primary);\n  color: var(--color-text-primary);\n\n  &__label {\n    color: var(--color-text-secondary);\n  }\n\n  &--highlighted {\n    border-color: var(--color-primary);\n  }\n}\n\n**Dark Mode Images:**\n\n<picture>\n  <source srcset="logo-dark.svg" media="(prefers-color-scheme: dark)">\n  <img src="logo-light.svg" alt="Logo">\n</picture>\n\n**Key Takeaways:**\n1. Add smooth transitions for theme switching\n2. Use CSS variables throughout to automatically support dark mode\n3. Provide alternate images for dark mode when needed' },
      { id: 'system-preference-detection', title: 'System Preference Detection', content: '**Detecting System Preferences:**\n\n// Dark mode detection\nconst darkModeQuery = window.matchMedia("(prefers-color-scheme: dark)");\ndarkModeQuery.addEventListener("change", (e) => {\n  if (theme() === "system") {\n    applyTheme(e.matches ? "dark" : "light");\n  }\n});\n\n// Reduced motion detection\nconst motionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");\nmotionQuery.addEventListener("change", (e) => {\n  document.documentElement.classList.toggle("reduce-motion", e.matches);\n});\n\n// High contrast detection\nconst contrastQuery = window.matchMedia("(prefers-contrast: high)");\ncontrastQuery.addEventListener("change", (e) => {\n  document.documentElement.classList.toggle("high-contrast", e.matches);\n});\n\n**Angular Directive for Preferences:**\n\n@Directive({\n  selector: "[appAdaptiveTheme]",\n  standalone: true\n})\nexport class AdaptiveThemeDirective implements OnInit {\n  private themeService = inject(ThemeService);\n\n  ngOnInit() {\n    if (!localStorage.getItem("theme")) {\n      this.themeService.setTheme("system");\n    }\n  }\n}\n\n**Key Takeaways:**\n1. Always respect system preferences as the default\n2. Allow users to override system settings\n3. Detect and respond to multiple system preferences' }
    ]
  },
  {
    id: 984, slug: 'dsys-a11y', title: 'Accessibility in Design Systems',
    description: 'Build accessible design systems with proper ARIA patterns, keyboard navigation, focus management, and automated testing with axe-core.',
    level: 'advanced', duration: '40 min',
    objectives: [
      'Implement proper ARIA patterns in design system components',
      'Build comprehensive keyboard navigation support',
      'Manage focus states for complex component interactions',
      'Test and validate accessibility with axe-core'
    ],
    quiz: [
      { id: 1, question: 'What does ARIA stand for?', options: ['Accessible Rich Internet Applications', 'Advanced Runtime Interface for Apps', 'Automated Responsive Input API', 'Application Runtime Integration Architecture'], correctIndex: 0, explanation: 'ARIA stands for Accessible Rich Internet Applications - it defines attributes that make web content more accessible to assistive technologies.' },
      { id: 2, question: 'When should you use ARIA attributes?', options: ['Always, for every element', 'Only when native HTML semantics are insufficient', 'Only for screen readers', 'Only for keyboard navigation'], correctIndex: 1, explanation: 'The first rule of ARIA is to use native HTML elements whenever possible. Only use ARIA when native semantics do not exist for your use case.' },
      { id: 3, question: 'What is focus trapping and when is it needed?', options: ['Preventing all focus on a page', 'Constraining keyboard focus within a modal or dialog', 'Removing focus indicators', 'Disabling tab navigation'], correctIndex: 1, explanation: 'Focus trapping restricts keyboard focus to a specific region (like a modal), preventing users from accidentally interacting with background content.' }
    ],
    topics: [
      { id: 'aria-patterns', title: 'ARIA Patterns', content: '**Common ARIA Patterns:**\n\n1. **Tab Panel**\n\n<div role="tablist" aria-label="Settings">\n  <button role="tab" aria-selected="true" aria-controls="panel-1" id="tab-1">\n    General\n  </button>\n  <button role="tab" aria-selected="false" aria-controls="panel-2" id="tab-2">\n    Advanced\n  </button>\n</div>\n<div role="tabpanel" id="panel-1" aria-labelledby="tab-1">\n  General settings content\n</div>\n\n2. **Disclosure (Accordion)**\n\n<button aria-expanded="false" aria-controls="content-1" id="trigger-1">\n  Section 1\n</button>\n<div id="content-1" role="region" aria-labelledby="trigger-1" hidden>\n  Content for section 1\n</div>\n\n3. **Alert**\n\n<div role="alert" aria-live="assertive">\n  Error: Please fill in all required fields.\n</div>\n\n**Angular Implementation:**\n\n@Component({\n  selector: "app-tabs",\n  template: `<div role="tablist">\n      @for (tab of tabs; track tab.id) {\n        <button role="tab"\n                [attr.aria-selected]="activeTab() === tab.id"\n                [attr.aria-controls]="\'panel-\' + tab.id"\n                (click)="selectTab(tab.id)">\n          {{ tab.label }}\n        </button>\n      }\n    </div>`\n})\n\n**Key Takeaways:**\n1. Use native HTML semantics first, ARIA only when necessary\n2. All interactive elements must have accessible names\n3. Use aria-live regions for dynamic content updates' },
      { id: 'keyboard-navigation', title: 'Keyboard Navigation', content: '**Keyboard Interaction Patterns:**\n\n1. **Arrow Key Navigation (Tabs)**\n\n@HostListener("keydown", ["$event"])\nonKeyDown(event: KeyboardEvent) {\n  const tabs = this.tabs();\n  const currentIndex = tabs.findIndex(t => t.id === this.activeTab());\n\n  switch (event.key) {\n    case "ArrowRight":\n      event.preventDefault();\n      this.selectTab(tabs[(currentIndex + 1) % tabs.length].id);\n      break;\n    case "ArrowLeft":\n      event.preventDefault();\n      this.selectTab(tabs[(currentIndex - 1 + tabs.length) % tabs.length].id);\n      break;\n    case "Home":\n      event.preventDefault();\n      this.selectTab(tabs[0].id);\n      break;\n    case "End":\n      event.preventDefault();\n      this.selectTab(tabs[tabs.length - 1].id);\n      break;\n  }\n}\n\n2. **Roving tabindex**\n\n<button tabindex="0">Active item</button>\n<button tabindex="-1">Inactive item</button>\n<button tabindex="-1">Inactive item</button>\n\n3. **Escape to Close**\n\n@HostListener("document:keydown.escape")\nonEscape() {\n  this.closeDropdown();\n}\n\n**Key Takeaways:**\n1. Support arrow keys for navigation within composite widgets\n2. Use roving tabindex for large lists and menus\n3. Always provide Escape to close overlays' },
      { id: 'focus-management', title: 'Focus Management', content: '**Focus Trapping in Modals:**\n\n@Component({\n  selector: "app-modal",\n  template: `\n    <div class="modal-overlay" (click)="close()">\n      <div class="modal" role="dialog" aria-modal="true"\n           #modalContent (click)="$event.stopPropagation()">\n        <ng-content></ng-content>\n      </div>\n    </div>`\n})\nexport class ModalComponent {\n  @ViewChild("modalContent") modalContent!: ElementRef;\n  private previousFocus: HTMLElement | null = null;\n\n  ngAfterViewInit() {\n    this.previousFocus = document.activeElement as HTMLElement;\n    this.modalContent.nativeElement.focus();\n  }\n\n  close() {\n    this.previousFocus?.focus();\n  }\n}\n\n**Focus Restoration:**\n\nexport class FocusManager {\n  static saveFocus(): HTMLElement | null {\n    return document.activeElement as HTMLElement;\n  }\n\n  static restoreFocus(saved: HTMLElement | null) {\n    if (saved && typeof saved.focus === "function") {\n      saved.focus();\n    }\n  }\n}\n\n**Skip Navigation Links:**\n\n<a href="#main-content" class="skip-link">Skip to main content</a>\n<main id="main-content" tabindex="-1">\n  <!-- Main content -->\n</main>\n\n**Key Takeaways:**\n1. Always trap focus in modals and dialogs\n2. Restore focus when overlays close\n3. Provide skip navigation links for keyboard users' },
      { id: 'a11y-testing', title: 'Testing with axe', content: '**axe-core Integration:**\n\nimport { axe, toHaveNoViolations } from "jest-axe";\n\nexpect.extend(toHaveNoViolations);\n\ndescribe("Button Component", () => {\n  it("should have no accessibility violations", async () => {\n    const { container } = render(ButtonComponent, {\n      props: { variant: "primary", children: "Click me" }\n    });\n\n    const results = await axe(container);\n    expect(results).toHaveNoViolations();\n  });\n});\n\n**Playwright Accessibility Testing:**\n\nimport AxeBuilder from "@axe-core/playwright";\n\ntest("page should have no accessibility violations", async ({ page }) => {\n  await page.goto("/components/button");\n\n  const results = await new AxeBuilder({ page })\n    .include("[data-testid=\\"button-example\\"]")\n    .analyze();\n\n  expect(results.violations).toEqual([]);\n});\n\n**Manual Testing Checklist:**\n\n1. Tab through all interactive elements\n2. Verify visible focus indicators\n3. Test with screen reader (VoiceOver/NVDA)\n4. Check color contrast ratios\n5. Verify all images have alt text\n6. Test keyboard-only navigation\n7. Verify ARIA labels are descriptive\n\n**Key Takeaways:**\n1. Automate accessibility testing with axe-core in your test suite\n2. Run manual screen reader testing for critical paths\n3. Include accessibility in your CI/CD pipeline' }
    ]
  },
  {
    id: 985, slug: 'dsys-governance', title: 'Design System Governance',
    description: 'Establish effective governance for your design system including versioning strategies, managing breaking changes, creating migration guides, and defining contribution models.',
    level: 'advanced', duration: '35 min',
    objectives: [
      'Implement semantic versioning for design system packages',
      'Manage and communicate breaking changes effectively',
      'Create clear migration guides for consumers',
      'Define contribution models and review processes'
    ],
    quiz: [
      { id: 1, question: 'What is semantic versioning (semver)?', options: ['A version format using random numbers', 'A versioning scheme using MAJOR.MINOR.PATCH to indicate change types', 'A way to name versions after animals', 'A versioning system only for JavaScript'], correctIndex: 1, explanation: 'Semantic versioning uses MAJOR.MINOR.PATCH format - MAJOR for breaking changes, MINOR for new features, PATCH for bug fixes.' },
      { id: 2, question: 'When should you increment the MAJOR version?', options: ['When fixing a bug', 'When adding a new component', 'When making a breaking change to the API', 'When updating documentation'], correctIndex: 2, explanation: 'MAJOR version increments indicate breaking changes that may require consumers to update their code when upgrading.' },
      { id: 3, question: 'What is a deprecation period?', options: ['Time to remove old code', 'A grace period where old APIs still work but warn about removal', 'The time between releases', 'The period of active development'], correctIndex: 1, explanation: 'A deprecation period keeps old APIs functional while showing warnings, giving consumers time to migrate before the feature is removed.' }
    ],
    topics: [
      { id: 'versioning', title: 'Versioning Strategies', content: '**Semantic Versioning for Design Systems:**\n\nMAJOR.MINOR.PATCH\n\nMAJOR: Breaking changes (removed props, changed APIs)\nMINOR: New features (new components, new props)\nPATCH: Bug fixes, documentation updates\n\n**Pre-release Versioning:**\n\n1.0.0-alpha.1   -> Early development\n1.0.0-beta.1    -> Feature complete, testing\n1.0.0-rc.1      -> Release candidate\n1.0.0            -> Stable release\n\n**Version Strategy in package.json:**\n\n{\n  "name": "@myorg/design-system",\n  "version": "2.3.1",\n  "peerDependencies": {\n    "@angular/core": "^17.0.0 || ^18.0.0"\n  }\n}\n\n**Automated Versioning:**\n\nnpx standard-version --release-as minor\nnpx lerna version minor --conventional-commits\n\n**Key Takeaways:**\n1. Always use semantic versioning for predictable upgrades\n2. Document all breaking changes in changelogs\n3. Use pre-release tags for testing before stable releases' },
      { id: 'breaking-changes', title: 'Managing Breaking Changes', content: '**Identifying Breaking Changes:**\n\nA change is breaking if it:\n- Removes a component or prop\n- Changes a component API signature\n- Changes default behavior\n- Removes or changes CSS class names\n\n**Strategies for Breaking Changes:**\n\n1. **Deprecation First**\n\n// Phase 1: Deprecate (still works, warns)\n@Input() @Deprecated() oldProp: string;\n\n// Phase 2: Remove (next major version)\n// oldProp removed entirely\n\n2. **Codemods**\n\nnpx @myorg/ds-codemod v2-migration src/\n\n3. **Dual API Support**\n\n@Component({ selector: "app-button" })\nexport class ButtonComponent {\n  @Input() variant: ButtonVariant;  // New API\n  @Input() set kind(value: string) {  // Deprecated, maps to new\n    this.variant = mapLegacyKind(value);\n  }\n}\n\n**Key Takeaways:**\n1. Never remove APIs without a deprecation period\n2. Provide codemods for automated migrations\n3. Support both old and new APIs during transition periods' },
      { id: 'migration-guides', title: 'Migration Guides', content: '**Migration Guide Structure:**\n\n# Migration Guide: v1.x to v2.0\n\n## Overview\nThis guide covers upgrading from v1.x to v2.0.\n\n## Breaking Changes\n\n### Button Component\n- kind prop renamed to variant\n- isDisabled renamed to disabled\n\n### Before (v1.x)\n<button app-button kind="primary" isDisabled>Click me</button>\n\n### After (v2.0)\n<button app-button variant="primary" disabled>Click me</button>\n\n### Migration Script\nnpx @myorg/ds-codemod v2-migration src/\n\n## New Features\n- Added ghost variant for buttons\n- Added size prop to all components\n\n## Timeline\n- v1.x: Maintenance mode (security fixes only)\n- v2.0: Active development\n- v1.x EOL: December 2025\n\n**Key Takeaways:**\n1. Provide clear before/after examples\n2. Include automated migration scripts when possible\n3. Set clear timelines for deprecated version support' },
      { id: 'contribution-models', title: 'Contribution Models', content: '**Contribution Workflow:**\n\n1. Proposal    -> Issue/PR with RFC\n2. Review      -> Design system team review\n3. Implementation -> Developer builds the feature\n4. Testing     -> A11y, visual, unit tests\n5. Documentation -> Props, examples, guidelines\n6. Release     -> Version bump and changelog\n\n**RFC Process:**\n\n# RFC: New Toast Component\n\n## Summary\nAdd a toast notification component.\n\n## Motivation\n- Consistent notification pattern across products\n- Accessibility compliance\n- Standardized positioning and animation\n\n## Detailed Design\n- Variants: success, error, warning, info\n- Auto-dismiss with configurable duration\n- Queue management for multiple toasts\n\n## Alternatives Considered\n- Third-party library (rejected: bundle size)\n- Service-only approach (rejected: no visual consistency)\n\n**Component Review Checklist:**\n\n[ ] Props API follows design system conventions\n[ ] Accessibility: keyboard, screen reader, focus management\n[ ] Visual testing: all variants and states documented\n[ ] Documentation: usage examples, do and do not guidelines\n[ ] Performance: no unnecessary re-renders\n[ ] Browser support: tested in target browsers\n[ ] Responsive: works across breakpoints\n\n**Key Takeaways:**\n1. Use RFCs for significant design system changes\n2. Maintain a clear contribution checklist\n3. Balance governance with velocity - not every change needs an RFC' }
    ]
  }
];
