import { Lesson } from '../models/lesson.model';

export const DSA_FRONTEND_LESSONS: Lesson[] = [
  {
    id: 1000, slug: 'dsa-big-o', title: 'Big O Notation',
    description: 'Master Big O notation to analyze algorithm complexity and make informed decisions about data structures and algorithms.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Analyze time and space complexity using Big O notation', 'Compare different algorithmic approaches', 'Identify common complexity patterns', 'Apply complexity analysis to real-world code'],
    quiz: [
      { id: 1, question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], correctIndex: 1, explanation: 'Binary search halves the search space each step, giving O(log n).' },
      { id: 2, question: 'What does O(n^2) typically represent?', options: ['Nested loops', 'Binary search', 'Hash table lookup', 'Single loop'], correctIndex: 0, explanation: 'O(n^2) usually comes from nested loops iterating over the same data.' },
      { id: 3, question: 'Which is faster for large datasets?', options: ['O(n^2)', 'O(n log n)', 'O(2^n)', 'O(n!)'], correctIndex: 1, explanation: 'O(n log n) is the most efficient for large datasets among these options.' }
    ],
    topics: [
      { id: 'big-o-notation', title: 'Big O Notation', content: '**What is Big O?** Big O notation describes how an algorithm scales with input size. It focuses on the dominant term and ignores constants.\n\n**Common Complexities:**\n- O(1) - Constant: Hash table lookup, array access\n- O(log n) - Logarithmic: Binary search\n- O(n) - Linear: Single loop through array\n- O(n log n) - Linearithmic: Merge sort, quicksort\n- O(n^2) - Quadratic: Nested loops\n- O(2^n) - Exponential: Recursive Fibonacci\n\n**Rules for Analysis:**\n1. Drop constants: O(2n) becomes O(n)\n2. Drop lower terms: O(n^2 + n) becomes O(n^2)\n3. Different inputs = different variables: O(a + b)\n4. Sequential code adds, loops multiply\n\n**Key Takeaways:**\n1. Big O measures growth rate, not exact time\n2. Always consider the worst case\n3. Constants matter for small inputs but not asymptotically' },
      { id: 'time-space-complexity', title: 'Time and Space Complexity', content: '**Time vs Space Trade-off:**\nSometimes you can reduce time complexity at the cost of more memory, and vice versa.\n\n**Space Complexity Analysis:**\n- O(1) - In-place algorithms\n- O(n) - Storing a copy of input\n- O(n^2) - 2D matrix\n\n**Examples:**\n| Algorithm | Time | Space |\n|-----------|------|-------|\n| Bubble Sort | O(n^2) | O(1) |\n| Merge Sort | O(n log n) | O(n) |\n| Binary Search | O(log n) | O(1) |\n| Hash Lookup | O(1) | O(n) |\n\n**Key Takeaways:**\n1. Consider both time and space complexity\n2. In-place algorithms save space\n3. Hash tables trade space for O(1) lookup' },
      { id: 'practical-analysis', title: 'Practical Analysis', content: '**How to Analyze Code:**\n1. Identify the input size (n)\n2. Find the dominant operation\n3. Count how many times it executes\n4. Express in Big O\n\n**Example - Find Max:**\n```javascript\nfunction findMax(arr) {\n  let max = arr[0];           // O(1)\n  for (let i = 1; i < arr.length; i++) {  // O(n)\n    if (arr[i] > max) max = arr[i];       // O(1)\n  }\n  return max;                 // O(1)\n}\n// Total: O(n)\n```\n\n**Common Pitfalls:**\n- Ignoring nested loops\n- Forgetting that array methods (map, filter) are O(n)\n- Not considering the cost of operations on different data structures\n\n**Key Takeaways:**\n1. Focus on the dominant operation\n2. Array methods like map/filter are O(n)\n3. Always analyze the worst case' },
      { id: 'optimization', title: 'Optimization Strategies', content: '**Optimization Principles:**\n1. Measure first, optimize second\n2. Focus on the bottleneck\n3. Consider the input size\n\n**Common Optimizations:**\n- Use a hash set for O(1) lookup instead of O(n) array search\n- Cache expensive computations\n- Use early termination\n- Choose the right data structure\n\n**Example - Two Sum:**\n```javascript\n// O(n^2) - brute force\ntwoSum(arr, target) {\n  for (let i = 0; i < arr.length; i++)\n    for (let j = i + 1; j < arr.length; j++)\n      if (arr[i] + arr[j] === target) return [i, j];\n}\n\n// O(n) - using hash map\ntwoSum(arr, target) {\n  const map = new Map();\n  for (let i = 0; i < arr.length; i++) {\n    if (map.has(target - arr[i])) return [map.get(target - arr[i]), i];\n    map.set(arr[i], i);\n  }\n}\n```\n\n**Key Takeaways:**\n1. Use hash maps for O(1) lookups\n2. Choose the right data structure first\n3. Profile before optimizing' }
    ]
  },
  {
    id: 1001, slug: 'dsa-arrays', title: 'Arrays and Hashing',
    description: 'Master array manipulation and hash table techniques for efficient data access and transformation.',
    level: 'beginner', duration: '45 min',
    objectives: ['Implement common array algorithms', 'Use hash tables for efficient lookups', 'Solve array-based problems with optimal complexity', 'Understand when to use arrays vs hash tables'],
    quiz: [
      { id: 1, question: 'What is the time complexity of hash table lookup?', options: ['O(n)', 'O(log n)', 'O(1) average', 'O(n^2)'], correctIndex: 2, explanation: 'Hash tables provide O(1) average lookup time.' },
      { id: 2, question: 'When would you use an array over a hash table?', options: ['When you need O(1) lookup', 'When order matters and you need index access', 'When keys are not integers', 'Never'], correctIndex: 1, explanation: 'Arrays provide O(1) index access and maintain insertion order.' },
      { id: 3, question: 'What causes hash collisions?', options: ['Different keys mapping to same bucket', 'Too many elements', 'Small array size', 'All of the above'], correctIndex: 0, explanation: 'Hash collisions occur when different keys produce the same hash value.' }
    ],
    topics: [
      { id: 'array-operations', title: 'Array Operations', content: '**Common Array Operations:**\n| Operation | Time | Notes |\n|-----------|------|-------|\n| Access by index | O(1) | Direct memory access |\n| Search (unsorted) | O(n) | Must check each element |\n| Search (sorted) | O(log n) | Binary search |\n| Insert at end | O(1) amortized | May trigger resize |\n| Insert at index | O(n) | Must shift elements |\n| Delete at index | O(n) | Must shift elements |\n\n**Two-Pointer Technique:**\n```javascript\n// Check if array is palindrome\nfunction isPalindrome(arr) {\n  let left = 0, right = arr.length - 1;\n  while (left < right) {\n    if (arr[left] !== arr[right]) return false;\n    left++;\n    right--;\n  }\n  return true;\n}\n```\n\n**Key Takeaways:**\n1. Arrays are fast for index access\n2. Two pointers can reduce O(n^2) to O(n)\n3. Consider the cost of insertions/deletions' },
      { id: 'hash-tables', title: 'Hash Tables', content: '**How Hash Tables Work:**\n1. Hash function converts key to array index\n2. Store value at that index\n3. Handle collisions via chaining or open addressing\n\n**Time Complexity:**\n| Operation | Average | Worst |\n|-----------|---------|-------|\n| Insert | O(1) | O(n) |\n| Lookup | O(1) | O(n) |\n| Delete | O(1) | O(n) |\n\n**Use Cases:**\n- Counting frequencies\n- Two Sum problem\n- Caching\n- Checking for duplicates\n\n**Key Takeaways:**\n1. Hash tables provide O(1) average operations\n2. Worst case is O(n) with many collisions\n3. Great for frequency counting and lookups' },
      { id: 'two-pointer', title: 'Two Pointer Technique', content: '**When to Use:**\n- Sorted arrays\n- Palindrome checking\n- Pair sum problems\n\n**Pattern:**\n```javascript\nfunction twoPointer(arr, target) {\n  let left = 0, right = arr.length - 1;\n  while (left < right) {\n    const sum = arr[left] + arr[right];\n    if (sum === target) return [left, right];\n    if (sum < target) left++;\n    else right--;\n  }\n  return [-1, -1];\n}\n```\n\n**Key Takeaways:**\n1. Two pointers reduce nested loops to single pass\n2. Works on sorted arrays\n3. Can be combined with other techniques' },
      { id: 'sliding-window', title: 'Sliding Window', content: '**Fixed Window:**\n```javascript\n// Max sum of k consecutive elements\nfunction maxSum(arr, k) {\n  let sum = 0;\n  for (let i = 0; i < k; i++) sum += arr[i];\n  let max = sum;\n  for (let i = k; i < arr.length; i++) {\n    sum += arr[i] - arr[i - k];\n    max = Math.max(max, sum);\n  }\n  return max;\n}\n```\n\n**Variable Window:**\n```javascript\n// Smallest subarray with sum >= target\nfunction minSubarray(arr, target) {\n  let left = 0, sum = 0, minLen = Infinity;\n  for (let right = 0; right < arr.length; right++) {\n    sum += arr[right];\n    while (sum >= target) {\n      minLen = Math.min(minLen, right - left + 1);\n      sum -= arr[left++];\n    }\n  }\n  return minLen === Infinity ? 0 : minLen;\n}\n```\n\n**Key Takeaways:**\n1. Sliding window reduces O(n^2) to O(n)\n2. Fixed window for fixed-size problems\n3. Variable window for size-range problems' }
    ]
  },
  {
    id: 1002, slug: 'dsa-stacks', title: 'Stacks and Queues',
    description: 'Understand stack and queue data structures, their applications, and when to use each.',
    level: 'beginner', duration: '35 min',
    objectives: ['Implement stacks and queues from scratch', 'Apply stacks for parsing and traversal problems', 'Use queues for BFS and scheduling', 'Choose between stack and queue for different scenarios'],
    quiz: [
      { id: 1, question: 'What is the LIFO principle?', options: ['Last In First Out', 'Last In First Out, First In Last Out', 'Linear Input Fixed Output', 'List In Fixed Order'], correctIndex: 1, explanation: 'LIFO means the last element added is the first to be removed.' },
      { id: 2, question: 'When would you use a queue over a stack?', options: ['For DFS traversal', 'For BFS traversal', 'For undo operations', 'For function calls'], correctIndex: 1, explanation: 'Queues are used for BFS because they process elements in the order they were added.' },
      { id: 3, question: 'What is the time complexity of stack push/pop?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n^2)'], correctIndex: 2, explanation: 'Stack push and pop are O(1) operations.' }
    ],
    topics: [
      { id: 'stack-fundamentals', title: 'Stack Fundamentals', content: '**Stack Operations:**\n- push(x): Add to top - O(1)\n- pop(): Remove from top - O(1)\n- peek(): View top element - O(1)\n- isEmpty(): Check if empty - O(1)\n\n**Implementation:**\n```javascript\nclass Stack {\n  constructor() { this.items = []; }\n  push(x) { this.items.push(x); }\n  pop() { return this.items.pop(); }\n  peek() { return this.items[this.items.length - 1]; }\n  isEmpty() { return this.items.length === 0; }\n}\n```\n\n**Key Takeaways:**\n1. Stack is LIFO (Last In First Out)\n2. All operations are O(1)\n3. Used for undo, parsing, and DFS' },
      { id: 'queue-fundamentals', title: 'Queue Fundamentals', content: '**Queue Operations:**\n- enqueue(x): Add to back - O(1)\n- dequeue(): Remove from front - O(1)\n- peek(): View front element - O(1)\n- isEmpty(): Check if empty - O(1)\n\n**Implementation:**\n```javascript\nclass Queue {\n  constructor() { this.items = []; }\n  enqueue(x) { this.items.push(x); }\n  dequeue() { return this.items.shift(); }\n  peek() { return this.items[0]; }\n  isEmpty() { return this.items.length === 0; }\n}\n```\n\n**Key Takeaways:**\n1. Queue is FIFO (First In First Out)\n2. Used for BFS and scheduling\n3. shift() is O(n), consider deque implementation' },
      { id: 'stack-applications', title: 'Stack Applications', content: '**Valid Parentheses:**\n```javascript\nfunction isValid(s) {\n  const stack = [];\n  const map = { ")": "(", "}": "{", "]": "[" };\n  for (const c of s) {\n    if (c in map) {\n      if (stack.pop() !== map[c]) return false;\n    } else {\n      stack.push(c);\n    }\n  }\n  return stack.length === 0;\n}\n```\n\n**Min Stack:**\n```javascript\nclass MinStack {\n  constructor() { this.stack = []; this.minStack = []; }\n  push(x) {\n    this.stack.push(x);\n    if (!this.minStack.length || x <= this.minStack[this.minStack.length - 1])\n      this.minStack.push(x);\n  }\n  pop() {\n    const val = this.stack.pop();\n    if (val === this.minStack[this.minStack.length - 1]) this.minStack.pop();\n    return val;\n  }\n  getMin() { return this.minStack[this.minStack.length - 1]; }\n}\n```\n\n**Key Takeaways:**\n1. Stack is great for matching pairs\n2. Min stack tracks minimum in O(1)\n3. Use stack for nested structures' },
      { id: 'queue-applications', title: 'Queue Applications', content: '**BFS with Queue:**\n```javascript\nfunction bfs(graph, start) {\n  const visited = new Set();\n  const queue = [start];\n  visited.add(start);\n  while (queue.length) {\n    const node = queue.shift();\n    for (const neighbor of graph[node]) {\n      if (!visited.has(neighbor)) {\n        visited.add(neighbor);\n        queue.push(neighbor);\n      }\n    }\n  }\n  return visited;\n}\n```\n\n**Sliding Window Maximum:**\nUse deque (double-ended queue) for O(n) solution.\n\n**Key Takeaways:**\n1. Queue is essential for BFS\n2. Deque provides O(1) operations at both ends\n3. Queue preserves insertion order' }
    ]
  },
  {
    id: 1003, slug: 'dsa-trees', title: 'Trees and BST',
    description: 'Learn tree traversals, BST operations, and solve tree-based problems efficiently.',
    level: 'intermediate', duration: '50 min',
    objectives: ['Implement tree traversals (inorder, preorder, postorder)', 'Perform BST operations (insert, search, delete)', 'Solve tree problems using recursion', 'Understand balanced vs unbalanced trees'],
    quiz: [
      { id: 1, question: 'What is an inorder traversal of a BST?', options: ['Root, Left, Right', 'Left, Root, Right', 'Left, Right, Root', 'Root, Right, Left'], correctIndex: 1, explanation: 'Inorder traversal visits left subtree, then root, then right subtree, producing sorted order for BST.' },
      { id: 2, question: 'What is the time complexity of BST search?', options: ['O(1)', 'O(log n) average', 'O(n)', 'O(n log n)'], correctIndex: 1, explanation: 'BST search is O(log n) on average, O(n) worst case for unbalanced trees.' },
      { id: 3, question: 'When does BST search become O(n)?', options: ['Tree is balanced', 'Tree is skewed (like a linked list)', 'Tree has many nodes', 'Tree is empty'], correctIndex: 1, explanation: 'A skewed tree degrades to O(n) because each node has only one child.' }
    ],
    topics: [
      { id: 'tree-traversals', title: 'Tree Traversals', content: '**Types of Traversal:**\n\nInorder (Left, Root, Right):\n```javascript\nfunction inorder(root) {\n  if (!root) return [];\n  return [...inorder(root.left), root.val, ...inorder(root.right)];\n}\n```\n\nPreorder (Root, Left, Right):\n```javascript\nfunction preorder(root) {\n  if (!root) return [];\n  return [root.val, ...preorder(root.left), ...preorder(root.right)];\n}\n```\n\nPostorder (Left, Right, Root):\n```javascript\nfunction postorder(root) {\n  if (!root) return [];\n  return [...postorder(root.left), ...postorder(root.right), root.val];\n}\n```\n\n**Key Takeaways:**\n1. Inorder gives sorted order for BST\n2. Preorder is useful for serialization\n3. Postorder is useful for deletion' },
      { id: 'bst-operations', title: 'BST Operations', content: '**Insert:**\n```javascript\nfunction insert(root, val) {\n  if (!root) return new TreeNode(val);\n  if (val < root.val) root.left = insert(root.left, val);\n  else root.right = insert(root.right, val);\n  return root;\n}\n```\n\n**Search:**\n```javascript\nfunction search(root, val) {\n  if (!root || root.val === val) return root;\n  if (val < root.val) return search(root.left, val);\n  return search(root.right, val);\n}\n```\n\n**Delete:**\n1. No children: remove node\n2. One child: replace with child\n3. Two children: replace with inorder successor\n\n**Key Takeaways:**\n1. BST operations are O(log n) average\n2. Delete has three cases\n3. Inorder successor for two-child delete' },
      { id: 'tree-dfs', title: 'Tree DFS', content: '**DFS Pattern:**\n```javascript\nfunction dfs(root) {\n  if (!root) return null;\n  // Process root\n  const left = dfs(root.left);\n  const right = dfs(root.right);\n  // Return result\n  return result;\n}\n```\n\n**Max Depth:**\n```javascript\nfunction maxDepth(root) {\n  if (!root) return 0;\n  return 1 + Math.max(maxDepth(root.left), maxDepth(root.right));\n}\n```\n\n**Key Takeaways:**\n1. DFS uses recursion or explicit stack\n2. Choose traversal based on problem\n3. Process nodes at the right time' },
      { id: 'tree-bfs', title: 'Tree BFS', content: '**BFS Pattern:**\n```javascript\nfunction bfs(root) {\n  if (!root) return [];\n  const queue = [root];\n  const result = [];\n  while (queue.length) {\n    const level = [];\n    const size = queue.length;\n    for (let i = 0; i < size; i++) {\n      const node = queue.shift();\n      level.push(node.val);\n      if (node.left) queue.push(node.left);\n      if (node.right) queue.push(node.right);\n    }\n    result.push(level);\n  }\n  return result;\n}\n```\n\n**Key Takeaways:**\n1. BFS processes level by level\n2. Use queue for BFS\n3. Track level size for level-order traversal' }
    ]
  },
  {
    id: 1004, slug: 'dsa-graphs', title: 'Graph Algorithms',
    description: 'Master graph representations, traversals, and essential algorithms like DFS, BFS, and shortest path.',
    level: 'intermediate', duration: '50 min',
    objectives: ['Represent graphs using adjacency lists and matrices', 'Implement DFS and BFS traversals', 'Detect cycles in directed and undirected graphs', 'Find shortest paths using Dijkstra algorithm'],
    quiz: [
      { id: 1, question: 'What is the time complexity of BFS?', options: ['O(V)', 'O(V + E)', 'O(V * E)', 'O(V^2)'], correctIndex: 1, explanation: 'BFS visits every vertex and edge once, giving O(V + E) complexity.' },
      { id: 2, question: 'When would you use DFS over BFS?', options: ['Finding shortest path', 'Detecting cycles', 'Level-order traversal', 'Both are equivalent'], correctIndex: 1, explanation: 'DFS is often simpler for cycle detection and uses less memory.' },
      { id: 3, question: 'What data structure is used for BFS?', options: ['Stack', 'Queue', 'Priority Queue', 'Hash Set'], correctIndex: 1, explanation: 'BFS uses a queue to process nodes in FIFO order.' }
    ],
    topics: [
      { id: 'graph-representations', title: 'Graph Representations', content: '**Adjacency List:**\n```javascript\nconst graph = {\n  A: ["B", "C"],\n  B: ["A", "D"],\n  C: ["A", "D"],\n  D: ["B", "C"]\n};\n```\n\n**Adjacency Matrix:**\n```javascript\nconst matrix = [\n  [0, 1, 1, 0],\n  [1, 0, 0, 1],\n  [1, 0, 0, 1],\n  [0, 1, 1, 0]\n];\n```\n\n**Comparison:**\n| Operation | List | Matrix |\n|-----------|------|--------|\n| Space | O(V + E) | O(V^2) |\n| Add edge | O(1) | O(1) |\n| Remove edge | O(E) | O(1) |\n| Check edge | O(degree) | O(1) |\n\n**Key Takeaways:**\n1. Adjacency list is space-efficient for sparse graphs\n2. Matrix is better for dense graphs\n3. Choose based on edge density' },
      { id: 'graph-dfs', title: 'Graph DFS', content: '**DFS Implementation:**\n```javascript\nfunction dfs(graph, start, visited = new Set()) {\n  visited.add(start);\n  console.log(start);\n  for (const neighbor of graph[start]) {\n    if (!visited.has(neighbor)) {\n      dfs(graph, neighbor, visited);\n    }\n  }\n}\n```\n\n**Cycle Detection:**\n```javascript\nfunction hasCycle(graph) {\n  const visited = new Set();\n  const recursionStack = new Set();\n  \n  function dfs(node) {\n    visited.add(node);\n    recursionStack.add(node);\n    for (const neighbor of graph[node]) {\n      if (!visited.has(neighbor)) {\n        if (dfs(neighbor)) return true;\n      } else if (recursionStack.has(neighbor)) {\n        return true;\n      }\n    }\n    recursionStack.delete(node);\n    return false;\n  }\n  \n  for (const node of Object.keys(graph)) {\n    if (!visited.has(node) && dfs(node)) return true;\n  }\n  return false;\n}\n```\n\n**Key Takeaways:**\n1. DFS uses recursion or explicit stack\n2. Track visited nodes to avoid cycles\n3. recursionStack detects back edges' },
      { id: 'graph-bfs', title: 'Graph BFS', content: '**BFS Implementation:**\n```javascript\nfunction bfs(graph, start) {\n  const visited = new Set([start]);\n  const queue = [start];\n  const result = [];\n  while (queue.length) {\n    const node = queue.shift();\n    result.push(node);\n    for (const neighbor of graph[node]) {\n      if (!visited.has(neighbor)) {\n        visited.add(neighbor);\n        queue.push(neighbor);\n      }\n    }\n  }\n  return result;\n}\n```\n\n**Shortest Path (Unweighted):**\n```javascript\nfunction shortestPath(graph, start, end) {\n  const visited = new Map([[start, null]]);\n  const queue = [start];\n  while (queue.length) {\n    const node = queue.shift();\n    if (node === end) {\n      const path = [];\n      while (node) { path.unshift(node); node = visited.get(node); }\n      return path;\n    }\n    for (const neighbor of graph[node]) {\n      if (!visited.has(neighbor)) {\n        visited.set(neighbor, node);\n        queue.push(neighbor);\n      }\n    }\n  }\n  return [];\n}\n```\n\n**Key Takeaways:**\n1. BFS finds shortest path in unweighted graphs\n2. Track parents for path reconstruction\n3. Use queue for FIFO processing' },
      { id: 'dijkstra', title: 'Dijkstra Algorithm', content: '**Dijkstra Implementation:**\n```javascript\nfunction dijkstra(graph, start) {\n  const dist = {};\n  const prev = {};\n  const pq = new MinPriorityQueue();\n  \n  for (const node of Object.keys(graph)) {\n    dist[node] = Infinity;\n    prev[node] = null;\n  }\n  dist[start] = 0;\n  pq.enqueue(start, 0);\n  \n  while (!pq.isEmpty()) {\n    const { element: u } = pq.dequeue();\n    for (const [v, weight] of graph[u]) {\n      const alt = dist[u] + weight;\n      if (alt < dist[v]) {\n        dist[v] = alt;\n        prev[v] = u;\n        pq.enqueue(v, alt);\n      }\n    }\n  }\n  return { dist, prev };\n}\n```\n\n**When to Use:**\n- Weighted graphs\n- Non-negative weights\n- Single-source shortest path\n\n**Key Takeaways:**\n1. Dijkstra finds shortest path in weighted graphs\n2. O((V + E) log V) with priority queue\n3. Does not work with negative weights' }
    ]
  },
  {
    id: 1005, slug: 'dsa-dynamic-programming', title: 'Dynamic Programming',
    description: 'Learn to identify and solve dynamic programming problems with memoization and tabulation.',
    level: 'advanced', duration: '55 min',
    objectives: ['Identify problems suitable for dynamic programming', 'Implement memoization (top-down) approach', 'Implement tabulation (bottom-up) approach', 'Optimize space complexity in DP solutions'],
    quiz: [
      { id: 1, question: 'What are the two key properties of DP problems?', options: ['Sorting and searching', 'Optimal substructure and overlapping subproblems', 'Recursion and iteration', 'Arrays and objects'], correctIndex: 1, explanation: 'DP problems have optimal substructure and overlapping subproblems.' },
      { id: 2, question: 'What is memoization?', options: ['Storing results in an array', 'Caching results of function calls', 'Sorting before processing', 'Using recursion only'], correctIndex: 1, explanation: 'Memoization caches results of function calls to avoid redundant computation.' },
      { id: 3, question: 'When should you use tabulation over memoization?', options: ['Always', 'When recursion depth is too high', 'Never', 'When there are no overlapping subproblems'], correctIndex: 1, explanation: 'Tabulation avoids stack overflow for deep recursion and is often faster.' }
    ],
    topics: [
      { id: 'dp-concepts', title: 'DP Concepts', content: '**What is Dynamic Programming?**\nDP solves complex problems by breaking them into simpler subproblems, storing solutions to avoid redundant work.\n\n**Two Approaches:**\n1. Memoization (Top-Down): Recursive + cache\n2. Tabulation (Bottom-Up): Iterative + table\n\n**When to Use DP:**\n- Optimal substructure\n- Overlapping subproblems\n- Counting problems\n- Optimization problems\n\n**Key Takeaways:**\n1. DP trades space for time\n2. Identify overlapping subproblems first\n3. Choose top-down or bottom-up based on needs' },
      { id: 'memoization', title: 'Memoization', content: '**Fibonacci - Naive:**\n```javascript\nfunction fib(n) {\n  if (n <= 1) return n;\n  return fib(n - 1) + fib(n - 2);  // O(2^n)\n}\n```\n\n**Fibonacci - Memoized:**\n```javascript\nfunction fib(n, memo = {}) {\n  if (n in memo) return memo[n];\n  if (n <= 1) return n;\n  memo[n] = fib(n - 1, memo) + fib(n - 2, memo);\n  return memo[n];\n}  // O(n)\n```\n\n**Key Takeaways:**\n1. Memoization caches recursive results\n2. Reduces exponential to polynomial\n3. Easy to implement from naive recursion' },
      { id: 'tabulation', title: 'Tabulation', content: '**Fibonacci - Tabulation:**\n```javascript\nfunction fib(n) {\n  if (n <= 1) return n;\n  const dp = [0, 1];\n  for (let i = 2; i <= n; i++) {\n    dp[i] = dp[i - 1] + dp[i - 2];\n  }\n  return dp[n];\n}\n```\n\n**Space Optimized:**\n```javascript\nfunction fib(n) {\n  if (n <= 1) return n;\n  let prev = 0, curr = 1;\n  for (let i = 2; i <= n; i++) {\n    [prev, curr] = [curr, prev + curr];\n  }\n  return curr;\n}\n```\n\n**Key Takeaways:**\n1. Tabulation builds solution from base cases\n2. Often more space-efficient\n3. Can be optimized by keeping only needed values' },
      { id: 'classic-dp', title: 'Classic DP Problems', content: '**Coin Change:**\n```javascript\nfunction coinChange(coins, amount) {\n  const dp = Array(amount + 1).fill(Infinity);\n  dp[0] = 0;\n  for (let i = 1; i <= amount; i++) {\n    for (const coin of coins) {\n      if (coin <= i && dp[i - coin] + 1 < dp[i]) {\n        dp[i] = dp[i - coin] + 1;\n      }\n    }\n  }\n  return dp[amount] === Infinity ? -1 : dp[amount];\n}\n```\n\n**Longest Common Subsequence:**\n```javascript\nfunction lcs(s1, s2) {\n  const m = s1.length, n = s2.length;\n  const dp = Array(m + 1).fill(null).map(() => Array(n + 1).fill(0));\n  for (let i = 1; i <= m; i++) {\n    for (let j = 1; j <= n; j++) {\n      if (s1[i-1] === s2[j-1]) dp[i][j] = dp[i-1][j-1] + 1;\n      else dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);\n    }\n  }\n  return dp[m][n];\n}\n```\n\n**Key Takeaways:**\n1. Coin change uses 1D DP\n2. LCS uses 2D DP\n3. Identify state and transitions' }
    ]
  },
  {
    id: 1006, slug: 'dsa-sorting', title: 'Sorting Algorithms',
    description: 'Understand and implement major sorting algorithms, their trade-offs, and when to use each.',
    level: 'intermediate', duration: '45 min',
    objectives: ['Implement bubble sort, selection sort, and insertion sort', 'Implement merge sort and quicksort', 'Compare sorting algorithm trade-offs', 'Choose the right sorting algorithm for different scenarios'],
    quiz: [
      { id: 1, question: 'What is the average time complexity of quicksort?', options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)'], correctIndex: 1, explanation: 'Quicksort has O(n log n) average time complexity.' },
      { id: 2, question: 'Which sorting algorithm is stable?', options: ['Quicksort', 'Heapsort', 'Merge sort', 'Selection sort'], correctIndex: 2, explanation: 'Merge sort is stable because it preserves the relative order of equal elements.' },
      { id: 3, question: 'When would you use insertion sort?', options: ['Large datasets', 'Nearly sorted small datasets', 'Random order', 'Never'], correctIndex: 1, explanation: 'Insertion sort is efficient for nearly sorted or small datasets.' }
    ],
    topics: [
      { id: 'comparison-based', title: 'Comparison Based Sorting', content: '**Bubble Sort:**\n```javascript\nfunction bubbleSort(arr) {\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = 0; j < arr.length - i - 1; j++) {\n      if (arr[j] > arr[j + 1]) {\n        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];\n      }\n    }\n  }\n  return arr;\n}\n```\n\n**Selection Sort:**\n```javascript\nfunction selectionSort(arr) {\n  for (let i = 0; i < arr.length; i++) {\n    let minIdx = i;\n    for (let j = i + 1; j < arr.length; j++) {\n      if (arr[j] < arr[minIdx]) minIdx = j;\n    }\n    [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];\n  }\n  return arr;\n}\n```\n\n**Key Takeaways:**\n1. Bubble and selection sort are O(n^2)\n2. Insertion sort is best for small/nearly sorted data\n3. All are in-place but not efficient for large data' },
      { id: 'efficient-sorting', title: 'Efficient Sorting', content: '**Merge Sort:**\n```javascript\nfunction mergeSort(arr) {\n  if (arr.length <= 1) return arr;\n  const mid = Math.floor(arr.length / 2);\n  const left = mergeSort(arr.slice(0, mid));\n  const right = mergeSort(arr.slice(mid));\n  return merge(left, right);\n}\nfunction merge(l, r) {\n  const result = [];\n  let i = 0, j = 0;\n  while (i < l.length && j < r.length) {\n    result.push(l[i] <= r[j] ? l[i++] : r[j++]);\n  }\n  return result.concat(l.slice(i), r.slice(j));\n}\n```\n\n**Quicksort:**\n```javascript\nfunction quickSort(arr) {\n  if (arr.length <= 1) return arr;\n  const pivot = arr[Math.floor(arr.length / 2)];\n  const left = arr.filter(x => x < pivot);\n  const mid = arr.filter(x => x === pivot);\n  const right = arr.filter(x => x > pivot);\n  return [...quickSort(left), ...mid, ...quickSort(right)];\n}\n```\n\n**Key Takeaways:**\n1. Merge sort: O(n log n) stable, O(n) space\n2. Quicksort: O(n log n) average, in-place\n3. Both are divide-and-conquer' },
      { id: 'space-complexity', title: 'Space Complexity', content: '**In-Place vs Out-of-Place:**\n\n| Algorithm | Time | Space | Stable |\n|-----------|------|-------|--------|\n| Bubble | O(n^2) | O(1) | Yes |\n| Selection | O(n^2) | O(1) | No |\n| Insertion | O(n^2) | O(1) | Yes |\n| Merge | O(n log n) | O(n) | Yes |\n| Quick | O(n log n) avg | O(log n) | No |\n| Heap | O(n log n) | O(1) | No |\n\n**Key Takeaways:**\n1. In-place algorithms use O(1) extra space\n2. Merge sort uses O(n) space\n3. Trade-off between time and space' },
      { id: 'choosing-sort', title: 'Choosing a Sort', content: '**Decision Guide:**\n\nSmall data (n < 50): Insertion sort\nNearly sorted: Insertion sort\nGeneral purpose: Quicksort or Timsort\nNeed stability: Merge sort\nMemory constrained: Heapsort\n\n**JavaScript Built-in:**\nArray.prototype.sort() uses Timsort (O(n log n))\n\n**Key Takeaways:**\n1. Consider data size and characteristics\n2. Use built-in sort for most cases\n3. Know the trade-offs for interviews' }
    ]
  },
  {
    id: 1007, slug: 'dsa-searching', title: 'Binary Search',
    description: 'Master binary search and its variations for efficient searching in sorted data.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Implement standard binary search', 'Solve search variations (first/last occurrence, peak element)', 'Apply binary search on answer space', 'Identify when binary search is applicable'],
    quiz: [
      { id: 1, question: 'What is the prerequisite for binary search?', options: ['Array must be unsorted', 'Array must be sorted', 'Array must be small', 'Array must have unique elements'], correctIndex: 1, explanation: 'Binary search requires sorted data to work correctly.' },
      { id: 2, question: 'What is binary search on answer space?', options: ['Searching for an index', 'Searching for a value in range [lo, hi]', 'Sorting first then searching', 'Searching in a string'], correctIndex: 1, explanation: 'Binary search on answer space finds the optimal value in a range.' },
      { id: 3, question: 'How do you handle integer overflow in mid calculation?', options: ['Use BigInt', 'mid = lo + (hi - lo) / 2', 'Use Math.floor', 'It never happens'], correctIndex: 1, explanation: 'Using lo + (hi - lo) / 2 prevents overflow instead of (lo + hi) / 2.' }
    ],
    topics: [
      { id: 'basic-binary-search', title: 'Basic Binary Search', content: '**Standard Implementation:**\n```javascript\nfunction binarySearch(arr, target) {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = lo + Math.floor((hi - lo) / 2);\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}\n```\n\n**Key Takeaways:**\n1. O(log n) time complexity\n2. Use lo + (hi - lo) / 2 to avoid overflow\n3. Maintain loop invariant' },
      { id: 'search-variations', title: 'Search Variations', content: '**First Occurrence:**\n```javascript\nfunction firstOccurrence(arr, target) {\n  let lo = 0, hi = arr.length - 1, result = -1;\n  while (lo <= hi) {\n    const mid = lo + Math.floor((hi - lo) / 2);\n    if (arr[mid] === target) { result = mid; hi = mid - 1; }\n    else if (arr[mid] < target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return result;\n}\n```\n\n**Peak Element:**\n```javascript\nfunction findPeak(arr) {\n  let lo = 0, hi = arr.length - 1;\n  while (lo < hi) {\n    const mid = lo + Math.floor((hi - lo) / 2);\n    if (arr[mid] < arr[mid + 1]) lo = mid + 1;\n    else hi = mid;\n  }\n  return lo;\n}\n```\n\n**Key Takeaways:**\n1. Modify comparison based on what you seek\n2. First/last occurrence: continue after finding\n3. Peak element: choose direction based on slope' },
      { id: 'binary-search-answer', title: 'Binary Search on Answer', content: '**Concept:**\nInstead of searching an array, search the answer space [lo, hi].\n\n**Example - Minimum K:**\nFind minimum value k such that condition(k) is true.\n```javascript\nfunction minK(lo, hi) {\n  while (lo < hi) {\n    const mid = lo + Math.floor((hi - lo) / 2);\n    if (condition(mid)) hi = mid;\n    else lo = mid + 1;\n  }\n  return lo;\n}\n```\n\n**Key Takeaways:**\n1. Binary search on monotonic functions\n2. Define clear condition function\n3. Choose lo, hi, and direction carefully' },
      { id: 'common-patterns', title: 'Common Patterns', content: '**Rotated Array Search:**\n```javascript\nfunction searchRotated(arr, target) {\n  let lo = 0, hi = arr.length - 1;\n  while (lo <= hi) {\n    const mid = lo + Math.floor((hi - lo) / 2);\n    if (arr[mid] === target) return mid;\n    if (arr[lo] <= arr[mid]) {\n      if (target >= arr[lo] && target < arr[mid]) hi = mid - 1;\n      else lo = mid + 1;\n    } else {\n      if (target > arr[mid] && target <= arr[hi]) lo = mid + 1;\n      else hi = mid - 1;\n    }\n  }\n  return -1;\n}\n```\n\n**Key Takeaways:**\n1. Binary search works on rotated sorted arrays\n2. Determine which half is sorted\n3. Check if target lies in the sorted half' }
    ]
  }
];
