import { Lesson } from '../models/lesson.model';

export const NETWORKING_LESSONS: Lesson[] = [
  {
    id: 940, slug: 'net-http', title: 'HTTP/HTTPS Fundamentals',
    description: 'Master the foundation of web communication — HTTP methods, status codes, headers, HTTPS security, and modern HTTP protocols.',
    level: 'beginner', duration: '40 min',
    objectives: ['Understand HTTP request/response lifecycle and methods', 'Identify and use appropriate HTTP status codes', 'Configure HTTP headers for security and performance'],
    quiz: [
      { id: 1, question: 'Which HTTP method is used to create a new resource?', options: ['GET', 'POST', 'PUT', 'DELETE'], correctIndex: 1, explanation: 'POST is used to create a new resource. GET retrieves, PUT replaces, and DELETE removes resources.' },
      { id: 2, question: 'What does the 304 status code indicate?', options: ['Resource moved permanently', 'Not modified — use cached version', 'Internal server error', 'Unauthorized access'], correctIndex: 1, explanation: '304 Not Modified means the resource has not changed since the last request, so the browser can use its cached copy.' },
      { id: 3, question: 'What is the primary advantage of HTTP/2 over HTTP/1.1?', options: ['Larger headers', 'Multiplexing multiple requests over a single connection', 'Plain text instead of binary', 'No need for TLS'], correctIndex: 1, explanation: 'HTTP/2 introduced multiplexing, allowing multiple requests and responses simultaneously over a single TCP connection.' }
    ],
    topics: [
      {
        id: 'http-methods', title: 'HTTP Methods',
        content: 'HTTP defines several request methods that indicate the desired action on a resource. GET retrieves data without side effects and is idempotent, meaning repeated calls produce the same result. POST creates new resources and is not idempotent — retrying may create duplicates. PUT replaces a resource entirely and is idempotent. PATCH partially updates a resource. DELETE removes a resource and is idempotent. HEAD returns only headers, useful for checking if a resource exists. OPTIONS returns allowed methods for a resource, critical for CORS preflight requests. In Angular, the HttpClient provides methods for each: this.http.get(), this.http.post(), this.http.put(), this.http.patch(), this.http.delete(). Understanding idempotency is crucial for designing reliable APIs — idempotent methods (GET, PUT, DELETE) are safe to retry on network failures.'
      },
      {
        id: 'status-codes', title: 'HTTP Status Codes',
        content: 'Status codes communicate the result of an HTTP request. The 1xx range indicates informational responses like 100 Continue. The 2xx range signals success: 200 OK is the standard success response, 201 Created is returned after successful resource creation via POST, and 204 No Content indicates success with no response body. The 3xx range handles redirection: 301 Moved Permanently tells clients to update bookmarks, 304 Not Modified enables conditional caching with ETags. The 4xx range represents client errors: 400 Bad Request for invalid syntax, 401 Unauthorized for authentication required, 403 Forbidden for authorization failures, 404 Not Found when resources do not exist, 409 Conflict for state conflicts, and 429 Too Many Requests for rate limiting. The 5xx range covers server errors: 500 Internal Server Error for unexpected failures and 503 Service Unavailable when servers are temporarily overloaded.'
      },
      {
        id: 'https-tls', title: 'HTTPS and TLS',
        content: 'HTTPS wraps HTTP in TLS (Transport Layer Security) encryption. The TLS handshake begins with a ClientHello message listing supported cipher suites. The server responds with its certificate and chosen cipher suite. The client verifies the certificate chain against trusted Certificate Authorities. Both parties perform key exchange to establish a shared secret. TLS 1.3, the latest version, reduces the handshake to a single round-trip (1-RTT) and supports 0-RTT resumption for returning connections. HSTS (HTTP Strict Transport Security) forces browsers to use HTTPS exclusively: Strict-Transport-Security: max-age=31536000; includeSubDomains. Modern certificates from Let Encrypt are free and auto-renew via certbot. Always redirect HTTP to HTTPS and enable HSTS with a long max-age. Monitor certificate expiry to prevent outages.'
      },
      {
        id: 'http2-http3', title: 'HTTP/2 and HTTP/3',
        content: 'HTTP/2 solves HTTP/1.1 limitations with multiplexing — multiple requests and responses travel simultaneously over a single TCP connection, eliminating head-of-line blocking at the HTTP layer. It uses binary framing instead of text, HPACK header compression, and can push resources proactively via server push. HTTP/3 builds on QUIC instead of TCP, eliminating TCP-level head-of-line blocking entirely. QUIC combines transport and encryption in one protocol, enabling faster connection establishment with 0-RTT. HTTP/3 performs better on lossy networks since packet loss on one stream does not block others. To enable HTTP/2 in nginx, use listen 443 ssl http2. For HTTP/3, use listen 443 quic reuseport with the Alt-Svc header. All modern browsers support both protocols, making them essential for performance optimization.'
      }
    ]
  },
  {
    id: 941, slug: 'net-rest', title: 'REST API Design',
    description: 'Design well-structured REST APIs — resource naming, HTTP methods, pagination, versioning, and error handling best practices.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Apply REST principles to design clean API interfaces', 'Use proper resource naming conventions and HTTP methods', 'Implement pagination, filtering, and sorting patterns'],
    quiz: [
      { id: 1, question: 'What makes an API RESTful?', options: ['Uses JSON exclusively', 'Follows REST constraints including statelessness and resource-based URLs', 'Must use POST for all operations', 'Requires a specific database'], correctIndex: 1, explanation: 'REST is an architectural style defined by constraints like statelessness, client-server separation, uniform interface, and resource-based URLs.' },
      { id: 2, question: 'What is the correct URL for fetching a specific user\'s orders?', options: ['/getUserOrders?id=123', '/users/123/orders', '/orders?userId=123', '/user/123/getOrders'], correctIndex: 1, explanation: 'REST uses nested resources: /users/{userId}/orders expresses the relationship hierarchically and predictably.' },
      { id: 3, question: 'What does statelessness mean in REST?', options: ['Server cannot maintain sessions', 'Each request contains all information needed to process it', 'API cannot have a database', 'Clients cannot send state in bodies'], correctIndex: 1, explanation: 'Statelessness means each request must contain all information needed to process it — the server stores no client context between requests.' }
    ],
    topics: [
      {
        id: 'rest-principles', title: 'REST Principles',
        content: 'REST (Representational State Transfer) is an architectural style with six constraints. Client-Server separates UI from data storage, enabling independent evolution. Statelessness means every request contains all necessary information — the server stores no client context. Cacheable responses must declare themselves cacheable or not. Uniform Interface defines four sub-constraints: resource identification via URIs, resource manipulation through representations, self-descriptive messages, and HATEOAS (Hypermedia as the Engine of Application State). Layered System allows clients to interact with intermediaries like load balancers or CDNs without knowing the direct server. Code on Demand is optional — servers can temporarily extend client functionality. Applying these constraints produces APIs that are scalable, maintainable, and evolvable. Resource-based design means URLs represent nouns (/users, /orders) and HTTP methods represent verbs (GET, POST, PUT, DELETE).'
      },
      {
        id: 'resource-naming', title: 'Resource Naming',
        content: 'REST resource naming follows predictable conventions. Use plural nouns for collections: /users for all users, /users/123 for user with ID 123. Express relationships through nesting: /users/123/orders for orders belonging to user 123, /products/456/reviews for reviews of product 456. Avoid verbs in URLs — instead of /getUsers or /createOrder, use GET /users and POST /orders. Use query parameters for filtering: /users?status=active, /products?category=electronics&sort=price. For actions that do not map cleanly to CRUD, use sub-resources: POST /users/123/activate instead of PUT /users/123 with an active flag. Search endpoints use a dedicated path: /users?q=john or /search/products?q=laptop. Keep URLs shallow — prefer /users/123 over /api/v1/organization/456/department/789/users/123. Case conventions typically use kebab-case for multi-word segments: /user-profiles, not /userProfiles.'
      },
      {
        id: 'pagination', title: 'Pagination Patterns',
        content: 'Pagination prevents returning entire datasets in a single response. Offset-based pagination uses offset and limit parameters: /users?offset=0&limit=20 for the first page, offset=20 for the second. It is simple but can skip or duplicate items when data changes between requests. Cursor-based pagination uses an opaque cursor returned in the response: /users?cursor=abc123&limit=20. The cursor encodes the position and is stable across data changes, making it reliable for real-time data. Page-based pagination serves UI pagination controls: /users?page=3&perPage=20 with total count in the response. Every paginated response should include metadata: total count, hasMore flag, nextCursor or next page number. Limit defaults to 20-50 items to balance completeness with performance. Always cap the maximum limit to prevent abuse — enforce a server-side maximum of 100 items per request.'
      },
      {
        id: 'versioning', title: 'API Versioning',
        content: 'API versioning manages breaking changes without disrupting existing clients. URL path versioning is most common and explicit: /api/v1/users, /api/v2/users. It is cacheable, discoverable, and simple to implement. Header versioning uses Accept or custom headers: Accept: application/vnd.myapp.v2+json. It keeps URLs clean but is less discoverable. Query parameter versioning adds ?version=2 — simple but not cacheable. For deprecation, provide 6-12 months notice, add Sunset and Deprecation headers, return 410 Gone for removed endpoints, and publish migration guides. In Angular, create an HttpInterceptor that prefixes URLs with the current API version. Consider content negotiation over versioning when possible — new fields in responses are backward-compatible and do not require version bumps. Only create new versions when you must change or remove existing fields or break response structures.'
      }
    ]
  },
  {
    id: 942, slug: 'net-graphql', title: 'GraphQL',
    description: 'Learn GraphQL — schema definition, queries, mutations, subscriptions, and integrating Apollo Client in Angular applications.',
    level: 'intermediate', duration: '45 min',
    objectives: ['Define GraphQL schemas with types, queries, and mutations', 'Write efficient queries to fetch exactly the data needed', 'Implement real-time updates with GraphQL subscriptions'],
    quiz: [
      { id: 1, question: 'What is the main advantage of GraphQL over REST?', options: ['Faster server response times', 'Clients request exactly the data they need', 'Does not require a server', 'Uses less bandwidth automatically'], correctIndex: 1, explanation: 'GraphQL lets clients specify exactly what fields they need, avoiding over-fetching and under-fetching.' },
      { id: 2, question: 'What is a GraphQL mutation used for?', options: ['Reading data', 'Modifying server-side data (create, update, delete)', 'Subscribing to real-time updates', 'Defining the schema'], correctIndex: 1, explanation: 'Mutations modify server-side data — equivalent to POST/PUT/DELETE in REST.' },
      { id: 3, question: 'What is the N+1 problem in GraphQL?', options: ['Having N+1 schema definitions', 'Making N+1 database queries to resolve a list of items', 'N+1 client connections', 'N+1 resolver functions'], correctIndex: 1, explanation: 'The N+1 problem occurs when resolving N items triggers N additional queries instead of a single batched query.' }
    ],
    topics: [
      {
        id: 'schema-definition', title: 'Schema Definition',
        content: 'A GraphQL schema defines the types, queries, mutations, and subscriptions available. Types describe data shapes: type User { id: ID!, name: String!, email: String!, posts: [Post!]! }. The ! marker indicates non-nullable fields. Query type defines read operations: type Query { users(limit: Int): [User!]!, user(id: ID!): User }. Mutation type defines write operations: type Mutation { createUser(input: CreateUserInput!): User! }. Input types separate mutation input from output types, preventing clients from sending unexpected fields. Custom scalars handle complex types like DateTime, JSON, or URL. Enums restrict values to a predefined set: enum Role { ADMIN, USER, GUEST }. Interfaces define shared fields across types. Unions allow a field to return one of several types. The schema is the contract between client and server — any query that violates the schema is rejected before reaching resolvers.'
      },
      {
        id: 'queries-mutations', title: 'Queries and Mutations',
        content: 'Queries fetch data with precise field selection: query GetUser { user(id: "123") { name, email, posts { title } } }. The client requests only the fields it needs. Variables make queries dynamic: query GetUser($id: ID!) { user(id: $id) { name } } — never interpolate values directly into query strings. Fragments promote reusability: fragment UserFields on User { id, name, email } can be spread into any query. Mutations modify data and return the updated object: mutation CreatePost($input: CreatePostInput!) { createPost(input: $input) { id, title, author { name } } }. In Angular with Apollo, use the gql tag to define queries: const GET_USERS = gql(\'query GetUsers { users { id, name } }\'); The Apollo service provides watchQuery for observable streams and mutate for one-off mutations. Always handle loading, error, and data states in components.'
      },
      {
        id: 'subscriptions', title: 'GraphQL Subscriptions',
        content: 'Subscriptions provide real-time data updates over WebSockets. Define them like queries: subscription OnNewPost { postCreated { id, title, author { name } } }. The server publishes events using a PubSub system — when a mutation creates a post, it publishes to a channel. Clients subscribe to that channel and receive updates instantly. In Angular, subscribe using Apollo: this.apollo.subscribe({ query: ON_POST_CREATED }).subscribe(result => { this.posts.unshift(result.data.postCreated); }). Always unsubscribe in ngOnDestroy to prevent memory leaks. Socket.io provides the WebSocket transport with automatic reconnection. Configure the WebSocket link in Apollo setup with reconnect: true. Subscriptions are ideal for chat applications, live dashboards, collaborative editing, and notification feeds. For low-frequency updates, consider polling instead — subscriptions add WebSocket connection overhead.'
      },
      {
        id: 'apollo-angular', title: 'Apollo Client Integration',
        content: 'Apollo Client integrates GraphQL with Angular through dependency injection and observables. Install with ng add apollo-angular and configure in app.config.ts with provideApollo. The HttpLink connects to your GraphQL endpoint, and InMemoryCache stores query results. watchQuery returns an Observable that emits data, loading, and error states: this.apollo.watchQuery({ query: GET_USERS }).valueChanges.subscribe(). For mutations, use mutate which returns a Promise: this.apollo.mutate({ mutation: CREATE_USER, variables: { input } }). Optimistic updates provide instant UI feedback — specify the expected result before the server responds, then reconcile with actual data. Cache updates after mutations keep the UI consistent: read existing data from cache, add the new item, and writeQuery back. Error handling uses the error property from valueChanges or catchError in the observable pipe. Apollo DevTools browser extension helps debug queries, cache, and network requests.'
      }
    ]
  },
  {
    id: 943, slug: 'net-websockets', title: 'WebSockets & Real-time',
    description: 'Build real-time features with WebSockets, Socket.io, and Server-Sent Events — chat, live updates, and collaborative editing.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Establish and manage WebSocket connections in Angular', 'Implement Socket.io for real-time bidirectional communication', 'Use Server-Sent Events for server-to-client streaming'],
    quiz: [
      { id: 1, question: 'How does a WebSocket differ from HTTP?', options: ['Faster HTTP requests', 'Maintains a persistent, bidirectional connection', 'Only supports GET requests', 'Does not need a server'], correctIndex: 1, explanation: 'WebSockets upgrade an HTTP connection to a persistent, full-duplex connection for bidirectional messaging.' },
      { id: 2, question: 'When should you use SSE instead of WebSockets?', options: ['Bidirectional communication needed', 'Only server-to-client streaming needed', 'Maximum throughput needed', 'Binary data transfer needed'], correctIndex: 1, explanation: 'SSE is ideal for one-way server-to-client streaming — it is simpler, auto-reconnects, and works over standard HTTP.' },
      { id: 3, question: 'What is the purpose of Socket.io rooms?', options: ['Store user data', 'Create isolated communication channels for groups of clients', 'Manage database connections', 'Cache messages'], correctIndex: 1, explanation: 'Rooms broadcast messages to specific subsets of connected clients — useful for chat rooms, channels, or per-user notifications.' }
    ],
    topics: [
      {
        id: 'websocket-protocol', title: 'WebSocket Protocol',
        content: 'WebSockets start as HTTP connections and upgrade via the Upgrade header. The client sends an HTTP request with Connection: Upgrade and Upgrade: websocket headers. The server responds with 101 Switching Protocols, establishing a persistent bidirectional connection. Unlike HTTP, messages flow freely in both directions without request-response overhead. Native WebSocket in JavaScript: const ws = new WebSocket("ws://localhost:3000"); ws.onopen handles connection establishment, ws.onmessage receives data, ws.onerror handles failures, and ws.onclose manages disconnection. Messages are sent with ws.send(JSON.stringify(data)). In Angular, wrap WebSocket in an Angular service with a Subject for observable message streams. Always handle the onclose event for cleanup and reconnection. WebSocket connections are not limited by the browser connection pool like HTTP — you can maintain many concurrent connections.'
      },
      {
        id: 'socketio', title: 'Socket.io Integration',
        content: 'Socket.io adds reliability and features on top of raw WebSockets. It provides automatic reconnection with backoff, room-based broadcasting, namespace isolation, and fallback to HTTP long-polling. Server setup: const io = new Server(3000, { cors: { origin: "http://localhost:4200" } }). Rooms let you group clients: socket.join("room-1") adds a client to a room, io.to("room-1").emit("message", data) broadcasts to all clients in that room. Namespaces separate concerns — /chat and /notifications can have different handlers. In Angular, use the socket.io-client package: this.socket = io("http://localhost:3000"). Listen with this.socket.on("event", callback) and emit with this.socket.emit("event", data). Handle connection errors with this.socket.on("connect_error"). Disconnect gracefully in ngOnDestroy: this.socket.disconnect(). Socket.io handles binary data, acknowledgments, and middleware for authentication.'
      },
      {
        id: 'server-sent-events', title: 'Server-Sent Events (SSE)',
        content: 'SSE provides one-way server-to-client streaming over standard HTTP. The server sets Content-Type: text/event-stream and sends events in the format: data: {"message": "hello"}\\n\\n. Events can include an event type, retry interval, and ID. The browser receives events through the EventSource API: const source = new EventSource("/api/events"); source.onmessage = handler. In Angular, wrap EventSource in an Observable for RxJS integration. SSE automatically reconnects after connection loss — the server can control reconnection timing with the retry field. SSE works through proxies and load balancers that may block WebSocket upgrades. SSE has a connection limit of 6 per domain in HTTP/1.1, mitigated by HTTP/2. Use SSE for live feeds, notifications, stock tickers, and log streaming. For bidirectional communication, use WebSockets instead. SSE is simpler to implement and debug than WebSockets.'
      },
      {
        id: 'reconnection', title: 'Reconnection Strategies',
        content: 'Robust reconnection handles network disruptions gracefully. Exponential backoff starts with a 1-second delay and doubles on each attempt, capping at 30 seconds: delay = Math.min(delay * 2, 30000). This prevents overwhelming the server during outages. Add jitter (random variation) to prevent thundering herd when many clients reconnect simultaneously: delay = delay + random(0, 1000). Track connection state with a BehaviorSubject: status$ = new BehaviorSubject("disconnected") — components can reactively show connection status. Socket.io provides built-in reconnection with configurable parameters: reconnectionDelay, reconnectionDelayMax, reconnectionAttempts. For WebSocket reconnection, store the last message ID to resume from where the connection dropped. Implement a heartbeat mechanism — send ping messages every 30 seconds and close the connection if no pong is received within 10 seconds. Visual indicators in the UI build user trust during temporary disconnections.'
      }
    ]
  },
  {
    id: 944, slug: 'net-cors', title: 'CORS & Security Headers',
    description: 'Understand and configure Cross-Origin Resource Sharing, Content Security Policy, HSTS, and other security headers.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Configure CORS correctly for development and production', 'Understand preflight requests and when they occur', 'Implement Content Security Policy to prevent XSS'],
    quiz: [
      { id: 1, question: 'When does a browser send a CORS preflight request?', options: ['For every cross-origin request', 'For simple GET requests only', 'For requests with non-standard headers or methods like PUT/DELETE', 'Only when cookies are included'], correctIndex: 2, explanation: 'Preflight (OPTIONS) is sent for non-simple requests — those with custom headers, non-standard methods, or non-standard content types.' },
      { id: 2, question: 'What does Content-Security-Policy protect against?', options: ['SQL injection', 'Cross-Site Scripting (XSS)', 'Man-in-the-middle attacks', 'Denial of service'], correctIndex: 1, explanation: 'CSP restricts which resources can be loaded, preventing XSS by blocking unauthorized script execution.' },
      { id: 3, question: 'What does Access-Control-Allow-Origin: * mean?', options: ['All origins blocked', 'Only HTTPS allowed', 'Any origin can make cross-origin requests', 'Only localhost allowed'], correctIndex: 2, explanation: 'The wildcard allows any origin. Never use with credentials (cookies, Authorization headers).' }
    ],
    topics: [
      {
        id: 'cors-preflight', title: 'CORS Preflight Requests',
        content: 'CORS (Cross-Origin Resource Sharing) is a browser security mechanism restricting cross-origin HTTP requests. The same-origin policy blocks requests to different protocol, host, or port combinations. Simple requests (GET, HEAD, POST with standard headers) proceed directly. Non-simple requests trigger a preflight: the browser sends an OPTIONS request to the server, including Access-Control-Request-Method and Access-Control-Request-Headers. The server responds with allowed origins, methods, and headers. If approved, the browser sends the actual request. Preflight responses can be cached with Access-Control-Max-Age (e.g., 86400 seconds = 1 day), reducing overhead. In development, Angular CLI proxy (proxy.conf.json) bypasses CORS by proxying requests through the same origin. In production, configure your API server or CDN to return appropriate CORS headers. The preflight adds one round-trip of latency — minimize non-simple headers when performance is critical.'
      },
      {
        id: 'access-control-headers', title: 'Access-Control Headers',
        content: 'CORS headers control cross-origin access. Access-Control-Allow-Origin specifies which origins can access the resource — use a specific origin, not *, when credentials are involved. Access-Control-Allow-Methods lists permitted HTTP methods (GET, POST, PUT, DELETE, OPTIONS). Access-Control-Allow-Headers specifies which request headers are allowed (Content-Type, Authorization, X-Custom-Header). Access-Control-Allow-Credentials: true enables sending cookies and Authorization headers. Access-Control-Max-Age caches preflight responses. Access-Control-Expose-Headers makes custom response headers readable by JavaScript (Content-Disposition, X-Request-Id). The Vary header tells caches to key on Origin — Vary: Origin prevents serving cached responses to wrong origins. In nginx, use conditional blocks to handle OPTIONS preflight and set headers for actual requests. Common mistake: returning Access-Control-Allow-Origin: * with credentials — browsers reject this combination.'
      },
      {
        id: 'csp-headers', title: 'Content Security Policy (CSP)',
        content: 'CSP is an HTTP response header that restricts which resources the browser is allowed to load. It prevents XSS, clickjacking, and data injection attacks. Directives control different resource types: default-src sets the fallback, script-src controls JavaScript, style-src controls CSS, img-src controls images, connect-src controls XHR/fetch/WebSocket, and frame-ancestors controls embedding. Start with Content-Security-Policy-Report-Only to test without breaking functionality — the browser reports violations without blocking. Replace unsafe-inline with nonces or hashes for inline scripts: script-src \'self\' \'nonce-abc123\'. Use \'strict-dynamic\' to trust scripts loaded by already-trusted scripts. Report violations to a endpoint with report-uri or report-to. CSP is one of the most effective defenses against XSS — combine it with input validation and output encoding for defense in depth.'
      },
      {
        id: 'hsts-security', title: 'HSTS and Security Headers',
        content: 'HSTS (HTTP Strict Transport Security) forces browsers to use HTTPS for all future requests to a domain. The header Strict-Transport-Security: max-age=31536000; includeSubDomains; preload instructs browsers to remember HTTPS-only for 1 year, apply to all subdomains, and include in browser preload lists. X-Content-Type-Options: nosniff prevents MIME type sniffing. X-Frame-Options: DENY or SAMEORIGIN prevents clickjacking (superseded by CSP frame-ancestors). Referrer-Policy controls how much referrer information is sent. Permissions-Policy restricts browser features: camera, microphone, geolocation. Cross-Origin-Opener-Policy: same-origin isolates browsing contexts. Cross-Origin-Embedder-Policy: require-corp enables cross-origin isolation for SharedArrayBuffer. Set all headers on every response, including error pages. Use ngsw-config.json or server configuration to ensure security headers are applied consistently. HSTS preload submission is permanent — verify all subdomains support HTTPS first.'
      }
    ]
  },
  {
    id: 945, slug: 'net-caching', title: 'Caching Strategies',
    description: 'Master HTTP caching with Cache-Control headers, ETags, service worker caching, and CDN strategies.',
    level: 'advanced', duration: '40 min',
    objectives: ['Configure Cache-Control headers for different resource types', 'Implement ETag-based conditional requests', 'Design service worker caching strategies'],
    quiz: [
      { id: 1, question: 'What is the difference between no-cache and no-store?', options: ['Identical', 'no-cache allows caching but requires revalidation, no-store prevents caching entirely', 'no-cache is more secure', 'no-store is faster'], correctIndex: 1, explanation: 'no-cache allows the response to be cached but requires revalidation. no-store prevents caching entirely.' },
      { id: 2, question: 'What is the purpose of an ETag?', options: ['Cache responses permanently', 'Validate if a cached response is still fresh', 'Compress response bodies', 'Encrypt responses'], correctIndex: 1, explanation: 'An ETag is a unique identifier for a resource version. The browser sends it back to check if the cached version is still valid.' },
      { id: 3, question: 'Which strategy serves cached content immediately while updating in the background?', options: ['Cache First', 'Network First', 'Stale While Revalidate', 'Network Only'], correctIndex: 2, explanation: 'Stale While Revalidate returns cached content immediately while fetching an updated version in the background.' }
    ],
    topics: [
      {
        id: 'cache-control', title: 'Cache-Control Headers',
        content: 'Cache-Control directives control caching behavior. public allows any cache (CDN, browser) to store the response. private restricts caching to the browser only. no-cache means the response can be cached but must be revalidated before each use. no-store prevents any caching. max-age specifies freshness duration in seconds. s-maxage sets a separate max-age for shared caches (CDNs). immutable indicates the content will never change — ideal for hashed filenames. must-revalidate forces revalidation when stale. For hashed static assets (JS, CSS with content hash), use Cache-Control: public, max-age=31536000, immutable. For HTML pages that change frequently, use no-cache to always check for updates. For API data, use private, max-age=60, must-revalidate. For sensitive data, use no-store. The cache hierarchy flows from browser (private) to CDN edge (s-maxage) to origin server — each level respects its own directives.'
      },
      {
        id: 'etag-validation', title: 'ETag and Conditional Requests',
        content: 'ETags enable conditional requests that save bandwidth. When a server returns a response, it includes an ETag header with a unique identifier for that version. When the cached response becomes stale, the browser sends an If-None-Match header with the ETag value. If the resource has not changed, the server returns 304 Not Modified with no body — the browser uses the cached version. If the ETag does not match, the server returns 200 OK with the new content and updated ETag. Strong ETags (no prefix) guarantee byte-level equivalence — any change in the response body produces a different ETag. Weak ETags (W/ prefix) indicate semantic equivalence — formatting changes do not alter the ETag. ETags work with Last-Modified as a fallback validation mechanism. In Angular, implement client-side caching by checking ETag headers before making requests. Combine ETags with Cache-Control max-age for optimal freshness and bandwidth savings.'
      },
      {
        id: 'sw-caching', title: 'Service Worker Caching',
        content: 'Service workers enable fine-grained caching control. The Cache API stores request-response pairs: caches.open("v1") returns a cache object, cache.put(request, response) stores entries, cache.match(request) retrieves them. Angular PWA uses ngsw-config.json to define caching strategies. The prefetch installMode downloads resources eagerly during service worker installation — ideal for app shell files. The lazy installMode downloads resources on first request — ideal for large assets. The freshness strategy prioritizes network responses, falling back to cache — best for API data. The performance strategy prioritizes cached responses, falling back to network — best for static assets. Stale While Revalidate returns cached content immediately while updating in the background — a balanced approach. Cache versioning with versioned cache names (v1, v2) prevents stale data after deployments. Clean up old caches in the activate event. Service workers also enable offline functionality by serving cached responses when the network is unavailable.'
      },
      {
        id: 'cdn-caching', title: 'CDN Caching',
        content: 'CDNs (Content Delivery Networks) cache content at edge locations worldwide, reducing latency. Multi-tier caching flows from browser cache to CDN edge cache to CDN shield cache to origin server. Each tier respects its own Cache-Control directives. CDN-Cache-Control overrides Cache-Control for CDN-specific behavior. Surrogate keys tag cached content for selective purging — tag resources by section (homepage, products) and purge by tag when content changes. Vary headers create separate cache entries: Vary: Accept-Encoding caches per compression format, Vary: Accept-Language caches per language. CDN cache purging can be instant (for security fixes), scheduled (for content updates), or tag-based (for related resources). Cache hit ratio measures effectiveness — aim for 90%+ hit ratio for static assets. Origin shielding reduces load on your origin server by routing all CDN misses through a single shield server. Always set immutable and long max-age for hashed filenames to maximize cache efficiency across deploys.'
      }
    ]
  },
  {
    id: 946, slug: 'net-auth', title: 'Authentication & Authorization',
    description: 'Implement secure authentication with JWT tokens, OAuth 2.0 flows, OpenID Connect, and session management.',
    level: 'advanced', duration: '45 min',
    objectives: ['Implement JWT-based authentication in Angular', 'Understand OAuth 2.0 authorization flows', 'Configure OpenID Connect for identity management'],
    quiz: [
      { id: 1, question: 'What information does a JWT contain?', options: ['Only user ID', 'Header, payload (claims), and signature', 'Password hash', 'A session ID only'], correctIndex: 1, explanation: 'A JWT has three parts: header (algorithm), payload (claims like user ID, expiry), and signature for integrity verification.' },
      { id: 2, question: 'What is the security risk of storing JWTs in localStorage?', options: ['Tokens expire too quickly', 'Vulnerable to XSS — JavaScript can access localStorage', 'Tokens are too large', 'localStorage is not encrypted'], correctIndex: 1, explanation: 'localStorage is accessible to any JavaScript on the page. XSS vulnerabilities can steal tokens. HttpOnly cookies are more secure.' },
      { id: 3, question: 'What is the purpose of the state parameter in OAuth 2.0?', options: ['Store user preferences', 'Prevent CSRF attacks by validating the authorization response', 'Specify user email', 'Set token expiry'], correctIndex: 1, explanation: 'The state parameter prevents CSRF — the client generates a random value, sends it with the request, and validates it in the callback.' }
    ],
    topics: [
      {
        id: 'jwt-tokens', title: 'JWT Tokens',
        content: 'JWT (JSON Web Token) is a compact, self-contained token format for securely transmitting information. It has three parts separated by dots: header (algorithm and type), payload (claims like sub, exp, iat), and signature (HMAC-SHA256 or RSA). The payload is base64-encoded, not encrypted — anyone can decode it, but the signature prevents tampering. Tokens expire via the exp claim — typically 15-60 minutes for access tokens. Store access tokens in memory (a variable, not localStorage) to minimize XSS exposure. HttpOnly cookies are more secure for storing tokens — JavaScript cannot access them. Implement token refresh with a refresh token stored in an HttpOnly cookie: when the access token expires, use the refresh token to obtain a new one without re-authentication. In Angular, create an HttpInterceptor that attaches the Authorization: Bearer <token> header to requests. Handle 401 responses by redirecting to login. Never store tokens in localStorage for production applications.'
      },
      {
        id: 'oauth2', title: 'OAuth 2.0',
        content: 'OAuth 2.0 is an authorization framework that allows third-party applications to access user resources without exposing credentials. Four grant types: Authorization Code (most secure, for server-side apps), Implicit (legacy, for SPAs), Resource Owner Password Credentials (trusted apps only), and Client Credentials (machine-to-machine). The Authorization Code flow with PKCE (Proof Key for Code Exchange) is recommended for SPAs — it prevents authorization code interception. Flow: client generates code_verifier and code_challenge, redirects user to authorization server with the challenge, user authenticates, server returns authorization code, client exchanges code + verifier for tokens. Tokens include access_token (short-lived, API access) and refresh_token (long-lived, obtains new access tokens). In Angular, use libraries like angular-oauth2-oidc that handle the flow, token storage, and automatic refresh. Always validate tokens server-side — do not trust client-side validation alone.'
      },
      {
        id: 'openid-connect', title: 'OpenID Connect',
        content: 'OpenID Connect (OIDC) is an identity layer built on top of OAuth 2.0. While OAuth 2.0 handles authorization (what you can access), OIDC handles authentication (who you are). OIDC adds an ID token — a JWT containing user identity claims (sub, name, email, picture). The UserInfo endpoint returns additional profile information. OIDC discovery (/.well-known/openid-configuration) provides server metadata including endpoints, supported scopes, and signing algorithms. Flows: Authorization Code with PKCE (recommended), Hybrid (combines redirect and token). In Angular, angular-oauth2-oidc library supports OIDC with automatic discovery, token refresh, and logout. Configure with the discovery document URL: this.oauthService.loadDiscoveryDocumentAndTryLogin(). OIDC supports single sign-on (SSO) — logging into one application logs you into all applications sharing the same identity provider. Scopes define what information is requested: openid, profile, email, address.'
      },
      {
        id: 'session-management', title: 'Session Management',
        content: 'Session management handles user authentication state across requests. Stateful sessions store session data on the server — the client receives a session ID (typically in a cookie). The server looks up session data on each request. Stateless JWTs carry all session data in the token itself — the server verifies the signature without storage. Trade-offs: stateful sessions are easier to invalidate (delete server-side), while JWTs are scalable (no server-side storage) but harder to revoke. Token rotation refreshes access tokens frequently and invalidates refresh tokens after use — if a refresh token is reused, it indicates compromise. Absolute timeout forces re-authentication after a fixed duration regardless of activity. In Angular, implement a SessionService that manages token lifecycle: store tokens securely, refresh before expiry, clear on logout, and handle concurrent tabs with BroadcastChannel. Logout should clear tokens from the client and invalidate the refresh token server-side. Use idle detection (Idle service) to auto-logout inactive users.'
      }
    ]
  },
  {
    id: 947, slug: 'net-api-perf', title: 'API Performance Optimization',
    description: 'Optimize API performance with request batching, response compression, connection pooling, and rate limiting.',
    level: 'advanced', duration: '40 min',
    objectives: ['Implement request batching to reduce HTTP overhead', 'Configure response compression for faster transfers', 'Understand connection pooling for database efficiency'],
    quiz: [
      { id: 1, question: 'What is request batching?', options: ['Sending larger requests', 'Combining multiple API calls into a single request', 'Compressing request bodies', 'Caching request responses'], correctIndex: 1, explanation: 'Request batching combines multiple related API calls into one HTTP request, reducing connection overhead and latency.' },
      { id: 2, question: 'Which compression format offers the best ratio and is supported by all modern browsers?', options: ['gzip', 'deflate', 'br (Brotli)', 'lz4'], correctIndex: 2, explanation: 'Brotli (br) offers 15-25% better compression than gzip and is supported by all modern browsers. It is ideal for text-based assets.' },
      { id: 3, question: 'What is the purpose of rate limiting?', options: ['Speed up responses', 'Protect APIs from abuse by limiting request frequency', 'Compress responses', 'Cache API responses'], correctIndex: 1, explanation: 'Rate limiting restricts how many requests a client can make in a given time period, preventing abuse and ensuring fair usage.' }
    ],
    topics: [
      {
        id: 'request-batching', title: 'Request Batching',
        content: 'Request batching reduces HTTP overhead by combining multiple API calls into a single request. REST APIs support this through endpoints like POST /api/batch with an array of operations. GraphQL natively supports batching — send multiple queries in a single HTTP request. In Angular, use RxJS forkJoin to parallelize independent requests: forkJoin([this.http.get("/api/users"), this.http.get("/api/posts")]).subscribe(). For sequential dependent requests, use switchMap or concatMap. DataLoader (for Node.js backends) automatically batches database queries within a single request tick — it collects all IDs requested during a tick and executes one SQL query with IN clause instead of N individual queries. Client-side batching libraries like apollo-link-batch-http aggregate GraphQL queries. Batch size limits prevent overwhelming the server — typically 10-50 operations per batch. Monitor batch performance — if individual operations take different times, the batch response time equals the slowest operation.'
      },
      {
        id: 'response-compression', title: 'Response Compression',
        content: 'Response compression reduces payload size and transfer time. Brotli (br) offers the best compression ratio for text-based content (HTML, CSS, JS, JSON) — typically 15-25% smaller than gzip. Gzip is universally supported and a solid fallback. Configure in nginx: brotli on; brotli_types text/html text/css application/json; gzip on; gzip_types text/plain text/css application/javascript. Content negotiation happens via Accept-Encoding header — the browser sends supported formats, and the server responds with the chosen one. Compress API responses (JSON) — a 100KB JSON response typically compresses to 15-20KB. Images should use format-specific compression (WebP, AVIF) rather than gzip. Set Vary: Accept-Encoding so caches store separate copies per compression. Angular CLI enables gzip compression by default in production builds. For dynamic compression, use nginx or a reverse proxy — application-level compression wastes CPU. Brotli pre-compression of static assets during build achieves maximum compression ratio.'
      },
      {
        id: 'connection-pooling', title: 'Connection Pooling',
        content: 'Connection pooling reuses database connections instead of creating new ones for each request. Creating a TCP connection takes 50-200ms (DNS lookup, TCP handshake, TLS negotiation). A connection pool maintains a set of open connections that requests borrow and return. Pool size settings: min connections (idle connections ready), max connections (concurrent database connections), idle timeout (close connections after inactivity). In Node.js with PostgreSQL, use pg-pool or the built-in pool in pg library. For MySQL, use mysql2/pool. In Angular, HTTP/2 multiplexing serves a similar purpose for API connections — multiple requests share a single TCP connection. Configure keep-alive headers: Connection: keep-alive, Keep-Alive: timeout=5, max=100. Connection pooling on the server side prevents exhausting database connections under load. Monitor pool metrics: active connections, idle connections, wait time for connections. Tune pool size based on database capacity — too few connections create bottlenecks, too many exhaust database resources.'
      },
      {
        id: 'rate-limiting', title: 'Rate Limiting',
        content: 'Rate limiting protects APIs from abuse and ensures fair resource usage. Common algorithms: Fixed window (count requests in a fixed time window — simple but allows bursts at window boundaries), sliding window (smooths bursts by counting requests in a rolling window), token bucket (allows bursts up to bucket capacity, refills at steady rate), and leaky bucket (processes requests at constant rate, queues or drops excess). Implement with HTTP headers: X-RateLimit-Limit (max requests), X-RateLimit-Remaining (remaining), X-RateLimit-Reset (reset timestamp). Return 429 Too Many Requests when limit exceeded, with Retry-After header. Tiered rate limiting: anonymous users get 100 requests/hour, authenticated users 1000/hour, premium users 10000/hour. In nginx: limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s; limit_req zone=api burst=20 nodelay. Client-side handling: show countdown timer, queue requests, implement exponential backoff for retries. Rate limiting should be per-endpoint — write operations get stricter limits than reads.'
      }
    ]
  },
  {
    id: 948, slug: 'net-api-versioning', title: 'API Versioning Strategies',
    description: 'Explore API versioning strategies — URL versioning, header versioning, and best practices for evolving APIs without breaking clients.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Implement URL-based versioning in REST APIs', 'Use header-based versioning with content negotiation', 'Apply versioning best practices for backward compatibility'],
    quiz: [
      { id: 1, question: 'Which versioning strategy embeds the version directly in the URL?', options: ['Header versioning', 'Query parameter versioning', 'URL path versioning', 'Content negotiation'], correctIndex: 2, explanation: 'URL path versioning places the version in the path, e.g., /api/v1/users, making it explicit and easy to identify.' },
      { id: 2, question: 'What header is commonly used for API versioning via content negotiation?', options: ['X-API-Version', 'Accept', 'Content-Type', 'Authorization'], correctIndex: 1, explanation: 'The Accept header can include version information, e.g., Accept: application/vnd.myapp.v2+json, enabling content-based versioning.' },
      { id: 3, question: 'What is a major risk of URL versioning?', options: ['URLs become too short', 'Cached responses may serve stale versions', 'Cannot be used with load balancers', 'Only supports GET requests'], correctIndex: 1, explanation: 'URL versioning can cause caching issues because different versions share CDN and browser caches, potentially serving outdated responses.' }
    ],
    topics: [
      {
        id: 'url-versioning', title: 'URL Versioning',
        content: 'URL versioning embeds the API version directly in the URL path, such as /api/v1/users or /api/v2/users. This approach is the most explicit and widely adopted strategy because the version is visible in every request, making debugging and documentation straightforward. Clients choose the version they need, and different versions can coexist simultaneously. URL versioning is cacheable since each version has a unique URL, and browsers and CDNs can store separate responses per version. It works well with API gateways and reverse proxies that route requests based on path patterns. The main drawback is URL proliferation — maintaining multiple URL paths increases code duplication and routing complexity. To mitigate this, use version-specific controllers or handlers that share common logic through inheritance or composition. In Express.js, create versioned routers: app.use(\'/api/v1\', v1Router) and app.use(\'/api/v2\', v2Router). Always start with v1 to leave room for future versions. URL versioning is ideal when you need clear, auditable version boundaries and maximum client visibility.'
      },
      {
        id: 'header-versioning', title: 'Header Versioning',
        content: 'Header versioning keeps URLs clean by specifying the version through HTTP headers. The most common approach uses the Accept header with vendor-specific media types: Accept: application/vnd.myapi.v2+json. Alternatively, custom headers like X-API-Version: 2 or Api-Version: 2023-01-15 can be used. The server inspects the header and routes to the appropriate version handler. This strategy follows REST principles more closely since the URL represents the resource, not the representation. Header versioning allows the same resource to be served in different formats without URL duplication. Cache behavior requires careful configuration — Vary: Accept must be set so CDNs cache separate responses per header value. The downside is discoverability — clients must know which headers to send, and version information is not visible in URLs shared via documentation or logs. Header versioning works best when versions represent different representations of the same resource rather than entirely different APIs. In Angular, set version headers in an HttpInterceptor to avoid scattering version logic across services.'
      },
      {
        id: 'versioning-best-practices', title: 'Versioning Best Practices',
        content: 'Effective versioning requires clear policies and consistent execution. Start versioning from day one — even if you begin with v1, having the infrastructure in place prevents painful migrations later. Define what constitutes a breaking change: removing or renaming fields, changing field types, altering response structures, or modifying authentication requirements. Non-breaking changes like adding new fields or endpoints do not require a new version. Maintain at least two supported versions simultaneously to give clients time to migrate. Provide a clear deprecation timeline — typically 6-12 months for major versions. Communicate deprecations through response headers (Sunset, Deprecation), developer portals, and changelogs. Use semantic versioning principles: increment major versions for breaking changes, minor versions for new features. Document migration guides for each version transition, highlighting what changed and how to update client code. Consider using feature flags or toggles to gradually roll out changes within a version. Monitor version adoption metrics to know when older versions have zero traffic and can be safely retired. Automated testing across all supported versions prevents regressions during maintenance.'
      }
    ]
  },
  {
    id: 949, slug: 'net-rate-limiting', title: 'Rate Limiting & Throttling',
    description: 'Learn rate limiting techniques — algorithms, implementation patterns, and how to protect APIs from abuse while ensuring fair usage.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Understand rate limiting algorithms and their trade-offs', 'Implement rate limiting in API gateways and servers', 'Configure throttling policies for different client tiers'],
    quiz: [
      { id: 1, question: 'Which rate limiting algorithm allows bursts while maintaining an average rate?', options: ['Fixed window', 'Sliding window', 'Token bucket', 'Leaky bucket'], correctIndex: 2, explanation: 'The token bucket algorithm refills tokens at a steady rate but allows bursts up to the bucket capacity, balancing flexibility with fairness.' },
      { id: 2, question: 'What HTTP status code indicates a request was rate limited?', options: ['400 Bad Request', '401 Unauthorized', '429 Too Many Requests', '503 Service Unavailable'], correctIndex: 2, explanation: 'HTTP 429 Too Many Requests signals that the client has exceeded the allowed request rate and should slow down.' },
      { id: 3, question: 'What header tells the client how long to wait before retrying?', options: ['X-RateLimit-Limit', 'Retry-After', 'Cache-Control', 'Content-Type'], correctIndex: 1, explanation: 'The Retry-After header specifies the number of seconds the client should wait before sending the next request.' }
    ],
    topics: [
      {
        id: 'what-is-rate-limiting', title: 'What is Rate Limiting',
        content: 'Rate limiting restricts how many requests a client can make within a specific time period. It protects APIs from abuse, denial-of-service attacks, and accidental overload. Without rate limiting, a single misbehaving client can exhaust server resources, degrade performance for all users, and cause cascading failures in dependent services. Rate limiting also ensures fair resource distribution — no single user can monopolize shared infrastructure. Common use cases include public APIs where free and paid tiers have different limits, authentication endpoints to prevent brute-force attacks, file upload endpoints to prevent storage exhaustion, and email sending APIs to prevent spam. Rate limiting is typically enforced at the API gateway level (Kong, AWS API Gateway, nginx) but can also be implemented in application code. Limits can be applied per IP address, per API key, per user account, or per endpoint. Response headers communicate limits to clients: X-RateLimit-Limit shows the maximum allowed, X-RateLimit-Remaining shows how many are left, and X-RateLimit-Reset indicates when the limit resets. Returning 429 Too Many Requests with a Retry-After header gives clients clear guidance on when to retry.'
      },
      {
        id: 'rate-limiting-algorithms', title: 'Rate Limiting Algorithms',
        content: 'Different algorithms balance accuracy, memory usage, and burst tolerance differently. Fixed window counting divides time into fixed intervals (e.g., 1-minute windows) and counts requests per window. It is simple but allows bursts at window boundaries — a client can make 100 requests at 11:59:59 and 100 more at 12:00:00, momentarily doubling the effective rate. Sliding window log timestamps each request and counts all requests within a rolling window from the current time. It prevents boundary bursts but requires storing every timestamp, consuming significant memory. Sliding window counter approximates the rolling window by weighting the current and previous fixed windows, offering a good balance. Token bucket maintains a bucket that holds tokens up to a maximum capacity. Each request consumes one token, and tokens refill at a steady rate. It allows controlled bursts up to the bucket size while enforcing the average rate. Leaky bucket processes requests at a constant rate, queuing or dropping excess requests. It produces perfectly smooth output but adds latency for queued requests. Redis-based implementations use sorted sets for sliding windows or atomic counters for fixed windows, providing distributed rate limiting across multiple server instances.'
      },
      {
        id: 'implementing-rate-limits', title: 'Implementing Rate Limits',
        content: 'Rate limiting implementation spans multiple layers. At the infrastructure level, nginx uses limit_req_zone and limit_req directives: limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s creates a zone with 10 requests per second per IP. Adding burst=20 nodelay allows short bursts without queuing. AWS API Gateway provides built-in throttling with configurable steady-state and burst limits per route. Application-level implementation in Node.js uses middleware like express-rate-limit: app.use(limit({ windowMs: 60000, max: 100 })). For distributed systems, Redis stores counters with TTL: INCR rate:{ip} followed by EXPIRE rate:{ip} 60. Tiered limits differentiate client types — anonymous users get 100 requests per hour, authenticated users get 1000, and premium users get 10000. Endpoint-specific limits protect expensive operations — file uploads might allow 10 per hour while list endpoints allow 1000. Client-side handling should parse X-RateLimit-Remaining headers, implement exponential backoff on 429 responses, queue requests when approaching limits, and display user-friendly messages. Always log rate limit events for monitoring and adjust limits based on real usage patterns and capacity planning.'
      }
    ]
  },
  {
    id: 950, slug: 'net-oauth-deep-dive', title: 'OAuth 2.0 & OIDC Deep Dive',
    description: 'Master OAuth 2.0 and OpenID Connect — authorization flows, token management, and securing modern applications with identity providers.',
    level: 'advanced', duration: '50 min',
    objectives: ['Understand OAuth 2.0 authorization flows in depth', 'Implement OpenID Connect authentication with identity tokens', 'Secure applications against common OAuth vulnerabilities'],
    quiz: [
      { id: 1, question: 'What does PKCE protect against in the OAuth 2.0 Authorization Code flow?', options: ['Password theft', 'Authorization code interception', 'SQL injection', 'Cross-site scripting'], correctIndex: 1, explanation: 'PKCE (Proof Key for Code Exchange) prevents authorization code interception by binding the code to the client that requested it.' },
      { id: 2, question: 'What is the difference between an access token and an ID token?', options: ['No difference', 'Access tokens authorize API access, ID tokens authenticate the user', 'ID tokens are longer-lived', 'Access tokens contain user identity'], correctIndex: 1, explanation: 'Access tokens are credentials for API authorization. ID tokens are JWTs containing user identity claims for authentication.' },
      { id: 3, question: 'Which OAuth 2.0 grant type is recommended for single-page applications?', options: ['Resource Owner Password Credentials', 'Client Credentials', 'Authorization Code with PKCE', 'Implicit'], correctIndex: 2, explanation: 'Authorization Code with PKCE is the recommended flow for SPAs — it provides security without exposing tokens in URLs.' }
    ],
    topics: [
      {
        id: 'oauth-flow', title: 'OAuth 2.0 Authorization Flows',
        content: 'OAuth 2.0 defines several grant types for different client scenarios. Authorization Code flow is the most secure — the client receives an authorization code, exchanges it server-side for tokens, keeping tokens away from the browser. The Implicit flow (deprecated) returns tokens directly in the URL fragment — it was designed for SPAs but exposes tokens to XSS attacks and URL leakage. Authorization Code with PKCE (Proof Key for Code Exchange) replaces Implicit for SPAs — the client generates a random code_verifier, sends a hashed code_challenge with the authorization request, and proves possession of the verifier during token exchange. This prevents authorization code interception even if the code is intercepted. Client Credentials flow is for machine-to-machine communication — no user involvement, just client ID and secret exchanged for an access token. Resource Owner Password Credentials (deprecated) sends username and password directly — only for highly trusted first-party applications. The Device Authorization flow handles input-constrained devices like smart TVs — the device displays a code, the user enters it on their phone. Each flow serves a specific trust model and device context.'
      },
      {
        id: 'oidc-authentication', title: 'OpenID Connect Authentication',
        content: 'OpenID Connect (OIDC) adds authentication to OAuth 2.0 by introducing the ID token — a JWT containing verified identity claims. The ID token includes standard claims: sub (unique user identifier), iss (issuer), aud (audience/client ID), exp (expiry), iat (issued at), nonce (to prevent replay attacks), and profile claims like name, email, and picture. The UserInfo endpoint provides additional profile data beyond what the ID token contains. OIDC discovery (/.well-known/openid-configuration) exposes server metadata: authorization endpoint, token endpoint, supported scopes, signing algorithms, and supported claims. This enables automatic client configuration. Scopes control what information is requested — openid (required, returns ID token), profile (name, picture), email (email address), address (physical address). The nonce parameter prevents token replay — the client generates a random value, includes it in the authorization request, and verifies it in the ID token. OIDC supports single sign-on (SSO) — authenticating with one application logs you into all applications sharing the identity provider. Session management uses the check_session_iframe endpoint to monitor login status across applications.'
      },
      {
        id: 'token-management', title: 'Token Management',
        content: 'Token lifecycle management is critical for security and user experience. Access tokens are short-lived (5-60 minutes) and grant API access. Store them in memory or HttpOnly cookies — never in localStorage which is vulnerable to XSS. Refresh tokens are long-lived (days to months) and obtain new access tokens without re-authentication. Store refresh tokens in HttpOnly, Secure, SameSite=Strict cookies to prevent JavaScript access and CSRF. Token rotation invalidates the old refresh token when a new one is issued — if the old refresh token is reused, it indicates token theft, so revoke the entire token family. Implement sliding sessions that extend expiry on activity while enforcing an absolute timeout. In Angular, create an AuthService that manages token lifecycle: store tokens securely, automatically refresh before expiry using timers, clear all tokens on logout, and handle concurrent tabs with BroadcastChannel API. Handle token refresh race conditions with a refresh lock — if multiple requests trigger refresh simultaneously, only one should perform the refresh while others wait. Monitor token usage and implement anomaly detection — unusual patterns like multiple IP addresses using the same token indicate compromise. When a user changes their password, invalidate all existing tokens server-side.'
      }
    ]
  },
  {
    id: 951, slug: 'net-grpc', title: 'gRPC & Protocol Buffers',
    description: 'Learn gRPC for high-performance RPC — Protocol Buffer definitions, streaming patterns, and how gRPC compares to REST for service communication.',
    level: 'advanced', duration: '45 min',
    objectives: ['Define services and messages using Protocol Buffers', 'Understand gRPC communication patterns (unary, server-streaming, bidirectional)', 'Compare gRPC and REST for different use cases'],
    quiz: [
      { id: 1, question: 'What serialization format does gRPC use?', options: ['JSON', 'XML', 'Protocol Buffers', 'YAML'], correctIndex: 2, explanation: 'gRPC uses Protocol Buffers (protobuf) for serialization, which produces compact binary messages faster than text-based formats.' },
      { id: 2, question: 'Which gRPC pattern allows the server to send a stream of responses to a single client request?', options: ['Unary RPC', 'Server streaming RPC', 'Client streaming RPC', 'Bidirectional streaming RPC'], correctIndex: 1, explanation: 'Server streaming RPC sends a stream of messages in response to a single client request, ideal for real-time data feeds.' },
      { id: 3, question: 'What transport protocol does gRPC use?', options: ['HTTP/1.1', 'HTTP/2', 'WebSocket', 'TCP raw'], correctIndex: 1, explanation: 'gRPC is built on HTTP/2, leveraging its multiplexing, header compression, and binary framing for efficient communication.' }
    ],
    topics: [
      {
        id: 'what-is-grpc', title: 'What is gRPC',
        content: 'gRPC is a high-performance Remote Procedure Call framework developed by Google. It enables clients to invoke methods on a server as if calling local functions, while the framework handles serialization, transport, and network communication. gRPC uses Protocol Buffers as both the interface definition language (IDL) and serialization format, producing compact binary messages that are significantly smaller and faster to parse than JSON. The framework leverages HTTP/2 for transport, gaining multiplexed streams, header compression, and bidirectional communication. gRPC supports four communication patterns: unary (single request, single response), server streaming (single request, stream of responses), client streaming (stream of requests, single response), and bidirectional streaming (both sides stream simultaneously). Built-in features include deadline propagation (timeouts cascade through service chains), load balancing, authentication, and error handling with structured status codes. gRPC is ideal for microservice-to-microservice communication where performance, type safety, and code generation matter more than human readability. It is less suitable for browser-facing APIs where REST and JSON remain more accessible.'
      },
      {
        id: 'protobuf-defined', title: 'Protocol Buffers Defined',
        content: 'Protocol Buffers (protobuf) define service interfaces and message structures in .proto files using a language-neutral syntax. A simple message definition: message User { string name = 1; int32 age = 2; string email = 3; }. Each field has a unique field number that identifies it in the binary format — field numbers must never change once deployed. Service definitions specify RPC methods: service UserService { rpc GetUser(GetUserRequest) returns (User); }. Proto3 syntax omits required/optional labels — all fields are optional with zero-value defaults. Enums, nested messages, maps, and oneof (union types) model complex data structures. The protoc compiler generates language-specific code — Go structs, Java classes, TypeScript interfaces — from .proto files, ensuring type safety across services. Package namespacing prevents collisions: package myapi.v1;. Imports reference other proto files: import "google/protobuf/timestamp.proto";. Proto files are the source of truth for API contracts, enabling frontend and backend teams to work in parallel. Tools like buf.build provide linting, breaking change detection, and managed protobuf repositories. Generated code includes serialization, deserialization, and comparison methods — no manual encoding needed.'
      },
      {
        id: 'grpc-vs-rest', title: 'gRPC vs REST',
        content: 'gRPC and REST serve different needs and complement each other. REST uses JSON over HTTP/1.1 with resource-based URLs — human-readable, widely supported, and cacheable. gRPC uses Protocol Buffers over HTTP/2 with service-based methods — compact, fast, and strongly typed. Performance: gRPC messages are 2-10x smaller than JSON and serialize/deserialize 2-5x faster. HTTP/2 multiplexing in gRPC avoids head-of-line blocking. REST benefits from browser support, HTTP caching, and widespread tooling (Postman, curl). gRPC requires code generation and specialized clients, making it less convenient for browser-to-server communication but ideal for server-to-server. REST APIs are self-describing through URLs and documentation; gRPC requires .proto files or compiled clients. Streaming: gRPC supports all four streaming patterns natively; REST approximates streaming through SSE or WebSockets. Error handling differs: REST uses HTTP status codes; gRPC uses structured status codes (OK, NOT_FOUND, INTERNAL). In practice, use REST for public APIs and browser clients, gRPC for internal microservice communication, and gRPC-Web (a proxy) when gRPC performance is needed from browsers. Many architectures use both — REST at the edge, gRPC internally.'
      }
    ]
  },
  {
    id: 952, slug: 'net-websockets-advanced', title: 'WebSocket Advanced Patterns',
    description: 'Master advanced WebSocket patterns — connection management, reconnection strategies, and scaling WebSocket servers for production applications.',
    level: 'advanced', duration: '45 min',
    objectives: ['Implement robust WebSocket connection management', 'Design reconnection strategies with exponential backoff', 'Scale WebSocket servers across multiple instances'],
    quiz: [
      { id: 1, question: 'What is the thundering herd problem in WebSocket reconnection?', options: ['Too many WebSocket messages', 'Many clients reconnecting simultaneously and overwhelming the server', 'Server running out of memory', 'Clients sending duplicate messages'], correctIndex: 1, explanation: 'Thundering herd occurs when many clients reconnect at once after a server restart, overwhelming it with simultaneous connection attempts.' },
      { id: 2, question: 'What is the purpose of WebSocket heartbeats?', options: ['Encrypt messages', 'Detect dead connections by exchanging periodic ping/pong frames', 'Route messages to specific clients', 'Compress message payloads'], correctIndex: 1, explanation: 'Heartbeats (ping/pong frames) detect dead connections when TCP keep-alive is too slow, enabling faster cleanup of stale connections.' },
      { id: 3, question: 'What technology enables scaling WebSockets across multiple server instances?', options: ['Load balancer sticky sessions only', 'Redis Pub/Sub or message broker for cross-instance message routing', 'HTTP/2 multiplexing', 'Database replication'], correctIndex: 1, explanation: 'A message broker like Redis Pub/Sub routes messages between server instances, enabling horizontal scaling of WebSocket servers.' }
    ],
    topics: [
      {
        id: 'connection-management', title: 'Connection Management',
        content: 'Effective WebSocket connection management tracks connection lifecycle and resource allocation. On connection establishment, authenticate the client using a token from the initial HTTP upgrade request or a first message. Store connection metadata (user ID, rooms, capabilities) in a Map keyed by connection ID. Implement connection limits per user — allow 3-5 concurrent connections to support multiple devices while preventing abuse. Heartbeat mechanisms detect dead connections faster than TCP keep-alive. Send ping frames every 30 seconds and close connections that do not receive pong within 10 seconds. Track connection state with a state machine: CONNECTING, CONNECTED, RECONNECTING, DISCONNECTED. Broadcast connection status to other clients when presence matters (chat applications). Handle backpressure — if the client cannot consume messages fast enough, buffer messages with a maximum size and drop oldest when full. Implement graceful shutdown: send a close frame with reason code, wait for acknowledgment, then terminate the TCP connection. Clean up all server-side resources (rooms, subscriptions, timers) on disconnect to prevent memory leaks.'
      },
      {
        id: 'reconnection-strategies', title: 'Reconnection Strategies',
        content: 'Robust reconnection handles network disruptions without overwhelming servers. Exponential backoff increases delay after each failed attempt: delay = min(baseDelay * 2^attempt + jitter, maxDelay). Start with 1 second, doubling to a maximum of 30 seconds. Jitter (random variation) prevents thundering herd when many clients reconnect simultaneously: delay = delay + random(0, 1000ms). Implement a maximum retry count — after 10-15 failed attempts, stop reconnecting and prompt the user to check their connection. Cache the last received message ID to resume from where the connection dropped — the server can replay missed messages. Connection state broadcasting keeps the UI informed: this.status$ = new BehaviorSubject(\'disconnected\'). Display visual indicators (reconnecting spinner, connection status badge) to maintain user trust. Socket.io provides built-in reconnection with reconnectionDelay, reconnectionDelayMax, and reconnectionAttempts configuration. For raw WebSocket reconnection, implement it in the close event handler: ws.onclose = (event) => { if (!event.wasClean) { setTimeout(reconnect, calculateDelay()); } }. Handle network state changes with navigator.onLine and the online/offline events to trigger immediate reconnection when connectivity returns.'
      },
      {
        id: 'scaling-websockets', title: 'Scaling WebSockets',
        content: 'Scaling WebSockets beyond a single server requires message routing across instances. Sticky sessions (source IP hashing) route all connections from a client to the same server — simple but prevents true horizontal scaling and causes uneven load. A message broker (Redis Pub/Sub, NATS, Kafka) decouples message routing from connection hosting. Each server instance subscribes to relevant channels; when a message arrives, it is published to the broker, which fans it out to all instances with subscribed clients. Redis Pub/Sub is the simplest approach — use channels per room or per user. For high-throughput scenarios, NATS or Kafka provide durable message delivery and replay. Connection affinity with a consistent hashing ring maps users to specific servers, reducing cross-instance communication. Server discovery lets clients find the optimal server — DNS SRV records or a service registry provide server lists. Health checks detect failed instances and redistribute connections. Memory management limits per-connection buffer sizes and total server memory. Monitor active connections, message throughput, and latency per instance. Deploy WebSocket servers behind a load balancer that supports WebSocket upgrade — nginx, HAProxy, or AWS ALB. Consider serverless WebSockets (AWS API Gateway WebSockets) for automatic scaling without managing infrastructure.'
      }
    ]
  },
  {
    id: 953, slug: 'net-http2-http3', title: 'HTTP/2 & HTTP/3',
    description: 'Understand modern HTTP protocols — HTTP/2 multiplexing and server push, HTTP/3 QUIC transport, and migration strategies from HTTP/1.1.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Understand HTTP/2 multiplexing and its performance benefits', 'Learn how HTTP/3 uses QUIC to eliminate head-of-line blocking', 'Configure servers for HTTP/2 and HTTP/3 support'],
    quiz: [
      { id: 1, question: 'What problem does HTTP/2 multiplexing solve?', options: ['Slow DNS resolution', 'Head-of-line blocking where one slow request blocks others', 'SSL certificate expiration', 'Large cookie sizes'], correctIndex: 1, explanation: 'HTTP/2 multiplexing allows multiple requests and responses to travel simultaneously over a single connection, eliminating head-of-line blocking at the HTTP layer.' },
      { id: 2, question: 'What transport protocol does HTTP/3 replace?', options: ['UDP', 'TCP', 'QUIC', 'WebSocket'], correctIndex: 1, explanation: 'HTTP/3 replaces TCP with QUIC, which is built on UDP but provides reliable delivery, eliminating TCP-level head-of-line blocking.' },
      { id: 3, question: 'What is the key advantage of HTTP/3 over HTTP/2?', options: ['Larger header compression', 'Eliminates TCP-level head-of-line blocking by using QUIC over UDP', 'Supports more concurrent connections', 'Uses text-based framing'], correctIndex: 1, explanation: 'HTTP/3 eliminates TCP head-of-line blocking because QUIC handles each stream independently — packet loss on one stream does not block others.' }
    ],
    topics: [
      {
        id: 'http2-features', title: 'HTTP/2 Features',
        content: 'HTTP/2 solves HTTP/1.1 performance limitations through several key features. Multiplexing allows multiple requests and responses to travel simultaneously over a single TCP connection, eliminating head-of-line blocking at the HTTP layer. In HTTP/1.1, browsers open 6-8 parallel TCP connections to work around this — HTTP/2 needs just one connection. Binary framing replaces HTTP/1.1 text-based protocol with a binary format that is faster to parse and more compact. Headers are compressed using HPACK, which maintains a dynamic table of previously seen headers — common headers like User-Agent and Accept are sent as small index references after the first request. Server push proactively sends resources the client will need: the server pushes CSS and JavaScript files alongside the HTML before the client requests them. Stream priority lets clients indicate which requests are more important — a browser can prioritize HTML over images. To enable HTTP/2 in nginx, add listen 443 ssl http2. In Apache, use Protocols h2 http/1.1. HTTP/2 requires TLS in practice (browsers negotiate h2 over TLS only), which also enables connection coalescing — multiple domains sharing a certificate can reuse the same TCP connection.'
      },
      {
        id: 'http3-quic', title: 'HTTP/3 and QUIC',
        content: 'HTTP/3 builds on QUIC (Quick UDP Internet Connections), which replaces TCP as the transport protocol. QUIC eliminates TCP-level head-of-line blocking — in HTTP/2, a single lost packet blocks all streams on that TCP connection. QUIC handles each stream independently, so packet loss on one stream does not affect others. QUIC combines transport and encryption in one protocol, reducing handshake latency. TCP requires a three-way handshake (1-RTT), then TLS adds another 1-2 round trips. QUIC achieves 0-RTT connection establishment for returning connections — data can be sent immediately. Connection migration identifies connections by a connection ID rather than IP:port tuples, so switching from WiFi to cellular preserves the connection without re-establishment. Flow control and congestion control are built into QUIC, with modern algorithms like BBR providing better performance than TCP\'s default CUBIC. To enable HTTP/3 in nginx, use listen 443 quic reuseport and set the Alt-Svc header: add_header Alt-Svc \'h3=":443"; ma=86400\' to advertise HTTP/3 availability. Browser support is universal — Chrome, Firefox, Safari, and Edge all support HTTP/3. Testing tools like curl --http3 and qlog help verify HTTP/3 connectivity.'
      },
      {
        id: 'migration-guide', title: 'Migration Guide',
        content: 'Migrating from HTTP/1.1 to HTTP/2 and HTTP/3 follows a progressive path. Start by enabling HTTP/2 — most servers and CDNs support it with minimal configuration changes. HTTP/2 is backward-compatible with HTTP/1.1 semantics, so existing APIs work without modification. Enable TLS if not already in place (required for HTTP/2 in browsers). Remove HTTP/1.1 workarounds: domain sharding (multiple subdomains for parallelism), file concatenation (combining files to reduce requests), and inline resources (embedding CSS/JS in HTML). HTTP/2 multiplexing makes these unnecessary — separate files cache better and load concurrently. For HTTP/3, enable QUIC on your server or CDN. Cloudflare, Google Cloud CDN, and AWS CloudFront support HTTP/3 with toggle switches. Test with browser developer tools — the Network tab shows protocol versions (h2 for HTTP/2, h3 for HTTP/3). Monitor performance metrics: Time to First Byte (TTFB), Largest Contentful Paint (LCP), and connection establishment time should improve. Gradual rollout: enable HTTP/3 for a percentage of traffic using CDN settings, monitor error rates and latency, then increase. Keep HTTP/2 as a fallback — QUIC uses UDP which some corporate firewalls block. The Alt-Svc header gracefully falls back to HTTP/2 when HTTP/3 is unavailable.'
      }
    ]
  }
];
