import { Lesson } from '../models/lesson.model';

export const PERFORMANCE_LESSONS: Lesson[] = [
  {
    id: 701, slug: 'perf-fundamentals', title: 'Web Performance Fundamentals',
    description: 'Learn the core principles of web performance — why performance matters, how to measure it, and the fundamentals of optimization.',
    level: 'beginner', duration: '25 min',
    objectives: ['Understand why web performance impacts user experience and business metrics', 'Identify the key performance metrics for web applications', 'Use browser DevTools to measure performance', 'Apply basic performance optimization techniques'],
    quiz: [
      { id: 1, question: 'How does page load time affect user behavior?', options: ['Users wait indefinitely for pages to load', '53% of users abandon sites that take over 3 seconds to load', 'Performance only matters for e-commerce sites', 'Users don\'t notice slow sites'], correctIndex: 1, explanation: 'Research shows 53% of mobile users abandon sites that take longer than 3 seconds to load, directly impacting conversion rates.' },
      { id: 2, question: 'Which Chrome DevTools panel is best for analyzing page load performance?', options: ['Elements panel', 'Network panel', 'Performance panel', 'Both B and C'], correctIndex: 3, explanation: 'The Network panel shows resource loading waterfall, while the Performance panel records runtime performance. Both are essential.' },
      { id: 3, question: 'What is the "first meaningful paint" metric?', options: ['When the browser starts painting pixels', 'When the primary content of the page becomes visible', 'When all images finish loading', 'When JavaScript finishes executing'], correctIndex: 1, explanation: 'First Meaningful Paint (FMP) measures when the primary content of the page becomes visually available to the user.' }
    ],
    topics: [
      { id: 'why-performance', title: 'Why Performance Matters', content: '**Business Impact of Performance:**\n\n- **Amazon** found every 100ms of latency cost 1% in sales\n- **Google** found a 0.5s delay in search results reduced traffic by 20%\n- **Pinterest** reduced load time by 40% and saw 15% increase in signups\n- **Akamai** found 100ms delay reduces conversion by 7%\n\n**User Experience Impact:**\n```\nLoad Time    | Bounce Rate | User Perception\n-------------|-------------|------------------\n< 1 second   | 7%          | Instant\n1-3 seconds  | 32%         | Slight delay\n3-6 seconds  | 53%         | Noticeable wait\n6-10 seconds | 90%         | Frustrating\n> 10 seconds | 123%        | Unacceptable\n```\n\n**Performance vs User Engagement:**\n- 47% of users expect pages to load in 2 seconds or less\n- 40% will abandon a page that takes more than 3 seconds\n- 79% of shoppers who experience dissatisfying performance are less likely to buy again\n\n**Key Takeaways:**\n1. Performance directly impacts revenue and user retention\n2. Every second of delay reduces conversions significantly\n3. Performance is a feature, not an afterthought' },
      { id: 'measuring', title: 'Measuring Performance', content: '**Core Measurement Tools:**\n\n1. **Chrome DevTools Performance Panel**\n```javascript\n// Record performance timeline\n// 1. Open DevTools > Performance tab\n// 2. Click Record\n// 3. Perform user actions\n// 4. Stop recording and analyze\n```\n\n2. **Lighthouse**\n```bash\n# Install and run Lighthouse\nnpm install -g lighthouse\nlighthouse https://example.com --output html --view\n```\n\n3. **Web Vitals API**\n```javascript\nimport { onLCP, onFID, onCLS } from \'web-vitals\';\n\nonLCP(console.log);  // Largest Contentful Paint\nonFID(console.log);  // First Input Delay\nonCLS(console.log);  // Cumulative Layout Shift\n```\n\n4. **Performance API**\n```javascript\n// Navigation Timing\nconst perfData = performance.getEntriesByType(\'navigation\')[0];\nconsole.log(\'DNS:\', perfData.domainLookupEnd - perfData.domainLookupStart);\nconsole.log(\'TTFB:\', perfData.responseStart - perfData.requestStart);\n```\n\n**Key Takeaways:**\n1. Use Lighthouse for automated performance auditing\n2. Web Vitals API tracks real user performance metrics\n3. Performance API provides detailed timing breakdowns' },
      { id: 'optimization-basics', title: 'Basic Optimization Techniques', content: '**Quick Wins:**\n\n1. **Minimize HTTP Requests**\n```html\n<!-- Combine CSS files -->\n<link rel="stylesheet" href="styles.css">\n<!-- Instead of multiple links -->\n```\n\n2. **Enable Compression**\n```nginx\n# nginx.conf\ngzip on;\ngzip_types text/css application/javascript text/xml;\n```\n\n3. **Leverage Browser Caching**\n```nginx\n# Cache static assets for 1 year\nlocation ~* \\.(js|css|png|jpg|jpeg|gif|ico)$ {\n  expires 1y;\n  add_header Cache-Control "public, immutable";\n}\n```\n\n4. **Optimize Images**\n```html\n<!-- Use modern formats -->\n<picture>\n  <source srcset="image.avif" type="image/avif">\n  <source srcset="image.webp" type="image/webp">\n  <img src="image.jpg" alt="Description" loading="lazy">\n</picture>\n```\n\n**Key Takeaways:**\n1. Reduce HTTP requests by combining and minifying resources\n2. Enable gzip/brotli compression for text-based assets\n3. Set long cache durations for immutable static assets' },
      { id: 'performance-budget', title: 'Performance Budgets', content: '**What is a Performance Budget?**\n\nA performance budget sets limits on metrics that affect user experience.\n\n```json\n// budget.json\n[\n  {\n    "path": "/",\n    "budgets": [\n      {\n        "metric": "first-contentful-paint",\n        "budget": 1500\n      },\n      {\n        "metric": "largest-contentful-paint",\n        "budget": 2500\n      },\n      {\n        "metric": "total-byte-weight",\n        "budget": 300000\n      }\n    ]\n  }\n]\n```\n\n**Budget Categories:**\n- **Timing budgets**: Max time for metrics (FCP < 1.5s, LCP < 2.5s)\n- **Size budgets**: Max size for resources (JS < 200KB, CSS < 50KB)\n- **Quantity budgets**: Max count (requests < 50, third-party scripts < 3)\n\n**Enforcing Budgets:**\n```json\n// lighthouserc.json\n{\n  "ci": {\n    "assert": {\n      "assertions": {\n        "first-contentful-paint": ["error", { "maxNumericValue": 1500 }],\n        "total-byte-weight": ["error", { "maxNumericValue": 300000 }]\n      }\n    }\n  }\n}\n```\n\n**Key Takeaways:**\n1. Set budgets based on user experience goals, not arbitrary numbers\n2. Enforce budgets in CI/CD to prevent regressions\n3. Review and update budgets as the application evolves' }
    ]
  },
  {
    id: 702, slug: 'perf-web-vitals', title: 'Core Web Vitals (LCP/FID/CLS)',
    description: 'Master Core Web Vitals — Google\'s metrics for user experience, including LCP, FID, CLS, and the newer INP.',
    level: 'beginner', duration: '30 min',
    objectives: ['Understand and measure Core Web Vitals (LCP, FID/INP, CLS)', 'Identify common causes of poor Web Vitals scores', 'Implement fixes for each Core Web Vital', 'Use tools to monitor Web Vitals in production'],
    quiz: [
      { id: 1, question: 'What does LCP (Largest Contentful Paint) measure?', options: ['Time to first byte', 'Time for the largest visible content element to render', 'Total page weight', 'JavaScript execution time'], correctIndex: 1, explanation: 'LCP measures when the largest content element in the viewport becomes visible, indicating when the main content has loaded.' },
      { id: 2, question: 'What causes high CLS (Cumulative Layout Shift)?', options: ['Slow server response', 'Elements moving after the page has loaded', 'Large image files', 'Too many DOM elements'], correctIndex: 1, explanation: 'CLS measures visual stability — layout shifts happen when elements move unexpectedly after the page has loaded.' },
      { id: 3, question: 'What replaced FID (First Input Delay) as a Core Web Vital?', options: ['TTI (Time to Interactive)', 'INP (Interaction to Next Paint)', 'FCP (First Contentful Paint)', 'TTFB (Time to First Byte)'], correctIndex: 1, explanation: 'INP (Interaction to Next Paint) replaced FID in March 2024. It measures responsiveness to all user interactions, not just the first.' }
    ],
    topics: [
      { id: 'lcp', title: 'Largest Contentful Paint (LCP)', content: '**What is LCP?**\n\nLCP measures how long it takes for the largest content element in the viewport to become visible.\n\n**Good LCP Thresholds:**\n```\nGood:       <= 2.5 seconds\nNeeds Work: 2.5 - 4.0 seconds\nPoor:       > 4.0 seconds\n```\n\n**Common LCP Elements:**\n- `<img>` elements\n- `<svg>` elements inside `<video>` poster\n- Block-level elements with text or background images\n\n**How to Improve LCP:**\n\n1. **Optimize hero images**\n```html\n<img src="hero.avif" \n     srcset="hero-400.avif 400w, hero-800.avif 800w"\n     sizes="100vw"\n     fetchpriority="high"\n     alt="Hero image">\n```\n\n2. **Preload critical resources**\n```html\n<link rel="preload" href="hero.avif" as="image" type="image/avif">\n```\n\n3. **Reduce server response time**\n- Use a CDN for static assets\n- Implement server-side caching\n- Optimize database queries\n\n**Key Takeaways:**\n1. LCP target is under 2.5 seconds\n2. Preload the largest contentful element\n3. Use fetchpriority=\"high\" for critical resources' },
      { id: 'cls', title: 'Cumulative Layout Shift (CLS)', content: '**What is CLS?**\n\nCLS measures the total of all unexpected layout shifts that occur during the lifespan of the page.\n\n**Good CLS Thresholds:**\n```\nGood:       <= 0.1\nNeeds Work: 0.1 - 0.25\nPoor:       > 0.25\n```\n\n**Common Causes of Layout Shift:**\n\n1. **Images without dimensions**\n```html\n<!-- Bad: causes layout shift -->\n<img src="photo.jpg" alt="Photo">\n\n<!-- Good: reserves space -->\n<img src="photo.jpg" alt="Photo" width="800" height="600">\n```\n\n2. **Dynamic content injection**\n```css\n/* Use aspect-ratio to reserve space */\n.ad-slot {\n  aspect-ratio: 16 / 9;\n  width: 100%;\n  background: #f0f0f0;\n}\n```\n\n3. **Web fonts causing FOIT/FOUT**\n```css\n/* Use font-display: optional */\n@font-face {\n  font-family: \'MyFont\';\n  src: url(\'myfont.woff2\') format(\'woff2\');\n  font-display: optional;\n}\n```\n\n**Key Takeaways:**\n1. Always specify width and height for images and videos\n2. Reserve space for dynamic content with CSS\n3. Use font-display: optional to prevent font-related shifts' },
      { id: 'inp', title: 'Interaction to Next Paint (INP)', content: '**What is INP?**\n\nINP measures the latency of all user interactions throughout the page lifecycle. It replaces FID.\n\n**Good INP Thresholds:**\n```\nGood:       <= 200 ms\nNeeds Work: 200 - 500 ms\nPoor:       > 500 ms\n```\n\n**How INP Works:**\n1. Measures all interactions (clicks, taps, key presses)\n2. Reports the worst-case interaction latency\n3. Covers the entire page session, not just the first interaction\n\n**Improving INP:**\n\n1. **Break up long tasks**\n```javascript\n// Bad: blocks the main thread\nfunction processLargeData() {\n  for (let i = 0; i < 1000000; i++) {\n    heavyComputation(i);\n  }\n}\n\n// Good: yields to the main thread\nasync function processLargeData() {\n  for (let i = 0; i < 1000000; i++) {\n    heavyComputation(i);\n    if (i % 1000 === 0) {\n      await new Promise(resolve => setTimeout(resolve, 0));\n    }\n  }\n}\n```\n\n2. **Use requestIdleCallback for non-critical work**\n```javascript\nrequestIdleCallback(() => {\n  // Non-critical work here\n  analytics.track(\'page-view\');\n});\n```\n\n**Key Takeaways:**\n1. INP measures responsiveness of ALL user interactions\n2. Break long tasks to keep the main thread responsive\n3. Use web workers for CPU-intensive computations' },
      { id: 'monitoring-vitals', title: 'Monitoring Web Vitals', content: '**Web Vitals Library:**\n```javascript\nimport { onLCP, onFID, onCLS, onINP, onTTFB } from \'web-vitals\';\n\nfunction sendToAnalytics(metric) {\n  console.log(`${metric.name}: ${metric.value}`);\n  // Send to your analytics service\n  fetch(\'/api/metrics\', {\n    method: \'POST\',\n    body: JSON.stringify({\n      name: metric.name,\n      value: metric.value,\n      rating: metric.rating,\n      delta: metric.delta,\n      id: metric.id\n    })\n  });\n}\n\nonLCP(sendToAnalytics);\nonFID(sendToAnalytics);\nonCLS(sendToAnalytics);\nonINP(sendToAnalytics);\nonTTFB(sendToAnalytics);\n```\n\n**Angular Performance Monitoring:**\n```typescript\nimport { afterRender } from \'@angular/core\';\n\n@Component({})\nexport class AppComponent {\n  constructor() {\n    afterRender(() => {\n      // Measure after each render\n      const perfEntries = performance.getEntriesByType(\'paint\');\n      console.log(perfEntries);\n    });\n  }\n}\n```\n\n**Tools for Production Monitoring:**\n- **Chrome UX Report (CrUX)**: Real user data from Chrome users\n- **PageSpeed Insights**: Combines CrUX data with Lighthouse lab data\n- **web-vitals npm package**: Client-side metrics collection\n\n**Key Takeaways:**\n1. Use the web-vitals library for standardized metrics collection\n2. Monitor real user data (RUM) alongside lab data\n3. Track metrics over time to detect regressions' }
    ]
  },
  {
    id: 703, slug: 'perf-rendering-pipeline', title: 'Browser Rendering Pipeline',
    description: 'Understand how browsers render pages — from HTML parsing to painting pixels on screen, and how to optimize each stage.',
    level: 'beginner', duration: '30 min',
    objectives: ['Explain the browser rendering pipeline stages', 'Identify what triggers layout, paint, and composite', 'Minimize forced reflows and repaints', 'Optimize animations for GPU compositing'],
    quiz: [
      { id: 1, question: 'What is the correct order of the browser rendering pipeline?', options: ['Parse -> Paint -> Layout -> Composite', 'Parse -> Style -> Layout -> Paint -> Composite', 'Style -> Parse -> Layout -> Composite -> Paint', 'Layout -> Parse -> Style -> Paint -> Composite'], correctIndex: 1, explanation: 'The browser pipeline: HTML parsing -> Style calculation -> Layout (geometry) -> Paint (pixels) -> Composite (layers).' },
      { id: 2, question: 'Which CSS property triggers a layout recalculation?', options: ['color', 'transform', 'width', 'opacity'], correctIndex: 2, explanation: 'Changing "width" triggers layout recalculation because it affects element geometry. Color, transform, and opacity only trigger paint or composite.' },
      { id: 3, question: 'What is "compositing" in the browser?', options: ['Combining multiple CSS files', 'Combining multiple pages into one', 'Drawing multiple layers into the final screen output', 'Merging JavaScript bundles'], correctIndex: 2, explanation: 'Compositing is the final step where the browser draws all the painted layers onto the screen in the correct order.' }
    ],
    topics: [
      { id: 'pipeline-overview', title: 'Rendering Pipeline Overview', content: '**The Browser Rendering Pipeline:**\n\n```\nHTML Document\n    |\n    v\n[Parse HTML] --> [Build DOM]\n    |\n    v\n[Parse CSS] --> [Build CSSOM]\n    |\n    v\n[Render Tree] (DOM + CSSOM)\n    |\n    v\n[Layout] (Calculate geometry and positions)\n    |\n    v\n[Paint] (Fill in pixels for each layer)\n    |\n    v\n[Composite] (Draw layers to screen)\n```\n\n**Each Stage Explained:**\n\n1. **DOM Construction**: Browser parses HTML into a tree of nodes\n2. **CSSOM Construction**: Browser parses CSS into style rules\n3. **Render Tree**: Combines DOM and CSSOM (excludes hidden elements)\n4. **Layout**: Calculates exact positions and sizes of every element\n5. **Paint**: Fills in pixels — text, colors, borders, shadows\n6. **Composite**: Arranges layers and draws them on screen\n\n**Key Takeaways:**\n1. Layout is the most expensive step — avoid triggering it\n2. Changes to geometry (width, height) trigger layout\n3. Changes to appearance (color, shadow) skip layout, trigger paint' },
      { id: 'reflow-repaint', title: 'Reflow & Repaint', content: '**What Triggers Reflow (Layout)?**\n- Changing `width`, `height`, `margin`, `padding`\n- Changing `border-width`, `position`, `display`\n- Changing `font-size`, `text-align`\n- Adding/removing DOM elements\n- Reading `offsetWidth`, `offsetHeight`\n\n**What Triggers Only Repaint (No Layout)?**\n- Changing `color`, `background-color`\n- Changing `box-shadow`, `text-shadow`\n- Changing `visibility`, `opacity`\n- Adding CSS outlines\n\n**What Triggers Only Composite (Cheapest)?**\n- `transform` (translate, rotate, scale)\n- `opacity`\n- `filter`\n\n**Minimizing Reflows:**\n```javascript\n// BAD: Multiple reflows\nfor (let i = 0; i < 100; i++) {\n  element.style.width = i + \'px\';\n  console.log(element.offsetWidth); // Forces layout\n}\n\n// GOOD: Batch reads and writes\nconst width = element.offsetWidth; // Read once\nfor (let i = 0; i < 100; i++) {\n  element.style.width = i + \'px\'; // Write\n}\n```\n\n**Key Takeaways:**\n1. Batch DOM reads and writes to minimize reflows\n2. Use `transform` instead of `top`/`left` for animations\n3. Read geometry properties once, then batch all writes' },
      { id: 'gpu-compositing', title: 'GPU Compositing & Layers', content: '**What is GPU Compositing?**\n\nThe browser can promote elements to separate GPU layers, which are composited on the GPU — much faster than CPU painting.\n\n**Promoting to Layers:**\n```css\n/* Create a new compositing layer */\n.animated-element {\n  will-change: transform;\n  /* or */\n  transform: translateZ(0);\n}\n```\n\n**Optimized Animations:**\n```css\n/* BAD: Triggers layout + paint */\n.bad-animation {\n  animation: moveBad 1s infinite;\n}\n@keyframes moveBad {\n  from { left: 0; }  /* Triggers layout */\n  to { left: 100px; }\n}\n\n/* GOOD: GPU-composited */\n.good-animation {\n  animation: moveGood 1s infinite;\n}\n@keyframes moveGood {\n  from { transform: translateX(0); }   /* Only composite */\n  to { transform: translateX(100px); }\n}\n```\n\n**will-change Best Practices:**\n- Use `will-change` sparingly — each promoted layer uses GPU memory\n- Remove `will-change` after the animation completes\n- Never use `will-change: transform` on more than 3-4 elements\n\n**Key Takeaways:**\n1. Use `transform` and `opacity` for animations — GPU-composited\n2. `will-change` promotes an element to its own layer\n3. Excessive layers waste GPU memory — use strategically' },
      { id: 'critical-rendering-path', title: 'Critical Rendering Path', content: '**What is the Critical Rendering Path?**\n\nThe sequence of steps the browser takes to convert HTML, CSS, and JavaScript into pixels on screen.\n\n**Optimizing the CRP:**\n\n1. **Inline critical CSS**\n```html\n<style>\n  /* Above-the-fold CSS inlined */\n  body { margin: 0; font-family: sans-serif; }\n  .hero { height: 100vh; background: #333; }\n</style>\n<link rel="preload" href="full-styles.css" as="style" onload="this.rel=\'stylesheet\'">\n```\n\n2. **Defer non-critical JavaScript**\n```html\n<!-- Defer parsing -->\n<script src="app.js" defer></script>\n\n<!-- Async for independent scripts -->\n<script src="analytics.js" async></script>\n```\n\n3. **Resource hints**\n```html\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="dns-prefetch" href="https://analytics.com">\n<link rel="preload" href="hero.avif" as="image">\n```\n\n**Render-Blocking Resources:**\n- CSS files in `<head>` are render-blocking\n- Synchronous `<script>` tags are render-blocking\n- Use `defer` or `async` for non-critical scripts\n\n**Key Takeaways:**\n1. Inline critical CSS for above-the-fold content\n2. Defer non-critical JavaScript with defer/async\n3. Use preconnect for known third-party origins' }
    ]
  },
  {
    id: 704, slug: 'perf-bundle-analysis', title: 'Bundle Analysis & Optimization',
    description: 'Analyze and optimize your JavaScript bundles — identify bloat, remove dead code, and reduce bundle sizes.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Analyze bundle contents using visualization tools', 'Identify and remove duplicate dependencies', 'Implement strategies to reduce JavaScript bundle size', 'Set up automated bundle size tracking'],
    quiz: [
      { id: 1, question: 'What does webpack-bundle-analyzer show you?', options: ['Network request waterfall', 'Treemap visualization of bundle contents and sizes', 'JavaScript error logs', 'CSS specificity issues'], correctIndex: 1, explanation: 'webpack-bundle-analyzer creates an interactive treemap showing what packages and modules make up your bundle.' },
      { id: 2, question: 'Which tool helps identify duplicate packages in your bundle?', options: ['Duplicate Package Checker', 'npm dedupe', 'Both A and B', 'Neither'], correctIndex: 2, explanation: 'Duplicate Package Checker identifies duplicates, and npm dedupe can resolve them. Using both gives the best results.' },
      { id: 3, question: 'What is the impact of moment.js on bundle size?', options: ['It\'s very small (~10KB)', 'It\'s large (~300KB) due to included locales', 'It doesn\'t affect bundle size', 'It\'s tree-shakeable'], correctIndex: 1, explanation: 'moment.js includes all locales by default, making it ~300KB. Replace with date-fns or dayjs for much smaller bundles.' }
    ],
    topics: [
      { id: 'bundle-visualization', title: 'Bundle Visualization', content: '**Webpack Bundle Analyzer:**\n```javascript\n// webpack.config.js\nconst { BundleAnalyzerPlugin } = require(\'webpack-bundle-analyzer\');\n\nmodule.exports = {\n  plugins: [\n    new BundleAnalyzerPlugin({\n      analyzerMode: \'static\',\n      reportFilename: \'bundle-report.html\',\n      openAnalyzer: true\n    })\n  ]\n};\n```\n\n**Vite Bundle Analysis:**\n```typescript\n// vite.config.ts\nimport { visualizer } from \'rollup-plugin-visualizer\';\n\nexport default defineConfig({\n  plugins: [\n    visualizer({\n      open: true,\n      filename: \'stats.html\',\n      gzipSize: true,\n      brotliSize: true\n    })\n  ]\n});\n```\n\n**What to Look For:**\n- Large, unexpected packages (moment.js, lodash full)\n- Duplicate packages (lodash + lodash-es)\n- Large internal modules\n- Unused code from dependencies\n\n**Key Takeaways:**\n1. Run bundle analysis before every major release\n2. Compare reports between builds to catch regressions\n3. Focus optimization on the largest modules first' },
      { id: 'removing-bloat', title: 'Removing Bundle Bloat', content: '**Common Bloat Sources:**\n\n1. **Full library imports**\n```javascript\n// BAD: Imports entire library\nimport _ from \'lodash\';\n\n// GOOD: Import specific functions\nimport debounce from \'lodash/debounce\';\n\n// BETTER: Use tree-shakeable alternative\nimport { debounce } from \'lodash-es\';\n```\n\n2. **moment.js alternatives**\n```javascript\n// BAD: ~300KB with locales\nimport moment from \'moment\';\n\n// GOOD: ~2KB\nimport { format } from \'date-fns\';\n\n// ALSO GOOD: ~7KB\nimport dayjs from \'dayjs\';\n```\n\n3. **Duplicate Package Check**\n```bash\n# Find duplicates\nnpx duplicate-package-checker\n\n# Auto-deduplicate\nnpm dedupe\n\n# For pnpm\npnpm dedupe\n```\n\n**Size Comparison:**\n```\nLibrary          | Full Size | Tree-Shakeable Alternative\n----------------|-----------|---------------------------\nlodash           | ~70KB     | lodash-es (~20KB)\nmoment.js        | ~300KB    | date-fns (~2KB)\nantd             | ~1.2MB    | Import individual components\nrxjs             | ~30KB     | Import specific operators\n```\n\n**Key Takeaways:**\n1. Use tree-shakeable libraries (lodash-es, date-fns)\n2. Run duplicate-package-checker to find duplicates\n3. Import only what you need from large libraries' },
      { id: 'code-splitting', title: 'Code Splitting Strategies', content: '**Route-Based Splitting:**\n```typescript\n// Angular\nconst routes: Routes = [\n  {\n    path: \'dashboard\',\n    loadComponent: () => import(\'./dashboard.component\')\n      .then(m => m.DashboardComponent)\n  }\n];\n\n// React\nconst Dashboard = lazy(() => import(\'./Dashboard\'));\n```\n\n**Component-Based Splitting:**\n```typescript\n// Load heavy component on demand\nasync function showChart() {\n  const { ChartComponent } = await import(\'./ChartComponent\');\n  // Render ChartComponent\n}\n```\n\n**Vendor Splitting:**\n```javascript\n// Vite manualChunks\nbuild: {\n  rollupOptions: {\n    output: {\n      manualChunks: {\n        vendor: [\'@angular/core\', \'@angular/common\', \'@angular/router\'],\n        utils: [\'lodash-es\', \'date-fns\']\n      }\n    }\n  }\n}\n```\n\n**Key Takeaways:**\n1. Split by routes — load only what the current page needs\n2. Lazy-load heavy components (charts, editors, modals)\n3. Separate vendor code for better caching across deploys' },
      { id: 'bundle-tracking', title: 'Automated Bundle Size Tracking', content: '**Size Limit (CI Integration):**\n```json\n// .size-limit.json\n[\n  {\n    "path": "dist/main.js",\n    "limit": "200 KB"\n  },\n  {\n    "path": "dist/vendor.js",\n    "limit": "100 KB"\n  }\n]\n```\n\n```bash\n# Install size-limit\nnpm install --save-dev size-limit @size-limit/preset-small-lib\n\n# Add to package.json scripts\n"size": "size-limit"\n\n# Run check\nnpx size-limit\n```\n\n**GitHub Actions Integration:**\n```yaml\n- name: Check bundle size\n  uses: andresz1/size-limit-action@v1\n  with:\n    github_token: ${{ secrets.GITHUB_TOKEN }}\n```\n\n**Bundlephobia Integration:**\n```bash\n# Check npm package sizes before installing\nnpx bundlephobia lodash-es\nnpx bundlephobia moment\n```\n\n**Key Takeaways:**\n1. Use size-limit to enforce bundle budgets in CI\n2. Check package sizes before installing new dependencies\n3. GitHub Actions can report bundle size changes on PRs' }
    ]
  },
  {
    id: 705, slug: 'perf-code-splitting', title: 'Code Splitting & Lazy Loading',
    description: 'Implement effective code splitting — split your application into smaller chunks that load on demand.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Implement route-based code splitting in Angular', 'Configure dynamic imports for on-demand loading', 'Optimize chunk sizes and loading strategies', 'Handle loading states and error boundaries'],
    quiz: [
      { id: 1, question: 'What is code splitting?', options: ['Breaking code into multiple files for editing', 'Dividing JavaScript bundles so only required code loads', 'Splitting CSS into multiple files', 'Separating frontend and backend code'], correctIndex: 1, explanation: 'Code splitting divides your bundle into smaller chunks that can be loaded on demand, reducing initial page load time.' },
      { id: 2, question: 'How do you implement lazy loading in Angular?', options: ['Using ngOnInit()', 'Using loadComponent in route configuration', 'Using @Lazy() decorator', 'Using async/await in components'], correctIndex: 1, explanation: 'Angular uses loadComponent (or loadChildren) in route configuration with dynamic import() for lazy loading.' },
      { id: 3, question: 'What is a "chunk" in webpack terminology?', options: ['A piece of candy', 'A group of modules forming a bundle', 'A CSS selector', 'A database record'], correctIndex: 1, explanation: 'A chunk is a group of modules that webpack bundles together — the output of code splitting is multiple chunks.' }
    ],
    topics: [
      { id: 'angular-lazy-loading', title: 'Angular Lazy Loading', content: '**Component-Level Lazy Loading:**\n```typescript\n// app.routes.ts\nexport const routes: Routes = [\n  {\n    path: \'dashboard\',\n    loadComponent: () => import(\'./dashboard/dashboard.component\')\n      .then(m => m.DashboardComponent)\n  },\n  {\n    path: \'settings\',\n    loadComponent: () => import(\'./settings/settings.component\')\n      .then(m => m.SettingsComponent)\n  },\n  {\n    path: \'admin\',\n    loadChildren: () => import(\'./admin/admin.routes\')\n      .then(m => m.ADMIN_ROUTES)\n  }\n];\n```\n\n**Preloading Strategy:**\n```typescript\n// app.config.ts\nexport const appConfig: ApplicationConfig = {\n  providers: [\n    provideRouter(\n      routes,\n      withPreloading(PreloadAllModules)  // Preload all lazy routes\n    )\n  ]\n};\n```\n\n**Loading State Handling:**\n```typescript\n// app.component.html\n<router-outlet></router-outlet>\n\n@if (isRouteLoading) {\n  <app-loading-spinner></app-loading-spinner>\n}\n```\n\n**Key Takeaways:**\n1. Use loadComponent for individual lazy-loaded components\n2. Use loadChildren for lazy-loaded feature modules\n3. withPreloading(PreloadAllModules) preloads lazy routes in background' },
      { id: 'dynamic-imports', title: 'Dynamic Imports', content: '**Syntax:**\n```typescript\n// Basic dynamic import\nconst module = await import(\'./heavy-module\');\n\n// With webpack magic comments\nconst module = await import(\n  /* webpackChunkName: "heavy" */\n  /* webpackPrefetch: true */\n  \'./heavy-module\'\n);\n```\n\n**Conditional Loading:**\n```typescript\n// Load polyfill only if needed\nif (!window.Promise) {\n  const { default: PromisePolyfill } = await import(\'promise-polyfill\');\n  window.Promise = PromisePolyfill;\n}\n\n// Load feature based on user role\nif (user.isAdmin) {\n  const { AdminPanel } = await import(\'./admin-panel\');\n  this.renderAdminPanel(AdminPanel);\n}\n```\n\n**Preloading Hints:**\n```javascript\n// Prefetch: Low priority - load during idle time\nconst link = document.createElement(\'link\');\nlink.rel = \'prefetch\';\nlink.href = \'chunk.js\';\ndocument.head.appendChild(link);\n\n// Preload: High priority - load immediately\nconst link = document.createElement(\'link\');\nlink.rel = \'modulepreload\';\nlink.href = \'critical.js\';\ndocument.head.appendChild(link);\n```\n\n**Key Takeaways:**\n1. Use dynamic import() for code splitting\n2. Use prefetch for non-critical chunks, preload for critical\n3. webpackChunkName creates meaningful chunk filenames' },
      { id: 'chunk-optimization', title: 'Chunk Optimization', content: '**Chunk Size Guidelines:**\n```\nInitial bundle:     < 200KB (gzipped)\nLazy-loaded chunks: < 50KB each\nVendor chunk:       < 100KB\n```\n\n**Manual Chunk Configuration:**\n```javascript\n// Vite\nexport default defineConfig({\n  build: {\n    rollupOptions: {\n      output: {\n        manualChunks(id) {\n          if (id.includes(\'node_modules\')) {\n            if (id.includes(\'@angular\')) return \'angular\';\n            if (id.includes(\'rxjs\')) return \'rxjs\';\n            return \'vendor\';\n          }\n        }\n      }\n    }\n  }\n});\n```\n\n**Chunk Naming:**\n```javascript\n// Predictable chunk names for caching\noutput: {\n  chunkFilename: \'[name].[contenthash].js\',\n  entryFilename: \'[name].[contenthash].js\'\n}\n```\n\n**Key Takeaways:**\n1. Keep initial bundle under 200KB gzipped\n2. Separate Angular, RxJS, and other vendor code into dedicated chunks\n3. Use content hashing for cache-busting' },
      { id: 'error-boundaries', title: 'Handling Lazy Load Errors', content: '**Error Handling for Dynamic Imports:**\n```typescript\nasync function loadDashboard() {\n  try {\n    const { DashboardComponent } = await import(\'./dashboard.component\');\n    return DashboardComponent;\n  } catch (error) {\n    console.error(\'Failed to load dashboard:\', error);\n    // Return fallback component\n    return FallbackComponent;\n  }\n}\n```\n\n**Angular Error Interceptor:**\n```typescript\n// With Angular\'s built-in error handling\nconst routes: Routes = [\n  {\n    path: \'dashboard\',\n    loadComponent: () => import(\'./dashboard.component\')\n      .then(m => m.DashboardComponent)\n      .catch(err => {\n        console.error(\'Lazy load failed:\', err);\n        return import(\'./fallback.component\')\n          .then(m => m.FallbackComponent);\n      })\n  }\n];\n```\n\n**Network-Aware Loading:**\n```typescript\nasync function smartLoad() {\n  const connection = navigator.connection;\n  \n  if (connection?.effectiveType === \'2g\' || connection?.saveData) {\n    // Load lightweight version on slow connections\n    return import(\'./lightweight-version\');\n  }\n  \n  return import(\'./full-version\');\n}\n```\n\n**Key Takeaways:**\n1. Always add .catch() to dynamic imports for error handling\n2. Provide fallback components when lazy loading fails\n3. Consider network conditions for optimal loading strategy' }
    ]
  },
  {
    id: 706, slug: 'perf-caching', title: 'Caching Strategies',
    description: 'Master web caching — HTTP caching, service workers, and cache invalidation strategies for optimal performance.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Configure HTTP caching headers for optimal performance', 'Implement service worker caching strategies', 'Design cache invalidation approaches', 'Balance freshness with cache hit rates'],
    quiz: [
      { id: 1, question: 'What is the difference between "no-cache" and "no-store"?', options: ['They are identical', 'no-cache allows caching but requires revalidation, no-store prevents all caching', 'no-store is faster', 'no-cache prevents caching entirely'], correctIndex: 1, explanation: 'no-cache allows the response to be cached but requires revalidation before use. no-store prevents the response from being cached at all.' },
      { id: 2, question: 'Which HTTP header controls how long a cached response is considered fresh?', options: ['ETag', 'Last-Modified', 'Cache-Control: max-age', 'Content-Type'], correctIndex: 2, explanation: 'max-age in Cache-Control specifies how many seconds the response is considered fresh without revalidation.' },
      { id: 3, question: 'What is "cache invalidation" often called?', options: ['Cache warming', 'Cache busting', 'Cache priming', 'Cache refreshing'], correctIndex: 1, explanation: 'Cache invalidation is often called "cache busting" — techniques to force the browser to fetch fresh content (e.g., query strings, content hashing).' }
    ],
    topics: [
      { id: 'http-caching', title: 'HTTP Caching Headers', content: '**Essential Cache Headers:**\n\n```nginx\n# nginx configuration\n\n# Immutable assets (hashed filenames)\nlocation ~* \\.(js|css|png|jpg|avif|woff2)$ {\n  Cache-Control: public, max-age=31536000, immutable;\n}\n\n# HTML files (always revalidate)\nlocation ~* \\.html$ {\n  Cache-Control: no-cache;\n}\n\n# API responses (short cache)\nlocation /api/ {\n  Cache-Control: private, max-age=300;\n}\n```\n\n**Cache-Control Directives:**\n```\ndirective       | Description\n----------------|------------------------------------------\npublic           | Response can be cached by any cache\nprivate          | Response only cacheable by browser\nno-cache         | Cache but require revalidation\nno-store         | Do not cache at all\nmax-age=<s>      | Fresh for <s> seconds\nimmutable        | Content will never change\nmust-revalidate  | Must revalidate when stale\n```\n\n**ETag and Last-Modified:**\n```nginx\nlocation /api/ {\n  add_header Cache-Control "no-cache";\n  add_header ETag "$upstream_http_etag";\n}\n```\n\n**Key Takeaways:**\n1. Use immutable + long max-age for hashed assets\n2. Use no-cache for HTML to always get fresh content\n3. ETag enables conditional requests (304 Not Modified)' },
      { id: 'cache-invalidation', title: 'Cache Invalidation Strategies', content: '**Content Hashing (Cache Busting):**\n```javascript\n// Vite generates hashed filenames\n// Output: main.a1b2c3d4.js\n// When content changes: main.e5f6g7h8.js\noutput: {\n  filename: \'[name].[contenthash].js\'\n}\n```\n\n**Query String Versioning:**\n```html\n<!-- Cache-busting via query string -->\n<script src="app.js?v=1.2.3"></script>\n```\n\n**Cache Invalidation Patterns:**\n```javascript\n// 1. Cache-Aside (Lazy Loading)\nasync function getData(key) {\n  let data = cache.get(key);\n  if (!data) {\n    data = await fetchFromAPI(key);\n    cache.set(key, data, ttl: 3600);\n  }\n  return data;\n}\n\n// 2. Write-Through\nasync function saveData(key, data) {\n  await saveToAPI(key, data);\n  cache.set(key, data);\n}\n\n// 3. Write-Behind (Write-Back)\nasync function saveData(key, data) {\n  cache.set(key, data);\n  queue.add(() => saveToAPI(key, data));\n}\n```\n\n**Key Takeaways:**\n1. Content hashing is the most reliable cache-busting strategy\n2. Cache-Aside is the most common caching pattern\n3. Match cache duration to content update frequency' },
      { id: 'service-worker-caching', title: 'Service Worker Caching', content: '**Cache API:**\n```javascript\n// Cache assets during install\nself.addEventListener(\'install\', (event) => {\n  event.waitUntil(\n    caches.open(\'v1\').then(cache => {\n      return cache.addAll([\n        \'/\',\n        \'/index.html\',\n        \'/styles.css\',\n        \'/app.js\'\n      ]);\n    })\n  );\n});\n\n// Serve from cache, fallback to network\nself.addEventListener(\'fetch\', (event) => {\n  event.respondWith(\n    caches.match(event.request).then(response => {\n      return response || fetch(event.request);\n    })\n  );\n});\n```\n\n**Caching Strategies:**\n```javascript\n// Cache First (offline-capable)\nasync function cacheFirst(request) {\n  const cached = await caches.match(request);\n  return cached || fetch(request);\n}\n\n// Network First (always fresh)\nasync function networkFirst(request) {\n  try {\n    const response = await fetch(request);\n    const cache = await caches.open(\'v1\');\n    cache.put(request, response.clone());\n    return response;\n  } catch {\n    return caches.match(request);\n  }\n}\n\n// Stale While Revalidate\nasync function staleWhileRevalidate(request) {\n  const cache = await caches.open(\'v1\');\n  const cached = await cache.match(request);\n  const fetchPromise = fetch(request).then(response => {\n    cache.put(request, response.clone());\n    return response;\n  });\n  return cached || fetchPromise;\n}\n```\n\n**Key Takeaways:**\n1. Cache First is best for static assets\n2. Network First is best for API data\n3. Stale While Revalidate provides fast response + freshness' },
      { id: 'cdn-caching', title: 'CDN Caching', content: '**CDN Caching Architecture:**\n```\nUser -> CDN Edge Node -> Origin Server\n         (cached)        (cache miss)\n```\n\n**CDN Cache Headers:**\n```nginx\n# CDN-specific caching\nlocation /static/ {\n  # Serve from CDN for 1 year\n  Cache-Control: public, max-age=31533600, immutable;\n  add_header CDN-Cache-Control "max-age=31536000";\n}\n\n# Purge CDN cache on deploy\n# curl -X PURGE https://cdn.example.com/static/\n```\n\n**Multi-Tier Caching:**\n```\nBrowser Cache (1 year)\n    \u2193 (miss)\nCDN Edge Cache (1 hour)\n    \u2193 (miss)\nCDN Shield Cache (5 min)\n    \u2193 (miss)\nOrigin Server\n```\n\n**CDN Cache Purging:**\n```bash\n# Purge by URL\ncurl -X POST "https://api.cdn.com/purge" \\\n  -H "Authorization: Bearer token" \\\n  -d \'{"urls": ["https://cdn.example.com/app.js"]}\'\n\n# Purge entire cache (last resort)\ncurl -X POST "https://api.cdn.com/purge" \\\n  -d \'{"purge_all": true}\'\n```\n\n**Key Takeaways:**\n1. Set long cache durations for immutable CDN assets\n2. Use CDN-Cache-Control for CDN-specific behavior\n3. Purge CDN cache when deploying critical updates' }
    ]
  },
  {
    id: 707, slug: 'perf-image-optimization', title: 'Image Optimization',
    description: 'Optimize images for web performance — modern formats, responsive images, lazy loading, and compression techniques.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Choose the right image format for different use cases', 'Implement responsive images with srcset and sizes', 'Use lazy loading and priority hints for images', 'Optimize image compression for quality vs size'],
    quiz: [
      { id: 1, question: 'Which image format offers the best compression for photographs?', options: ['PNG', 'GIF', 'WebP', 'BMP'], correctIndex: 2, explanation: 'WebP offers 25-35% better compression than JPEG for photographs with comparable quality, supported by all modern browsers.' },
      { id: 2, question: 'What does the "loading=lazy" attribute do?', options: ['Delays image download until near viewport', 'Loads image immediately at full resolution', 'Prevents image from loading', 'Loads image in a separate thread'], correctIndex: 0, explanation: 'loading=lazy defers loading of off-screen images until they are about to enter the viewport, saving bandwidth.' },
      { id: 3, question: 'What is the purpose of srcset in <img> tags?', options: ['To set image source URL', 'To provide multiple image versions for different screen sizes', 'To add alt text', 'To set image dimensions'], correctIndex: 1, explanation: 'srcset provides multiple image versions, and the browser picks the most appropriate one based on screen size and pixel density.' }
    ],
    topics: [
      { id: 'image-formats', title: 'Image Format Selection', content: '**Format Comparison:**\n```\nFormat  | Best For          | Compression | Transparency | Animation\n--------|-------------------|-------------|--------------|----------\nJPEG    | Photos            | Lossy       | No           | No\nPNG     | Graphics, logos   | Lossless    | Yes          | No\nWebP    | Everything        | Both        | Yes          | Yes\nAVIF    | Photos (modern)   | Superior    | Yes          | Yes\nSVG     | Icons, logos      | N/A         | Yes          | Yes\nGIF     | Simple animation  | LZW         | No           | Yes\n```\n\n**Modern Format Usage:**\n```html\n<picture>\n  <source srcset="image.avif" type="image/avif">\n  <source srcset="image.webp" type="image/webp">\n  <img src="image.jpg" alt="Description">\n</picture>\n```\n\n**When to Use Each:**\n- **JPEG**: Photographs, complex images (older browser support needed)\n- **PNG**: Graphics with transparency, screenshots, logos\n- **WebP**: Default choice for most images (excellent browser support)\n- **AVIF**: Highest quality photos (Chrome/Firefox support)\n- **SVG**: Icons, logos, illustrations, simple graphics\n\n**Key Takeaways:**\n1. Use WebP as the default image format\n2. Use AVIF for maximum compression on photos\n3. Always provide JPEG fallback for maximum compatibility' },
      { id: 'responsive-images', title: 'Responsive Images', content: '**srcset and sizes:**\n```html\n<img \n  src="photo-800.jpg"\n  srcset="photo-400.jpg 400w,\n          photo-800.jpg 800w,\n          photo-1200.jpg 1200w"\n  sizes="(max-width: 600px) 100vw,\n         (max-width: 1200px) 50vw,\n         33vw"\n  alt="Responsive photo"\n  loading="lazy"\n  width="800"\n  height="600"\n>\n```\n\n**How it works:**\n1. `srcset` lists available images with their widths\n2. `sizes` tells the browser how wide the image will display\n3. Browser picks the optimal image from srcset\n\n**Art Direction:**\n```html\n<picture>\n  <source media="(min-width: 1200px)" srcset="wide-crop.jpg">\n  <source media="(min-width: 600px)" srcset="medium-crop.jpg">\n  <img src="narrow-crop.jpg" alt="Art-directed image">\n</picture>\n```\n\n**Key Takeaways:**\n1. Always set width and height attributes (prevents layout shift)\n2. Use sizes to describe how the image will be displayed\n3. Use <picture> for art direction (different crops for different viewports)' },
      { id: 'lazy-loading', title: 'Image Lazy Loading', content: '**Native Lazy Loading:**\n```html\n<!-- Below the fold - lazy load -->\n<img src="photo.jpg" loading="lazy" alt="Below fold">\n\n<!-- Above the fold - eager load -->\n<img src="hero.jpg" loading="eager" fetchpriority="high" alt="Hero">\n```\n\n**JavaScript Lazy Loading:**\n```javascript\n// Intersection Observer approach\nconst observer = new IntersectionObserver((entries) => {\n  entries.forEach(entry => {\n    if (entry.isIntersecting) {\n      const img = entry.target;\n      img.src = img.dataset.src;\n      observer.unobserve(img);\n    }\n  });\n});\n\ndocument.querySelectorAll(\'img[data-src]\').forEach(img => {\n  observer.observe(img);\n});\n```\n\n**Priority Hints:**\n```html\n<!-- Critical hero image -->\n<img src="hero.jpg" fetchpriority="high" alt="Hero">\n\n<!-- Non-critical below-fold -->\n<img src="photo.jpg" fetchpriority="low" loading="lazy" alt="Photo">\n```\n\n**Lazy Loading Best Practices:**\n- Never lazy-load above-the-fold images (hurts LCP)\n- Use `loading="lazy"` for all below-fold images\n- Set `fetchpriority="high"` on the LCP image\n- Always set width and height to prevent CLS\n\n**Key Takeaways:**\n1. Never lazy-load above-the-fold images — it hurts LCP\n2. Use fetchpriority=\"high\" on the LCP element\n3. Native loading=lazy is supported in all modern browsers' },
      { id: 'image-compression', title: 'Image Compression', content: '**Lossy vs Lossless:**\n- **Lossy**: Removes data for smaller files (JPEG, WebP lossy)\n- **Lossless**: Preserves all data (PNG, WebP lossless)\n\n**Compression Tools:**\n```bash\n# Image optimization in build pipeline\nnpm install --save-dev imagemin imagemin-mozjpeg imagemin-pngquant imagemin-webp\n\n# CLI tools\nnpm install -g sharp-cli\nsharp -i input.jpg -o output.webp --format webp --quality 80\n```\n\n**Compression Quality Guide:**\n```\nFormat  | Recommended Quality | Use Case\n--------|---------------------|--------------------------\nJPEG    | 75-85%              | Photos\nWebP    | 75-85%              | Photos (better compression)\nAVIF    | 60-75%              | Photos (best compression)\n```\n\n**Automated Optimization (Build-Time):**\n```typescript\n// sharp in Node.js\nimport sharp from \'sharp\';\n\nawait sharp(\'input.jpg\')\n  .resize(1200, 800, { fit: \'inside\' })\n  .webp({ quality: 80 })\n  .toFile(\'output.webp\');\n```\n\n**Key Takeaways:**\n1. WebP at 80% quality is usually indistinguishable from JPEG at 95%\n2. Use sharp or imagemin in your build pipeline\n3. Generate multiple sizes and formats for responsive images' }
    ]
  },
  {
    id: 708, slug: 'perf-monitoring-rum', title: 'Performance Monitoring & RUM',
    description: 'Set up Real User Monitoring (RUM) to track performance metrics from actual users in production.',
    level: 'advanced', duration: '30 min',
    objectives: ['Implement a RUM system for collecting real user performance data', 'Track Core Web Vitals from production traffic', 'Set up performance alerts and dashboards', 'Correlate performance with business metrics'],
    quiz: [
      { id: 1, question: 'What is Real User Monitoring (RUM)?', options: ['Running tests in a lab environment', 'Collecting performance data from actual users in production', 'Simulating user traffic with bots', 'Monitoring server CPU usage'], correctIndex: 1, explanation: 'RUM collects real performance data from actual users visiting your production site, providing insights into real-world performance.' },
      { id: 2, question: 'What is the advantage of RUM over Lighthouse lab data?', options: ['RUM is faster to run', 'RUM captures real device and network conditions', 'RUM is free', 'RUM tests more pages'], correctIndex: 1, explanation: 'RUM captures performance on real devices with real network conditions, while lab data uses controlled environments that may not represent actual users.' },
      { id: 3, question: 'How should RUM data be sampled in high-traffic applications?', options: ['Collect every data point', 'Use statistical sampling (e.g., 1-10% of sessions)', 'Only collect from mobile users', 'Only collect on page errors'], correctIndex: 1, explanation: 'High-traffic sites use statistical sampling to keep costs manageable while maintaining statistical significance.' }
    ],
    topics: [
      { id: 'rum-implementation', title: 'RUM Implementation', content: '**Web Vitals Collection:**\n```typescript\n// performance-monitor.ts\nimport { onLCP, onFID, onCLS, onINP, onTTFB, Metric } from \'web-vitals\';\n\ninterface PerformanceReport {\n  metric: string;\n  value: number;\n  rating: \'good\' | \'needs-improvement\' | \'poor\';\n  delta: number;\n  id: string;\n  url: string;\n  userAgent: string;\n  connection: string;\n  timestamp: number;\n}\n\nfunction reportMetric(metric: Metric) {\n  const report: PerformanceReport = {\n    metric: metric.name,\n    value: metric.value,\n    rating: metric.rating,\n    delta: metric.delta,\n    id: metric.id,\n    url: window.location.href,\n    userAgent: navigator.userAgent,\n    connection: (navigator.connection as any)?.effectiveType || \'unknown\',\n    timestamp: Date.now()\n  };\n\n  // Send to analytics endpoint\n  if (navigator.sendBeacon) {\n    navigator.sendBeacon(\'/api/metrics\', JSON.stringify(report));\n  } else {\n    fetch(\'/api/metrics\', {\n      method: \'POST\',\n      body: JSON.stringify(report),\n      keepalive: true\n    });\n  }\n}\n\n// Initialize all metrics\nonLCP(reportMetric);\nonFID(reportMetric);\nonCLS(reportMetric);\nonINP(reportMetric);\nonTTFB(reportMetric);\n```\n\n**Key Takeaways:**\n1. Use web-vitals library for standardized metric collection\n2. SendBeacon ensures data survives page unload\n3. Include context (URL, connection type, device) with metrics' },
      { id: 'rum-dashboard', title: 'Performance Dashboard', content: '**Dashboard Components:**\n```\n1. Overview Panel\n   - P50/P75/P95/P99 for each metric\n   - Good/Needs Improvement/Poor distribution\n   - Trend over time\n\n2. Breakdown Panel\n   - By device type (mobile/desktop)\n   - By geographic region\n   - By page/URL\n   - By connection type\n\n3. Alerts Panel\n   - LCP > 4s alert\n   - CLS > 0.25 alert\n   - Error rate spike alert\n```\n\n**Grafana Dashboard Query Example:**\n```sql\n-- P75 LCP by page\nSELECT \n  percentile_cont(0.75) WITHIN GROUP (ORDER BY value) as p75_lcp\nFROM metrics\nWHERE name = \'LCP\'\n  AND timestamp > NOW() - INTERVAL \'24 hours\'\nGROUP BY url;\n```\n\n**Alerting Rules:**\n```yaml\n# Example alerting rule\n- alert: HighLCP\n  expr: percentile(0.75, metric_lcp) > 4000\n  for: 5m\n  labels:\n    severity: warning\n  annotations:\n    summary: "LCP P75 exceeds 4 seconds"\n```\n\n**Key Takeaways:**\n1. Track P75 as the primary percentile (balances outliers and typical experience)\n2. Break down metrics by device, region, and page for actionable insights\n3. Set alerts on metric degradation, not just thresholds' },
      { id: 'performance-budgets-ci', title: 'Performance Budgets in CI', content: '**Lighthouse CI:**\n```yaml\n# .github/workflows/lighthouse.yml\nname: Lighthouse CI\non: [pull_request]\njobs:\n  lighthouse:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n      - run: npm ci\n      - run: npm run build\n      - uses: treosh/lighthouse-ci-action@v10\n        with:\n          configPath: .lighthouserc.json\n```\n\n**Budget Configuration:**\n```json\n// .lighthouserc.json\n{\n  "ci": {\n    "assert": {\n      "assertions": {\n        "categories:performance": ["error", { "minScore": 0.8 }],\n        "first-contentful-paint": ["error", { "maxNumericValue": 2000 }],\n        "largest-contentful-paint": ["error", { "maxNumericValue": 2500 }],\n        "cumulative-layout-shift": ["error", { "maxNumericValue": 0.1 }],\n        "total-byte-weight": ["error", { "maxNumericValue": 300000 }]\n      }\n    }\n  }\n}\n```\n\n**Size Budgets:**\n```json\n// budget.json\n[\n  {\n    "path": "/",\n    "budgets": [\n      { "metric": "total-byte-weight", "budget": 300000 },\n      { "metric": "total-scripting-time", "budget": 3000 }\n    ]\n  }\n]\n```\n\n**Key Takeaways:**\n1. Set performance budgets as CI gates — block PRs that regress\n2. Use Lighthouse CI for automated performance testing\n3. Track budgets over time and tighten as performance improves' },
      { id: 'performance-profiling', title: 'Production Profiling', content: '**Chrome DevTools Remote Debugging:**\n```javascript\n// Enable performance monitoring in production\nif (window.location.search.includes(\'debug=true\')) {\n  const script = document.createElement(\'script\');\n  script.src = \'https://chrome-devtools-frontend.appspot.com/...\';\n  document.head.appendChild(script);\n}\n```\n\n**User Timing API:**\n```typescript\n// Custom performance marks\nperformance.mark(\'component-start\');\n// ... render component\nperformance.mark(\'component-end\');\n\nperformance.measure(\n  \'component-render\',\n  \'component-start\',\n  \'component-end\'\n);\n\n// Send to analytics\nconst measures = performance.getEntriesByType(\'measure\');\nmeasures.forEach(m => {\n  sendToAnalytics({\n    name: m.name,\n    duration: m.duration\n  });\n});\n```\n\n**Performance Profiling Best Practices:**\n- Use sampling profilers in production (not in development)\n- Profile real user sessions, not just synthetic tests\n- Correlate performance metrics with error rates\n- Track performance by page, device, and connection type\n\n**Key Takeaways:**\n1. Use User Timing API for custom performance measurements\n2. Profile production data, not just lab data\n3. Correlate performance with business metrics (conversion, bounce rate)' }
    ]
  },
  {
    id: 709, slug: 'perf-advanced-caching', title: 'Advanced Caching (Service Workers, CDN)',
    description: 'Implement advanced caching with service workers, CDN edge caching, and cache-first strategies for offline-capable apps.',
    level: 'advanced', duration: '35 min',
    objectives: ['Implement a service worker with Workbox for advanced caching', 'Configure CDN caching for global performance', 'Design offline-first caching strategies', 'Implement cache warming and prefetching strategies'],
    quiz: [
      { id: 1, question: 'What is the "stale-while-revalidate" caching strategy?', options: ['Only use cache', 'Return cached response immediately while fetching fresh data in background', 'Only use network', 'Delete cache and refetch'], correctIndex: 1, explanation: 'Stale-while-revalidate returns the cached version instantly while updating the cache in the background, giving users fast responses.' },
      { id: 2, question: 'What is CDN edge caching?', options: ['Caching on the user\'s browser', 'Caching content on servers distributed globally, close to users', 'Caching in the origin server', 'Caching database queries'], correctIndex: 1, explanation: 'CDN edge caching stores copies of content on geographically distributed servers, reducing latency by serving from the nearest location.' },
      { id: 3, question: 'What is cache warming?', options: ['Deleting old cache entries', 'Pre-populating cache before users request content', 'Heating the server CPU', 'Clearing all caches'], correctIndex: 1, explanation: 'Cache warming pre-populates caches with frequently accessed content, ensuring fast responses from the first request.' }
    ],
    topics: [
      { id: 'workbox', title: 'Workbox Service Worker', content: '**Setting Up Workbox:**\n```typescript\n// service-worker.ts\nimport { precacheAndRoute } from \'workbox-precaching\';\nimport { registerRoute } from \'workbox-routing\';\nimport { CacheFirst, StaleWhileRevalidate, NetworkFirst } from \'workbox-strategies\';\nimport { ExpirationPlugin } from \'workbox-expiration\';\n\n// Precache all built assets\nprecacheAndRoute(self.__WB_MANIFEST);\n\n// Cache-First for static assets\nregisterRoute(\n  ({ request }) => request.destination === \'image\',\n  new CacheFirst({\n    cacheName: \'images\',\n    plugins: [\n      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 30 * 24 * 60 * 60 })\n    ]\n  })\n);\n\n// Stale-While-Revalidate for styles/scripts\nregisterRoute(\n  ({ request }) => request.destination === \'style\' || request.destination === \'script\',\n  new StaleWhileRevalidate({ cacheName: \'static-resources\' })\n);\n\n// Network-First for API calls\nregisterRoute(\n  ({ url }) => url.pathname.startsWith(\'/api/\'),\n  new NetworkFirst({\n    cacheName: \'api-cache\',\n    networkTimeoutSeconds: 3\n  })\n);\n```\n\n**Key Takeaways:**\n1. Workbox simplifies service worker caching with high-level strategies\n2. Cache-First for immutable assets, Network-First for APIs\n3. Always set expiration policies to prevent unbounded cache growth' },
      { id: 'caching-strategies', title: 'Advanced Caching Patterns', content: '**Cache Strategies Comparison:**\n```\nStrategy              | When to Use          | Pros                    | Cons\n---------------------|----------------------|-------------------------|------------------\nCache-First          | Static assets        | Fast, offline capable   | May serve stale\nNetwork-First        | API data             | Always fresh            | Slower on slow networks\nStale-While-Revalidate | Semi-dynamic data  | Fast + fresh            | May show stale briefly\nNetwork-Only         | Never cache          | Always fresh            | No offline, slow\nCache-Only           | Offline-only apps    | Works offline           | No freshness\n```\n\n**Advanced Workbox Patterns:**\n```typescript\nimport { BackgroundSyncPlugin } from \'workbox-background-sync\';\n\n// Background sync for offline form submissions\nregisterRoute(\n  ({ url }) => url.pathname === \'/api/submit\',\n  new NetworkFirst({\n    plugins: [\n      new BackgroundSyncPlugin(\'submit-queue\', {\n        maxRetentionTime: 24 * 60  // Retry for 24 hours\n      })\n    ]\n  })\n);\n```\n\n**Cache Warming:**\n```javascript\n// Prefetch likely next pages\nconst link = document.createElement(\'link\');\nlink.rel = \'prefetch\';\nlink.href = \'/dashboard.js\';\ndocument.head.appendChild(link);\n```\n\n**Key Takeaways:**\n1. Choose caching strategy based on content freshness requirements\n2. Background sync enables offline functionality for forms\n3. Prefetch resources users are likely to need next' },
      { id: 'cdn-strategy', title: 'CDN Strategy & Configuration', content: '**CDN Architecture:**\n```\nUser\n  \u251c\u2500\u2500 Edge Server (nearest city) \u2192 Cache Hit? Return\n  \u2502\n  \u2514\u2500\u2500 Shield Server (regional) \u2192 Cache Hit? Return\n       \u2502\n       \u2514\u2500\u2500 Origin Server \u2192 Generate & Cache\n```\n\n**CDN Configuration (CloudFront example):**\n```javascript\n// CloudFront distribution\nconst distribution = {\n  CacheBehaviors: [\n    {\n      PathPattern: \'*.immutable.*\',\n      TTL: {\n        DefaultTTL: 365 * 24 * 60 * 60,  // 1 year\n        MaxTTL: 365 * 24 * 60 * 60\n      },\n      ViewerProtocolPolicy: \'redirect-to-https\'\n    },\n    {\n      PathPattern: \'*.html\',\n      TTL: {\n        DefaultTTL: 0,  // No caching\n        MaxTTL: 0\n      }\n    }\n  ]\n};\n```\n\n**Multi-CDN Strategy:**\n```\nPrimary CDN (CloudFront)\n  \u251c\u2500\u2500 Failover CDN (Fastly)\n  \u2502    \u251c\u2500\u2500 Health checks\n  \u2502    \u2514\u2500\u2500 Automatic failover\n  \u2514\u2500\u2500 Origin Shield\n```\n\n**Key Takeaways:**\n1. Use immutable caching for hashed assets (1 year+)\n2. No-cache for HTML files to always serve fresh content\n3. Multi-CDN provides redundancy and performance optimization' },
      { id: 'offline-first', title: 'Offline-First Applications', content: '**Offline-First Architecture:**\n```\n1. App Shell (cached by service worker)\n2. Dynamic data (cached with network fallback)\n3. Background sync (queue actions when offline)\n4. Conflict resolution (handle data sync conflicts)\n```\n\n**IndexedDB for Offline Storage:**\n```typescript\n// Using Dexie.js for IndexedDB\nimport Dexie from \'dexie\';\n\nclass OfflineDB extends Dexie {\n  pendingActions: Dexie.Table;\n  cachedData: Dexie.Table;\n\n  constructor() {\n    super(\'OfflineApp\');\n    this.version(1).stores({\n      pendingActions: \'++id, type, timestamp\',\n      cachedData: \'key, value, timestamp\'\n    });\n  }\n}\n\nconst db = new OfflineDB();\n\n// Save action for later sync\nasync function saveAction(action) {\n  await db.pendingActions.add({\n    ...action,\n    timestamp: Date.now(),\n    synced: false\n  });\n}\n\n// Sync when online\nasync function syncPendingActions() {\n  const pending = await db.pendingActions\n    .where(\'synced\').equals(0)\n    .toArray();\n  \n  for (const action of pending) {\n    await fetch(\'/api/sync\', {\n      method: \'POST\',\n      body: JSON.stringify(action)\n    });\n    await db.pendingActions.update(action.id, { synced: 1 });\n  }\n}\n```\n\n**Key Takeaways:**\n1. Cache the app shell for instant loading\n2. Use IndexedDB for offline data persistence\n3. Background sync queues actions until connectivity returns' }
    ]
  },
  {
    id: 710, slug: 'perf-budgets-ci', title: 'Performance Budgets & CI',
    description: 'Enforce performance budgets in CI/CD — automated performance testing, regression detection, and deployment gates.',
    level: 'advanced', duration: '30 min',
    objectives: ['Set up automated performance testing in CI/CD pipelines', 'Configure performance budgets as deployment gates', 'Detect and prevent performance regressions', 'Track performance metrics across deployments'],
    quiz: [
      { id: 1, question: 'What is the primary purpose of a performance budget in CI/CD?', options: ['To speed up builds', 'To prevent code changes that degrade performance', 'To reduce test coverage', 'To compress images'], correctIndex: 1, explanation: 'Performance budgets in CI/CD act as gates that prevent deploying code that exceeds defined performance thresholds.' },
      { id: 2, question: 'Which tool is most commonly used for Lighthouse testing in CI?', options: ['Jest', 'Playwright', 'Lighthouse CI', 'Karma'], correctIndex: 2, explanation: 'Lighthouse CI (lhci) is the official tool for running Lighthouse in CI environments with assertion support.' },
      { id: 3, question: 'What should happen when a performance budget is exceeded in CI?', options: ['The build should continue', 'The build should fail, blocking deployment', 'Only send a warning email', 'Skip the test'], correctIndex: 1, explanation: 'Performance budgets should fail the build to prevent performance regressions from reaching production.' }
    ],
    topics: [
      { id: 'lighthouse-ci', title: 'Lighthouse CI Setup', content: '**Lighthouse CI Configuration:**\n```yaml\n# .github/workflows/performance.yml\nname: Performance Tests\non: [pull_request]\n\njobs:\n  lighthouse:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm ci\n      - run: npm run build\n      \n      - name: Run Lighthouse\n        uses: treosh/lighthouse-ci-action@v10\n        with:\n          configPath: .lighthouserc.json\n          uploadArtifacts: true\n          temporaryPublicStorage: true\n```\n\n**Assertion Configuration:**\n```json\n// .lighthouserc.json\n{\n  "ci": {\n    "collect": {\n      "url": ["http://localhost:4200"],\n      "numberOfRuns": 3\n    },\n    "assert": {\n      "assertions": {\n        "categories:performance": ["error", { "minScore": 0.9 }],\n        "categories:accessibility": ["warn", { "minScore": 0.9 }],\n        "first-contentful-paint": ["error", { "maxNumericValue": 2000 }],\n        "largest-contentful-paint": ["error", { "maxNumericValue": 2500 }],\n        "cumulative-layout-shift": ["error", { "maxNumericValue": 0.1 }],\n        "total-byte-weight": ["error", { "maxNumericValue": 400000 }]\n      }\n    },\n    "upload": {\n      "target": " lhci",\n      "serverBaseUrl": "https://your-lhci-server.com"\n    }\n  }\n}\n```\n\n**Key Takeaways:**\n1. Run Lighthouse CI on every pull request\n2. Use numberOfRuns: 3 for statistical significance\n3. Set minimum scores for each metric category' },
      { id: 'performance-gates', title: 'Performance Gates', content: '**Multi-Stage Performance Gates:**\n```yaml\n# Stage 1: Bundle size gate\n- name: Check bundle size\n  run: |\n    npx bundlesize --config .bundlesize.json\n\n# Stage 2: Lighthouse score gate\n- name: Lighthouse assertions\n  run: npx lhci autorun --config=.lighthouserc.json\n\n# Stage 3: Custom performance gate\n- name: Custom performance check\n  run: |\n    node scripts/check-performance.js\n```\n\n**Bundle Size Gate:**\n```json\n// .bundlesize.json\n[\n  {\n    "path": "dist/main.js",\n    "maxSize": "200 kB",\n    "compression": "gzip"\n  },\n  {\n    "path": "dist/vendor.js",\n    "maxSize": "100 kB",\n    "compression": "gzip"\n  }\n]\n```\n\n**Custom Performance Gate:**\n```javascript\n// scripts/check-performance.js\nconst fs = require(\'fs\');\nconst budget = JSON.parse(fs.readFileSync(\'budget.json\'));\nconst stats = JSON.parse(fs.readFileSync(\'dist/stats.json\'));\n\nconst failures = [];\n\nbudget.forEach(rule => {\n  const actual = stats[rule.metric];\n  if (actual > rule.max) {\n    failures.push(`${rule.metric}: ${actual} exceeds ${rule.max}`);\n  }\n});\n\nif (failures.length > 0) {\n  console.error(\'Performance budget exceeded:\');\n  failures.forEach(f => console.error(`  - ${f}`));\n  process.exit(1);\n}\n```\n\n**Key Takeaways:**\n1. Use multiple gates: bundle size, Lighthouse, custom metrics\n2. Fail the build when any gate is exceeded\n3. Report performance results as PR comments for visibility' },
      { id: 'regression-detection', title: 'Performance Regression Detection', content: '**Baseline Comparison:**\n```bash\n# Compare current build with baseline\nnpx lhci compare --baselineUrl=https://staging.example.com \\\n  --compareUrl=http://localhost:4200\n```\n\n**Automated Regression Alerts:**\n```yaml\n# Compare with previous deployment\n- name: Detect regression\n  run: |\n    PREV_SCORE=$(cat previous-lighthouse.json | jq \'.categories.performance.score\')\n    CURR_SCORE=$(cat current-lighthouse.json | jq \'.categories.performance.score\')\n    \n    REGRESSION=$(echo "$CURR_SCORE < $PREV_SCORE - 0.05" | bc -l)\n    if [ "$REGRESSION" = "1" ]; then\n      echo "Performance regression detected: $PREV_SCORE -> $CURR_SCORE"\n      exit 1\n    fi\n```\n\n**Performance Tracking Over Time:**\n```typescript\n// Store metrics in database\ninterface PerformanceRecord {\n  commit: string;\n  timestamp: number;\n  metrics: {\n    lcp: number;\n    cls: number;\n    inp: number;\n    fcp: number;\n    ttfb: number;\n  };\n  bundleSize: number;\n  lighthouseScore: number;\n}\n```\n\n**Key Takeaways:**\n1. Store baseline performance metrics for comparison\n2. Detect regressions automatically in CI/CD\n3. Track performance trends over time to identify patterns' },
      { id: 'performance-reporting', title: 'Performance Reporting & Alerts', content: '**PR Comment Reporting:**\n```yaml\n# Add Lighthouse scores as PR comment\n- name: Lighthouse CI Comment\n  uses: treosh/lighthouse-ci-action@v10\n  with:\n    configPath: .lighthouserc.json\n  # Automatically posts scores as PR comment\n```\n\n**Slack/Discord Alerts:**\n```yaml\n- name: Alert on regression\n  if: failure()\n  uses: slackapi/slack-github-action@v1\n  with:\n    payload: |\n      {\n        "text": "Performance regression detected in PR #${{ github.event.pull_request.number }}",\n        "blocks": [\n          {\n            "type": "section",\n            "text": {\n              "type": "mrkdwn",\n              "text": "*Performance Regression*\\nLighthouse score dropped below threshold.\\nPR: #${{ github.event.pull_request.number }}"\n            }\n          }\n        ]\n      }\n```\n\n**Performance Dashboard:**\n```\n1. Real-time Dashboard\n   - Current production performance metrics\n   - Trend graphs (7-day, 30-day)\n   - Alerts and incidents\n\n2. Deployment Dashboard\n   - Performance before/after each deploy\n   - Correlation with deployment events\n   - Regression history\n\n3. Team Dashboard\n   - Performance by team/feature\n   - Budget utilization\n   - Improvement tracking\n```\n\n**Key Takeaways:**\n1. Post performance scores as PR comments for visibility\n2. Alert the team on performance regressions\n3. Maintain dashboards for ongoing performance tracking' }
    ]
  }
];
