import { Lesson } from '../models/lesson.model';

export const SECURITY_LESSONS: Lesson[] = [
  {
    id: 1101, slug: 'sec-xss', title: 'Cross-Site Scripting (XSS)',
    description: 'Understand and prevent Cross-Site Scripting attacks that target frontend applications.',
    level: 'beginner', duration: '30 min',
    objectives: ['Identify types of XSS attacks', 'Understand how XSS exploits work', 'Implement prevention strategies'],
    quiz: [
      { id: 1, question: 'What is Cross-Site Scripting (XSS)?', options: ['A server-side attack', 'An attack that injects malicious scripts into web pages viewed by other users', 'A network protocol vulnerability', 'A database injection attack'], correctIndex: 1, explanation: 'XSS attacks inject malicious scripts into content that other users view, allowing attackers to steal cookies, session tokens, or perform actions on behalf of users.' },
      { id: 2, question: 'Which type of XSS stores the malicious script on the target server?', options: ['Reflected XSS', 'Stored XSS', 'DOM-based XSS', 'None of the above'], correctIndex: 1, explanation: 'Stored XSS persists the malicious payload on the target server (e.g., in a database), affecting every user who views the compromised content.' },
      { id: 3, question: 'What is the primary defense against XSS in Angular?', options: ['CSP headers only', 'Built-in template sanitization', 'Using jQuery', 'Server-side rendering only'], correctIndex: 1, explanation: 'Angular automatically sanitizes all untrusted values in templates, stripping dangerous HTML and scripts before rendering.' }
    ],
    topics: [
      { id: 'what-is-xss', title: 'What is XSS', content: '**Cross-Site Scripting (XSS)** is a vulnerability that allows attackers to inject malicious client-side scripts into web applications. When other users visit the affected page, the malicious script executes in their browser context.\n\n**How XSS Works:**\n1. Attacker identifies an input field or URL parameter that is reflected in the page\n2. Attacker crafts a malicious script payload\n3. The script is stored or reflected in the application\n4. A victim user loads the page, and the script executes\n5. The script can steal cookies, session tokens, or perform actions as the user\n\n**Impact of XSS:**\n- Session hijacking through cookie theft\n- Credential stealing via fake login forms\n- Keylogging to capture user input\n- Defacing website content\n- Redirecting users to malicious sites\n- Cryptocurrency mining in the browser\n\n**Real-World Example:**\nA comment field that does not sanitize input allows an attacker to post: script tags that redirect cookies to an evil domain. When other users view the comments, their cookies are sent to the attacker.\n\n**Key Takeaways:**\n1. XSS exploits trust between the browser and the application\n2. Scripts execute in the victim\'s browser context\n3. Prevention requires both input validation and output encoding' },
      { id: 'types-of-xss', title: 'Types of XSS', content: '**Three Main Types of XSS:**\n\n**1. Stored XSS (Persistent):**\nThe malicious script is permanently stored on the target server.\n- Stored in database, comments, forum posts\n- Affects all users who view the stored content\n- Most dangerous type of XSS\n- Example: A blog comment that stores an img tag with onerror=alert(1) and src=x\n\n**2. Reflected XSS (Non-Persistent):**\nThe script is reflected off a web server in error messages or search results.\n- Included in URL parameters\n- Requires user interaction (clicking a link)\n- Script is not stored on the server\n- Example: A search query parameter containing script tags like script alert(1) script\n\n**3. DOM-based XSS:**\nThe vulnerability exists in client-side code rather than server-side code.\n- The DOM environment is modified by the attack\n- Server response may be safe, but client-side processing is vulnerable\n- JavaScript reads attacker-controlled data and writes it to the DOM unsafely\n- Example: document.getElementById(\'output\').innerHTML = location.hash.slice(1)\n\n**XSS Attack Vectors:**\n- Event handlers: img onerror, body onload\n- JavaScript URIs: a href with javascript:alert(1)\n- SVG payloads: svg onload=alert(1)\n- CSS expressions: background: expression(alert(1))\n- Encoding tricks: percent-encoded tags, HTML entities, Unicode\n\n**Key Takeaways:**\n1. Stored XSS is the most dangerous as it affects all viewers\n2. Reflected XSS requires social engineering to trick users\n3. DOM-based XSS bypasses server-side protections entirely' },
      { id: 'prevention', title: 'Prevention Strategies', content: '**Angular Built-in XSS Protection:**\n\nAngular automatically sanitizes untrusted values in templates. It strips dangerous HTML and scripts.\n\nExample component using Angular sanitization: import Component from @angular/core and DomSanitizer from @angular/platform-browser. In the template, bind innerHTML to userContent (safe because Angular auto-sanitizes), bind href to userUrl (safe URL), and bind style.background to userStyle (safe style value). The component class sets userContent to bold HTML text, userUrl to a safe URL, and userStyle to a safe color value.\n\n**Content Security Policy (CSP):**\n\nAdd a CSP meta tag to index.html with default-src set to self, script-src set to self, and style-src set to self with unsafe-inline.\n\n**Input Validation:**\n\nUse a whitelist approach for sanitization. Create a sanitizeInput function that replaces angle brackets with HTML entities, quotes with HTML entities, and forward slashes with HTML entities. For rich content, use DOMPurify by importing it from dompurify and calling DOMPurify.sanitize(dirty) to strip dangerous content.\n\n**Key Takeaways:**\n1. Always sanitize user input before rendering\n2. Use Angular\'s built-in sanitization over manual escaping\n3. Implement CSP headers as an additional defense layer\n4. Use DOMPurify when you need to allow safe HTML' }
    ]
  },
  {
    id: 1102, slug: 'sec-csrf', title: 'Cross-Site Request Forgery (CSRF)',
    description: 'Understand how CSRF attacks work and implement effective prevention mechanisms.',
    level: 'beginner', duration: '30 min',
    objectives: ['Understand CSRF attack vectors', 'Recognize how CSRF tokens work', 'Implement CSRF protection in Angular'],
    quiz: [
      { id: 1, question: 'What does CSRF stand for?', options: ['Cross-Site Request Forgery', 'Cross-Server Request Forgery', 'Client-Side Request Forgery', 'Cross-Site Resource Forgery'], correctIndex: 0, explanation: 'CSRF stands for Cross-Site Request Forgery, an attack that forces authenticated users to submit unwanted requests to web applications.' },
      { id: 2, question: 'What is the primary defense against CSRF?', options: ['CAPTCHA on every form', 'Anti-CSRF tokens', 'Disabling all forms', 'Using GET requests only'], correctIndex: 1, explanation: 'Anti-CSRF tokens are unique, unpredictable values included in state-changing requests that the server validates before processing.' },
      { id: 3, question: 'Which HTTP methods are vulnerable to CSRF?', options: ['Only GET', 'Only POST', 'Any state-changing method (POST, PUT, DELETE, PATCH)', 'No methods are vulnerable'], correctIndex: 2, explanation: 'Any HTTP method that changes state (POST, PUT, DELETE, PATCH) can be exploited by CSRF attacks. GET should never change state.' }
    ],
    topics: [
      { id: 'what-is-csrf', title: 'What is CSRF', content: '**Cross-Site Request Forgery (CSRF)** is an attack that forces an authenticated user to perform unwanted actions on a web application where they are currently authenticated.\n\n**How CSRF Differs from XSS:**\n- XSS: Attacker injects their own script into a trusted site\n- CSRF: Attacker tricks the victim\'s browser into making requests to a trusted site\n\n**CSRF Attack Scenario:**\n1. User logs into bank.com and receives a session cookie\n2. User visits a malicious website containing an img tag with src pointing to the bank\'s transfer endpoint with attacker\'s account and amount as parameters\n3. The browser automatically includes the bank.com session cookie\n4. Bank processes the transfer thinking it came from the user\n\n**Why CSRF Works:**\n- Browsers automatically include cookies with every request to a domain\n- Session cookies authenticate the user without additional verification\n- The malicious site cannot read the response, but the request still executes\n\n**Common CSRF Targets:**\n- Password change forms\n- Email address changes\n- Fund transfers\n- Account settings modifications\n- Data deletion operations\n\n**Key Takeaways:**\n1. CSRF exploits the trust a site has in the user\'s browser\n2. Cookies are automatically sent with requests to the same domain\n3. Any state-changing operation is potentially vulnerable to CSRF' },
      { id: 'how-csrf-works', title: 'How CSRF Works', content: '**CSRF Attack Flow:**\n\n1. User logs into target-site.com - server sets session cookie (session_id=abc123)\n2. User visits evil-site.com - evil-site.com contains malicious form or link\n3. Browser sends request to target-site.com - includes session_id cookie automatically - server sees valid session, processes request\n4. User\'s account is compromised without their knowledge or consent\n\n**Attack Vectors:**\n\n**1. Image Tag Injection:**\nAn img tag with src pointing to a bank endpoint and style display:none to hide the image.\n\n**2. Form Auto-Submit:**\nA hidden form with action pointing to the bank transfer endpoint, method POST, hidden inputs for to=attacker and amount=10000, and a script that calls document.getElementById(\'csrf-form\').submit() to auto-submit.\n\n**3. XMLHttpRequest/Fetch:**\nUsing fetch with the bank transfer URL, method POST, credentials include to send cookies, and a JSON body with to=attacker and amount=10000.\n\n**Why Same-Origin Policy Does Not Prevent CSRF:**\n- SOP prevents reading responses from other origins\n- SOP does NOT prevent sending requests to other origins\n- Browsers allow forms and images to make cross-origin requests\n\n**Key Takeaways:**\n1. CSRF attacks leverage automatic cookie inclusion\n2. Multiple vectors exist: forms, images, scripts\n3. The Same-Origin Policy does not prevent CSRF attacks' },
      { id: 'prevention', title: 'CSRF Prevention', content: '**Anti-CSRF Tokens:**\n\nA unique, unpredictable token embedded in forms and validated by the server.\n\nExample Angular HttpClient CSRF interceptor: Import HttpInterceptorFn from @angular/common/http. Export a csrfInterceptor function that checks if the request method is POST, PUT, DELETE, or PATCH. If so, read the CSRF token from a cookie or meta tag, clone the request with an X-CSRF-Token header set to the token, and pass the cloned request to the next handler. Otherwise, pass the original request.\n\n**SameSite Cookie Attribute:**\n\nServer-side cookie configuration using Set-Cookie header with SameSite=Strict, Secure, and HttpOnly flags.\n\n- SameSite=Strict: Cookie never sent with cross-origin requests\n- SameSite=Lax: Cookie sent with top-level navigation GET requests only\n- SameSite=None: Cookie sent with all cross-origin requests (requires Secure)\n\n**Angular\'s Built-in CSRF Support:**\n\nAngular reads the XSRF-TOKEN cookie automatically and sends it as X-XSRF-TOKEN header. Use provideHttpClient with withXsrfConfiguration to set cookieName to XSRF-TOKEN and headerName to X-XSRF-TOKEN.\n\n**Additional Defenses:**\n- Check Origin and Referer headers\n- Use custom headers for API calls (CORS blocks unauthorized headers)\n- Require re-authentication for sensitive operations\n- Implement rate limiting\n\n**Key Takeaways:**\n1. Use SameSite cookies as the first line of defense\n2. Implement CSRF tokens for state-changing requests\n3. Angular has built-in XSRF protection via interceptors\n4. Combine multiple defense strategies for robust protection' }
    ]
  },
  {
    id: 1103, slug: 'sec-csp', title: 'Content Security Policy (CSP)',
    description: 'Master Content Security Policy to restrict the sources of executable scripts and resources.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Understand CSP directives', 'Configure CSP for Angular apps', 'Implement CSP reporting'],
    quiz: [
      { id: 1, question: 'What does Content Security Policy do?', options: ['Encrypts all page content', 'Restricts which resources can be loaded and executed', 'Blocks all third-party content', 'Only affects JavaScript execution'], correctIndex: 1, explanation: 'CSP is a browser security mechanism that restricts the sources from which resources like scripts, styles, and images can be loaded.' },
      { id: 2, question: 'What CSP directive controls where scripts can be loaded from?', options: ['style-src', 'script-src', 'img-src', 'connect-src'], correctIndex: 1, explanation: 'The script-src directive specifies valid sources for JavaScript files, inline scripts, and eval() usage.' },
      { id: 3, question: 'What is the safest value for script-src to prevent XSS?', options: ["'unsafe-inline'", "'unsafe-eval'", "'self'", "'none'"], correctIndex: 2, explanation: "'self' allows scripts only from the same origin, preventing inline script injection and external script loading." }
    ],
    topics: [
      { id: 'what-is-csp', title: 'What is CSP', content: '**Content Security Policy (CSP)** is a security mechanism that restricts the sources from which a browser can load resources. It provides a layer of defense against XSS, data injection, and clickjacking.\n\n**How CSP Works:**\n1. Server sends a Content-Security-Policy header or meta tag\n2. Browser parses the policy and enforces restrictions\n3. Any resource violating the policy is blocked\n4. Violations can be reported to a reporting endpoint\n\n**CSP Headers:**\nThe Content-Security-Policy header can be set to values like default-src \'self\' and script-src \'self\'.\n\n**Meta Tag Alternative:**\nA meta tag with http-equiv Content-Security-Policy and content attribute containing the policy directives.\n\n**What CSP Protects Against:**\n- Cross-Site Scripting (XSS)\n- Clickjacking\n- Data injection attacks\n- Code injection attacks\n- Unauthorized resource loading\n\n**CSP Enforcement Levels:**\n- Content-Security-Policy: Enforce the policy\n- Content-Security-Policy-Report-Only: Report violations without blocking\n\n**Key Takeaways:**\n1. CSP restricts resource loading to approved sources\n2. It is one of the most effective defenses against XSS\n3. Start with report-only mode before enforcing' },
      { id: 'directives', title: 'CSP Directives', content: '**Common CSP Directives:**\n\n**Resource Loading Directives:**\n- default-src: Fallback for all resource types\n- script-src: Controls JavaScript sources\n- style-src: Controls CSS sources\n- img-src: Controls image sources\n- font-src: Controls font sources\n- connect-src: Controls XHR/fetch/WebSocket connections\n- media-src: Controls video/audio sources\n- object-src: Controls plugin sources (Flash, Java)\n- frame-src: Controls iframe sources\n\n**Common Values:**\n- \'self\': Allow resources from same origin\n- \'none\': Block all resources\n- \'unsafe-inline\': Allow inline scripts/styles (dangerous)\n- \'unsafe-eval\': Allow eval() and new Function() (dangerous)\n- \'nonce-{random}\': Allow scripts with specific nonce attribute\n- \'sha256-{hash}\': Allow specific script content by hash\n\n**Example CSP Configuration:**\ndefault-src \'self\'; script-src \'self\' \'nonce-abc123\'; style-src \'self\' \'unsafe-inline\'; img-src \'self\' data: https:; font-src \'self\' https://fonts.gstatic.com; connect-src \'self\' https://api.example.com; frame-ancestors \'none\'; form-action \'self\'; base-uri \'self\'; object-src \'none\';\n\n**Key Takeaways:**\n1. Use default-src as a fallback for all resource types\n2. Avoid unsafe-inline and unsafe-eval whenever possible\n3. Use nonces or hashes for inline scripts instead of unsafe-inline' },
      { id: 'implementation', title: 'Implementation in Angular', content: '**CSP Meta Tag in Angular:**\n\nAdd a CSP meta tag to index.html with default-src set to self, script-src set to self, style-src set to self with unsafe-inline, and img-src set to self with data and https.\n\n**CSP HTTP Header with Angular Universal:**\n\nIn the Express server setup (server.ts), use server.use middleware to set the Content-Security-Policy header with the desired directives.\n\n**CSP with Angular Build:**\n\nConfigure CSP headers in angular.json under the build options headers object with the Content-Security-Policy key.\n\n**CSP Violation Reporting:**\n\nSet up a CSP report endpoint in Express that parses application/csp-report JSON body and logs violation details including violatedDirective, blockedUri, documentUri, sourceFile, and lineNumber.\n\n**CSP Reporting Directive:**\nAdd report-uri /csp-report and report-to csp-endpoint to your CSP policy to receive violation reports.\n\n**Key Takeaways:**\n1. Start with Content-Security-Policy-Report-Only to identify issues\n2. Use nonces for inline scripts instead of unsafe-inline\n3. Set up violation reporting to monitor CSP effectiveness\n4. Test CSP thoroughly before enforcing in production' }
    ]
  },
  {
    id: 1104, slug: 'sec-auth', title: 'Authentication Patterns',
    description: 'Master authentication patterns and token management for secure Angular applications.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Understand JWT and OAuth flows', 'Implement secure session management', 'Handle token refresh strategies'],
    quiz: [
      { id: 1, question: 'What is the main advantage of JWT over session cookies?', options: ['JWT is more secure', 'JWT is stateless and scalable', 'JWT is smaller in size', 'JWT is easier to implement'], correctIndex: 1, explanation: 'JWTs are self-contained tokens that carry all necessary information, eliminating the need for server-side session storage and enabling horizontal scaling.' },
      { id: 2, question: 'Where should JWT access tokens be stored for maximum security?', options: ['localStorage', 'sessionStorage', 'Memory (JavaScript variable)', 'All are equally secure'], correctIndex: 2, explanation: 'Storing tokens in memory (not persistent storage) prevents XSS attacks from stealing tokens. The token is lost on page refresh but can be refreshed silently.' },
      { id: 3, question: 'What is the purpose of a refresh token?', options: ['Replace expired access tokens without requiring re-login', 'Encrypt sensitive data', 'Prevent CSRF attacks', 'Store user preferences'], correctIndex: 0, explanation: 'Refresh tokens allow the application to obtain new access tokens without forcing the user to re-authenticate, improving user experience while maintaining security.' }
    ],
    topics: [
      { id: 'jwt-tokens', title: 'JWT Tokens', content: '**JSON Web Tokens (JWT)** are a compact, URL-safe means of representing claims to be transferred between two parties.\n\n**JWT Structure:**\nJWT has three parts separated by dots: Header.Payload.Signature. Header contains algorithm and type (e.g. HS256, JWT). Payload contains claims like sub (subject), name, and exp (expiration). Signature is HMACSHA256 of the base64UrlEncoded header and payload with a secret.\n\n**Angular JWT Implementation:**\n\nCreate an AuthService with a private accessToken property. The login method posts credentials to /api/auth/login, stores the access token in memory, and stores the refresh token via httpOnly cookie. The getAccessToken method returns the stored token.\n\n**JWT Interceptor:**\n\nCreate an authInterceptor function that reads the access token from AuthService. If a token exists, clone the request with an Authorization header set to Bearer {token} and pass it to the next handler.\n\n**Key Takeaways:**\n1. Store access tokens in memory, not persistent storage\n2. Store refresh tokens in httpOnly cookies\n3. Use interceptors to attach tokens to requests\n4. Implement token refresh before expiration' },
      { id: 'oauth-oidc', title: 'OAuth & OpenID Connect', content: '**OAuth 2.0 Authorization Flows:**\n\n**Authorization Code Flow (Recommended for SPAs):**\n1. User clicks Login\n2. Redirect to Authorization Server\n3. User authenticates\n4. Auth Server redirects back with authorization code\n5. App exchanges code for tokens\n6. Tokens stored securely\n\n**Angular OAuth Implementation:**\n\nCreate an AuthService that initializes an OIDCClient with issuer URL, clientId, redirectUri, scope (openid profile email), and responseType set to code. The login method calls initLoginFlow. The handleCallback method processes the callback and stores tokens. The logout method calls logOut on the client.\n\n**Token Refresh Flow:**\n\nCreate a refreshTokens method that calls refreshTokens on the OIDC client. On success, store the new tokens. On failure, redirect to login.\n\n**PKCE for Public Clients:**\n\nPKCE prevents authorization code interception. Generate a random codeVerifier, hash it with SHA-256 to get a codeChallenge, then include code_challenge and code_challenge_method S256 in the authorization URL.\n\n**Key Takeaways:**\n1. Use Authorization Code Flow with PKCE for SPAs\n2. Never store tokens in localStorage\n3. Implement proper token refresh mechanisms\n4. Use short-lived access tokens with longer-lived refresh tokens' },
      { id: 'session-management', title: 'Session Management', content: '**Session Management Strategies:**\n\n**1. Token-Based Sessions:**\nCreate a SessionService with a sessionTimeout (30 minutes), lastActivity timestamp, and inactivityTimer. Start the session by setting lastActivity and setting up an inactivity timer that checks every 60 seconds. Track user activity by listening for click, keypress, and mousemove events and updating lastActivity. On timeout, clear the timer and log out.\n\n**2. Silent Token Refresh:**\nCreate a TokenRefreshService that schedules token refresh 60 seconds before expiration using setTimeout. On successful refresh, reschedule for the new expiresIn value. On failure, log out.\n\n**3. Multi-Tab Session Synchronization:**\nUse BroadcastChannel for cross-tab communication. Create a channel named auth-channel. Listen for messages and handle LOGOUT events by calling authService.logout. Broadcast logout to all tabs when the user logs out.\n\n**Key Takeaways:**\n1. Implement session timeout with inactivity detection\n2. Use silent token refresh to maintain sessions\n3. Synchronize session state across browser tabs\n4. Always provide a way for users to manually logout' }
    ]
  },
  {
    id: 1105, slug: 'sec-input-validation', title: 'Input Validation & Sanitization',
    description: 'Master client-side and server-side input validation and data sanitization techniques.',
    level: 'beginner', duration: '30 min',
    objectives: ['Implement effective client validation', 'Understand server-side validation requirements', 'Apply proper sanitization techniques'],
    quiz: [
      { id: 1, question: 'Why should input validation never rely solely on client-side validation?', options: ['Client validation is too slow', 'Client-side code can be bypassed by attackers', 'Browsers do not support validation', 'Server-side validation is faster'], correctIndex: 1, explanation: 'Client-side validation can be easily bypassed by modifying HTML, disabling JavaScript, or sending requests directly to the server. Server-side validation is essential.' },
      { id: 2, question: 'What is input sanitization?', options: ['Removing all input', 'Converting potentially dangerous input into safe format', 'Encrypting input data', 'Validating input length'], correctIndex: 1, explanation: 'Input sanitization transforms potentially dangerous input (like HTML tags or scripts) into a safe format that cannot execute as code.' },
      { id: 3, question: 'Which is the best approach for email validation?', options: ['Check if input contains @', 'Use a proper regex pattern or built-in browser validation', 'Only validate server-side', 'Accept any string'], correctIndex: 1, explanation: 'A proper regex pattern or HTML5 built-in email validation provides reliable client-side checking, while server-side validation provides the authoritative check.' }
    ],
    topics: [
      { id: 'client-validation', title: 'Client Validation', content: '**Angular Reactive Forms Validation:**\n\nCreate a ValidationComponent with a FormGroup containing email and password FormControls. Use Validators.required and Validators.email for email. Use Validators.required, Validators.minLength(8), and a pattern regex for password requiring uppercase, lowercase, and digit. In the template, show error messages when fields are invalid and touched. Disable the submit button when the form is invalid.\n\n**Custom Validators:**\n\nCreate a noWhitespaceValidator that returns a ValidatorFn checking if the trimmed value is empty. Create a passwordStrengthValidator that checks for uppercase, lowercase, numeric, and special characters, returning a passwordStrength error if any are missing.\n\n**Key Takeaways:**\n1. Use Angular reactive forms for structured validation\n2. Create custom validators for complex rules\n3. Always provide clear validation messages\n4. Client validation improves UX but is not a security measure' },
      { id: 'server-validation', title: 'Server Validation', content: '**Why Server-Side Validation is Essential:**\n\n1. Client-side validation can be bypassed\n2. API requests can be sent directly without a browser\n3. Server is the authoritative source for data integrity\n4. Prevents injection attacks and data corruption\n\n**Server Validation Best Practices:**\n\nUse express-validator middleware with body validators for email (isEmail, normalizeEmail), password (isLength, matches regex), name (trim, isLength, escape), and age (isInt). Check validationResult and return 400 with errors if validation fails.\n\n**Type Validation:**\n\nCreate a validateUser function that checks typeof for name (string), email (string), and age (number), throwing errors for mismatches. Return a cleaned User object with trimmed name, lowercased email, and floored age.\n\n**Key Takeaways:**\n1. Always validate on the server regardless of client validation\n2. Use schema validation libraries for complex validation\n3. Validate data types, not just formats\n4. Return meaningful error messages for debugging' },
      { id: 'sanitization', title: 'Sanitization Techniques', content: '**HTML Sanitization with DOMPurify:**\n\nImport DOMPurify from dompurify. Sanitize dirty HTML containing script tags to strip dangerous content while keeping safe HTML like paragraph and bold tags. Configure ALLOWED_TAGS and ALLOWED_ATTR for custom sanitization.\n\n**String Sanitization:**\n\nCreate a sanitizeString function that replaces & with &amp;, < with &lt;, > with &gt;, double quotes with &quot;, single quotes with &#x27;, and forward slashes with &#x2F;. Create a sanitizeEmail function that trims, lowercases, and strips non-alphanumeric characters except @ and dot.\n\n**Angular Sanitization:**\n\nImport DomSanitizer and SafeHtml from @angular/platform-browser. In a component, inject DomSanitizer and use bypassSecurityTrustHtml to mark safe HTML content. Bind innerHTML in the template to the trusted HTML and bind href to trusted URL.\n\n**Key Takeaways:**\n1. Use DOMPurify for rich HTML content sanitization\n2. Angular provides built-in sanitization for templates\n3. Always sanitize before rendering user-generated content\n4. Use whitelist-based sanitization for maximum security' }
    ]
  },
  {
    id: 1106, slug: 'sec-cors', title: 'CORS Deep Dive',
    description: 'Master Cross-Origin Resource Sharing configuration and security implications.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Understand how CORS works', 'Configure CORS properly', 'Handle preflight requests correctly'],
    quiz: [
      { id: 1, question: 'What triggers a CORS preflight request?', options: ['Any cross-origin request', 'Requests with custom headers or non-simple methods', 'GET requests only', 'POST requests only'], correctIndex: 1, explanation: 'Preflight requests are triggered by non-simple requests that include custom headers, use methods other than GET/POST/HEAD, or have content types other than form-encoded/text/plain.' },
      { id: 2, question: 'What does the Access-Control-Allow-Origin header do?', options: ['Allows cookies to be sent', 'Specifies which origins can access the resource', 'Enables HTTPS', 'Sets the response content type'], correctIndex: 1, explanation: 'Access-Control-Allow-Origin tells the browser which origins are permitted to access the response. It can be a specific origin or wildcard (*).' },
      { id: 3, question: 'Can CORS prevent all cross-origin attacks?', options: ['Yes, CORS is a complete security solution', 'No, CORS only controls browser behavior and does not protect against server-side attacks', 'Yes, but only for GET requests', 'No, CORS is deprecated'], correctIndex: 1, explanation: 'CORS is enforced by browsers but does not protect against direct server attacks. CORS headers are ignored by non-browser HTTP clients.' }
    ],
    topics: [
      { id: 'how-cors-works', title: 'How CORS Works', content: '**Cross-Origin Resource Sharing (CORS)** is a mechanism that allows restricted resources on a web page to be requested from another domain.\n\n**Same-Origin Policy:**\nBrowsers restrict scripts from reading responses from a different origin (protocol + domain + port).\n\nSame Origin examples: https://example.com/page and https://example.com/other are same origin. Different origins include different subdomain (api.example.com), different protocol (http vs https), or different port (8080).\n\n**CORS Request Flow:**\n1. Browser sends request to different origin\n2. Server responds with CORS headers\n3. Browser checks headers and allows/blocks response\n4. For preflight requests, OPTIONS is sent first\n\n**Simple vs Non-Simple Requests:**\n\n**Simple Requests:**\n- Method: GET, POST, HEAD\n- No custom headers\n- Content-Type: text/plain, multipart/form-data, application/x-www-form-urlencoded\n\n**Non-Simple Requests (require preflight):**\n- Method: PUT, DELETE, PATCH\n- Custom headers (Authorization, Content-Type: application/json)\n- Credentials: include\n\n**Key Takeaways:**\n1. CORS is enforced by browsers, not servers\n2. Simple requests go directly; non-simple requests trigger preflight\n3. CORS headers control which origins can access resources' },
      { id: 'preflight', title: 'Preflight Requests', content: '**Preflight Request Flow:**\n\n1. Browser sends OPTIONS request with Origin, Access-Control-Request-Method, and Access-Control-Request-Headers headers\n2. Server responds with CORS headers: Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers, and Access-Control-Max-Age (cache preflight for 24 hours)\n3. Browser sends actual request with original method\n\n**Preflight Caching:**\n\nSet the Access-Control-Max-Age header on the server response to cache preflight results. For example, set it to 86400 for 24 hours.\n\n**Handling Preflight in Express:**\n\nUse the cors middleware with origin set to the allowed URL, methods array, allowedHeaders array, credentials true, and maxAge set to 86400.\n\n**Key Takeaways:**\n1. Preflight requests use the OPTIONS method\n2. Cache preflight responses with Access-Control-Max-Age\n3. Only non-simple requests trigger preflight\n4. Preflight adds latency to cross-origin requests' },
      { id: 'configuration', title: 'CORS Configuration', content: '**Angular CORS Configuration:**\n\nConfigure a proxy in angular.json under the serve options with /api target pointing to the backend URL, secure true, changeOrigin true, and pathRewrite to strip the /api prefix.\n\n**Express CORS Middleware:**\n\nUse the cors middleware to allow a specific origin. For multiple origins, provide a function that checks the request origin against a whitelist array. Set credentials true to allow cookies.\n\n**CORS for API Gateways:**\n\nConfigure Nginx to add CORS headers: Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers, Access-Control-Allow-Credentials, and Access-Control-Max-Age. Return 204 for OPTIONS requests.\n\n**CORS Security Best Practices:**\n\nNever use origin: true in production as it reflects any origin. Use a whitelist approach by checking the origin against an array of allowed URLs. Only allow necessary HTTP methods and headers.\n\n**Key Takeaways:**\n1. Never use origin: true in production\n2. Use a whitelist for allowed origins\n3. Only allow necessary HTTP methods and headers\n4. Configure CORS at the API gateway level when possible' }
    ]
  },
  {
    id: 1107, slug: 'sec-owasp', title: 'OWASP Top 10 for Frontend',
    description: 'Understand OWASP Top 10 vulnerabilities and their impact on frontend applications.',
    level: 'advanced', duration: '45 min',
    objectives: ['Identify OWASP Top 10 vulnerabilities', 'Understand frontend-specific attack vectors', 'Implement mitigation strategies'],
    quiz: [
      { id: 1, question: 'Which OWASP vulnerability involves injecting malicious code through user input?', options: ['Broken Authentication', 'Injection (including XSS)', 'Security Misconfiguration', 'Insecure Deserialization'], correctIndex: 1, explanation: 'Injection attacks, including XSS, occur when untrusted data is sent to an interpreter as part of a command or query.' },
      { id: 2, question: 'What is the 2021 OWASP Top 10 category for client-side vulnerabilities like XSS?', options: ['A01: Broken Access Control', 'A03: Injection', 'A05: Security Misconfiguration', 'A07: Identification and Authentication Failures'], correctIndex: 1, explanation: 'A03: Injection (2021) includes XSS, SQL injection, NoSQL injection, and other injection attacks where hostile data is sent to an interpreter.' },
      { id: 3, question: 'Which OWASP risk is specifically relevant to SPAs using JWT tokens?', options: ['A02: Cryptographic Failures', 'A01: Broken Access Control', 'A04: Insecure Design', 'All of the above'], correctIndex: 3, explanation: 'SPAs with JWT tokens can be affected by multiple OWASP risks: token storage issues (A02), broken access control (A01), and insecure design patterns (A04).' }
    ],
    topics: [
      { id: 'owasp-overview', title: 'OWASP Overview', content: '**OWASP Top 10 (2021) Summary:**\n\n1. A01: Broken Access Control - Restrictions on what authenticated users are allowed to do are not properly enforced.\n2. A02: Cryptographic Failures - Failures related to cryptography which often leads to exposure of sensitive data.\n3. A03: Injection - User-supplied data is not validated, filtered, or sanitized by the application.\n4. A04: Insecure Design - Risks related to design flaws, missing security controls.\n5. A05: Security Misconfiguration - Missing appropriate security hardening or improperly configured permissions.\n6. A06: Vulnerable and Outdated Components - Using components with known vulnerabilities.\n7. A07: Identification and Authentication Failures - Confirmation of the user\'s identity, authentication, and session management.\n8. A08: Software and Data Integrity Failures - Code and infrastructure that does not protect against integrity violations.\n9. A09: Security Logging and Monitoring Failures - Insufficient logging, detection, monitoring, and active response.\n10. A10: Server-Side Request Forgery (SSRF) - SSRF flaws occur when a web application fetches a remote resource without validating the user-supplied URL.\n\n**Relevance to Frontend Engineers:**\n- XSS falls under A03: Injection\n- Broken authentication relates to A07\n- Component security relates to A06\n- Access control enforcement relates to A01\n\n**Key Takeaways:**\n1. OWASP Top 10 is the standard for web application security awareness\n2. Frontend engineers must understand client-side implications of each risk\n3. Security is a shared responsibility between frontend and backend' },
      { id: 'frontend-specific-risks', title: 'Frontend-Specific Risks', content: '**XSS (A03: Injection):**\n- Stored XSS in user-generated content\n- DOM-based XSS in client-side JavaScript\n- Reflected XSS in URL parameters\n- Impact: Session hijacking, credential theft, defacement\n\n**Broken Access Control (A01):**\n- Client-side authorization checks only (can be bypassed)\n- Exposed API endpoints without proper checks\n- Missing role-based UI controls\n- Horizontal privilege escalation via API manipulation\n\n**Security Misconfiguration (A05):**\n- Missing CSP headers\n- Exposed source maps in production\n- Debug mode enabled in production\n- Default credentials or configurations\n\n**Vulnerable Components (A06):**\n- Outdated npm packages with known CVEs\n- Dependencies with known vulnerabilities\n- Unmaintained third-party libraries\n- Supply chain attacks through compromised packages\n\n**Insecure Design (A04):**\n- Tokens stored in localStorage (XSS vulnerability)\n- Client-side validation without server validation\n- Exposing sensitive data in JavaScript bundles\n- Missing rate limiting on authentication endpoints\n\n**Identification Failures (A07):**\n- Weak password requirements\n- Missing multi-factor authentication\n- Insecure session management\n- Predictable session tokens\n\n**Key Takeaways:**\n1. XSS remains the most common frontend vulnerability\n2. Never rely solely on client-side access control\n3. Keep dependencies updated and audit regularly\n4. Store sensitive tokens in memory or httpOnly cookies' },
      { id: 'mitigation', title: 'Mitigation Strategies', content: '**Mitigating XSS:**\n\nUse Angular sanitization by binding innerHTML to trusted content. Implement CSP via a meta tag with script-src \'self\'. Use DOMPurify for rich content by importing from dompurify and calling sanitize on dirty HTML.\n\n**Mitigating Broken Access Control:**\n\nAlways validate permissions on the server. Client-side route guards are for UX only, not security. Create an AuthGuard that checks authService.isAuthenticated() for UX purposes, but the server must validate permissions independently.\n\n**Mitigating Security Misconfiguration:**\n\nRemove source maps in production by setting sourceMap to false in angular.json production build. Implement CSP headers and set secure HTTP headers.\n\n**Mitigating Vulnerable Components:**\n\nRun npm audit regularly and npm audit fix to patch vulnerabilities. Use Snyk for continuous monitoring with npx snyk test.\n\n**Mitigating Insecure Token Storage:**\n\nStore tokens in memory (private accessToken string | null = null), not localStorage. Use httpOnly cookies for refresh tokens set by server with HttpOnly; Secure; SameSite=Strict.\n\n**Security Headers Configuration:**\n\nUse helmet middleware in Express for automatic security headers, or manually set X-Content-Type-Options nosniff, X-Frame-Options DENY, X-XSS-Protection 1; mode=block, and Referrer-Policy strict-origin-when-cross-origin.\n\n**Key Takeaways:**\n1. Defense in depth: multiple layers of security controls\n2. Never trust client-side security checks alone\n3. Keep dependencies updated and audit regularly\n4. Implement proper security headers and CSP' }
    ]
  },
  {
    id: 1108, slug: 'sec-https', title: 'HTTPS & TLS',
    description: 'Understand how HTTPS and TLS protect data in transit and implement them properly.',
    level: 'beginner', duration: '25 min',
    objectives: ['Understand TLS handshake process', 'Configure proper certificates', 'Avoid mixed content issues'],
    quiz: [
      { id: 1, question: 'What does TLS stand for?', options: ['Transport Layer Security', 'True Layer Security', 'Type Layer Security', 'Transaction Layer Security'], correctIndex: 0, explanation: 'TLS (Transport Layer Security) is the cryptographic protocol that provides secure communication over a computer network.' },
      { id: 2, question: 'What is mixed content?', options: ['Using both HTTP and HTTPS on different pages', 'Loading HTTP resources on an HTTPS page', 'Using different TLS versions', 'Having multiple certificates'], correctIndex: 1, explanation: 'Mixed content occurs when an HTTPS page loads subresources (scripts, images, styles) over HTTP, creating a security vulnerability.' },
      { id: 3, question: 'What happens during the TLS handshake?', options: ['Data is compressed', 'Client and server agree on encryption methods and exchange keys', 'Cookies are set', 'DNS resolution occurs'], correctIndex: 1, explanation: 'During the TLS handshake, the client and server negotiate cipher suites, verify certificates, and exchange keys to establish a secure connection.' }
    ],
    topics: [
      { id: 'how-tls-works', title: 'How TLS Works', content: '**TLS Handshake Process:**\n\n1. Client Hello - Client sends supported TLS versions and cipher suites, plus a random number for key generation\n2. Server Hello - Server selects TLS version and cipher suite, sends its certificate and random number\n3. Certificate Verification - Client verifies server certificate against trusted CAs, checks expiration and domain name\n4. Key Exchange - Client generates pre-master secret encrypted with server public key, both derive session keys\n5. Finished - Both verify handshake integrity, encrypted communication begins\n\n**TLS Versions:**\n- TLS 1.0/1.1: Deprecated (insecure)\n- TLS 1.2: Current standard\n- TLS 1.3: Latest (faster, more secure)\n\n**Cipher Suite Components:**\n- Key Exchange: ECDHE (Elliptic Curve Diffie-Hellman Ephemeral)\n- Authentication: RSA or ECDSA\n- Encryption: AES-256-GCM or ChaCha20\n- Hash: SHA-256 or SHA-384\n\n**Key Takeaways:**\n1. TLS encrypts all data in transit between client and server\n2. The handshake establishes trust and negotiates encryption\n3. Always use TLS 1.2 or higher' },
      { id: 'certificates', title: 'Certificates', content: '**SSL/TLS Certificates:**\n\n**Certificate Types:**\n- Domain Validation (DV): Basic, validates domain ownership\n- Organization Validation (OV): Validates organization identity\n- Extended Validation (EV): Highest validation level\n\n**Certificate Contents:**\n- Subject: Domain name and organization\n- Issuer: Certificate Authority (CA)\n- Validity: Start and end dates\n- Public Key: For encryption\n- Signature: CA digital signature\n\n**Free Certificates with Let\'s Encrypt:**\n\nInstall certbot with sudo apt install certbot. Obtain a certificate with sudo certbot certonly --webroot -w /var/www/html -d example.com. Set up auto-renewal with a cron job: 0 12 * * * /usr/bin/certbot renew --quiet.\n\n**Certificate Pinning (Advanced):**\n\nCertificate pinning can be implemented via an Angular HTTP interceptor, but it is complex and can cause issues. Use HPKP header instead or rely on CA trust.\n\n**Key Takeaways:**\n1. Use certificates from trusted Certificate Authorities\n2. Let\'s Encrypt provides free, automated certificates\n3. Implement auto-renewal to prevent expiration\n4. Monitor certificate expiration dates' },
      { id: 'mixed-content', title: 'Mixed Content', content: '**Types of Mixed Content:**\n\n**Passive Mixed Content:**\n- Images, video, audio loaded over HTTP on HTTPS page\n- Browser blocks or warns but page partially works\n- Low security risk but still a vulnerability\n\n**Active Mixed Content:**\n- Scripts, stylesheets, iframes, XMLHttpRequest over HTTP\n- Browser blocks entirely\n- High security risk - allows MITM attacks\n\n**Detecting Mixed Content:**\n\nUse Browser DevTools: the Console tab shows mixed content warnings, and the Network tab shows HTTP requests on an HTTPS page.\n\n**Fixing Mixed Content:**\n\nChange HTTP URLs to HTTPS in img and script tags. Use protocol-relative URLs like //example.com/image.png. Use Content Security Policy with upgrade-insecure-requests to auto-upgrade HTTP to HTTPS.\n\n**Angular Configuration:**\n\nConfigure angular.json serve options with ssl true, sslCert pointing to the cert.pem file, and sslKey pointing to the key.pem file for HTTPS in development.\n\n**Key Takeaways:**\n1. Never load HTTP resources on HTTPS pages\n2. Use CSP upgrade-insecure-requests to auto-upgrade\n3. Check DevTools console for mixed content warnings\n4. Ensure all third-party resources support HTTPS' }
    ]
  },
  {
    id: 1109, slug: 'sec-secrets', title: 'Secrets Management',
    description: 'Learn how to manage secrets, API keys, and sensitive data securely in frontend applications.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Understand environment variable usage', 'Secure API keys properly', 'Manage build-time secrets safely'],
    quiz: [
      { id: 1, question: 'Why should API keys not be embedded in frontend code?', options: ['They make the bundle larger', 'Frontend code is visible to users and can be extracted', 'They slow down the application', 'They only work on certain browsers'], correctIndex: 1, explanation: 'Frontend code is downloaded to the browser and can be inspected. Any secrets embedded in it are exposed to anyone who views the source code.' },
      { id: 2, question: 'What is the recommended way to handle API keys in a frontend app?', options: ['Store them in localStorage', 'Use environment variables at build time and proxy API calls through your backend', 'Hardcode them in the JavaScript bundle', 'Store them in sessionStorage'], correctIndex: 1, explanation: 'Use environment variables for non-sensitive configuration and proxy sensitive API calls through your backend server where secrets remain secure.' },
      { id: 3, question: 'What should you do if you accidentally commit a secret to Git?', options: ['Delete the file', 'Immediately rotate the secret and remove it from Git history', 'Just add it to .gitignore', 'Nothing, it is not a problem'], correctIndex: 1, explanation: 'Once a secret is committed, it must be considered compromised. Rotate the secret immediately and use git filter-branch or BFG to remove it from history.' }
    ],
    topics: [
      { id: 'env-variables', title: 'Environment Variables', content: '**Angular Environment Variables:**\n\nCreate environment.ts files for different environments. The development environment.ts exports production false, apiUrl with dev API URL, and featureFlag true. The production environment.prod.ts exports production true, apiUrl with production URL, and featureFlag false.\n\n**Using Environment Variables:**\n\nImport the environment object and create a ConfigService that exposes apiUrl as a getter returning environment.apiUrl.\n\n**Important Security Notes:**\n- Environment variables are embedded at build time\n- They are visible in the production JavaScript bundle\n- NEVER store secrets in environment variables for frontend apps\n- Only use for non-sensitive configuration\n\n**What NOT to Store:**\n- API keys or tokens\n- Database credentials\n- Private keys\n- Passwords\n\n**What IS Safe:**\n- API endpoint URLs\n- Feature flags\n- Public configuration values\n- Analytics IDs (non-sensitive)\n\n**Key Takeaways:**\n1. Environment variables are embedded at build time and visible in bundles\n2. Never store secrets in frontend environment variables\n3. Use environment variables only for non-sensitive configuration' },
      { id: 'api-keys', title: 'API Key Security', content: '**Securing API Keys:**\n\n**Backend Proxy Pattern:**\n\nThe frontend calls your own backend endpoint (e.g. /api/weather) without needing any API key. The backend proxy server-side has access to process.env.WEATHER_API_KEY and makes the external API call with the key, keeping it safe.\n\n**Firebase/Supabase Public Keys:**\n\nSome services provide public API keys designed to be exposed. These are safe to use in frontend code. For example, Firebase config includes a public apiKey, authDomain, and projectId. Firebase security rules protect your data, not the API key.\n\n**Key Takeaways:**\n1. Proxy sensitive API calls through your backend\n2. Some services (Firebase, Supabase) use public API keys safely\n3. Implement security rules on the backend for public API keys' },
      { id: 'build-time-secrets', title: 'Build-Time Secrets', content: '**Handling Secrets During Build:**\n\n**CI/CD Environment Variables:**\n\nIn GitHub Actions, set NODE_AUTH_TOKEN from secrets.NPM_TOKEN and API_URL from secrets.API_URL as environment variables in the build steps.\n\n**Docker Build Secrets:**\n\nUse Docker build secrets (not build args for secrets). Use RUN --mount=type=secret to mount secrets during the build process.\n\n**Never Commit Secrets:**\n\nAdd .env, .env.local, .env.*.local, *.pem, and *.key to .gitignore to prevent committing secrets.\n\n**Secret Scanning Tools:**\n\nUse GitLeaks (gitleaks detect --source .) and TruffleHog (trufflehog git file://. --only-verified) to scan for accidentally committed secrets. Run npm audit for dependency vulnerabilities.\n\n**Secret Rotation:**\n\nImplement automatic secret rotation by using short-lived tokens, rotating keys regularly, monitoring for unauthorized usage, and having a rotation plan before secrets expire.\n\n**Key Takeaways:**\n1. Use CI/CD secret management for build-time secrets\n2. Never commit secrets to version control\n3. Implement automated secret rotation\n4. Use secret scanning tools in your pipeline' }
    ]
  },
  {
    id: 1110, slug: 'sec-deps', title: 'Dependency Security',
    description: 'Master dependency vulnerability scanning, supply chain security, and auditing practices.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Scan for vulnerabilities in dependencies', 'Understand supply chain risks', 'Implement dependency auditing'],
    quiz: [
      { id: 1, question: 'What is a supply chain attack in the context of npm packages?', options: ['A DDoS attack on npm servers', 'Compromising a legitimate package to inject malicious code', 'Downloading packages too slowly', 'Running out of disk space'], correctIndex: 1, explanation: 'Supply chain attacks compromise legitimate packages (or their maintainers) to inject malicious code that affects all users of that package.' },
      { id: 2, question: 'What does `npm audit` do?', options: ['Installs packages faster', 'Scans dependencies for known security vulnerabilities', 'Updates all packages to latest', 'Removes unused packages'], correctIndex: 1, explanation: 'npm audit checks your dependencies against a database of known vulnerabilities and provides recommendations for fixes.' },
      { id: 3, question: 'Why should you pin dependency versions?', options: ['To prevent supply chain attacks', 'To ensure consistent builds across environments', 'To reduce bundle size', 'All of the above'], correctIndex: 3, explanation: 'Pinning versions prevents unexpected updates, ensures reproducible builds, reduces attack surface, and helps identify changes in dependencies.' }
    ],
    topics: [
      { id: 'vulnerability-scanning', title: 'Vulnerability Scanning', content: '**npm Audit:**\n\nRun npm audit to scan for vulnerabilities. Use npm audit fix to fix automatically where possible. Use npm audit fix --force to fix including breaking changes. Run npm audit --json to generate a detailed report.\n\n**Snyk Integration:**\n\nInstall Snyk globally with npm install -g snyk. Test for vulnerabilities with snyk test. Monitor the project with snyk monitor. Integrate into GitHub Actions using the snyk/actions/node@master action with SNYK_TOKEN.\n\n**GitHub Dependabot:**\n\nConfigure .github/dependabot.yml with version 2, package-ecosystem npm, directory /, weekly schedule, and open-pull-requests-limit of 10.\n\n**Angular Security Best Practices:**\n\nRun ng update --dry-run to check Angular-specific vulnerabilities. Update Angular packages with ng update @angular/core @angular/cli.\n\n**Key Takeaways:**\n1. Run npm audit regularly in your CI pipeline\n2. Use Snyk or Dependabot for automated monitoring\n3. Update dependencies promptly when vulnerabilities are found\n4. Review vulnerability details before applying fixes' },
      { id: 'supply-chain', title: 'Supply Chain Security', content: '**Common Supply Chain Attacks:**\n\n**1. Typosquatting:**\nAttacker publishes a package with a similar name to a popular package (e.g. lodahs instead of lodash). Users install the malicious package by mistake.\n\n**2. Dependency Confusion:**\nAttacker publishes a public package with the same name as a private internal package. Package manager may install the public version instead.\n\n**3. Account Compromise:**\nMaintainer account is compromised and malicious code published to the legitimate package.\n\n**4. Maintainer Malice:**\nPackage maintainer intentionally adds malicious code.\n\n**Prevention Strategies:**\n\nUse npm ci for lock file integrity (uses package-lock.json exactly). Run npm cache verify to verify package integrity. Check package sources with npm config get registry.\n\n**Package Verification:**\n\nCheck package checksums in package-lock.json which contains integrity hashes (shasum-512 hash of the package tarball).\n\n**Key Takeaways:**\n1. Always use lock files (package-lock.json, yarn.lock)\n2. Use npm ci for clean, reproducible installs\n3. Verify package integrity before installation\n4. Monitor for typosquatting and dependency confusion' },
      { id: 'auditing', title: 'Auditing Practices', content: '**Regular Audit Schedule:**\n\nRun weekly automated audits with npm audit --json. Do monthly manual review: review all dependencies, check for unused packages, evaluate package maintenance status, and review security advisories.\n\n**Dependency Review Checklist:**\n\nVerify: package has active maintenance, no known vulnerabilities (npm audit), license is compatible with project, bundle size is acceptable, download count indicates community trust, source code is reviewable, and no suspicious post-install scripts.\n\n**Removing Unused Dependencies:**\n\nFind unused dependencies with npx depcheck. Remove unused packages with npm uninstall. Check for duplicate dependencies with npx yarn-deduplicate for Yarn.\n\n**Automated Security Pipeline:**\n\nSet up a GitHub Actions security workflow that runs on push and pull_request. Steps: checkout, npm ci, npm audit --audit-level=high, npx snyk test, and snyk/actions/node@master on pull requests.\n\n**Key Takeaways:**\n1. Establish a regular audit schedule\n2. Remove unused dependencies promptly\n3. Integrate security scanning into CI/CD\n4. Review package maintenance status regularly' }
    ]
  },
  {
    id: 1111, slug: 'sec-storage', title: 'Secure Client Storage',
    description: 'Understand the security implications of localStorage, cookies, and IndexedDB for storing sensitive data.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Understand localStorage security risks', 'Implement secure cookie practices', 'Use IndexedDB safely'],
    quiz: [
      { id: 1, question: 'Why is localStorage not recommended for storing sensitive data?', options: ['It has limited storage capacity', 'It is accessible via JavaScript and vulnerable to XSS', 'It does not work offline', 'It is slower than cookies'], correctIndex: 1, explanation: 'localStorage is accessible to any JavaScript running on the page, making it vulnerable to XSS attacks that can steal stored data.' },
      { id: 2, question: 'What makes httpOnly cookies more secure than localStorage?', options: ['They are encrypted automatically', 'They cannot be accessed by JavaScript', 'They have larger storage capacity', 'They expire faster'], correctIndex: 1, explanation: 'httpOnly cookies are not accessible to JavaScript, preventing XSS attacks from stealing the cookie value.' },
      { id: 3, question: 'What is the primary risk of storing JWT tokens in sessionStorage?', options: ['Tokens are lost on page refresh', 'Tokens are accessible to XSS attacks', 'Tokens cannot be shared across tabs', 'Tokens expire too quickly'], correctIndex: 1, explanation: 'sessionStorage, like localStorage, is accessible to JavaScript on the page and can be stolen via XSS attacks.' }
    ],
    topics: [
      { id: 'localStorage-risks', title: 'localStorage Risks', content: '**localStorage Security Issues:**\n\n**XSS Vulnerability:**\nIf an attacker can run JavaScript, they can steal all localStorage data by calling localStorage.getItem and sending it to a malicious endpoint via fetch.\n\n**No Expiration:**\n- Data persists indefinitely\n- No automatic cleanup\n- Grows unbounded\n\n**Synchronous API:**\n- Blocks main thread during operations\n- Performance impact with large datasets\n\n**What localStorage Should Store:**\n- UI preferences (theme, language)\n- Non-sensitive application state\n- Cached data that can be re-fetched\n\n**What NOT to Store:**\n- Authentication tokens\n- Personal identifiable information (PII)\n- Financial data\n- Any sensitive user data\n\n**Mitigation:**\nOnly store non-sensitive data like theme and language. Never store tokens or user data.\n\n**Key Takeaways:**\n1. localStorage is accessible to all JavaScript on the page\n2. Never store authentication tokens in localStorage\n3. Use localStorage only for non-sensitive UI preferences' },
      { id: 'cookies-security', title: 'Cookies Security', content: '**Secure Cookie Attributes:**\n\nSet cookies server-side with the following attributes:\n- HttpOnly: Not accessible to JavaScript (XSS protection)\n- Secure: Only sent over HTTPS\n- SameSite=Strict: Not sent with cross-origin requests\n- Path=/: Scope to path\n- Max-Age=3600: Expires in 1 hour\n\n**Cookie Security Properties:**\n\n- HttpOnly: Prevents JavaScript access (XSS protection)\n- Secure: Only sent over HTTPS\n- SameSite: Controls cross-origin cookie behavior\n  - Strict: Never sent cross-origin\n  - Lax: Sent with top-level navigation only\n  - None: Sent with all requests (requires Secure)\n\n**Angular Cookie Usage:**\n\nImport CookieService from ngx-cookie-service. Inject it in a component and use cookieService.get(\'theme\') to read non-httpOnly cookies.\n\n**Key Takeaways:**\n1. Always use HttpOnly for authentication cookies\n2. Use SameSite=Strict or Lax to prevent CSRF\n3. Set Secure flag to ensure HTTPS-only transmission\n4. Set appropriate expiration with Max-Age or Expires' },
      { id: 'indexeddb', title: 'IndexedDB Security', content: '**IndexedDB Overview:**\n- Large-scale client-side storage\n- Asynchronous API (non-blocking)\n- Structured data storage\n- Indexed queries\n\n**Security Considerations:**\n\nIndexedDB is accessible to JavaScript with the same XSS risks as localStorage. Opening a database, creating transactions, and reading object stores all expose data to any JavaScript running on the page.\n\n**IndexedDB vs localStorage:**\n\nlocalStorage: 5-10MB limit, synchronous, key-value strings, simple API.\nIndexedDB: Large storage (hundreds of MB), asynchronous, structured objects, indexed queries, transactions.\n\n**Secure IndexedDB Usage:**\n\nStore only non-sensitive cached data. Create a cacheApiResponse function that opens a database, creates a readwrite transaction, and stores URL, data, and timestamp. Create a fetchWithCache function that checks the cache before making a network request, using cached data if it is less than 1 hour old.\n\n**Key Takeaways:**\n1. IndexedDB has the same XSS vulnerabilities as localStorage\n2. Use IndexedDB for large non-sensitive cached data\n3. Never store sensitive data in IndexedDB\n4. Implement proper error handling for storage operations' }
    ]
  },
  {
    id: 1112, slug: 'sec-clickjacking', title: 'Clickjacking & UI Redress',
    description: 'Understand and prevent clickjacking attacks that trick users into clicking unintended elements.',
    level: 'advanced', duration: '30 min',
    objectives: ['Identify clickjacking attack vectors', 'Implement frame-busting techniques', 'Configure X-Frame-Options properly'],
    quiz: [
      { id: 1, question: 'What is clickjacking?', options: ['A type of SQL injection', 'A technique that tricks users into clicking hidden elements on a page', 'A form of cross-site scripting', 'A man-in-the-middle attack'], correctIndex: 1, explanation: 'Clickjacking (UI redress attack) tricks users into clicking on a hidden or disguised element by overlaying it with visible content.' },
      { id: 2, question: 'Which HTTP header prevents your site from being embedded in iframes?', options: ['X-Content-Type-Options', 'X-Frame-Options', 'X-XSS-Protection', 'Content-Security-Policy'], correctIndex: 1, explanation: 'X-Frame-Options tells the browser whether your page can be embedded in frames, iframes, or objects.' },
      { id: 3, question: 'What CSP directive provides more granular control over framing than X-Frame-Options?', options: ['script-src', 'style-src', 'frame-ancestors', 'form-action'], correctIndex: 2, explanation: 'frame-ancestors in CSP replaces X-Frame-Options with more granular control, allowing specific origins to frame your content.' }
    ],
    topics: [
      { id: 'what-is-clickjacking', title: 'What is Clickjacking', content: '**Clickjacking (UI Redress Attack)** is a technique where an attacker overlays transparent or deceptive content on top of a legitimate page to trick users into clicking hidden elements.\n\n**How Clickjacking Works:**\n\n1. Attacker creates malicious page - contains invisible iframe of target site, overlays visible buttons or links\n2. Victim visits attacker\'s page - sees attractive button (e.g., "Click to win!"), actually clicking hidden iframe element\n3. Victim performs unintended action - clicks "Delete Account" button, approves payment, changes account settings\n\n**Real-World Clickjacking Examples:**\n\n**1. Facebook Likejacking:**\nA div with position relative containing an iframe with opacity 0.01 pointing to the Facebook like button, and a visible button saying "Click to see amazing video!" with z-index 1.\n\n**2. Banking Fraud:**\nA div with position relative containing an iframe with opacity 0 pointing to the bank transfer page (full width and height), and a visible button saying "Claim Free Gift" with z-index 1.\n\n**Key Takeaways:**\n1. Clickjacking tricks users into clicking hidden elements\n2. Transparent iframes are the primary attack vector\n3. Any action requiring a click can be hijacked' },
      { id: 'frame-busting', title: 'Frame-Busting Techniques', content: '**JavaScript Frame-Busting:**\n\nBasic frame-busting: check if self !== top, then set top.location = self.location. More robust version: check if window.top !== window.self, then call window.top.location.replace(window.self.location). With timeout: setTimeout to handle edge cases, check if top !== self, then top.location.replace(document.location).\n\n**CSS Frame-Busting:**\n\nSet html to display: none by default. Use @supports not (display: none) to show html only when not in a frame.\n\n**Limitations of Frame-Busting:**\n- Can be bypassed with sandbox attribute\n- May break legitimate embedding\n- JavaScript can be disabled\n- Not recommended as primary defense\n\n**Key Takeaways:**\n1. Frame-busting is a defense-in-depth measure\n2. JavaScript frame-busting can be bypassed\n3. Use X-Frame-Options or CSP as primary defense' },
      { id: 'x-frame-options', title: 'X-Frame-Options', content: '**X-Frame-Options Header:**\n\nDENY: Deny all framing. SAMEORIGIN: Allow framing from same origin only. ALLOW-FROM https://example.com: Allow framing from specific origin (deprecated, use CSP).\n\n**CSP frame-ancestors (Recommended):**\n\nframe-ancestors \'none\': Deny all framing. frame-ancestors \'self\': Allow same origin only. frame-ancestors \'self\' https://trusted.com: Allow specific origins.\n\n**Angular Implementation:**\n\nIn Express server (server.ts), use middleware to set X-Frame-Options header to DENY, or use CSP frame-ancestors with \'none\'.\n\n**Allowing Specific Framing:**\n\nSet X-Frame-Options to SAMEORIGIN for same-domain framing. Use CSP frame-ancestors with \'self\' and additional allowed origins for more flexibility.\n\n**Testing Frame Protection:**\n\nCreate an iframe pointing to your site to test if framing protection is enabled. It should be blocked if protection is configured correctly.\n\n**Key Takeaways:**\n1. Use CSP frame-ancestors over X-Frame-Options (more flexible)\n2. Set DENY for pages that should never be framed\n3. Use SAMEORIGIN if you need to frame your own content\n4. Test framing protection regularly' }
    ]
  }
];
