import { Lesson } from '../models/lesson.model';

export const SOFT_SKILLS_LESSONS: Lesson[] = [
  {
    id: 1026, slug: 'soft-why-skills', title: 'Why Soft Skills Matter',
    description: 'Understand the difference between technical and soft skills, their career impact, and why communication is the most important skill for engineers.',
    level: 'beginner', duration: '20 min',
    objectives: [
      'Differentiate between technical and soft skills',
      'Recognize the career impact of strong soft skills',
      'Understand why communication is critical for engineers',
      'Identify your own soft skill strengths and gaps'
    ],
    quiz: [
      { id: 1, question: 'Which is an example of a soft skill?', options: ['Writing TypeScript', 'Active listening', 'Using Git', 'Configuring Webpack'], correctIndex: 1, explanation: 'Soft skills are interpersonal abilities like communication, teamwork, and problem-solving - distinct from technical abilities like coding or tooling.' },
      { id: 2, question: 'Why do soft skills matter for engineers?', options: ['They replace the need for technical skills', 'They help you collaborate, communicate ideas, and advance in your career', 'They are only needed for management roles', 'They are optional'], correctIndex: 1, explanation: 'Soft skills enable you to work effectively with others, present your ideas clearly, and grow into leadership roles.' },
      { id: 3, question: 'What is the most commonly cited skill gap for engineering hires?', options: ['Algorithm knowledge', 'Framework expertise', 'Communication and teamwork', 'Database skills'], correctIndex: 2, explanation: 'Studies consistently show that communication and teamwork are the top soft skill gaps that companies struggle to find in engineering candidates.' }
    ],
    topics: [
      { id: 'technical-vs-soft-skills', title: 'Technical vs Soft Skills', content: 'Engineering success requires both technical and soft skills. They complement each other.\n\n**Technical Skills:**\n\n- Programming languages (TypeScript, Python, Java)\n- Frameworks and libraries (Angular, React, Spring)\n- Tools (Git, Docker, CI/CD)\n- Architecture and system design\n- Database design and querying\n- Testing methodologies\n\n**Soft Skills:**\n\n- Communication (written and verbal)\n- Collaboration and teamwork\n- Problem-solving and critical thinking\n- Time management\n- Empathy and emotional intelligence\n- Conflict resolution\n- Adaptability\n- Leadership\n\n**Why Both Matter:**\n\nThe best code in the world is useless if you cannot explain your approach to the team, gather requirements from stakeholders, or collaborate effectively with designers.\n\nConversely, great communication without technical skills means you cannot execute on your ideas.\n\n**Career Progression:**\n\nJunior Engineer: Mostly technical skills, learning basics\nMid-Level Engineer: Technical skills + collaboration, mentoring\nSenior Engineer: Deep technical + leadership, cross-team work\nStaff+ Engineer: Strategic thinking, influence, org-wide impact\n\nAt each level, the ratio shifts toward more soft skills.\n\n**Key Takeaway:** Technical skills get you hired. Soft skills determine how far you advance. The best engineers invest in both equally.' },
      { id: 'career-impact', title: 'Career Impact of Soft Skills', content: 'Soft skills directly influence your career trajectory, compensation, and job satisfaction.\n\n**Promotion Criteria at Most Companies:**\n\nJunior to Mid: Can you write reliable code independently?\nMid to Senior: Can you lead features and mentor others?\nSenior to Staff: Can you influence technical direction across teams?\nStaff to Principal: Can you shape the engineering org strategy?\n\nNotice how each level requires more soft skills than the last.\n\n**Real-World Scenarios:**\n\nScenario 1: Two engineers with identical technical skills. One explains trade-offs clearly in code reviews and design docs. The other writes great code but cannot articulate their approach. Who gets promoted first?\n\nScenario 2: A senior engineer who cannot give constructive feedback causes team friction. A mid-level engineer with strong feedback skills becomes the team lead.\n\n**Impact on Job Satisfaction:**\n\nEngineers with strong soft skills:\n- Resolve conflicts faster\n- Build stronger team relationships\n- Feel more confident presenting ideas\n- Experience less workplace frustration\n- Are more likely to be sought for interesting projects\n\n**Salary Correlation:**\n\nStudies show that engineers with strong communication skills earn 10-20% more than equally skilled peers, primarily because they can advocate for themselves and lead initiatives.\n\n**Key Takeaway:** Investing in soft skills is not about being nice - it is about unlocking career growth that technical skills alone cannot provide.' },
      { id: 'communication-fundamentals', title: 'Communication Fundamentals', content: 'Communication is the most important soft skill for engineers. Here are the fundamentals.\n\n**Written Communication:**\n\n- Be concise: One idea per sentence\n- Structure: Lead with the important point\n- Clarity: Avoid jargon when possible\n- Proofread: Read before sending\n\n**Verbal Communication:**\n\n- Listen actively: Do not interrupt, ask clarifying questions\n- Be clear: State your point first, then supporting details\n- Adjust for audience: Technical details with engineers, outcomes with stakeholders\n- Pause: Think before responding to tough questions\n\n**Active Listening Techniques:**\n\n1. Paraphrase: So what you are saying is...\n2. Ask clarifying questions: Can you explain what you mean by...\n3. Summarize: Let me make sure I understand...\n4. Non-verbal: Nod, maintain eye contact, lean in\n\n**Common Communication Mistakes:**\n\n- Assuming everyone knows what you know\n- Using technical terms with non-technical audiences\n- Not checking for understanding\n- Responding emotionally instead of thoughtfully\n- Not following up after important conversations\n\n**Practice Exercise:**\n\nNext time you explain a technical concept, try explaining it to a non-technical friend first. If they understand, you have communicated clearly.\n\n**Key Takeaway:** Communication is a skill, not a talent. Like coding, it improves with deliberate practice and feedback.' },
      { id: 'self-assessment', title: 'Self-Assessment Exercise', content: 'Understanding your current soft skill level helps you focus improvement efforts.\n\n**Soft Skills Self-Assessment:**\n\nRate yourself 1-5 on each skill:\n\nCommunication:\n- I clearly explain technical concepts to non-technical people\n- I write concise, well-structured documentation\n- I listen actively in meetings\n\nCollaboration:\n- I give constructive feedback in code reviews\n- I handle disagreements professionally\n- I help teammates when they are stuck\n\nTime Management:\n- I prioritize tasks effectively\n- I meet deadlines consistently\n- I manage distractions and stay focused\n\nLeadership:\n- I take ownership of technical decisions\n- I mentor junior developers\n- I drive improvements in team processes\n\n**Interpreting Your Results:**\n\n1-2: Focus area - invest time here first\n3: Developing - room for growth\n4: Strong - maintain and help others\n5: Strength - teach and mentor others\n\n**Creating a Growth Plan:**\n\n1. Pick one skill to improve this quarter\n2. Find specific situations to practice\n3. Ask for feedback from peers\n4. Track your progress monthly\n5. Celebrate improvements\n\n**Key Takeaway:** Self-awareness is the first step to growth. Be honest about your strengths and weaknesses, then create a plan to improve deliberately.' }
    ]
  },
  {
    id: 1027, slug: 'soft-email-writing', title: 'Writing Effective Emails',
    description: 'Master professional email writing including structure, tone, follow-ups, and async communication best practices for engineering teams.',
    level: 'beginner', duration: '20 min',
    objectives: [
      'Structure emails for clarity and quick action',
      'Adapt tone for different audiences and contexts',
      'Write effective follow-ups without being pushy',
      'Communicate asynchronously with minimal back-and-forth'
    ],
    quiz: [
      { id: 1, question: 'What is the most important part of a professional email?', options: ['A long introduction', 'A clear subject line and concise body', 'Formal language throughout', 'Multiple paragraphs of context'], correctIndex: 1, explanation: 'A clear subject line and concise body help the reader quickly understand what you need and respond appropriately.' },
      { id: 2, question: 'When should you follow up on an unanswered email?', options: ['After 1 hour', 'After 2-3 business days with a polite reminder', 'After 1 week with a complaint', 'Never - they will respond when ready'], correctIndex: 1, explanation: 'A polite follow-up after 2-3 business days is professional and ensures important items do not slip through the cracks.' },
      { id: 3, question: 'What is the best way to start an email requesting action?', options: ['Hope you are doing well...', 'Start with the specific ask or deadline', 'List all background information first', 'Ask how their day is going'], correctIndex: 1, explanation: 'Leading with the ask saves the reader time and makes it clear what you need from them immediately.' }
    ],
    topics: [
      { id: 'email-structure', title: 'Email Structure', content: 'Professional emails follow a clear structure that respects the reader\'s time.\n\n**The BARS Framework:**\n\nB - Background (1-2 sentences of context)\nA - Ask (what you need from them)\nR - Response (what they should do)\nS - Supporting details (if needed)\n\n**Example:**\n\nSubject: API Rate Limit Decision Needed by Friday\n\nBackground: We are hitting rate limits on the payment API during peak traffic.\n\nAsk: I need a decision on our approach by Friday.\n\nOptions:\nA) Request higher limits ($500/month)\nB) Implement caching (2 days)\nC) Queue requests (1 day, adds latency)\n\nRecommendation: Option B - best balance of cost and effort.\n\nPlease reply with your preference by EOD Friday.\n\n**Subject Line Best Practices:**\n\n- Action Required: [Topic] by [Date]\n- Decision Needed: [Topic]\n- FYI: [Topic] Update\n- Question: [Topic]\n\nAvoid: Help, Quick question, Hi, No subject\n\n**Formatting Tips:**\n\n- Short paragraphs (2-3 sentences)\n- Bullet points for lists\n- Bold for key dates or actions\n- Keep under 200 words when possible\n\n**Key Takeaway:** Structure emails so the reader can scan, understand the ask, and respond quickly.' },
      { id: 'tone-and-audience', title: 'Tone and Audience', content: 'Adapting your email tone to the audience and context is critical for effective communication.\n\n**Tone Spectrum:**\n\nFormal: Dear Mr. Smith, I am writing to inquire about...\nProfessional: Hi Alex, Quick question about the API...\nCasual: Hey, about that API thing...\n\n**When to Use Each:**\n\nFormal:\n- First contact with external parties\n- Legal or compliance communications\n- Company-wide announcements\n\nProfessional:\n- Team communications\n- Stakeholder updates\n- Cross-team coordination\n\nCasual:\n- Close teammates you work with daily\n- Quick clarifications\n- Internal chat messages\n\n**Tone Adjustments for Context:**\n\nBad news: Empathetic, acknowledge impact, provide alternatives\nGood news: Enthusiastic, clear, call to action\nRequest: Direct, specific, deadline if needed\nUpdate: Concise, actionable, next steps\n\n**Common Tone Mistakes:**\n\n- Too casual with leadership: Hey boss, need stuff\n- Too formal with teammates: Dear colleague, I kindly request...\n- Passive-aggressive: Per my last email...\n- Unclear urgency: This needs attention (when does it actually need action?)\n\n**Key Takeaway:** Match your tone to the relationship and context. When in doubt, default to professional and clear.' },
      { id: 'follow-ups', title: 'Writing Follow-Ups', content: 'Follow-ups are necessary and professional. Here is how to do them well.\n\n**When to Follow Up:**\n\n- After 2-3 business days with no response on action items\n- Before a deadline passes\n- After a meeting with unresolved action items\n- When you need to escalate priority\n\n**The 3-Step Follow-Up:**\n\nStep 1 (Day 3): Gentle reminder\nSubject: Re: [Original Subject]\nHi [Name], Following up on my email below about [topic]. Do you have a chance to review? Let me know if you need more information.\n\nStep 2 (Day 5): Add context\nSubject: Re: [Original Subject] - Need by [Date]\nHi [Name], Checking in again on the [topic] decision. We need this by [date] to stay on schedule. Happy to discuss if easier.\n\nStep 3 (Day 7): Escalate politely\nSubject: Re: [Original Subject] - Escalating\nHi [Name], I have not heard back on the [topic]. I am looping in [manager/stakeholder] to help prioritize. Can we connect this week?\n\n**What NOT to Do:**\n\n- Follow up after 1 day (too aggressive)\n- Send multiple follow-ups in one day\n- Use guilt: I am waiting on you...\n- Escalate without first attempting direct communication\n\n**Key Takeaway:** Follow-ups are professional, not pushy. Space them out and add value or context each time.' },
      { id: 'async-communication', title: 'Async Communication Best Practices', content: 'Async communication reduces meetings and lets people work on their own schedule.\n\n**Principles of Async Communication:**\n\n1. Write it down first - documentation over meetings\n2. Be self-contained - include all necessary context\n3. Set expectations - response time, deadline, urgency\n4. Use threads - keep related discussions together\n5. Summarize decisions - capture outcomes in writing\n\n**Async Communication Tools and When to Use Them:**\n\nEmail: Formal decisions, external communication, detailed updates\nSlack/Teams: Quick questions, informal updates, team chat\nGitHub Issues/PRs: Technical discussions, code reviews\nDocumentation: Architecture decisions, how-to guides\n\n**Writing Async Messages:**\n\nSubject: [Topic] - [Urgency Level]\n\nContext: 1-2 sentences of background\nAsk: What specifically do you need?\nDeadline: When is this needed?\nDetails: Supporting information below\n\n**Example:**\n\nSubject: Database Migration Approach - Decision by Thursday\n\nContext: We need to migrate the user table to support the new auth system.\n\nAsk: Please review the two approaches below and vote by Thursday.\n\nApproach A: Zero-downtime migration (3 days)\nApproach B: Maintenance window (1 day)\n\nI recommend Approach A to avoid downtime. Thoughts?\n\n**Reducing Back-and-Forth:**\n\n- Include all context in the first message\n- Anticipate questions and answer them upfront\n- Propose solutions, not just problems\n- Set clear deadlines\n- Use decision documents for complex topics\n\n**Key Takeaway:** Good async communication reduces meetings, respects focus time, and creates written records of decisions.' }
    ]
  },
  {
    id: 1028, slug: 'soft-time-management', title: 'Time Management for Engineers',
    description: 'Learn practical time management techniques including prioritization frameworks, the Pomodoro Technique, avoiding burnout, and focus strategies.',
    level: 'beginner', duration: '20 min',
    objectives: [
      'Apply prioritization frameworks to daily work',
      'Use the Pomodoro Technique to maintain focus',
      'Recognize and prevent burnout',
      'Implement focus techniques to reduce distractions'
    ],
    quiz: [
      { id: 1, question: 'What is the Pomodoro Technique?', options: ['A cooking method', 'Working in focused 25-minute intervals with short breaks', 'A way to skip meetings', 'A code review method'], correctIndex: 1, explanation: 'The Pomodoro Technique involves working in focused 25-minute intervals (pomodoros) followed by 5-minute breaks to maintain concentration.' },
      { id: 2, question: 'What is the Eisenhower Matrix used for?', options: ['Writing code faster', 'Prioritizing tasks by urgency and importance', 'Tracking bugs', 'Managing Git branches'], correctIndex: 1, explanation: 'The Eisenhower Matrix helps you categorize tasks into four quadrants: urgent/important, important/not urgent, urgent/not important, and neither.' },
      { id: 3, question: 'What is a common sign of engineer burnout?', options: ['Being excited about new projects', 'Feeling exhausted, cynical, and less productive', 'Learning new technologies', 'Mentoring junior developers'], correctIndex: 1, explanation: 'Burnout manifests as emotional exhaustion, cynicism about work, and reduced professional efficacy. It is preventable with proper management.' }
    ],
    topics: [
      { id: 'prioritization-frameworks', title: 'Prioritization Frameworks', content: 'Effective prioritization ensures you work on what matters most.\n\n**Eisenhower Matrix:**\n\n| Urgent + Important | Not Urgent + Important |\n|---|---|\n| Do immediately | Schedule it |\n| Deadline-driven tasks | Strategic work, learning |\n\n| Urgent + Not Important | Not Urgent + Not Important |\n|---|---|\n| Delegate if possible | Eliminate |\n| Some meetings, emails | Time-wasters, distractions |\n\n**Impact vs Effort Matrix:**\n\nHigh Impact + Low Effort: Do first (quick wins)\nHigh Impact + High Effort: Plan and schedule\nLow Impact + Low Effort: Do if time permits\nLow Impact + High Effort: Avoid or delegate\n\n**ICE Scoring (for feature prioritization):**\n\nI - Impact (1-10): How much value will this deliver?\nC - Confidence (1-10): How sure are we about the impact?\nE - Effort (1-10): How much work is required?\n\nICE Score = (I x C x E) / Effort\n\n**Daily Prioritization Routine:**\n\n1. Start of day: Identify top 3 priorities\n2. Block time for deep work on priorities\n3. Handle reactive work in batches\n4. End of day: Review progress, plan tomorrow\n\n**Key Takeaway:** Use frameworks to make prioritization objective rather than relying on whoever shouts loudest.' },
      { id: 'pomodoro-technique', title: 'Pomodoro Technique', content: 'The Pomodoro Technique is a time management method that uses timed intervals to maintain focus.\n\n**How It Works:**\n\n1. Choose a task\n2. Set timer for 25 minutes\n3. Work with full focus (no phone, no Slack, no email)\n4. When timer rings, take a 5-minute break\n5. After 4 pomodoros, take a longer 15-30 minute break\n\n**Why It Works:**\n\n- Creates urgency: 25 minutes feels manageable\n- Forces breaks: Prevents burnout and mental fatigue\n- Builds focus: Trains your brain to concentrate\n- Provides measurement: Track how many pomodoros tasks take\n\n**Adapting for Engineering:**\n\nProblem:打断 is common in engineering work\n\nSolution:\n- Batch Slack/email checks between pomodoros\n- Use Focus mode or Do Not Disturb\n- Communicate your focus schedule to the team\n- For complex debugging, extend to 50-minute intervals\n\n**Tracking Pomodoros:**\n\nFeature A: 3 pomodoros (estimated 2, actual 3)\nBug Fix B: 1 pomodoro (estimated 3, actual 1)\nCode Review: 2 pomodoros (estimated 2, actual 2)\n\nOver time, this helps you estimate tasks more accurately.\n\n**Tools:**\n\n- Physical timer (most effective for focus)\n- Forest app (gamified focus)\n- Toggl (time tracking)\n- Simple phone timer\n\n**Key Takeaway:** Start with 4 pomodoros per day and gradually increase. Consistency matters more than quantity.' },
      { id: 'avoiding-burnout', title: 'Avoiding Burnout', content: 'Burnout is preventable with awareness and proactive habits.\n\n**Signs of Burnout:**\n\n1. Chronic exhaustion even after rest\n2. Cynicism about work and team\n3. Reduced productivity and concentration\n4. Feeling disconnected from achievements\n5. Physical symptoms (headaches, sleep issues)\n6. Dreading Monday morning\n\n**Common Causes in Engineering:**\n\n- Sustained crunch without recovery\n- Unclear priorities and constant context-switching\n- Lack of autonomy or recognition\n- Toxic team dynamics\n- Imposter syndrome\n- Perfectionism\n\n**Prevention Strategies:**\n\n1. **Set Boundaries**\n   - Define work hours and stick to them\n   - Turn off notifications after hours\n   - Say no to non-essential work\n\n2. **Manage Energy**\n   - Take real lunch breaks\n   - Walk between focus sessions\n   - Exercise regularly\n   - Sleep 7-8 hours\n\n3. **Build Recovery**\n   - Use vacation time\n   - Take mental health days\n   - Pursue hobbies outside work\n   - Disconnect completely on weekends\n\n4. **Seek Support**\n   - Talk to your manager about workload\n   - Connect with peers\n   - Consider professional coaching\n   - Use Employee Assistance Programs\n\n**Key Takeaway:** Burnout is not a badge of honor. Sustainable pace leads to better work and longer careers.' },
      { id: 'focus-techniques', title: 'Focus Techniques', content: 'Deep focus is essential for engineering work. Here are techniques to protect and enhance it.\n\n**Time Blocking:**\n\nBlock specific hours for specific types of work:\n\n9:00-11:00 - Deep coding (no meetings, no Slack)\n11:00-11:30 - Email and Slack responses\n11:30-12:00 - Code reviews\n12:00-13:00 - Lunch and break\n13:00-14:00 - Meetings\n14:00-16:00 - Deep coding\n16:00-16:30 - End-of-day wrap-up\n\n**The 2-Minute Rule:**\n\nIf a task takes less than 2 minutes, do it now. Do not add it to a list.\n\nThis prevents small tasks from accumulating into an overwhelming backlog.\n\n**Context Switching Costs:**\n\nResearch shows it takes 23 minutes to regain focus after an interruption.\n\nIf interrupted 4 times per hour, you lose ~1.5 hours of productive time.\n\n**Reducing Interruptions:**\n\n- Turn off non-urgent notifications\n- Use Focus mode on your OS\n- Communicate your focus schedule\n- Wear headphones as a visual signal\n- Batch-check messages at set times\n\n**The 5-Minute Rule for Procrastination:**\n\nIf you are avoiding a task, commit to working on it for just 5 minutes. Most of the time, you will continue past 5 minutes once started.\n\n**Environmental Design:**\n\n- Clean desk, clean desktop\n- Consistent workspace routine\n- Background music (instrumental)\n- Natural light when possible\n- Comfortable ergonomics\n\n**Key Takeaway:** Focus is a muscle. Protect it deliberately, and it strengthens over time. Start with just 2 hours of uninterrupted focus per day.' }
    ]
  },
  {
    id: 1020, slug: 'soft-communication', title: 'Technical Communication',
    description: 'Master the art of technical communication - writing clear documentation, creating architecture proposals, and presenting technical topics.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Write clear and concise technical documentation', 'Create effective architecture proposals and RFCs', 'Present technical topics to both technical and non-technical audiences', 'Adapt communication style for different stakeholders'],
    quiz: [
      { id: 1, question: 'What is the most important aspect of technical writing?', options: ['Using technical jargon', 'Clarity and simplicity for the target audience', 'Making documents as long as possible', 'Using complex sentence structures'], correctIndex: 1, explanation: 'Technical writing prioritizes clarity and simplicity.' },
      { id: 2, question: 'What is an RFC (Request for Comments)?', options: ['A legal document', 'A proposal for a technical change that invites feedback', 'A bug report', 'A performance review'], correctIndex: 1, explanation: 'An RFC is a structured proposal for a technical change.' },
      { id: 3, question: 'How should you present to a non-technical stakeholder?', options: ['Use as much technical detail as possible', 'Focus on business impact and outcomes', 'Skip the presentation', 'Only show code examples'], correctIndex: 1, explanation: 'Non-technical stakeholders care about business impact, timeline, and outcomes.' }
    ],
    topics: [
      { id: 'writing-technical-docs', title: 'Writing Technical Docs', content: '**Structure of Good Technical Documentation:**\n\n1. Title and Summary\n2. Problem Statement\n3. Background\n4. Proposed Solution\n5. Alternatives Considered\n6. Implementation Plan\n7. Risks and Mitigations\n8. Success Metrics\n\n**Writing Principles:**\n\n1. Know your audience\n2. Lead with the why\n3. Use concrete examples\n4. Keep it scannable with headers and bullet points\n5. Version control your docs\n\n**Example - Good vs Bad:**\n\nBad: The system shall utilize a microservices architecture leveraging event-driven patterns to optimize throughput.\n\nGood: We are splitting the monolith into 4 services to reduce deployment risk. Each service handles one business capability (users, orders, payments, notifications).\n\n**Key Takeaways:**\n1. Start with the problem, not the solution\n2. Use simple language and concrete examples\n3. Structure documents for scannability' },
      { id: 'architecture-proposals', title: 'Architecture Proposals', content: '**RFC Template:**\n\n# RFC: [Title]\n## Status\nProposed / Accepted / Deprecated\n## Summary\nOne paragraph explanation.\n## Motivation\nWhy are we doing this?\n## Detailed Design\nHow does the solution work?\n## Alternatives Considered\nWhat else did we evaluate?\n## Migration Plan\nHow do we get there?\n## Timeline\nWhen will this be implemented?\n\n**Presenting Architecture:**\n\n1. Start with the current state\n2. Identify the pain points\n3. Propose the future state\n4. Show the path\n5. Discuss trade-offs\n\n**Key Takeaways:**\n1. Follow a consistent RFC template\n2. Always discuss trade-offs\n3. Use diagrams to complement written descriptions' },
      { id: 'presenting-to-stakeholders', title: 'Presenting to Stakeholders', content: '**Audience Adaptation:**\n\n| Audience | Focus | Language |\n| Engineers | Implementation details | Technical |\n| Product Managers | User impact, timelines | Business |\n| Leadership | ROI, risk, strategic alignment | Business |\n| Designers | User experience, constraints | Collaborative |\n\n**Presentation Structure:**\n\n1. Opening (30s) - Hook with the problem\n2. Context (2min) - Why this matters\n3. Proposal (5min) - What we are building\n4. Demo (3min) - Show, do not just tell\n5. Timeline and Risks (2min) - Be honest\n6. Q&A (5min) - Invite questions\n\n**Handling Tough Questions:**\n\n- I do not know - Research and follow up\n- Pushback on timeline - Present trade-offs\n- Scope creep - Add to backlog for discussion\n\n**Key Takeaways:**\n1. Adapt language for each audience\n2. Lead with problem and business impact\n3. Prepare for tough questions' },
      { id: 'async-communication', title: 'Async Communication', content: '**Effective Messages:**\n\n1. Context - What is this about?\n2. Ask - What do you need from me?\n3. Deadline - When is this needed?\n4. Details - Supporting information\n\n**Example:**\n\nSubject: API Rate Limiting Decision Needed by Friday\n\nWe are hitting rate limits on the third-party API during peak traffic. I need a decision by Friday.\n\nOptions:\nA) Request higher limits ($500/month)\nB) Implement caching layer (2 days)\nC) Queue requests (1 day, adds latency)\n\nRecommendation: Option B.\n\n**Best Practices:**\n- Subject lines that summarize the ask\n- Action item first, details after\n- Clear deadlines\n- Document decisions in writing\n\n**Key Takeaways:**\n1. Lead with the ask\n2. Set clear deadlines\n3. Document decisions for future reference' }
    ]
  },
  {
    id: 1021, slug: 'soft-code-review', title: 'Code Review Mastery',
    description: 'Excel at code reviews - build effective review checklists, give constructive feedback, and handle disagreements professionally.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Build a comprehensive code review checklist', 'Give feedback that is constructive and actionable', 'Handle disagreements during code reviews professionally', 'Balance thoroughness with review speed'],
    quiz: [
      { id: 1, question: 'What is the primary goal of a code review?', options: ['Finding bugs before production', 'Improving code quality and sharing knowledge', 'Slowing down development', 'Assigning blame'], correctIndex: 1, explanation: 'Code reviews catch bugs, ensure quality, share knowledge, and maintain standards.' },
      { id: 2, question: 'How should you phrase critical feedback?', options: ['This code is wrong', 'I think this could be improved because...', 'You should have done this differently', 'This needs to be rewritten'], correctIndex: 1, explanation: 'Use I statements and explain reasoning for actionable, non-personal feedback.' },
      { id: 3, question: 'When should you block a PR from merging?', options: ['Disagree with variable naming', 'Security vulnerabilities or critical bugs', 'Code style does not match preference', 'PR is too large'], correctIndex: 1, explanation: 'Block only for critical issues like security vulnerabilities or data loss risks.' }
    ],
    topics: [
      { id: 'review-checklist', title: 'Review Checklist', content: '**Code Review Checklist:**\n\n**Functionality:**\n- Does the code do what it claims?\n- Are edge cases handled?\n- Are error conditions properly managed?\n\n**Code Quality:**\n- Is the code readable?\n- Are functions small and focused?\n- Are names descriptive?\n\n**Testing:**\n- Are there adequate tests?\n- Do tests cover edge cases?\n- Do all tests pass?\n\n**Security:**\n- No hardcoded secrets\n- Input is sanitized\n- Auth is checked\n\n**Performance:**\n- No unnecessary re-renders\n- DB queries are efficient\n- No memory leaks\n\n**Key Takeaways:**\n1. Use a checklist for consistency\n2. Prioritize functionality and security\n3. Tailor the checklist to your team' },
      { id: 'constructive-feedback', title: 'Constructive Feedback', content: '**SBI Framework:**\n\n**Situation** - Describe the context\n**Behavior** - Describe what you observed\n**Impact** - Explain the effect\n\n**Example:**\n\nBad: This function is terrible.\n\nGood: In processOrder (Situation), I noticed error handling silently catches exceptions (Behavior). This means failed orders appear successful to users (Impact). Could we add proper error logging?\n\n**Comment Types:**\n\n[Must Fix] - Blocking issues (bugs, security)\n[Should Fix] - Important improvements\n[Nit] - Minor style preferences\n[Question] - Seeking understanding\n[Suggestion] - Optional improvement\n\n**Key Takeaways:**\n1. Use SBI for clear, non-personal feedback\n2. Label by severity\n3. Ask questions before suggesting changes' },
      { id: 'handling-disagreements', title: 'Handling Disagreements', content: '**When You Disagree:**\n\n1. Listen First - Understand the concern\n2. Ask Clarifying Questions\n3. Present Your Reasoning\n4. Find Common Ground\n5. Escalate if Needed\n\n**Example Dialogue:**\n\nReviewer: This should use a class.\nYou: I chose a function because it is simpler and does not need state. Is there a specific concern?\nReviewer: Testability. Functions are harder to mock.\nYou: Fair point. I used dependency injection for testability. Let me add a comment.\n\n**When You Are the Reviewer:**\n- Acknowledge good work first\n- Accept valid counter-arguments\n- Focus on code, not the person\n- Approve with minor suggestions as follow-ups\n\n**Key Takeaways:**\n1. Treat disagreements as learning opportunities\n2. Focus on technical reasoning\n3. Know when to escalate and compromise' },
      { id: 'review-efficiency', title: 'Review Efficiency', content: '**Reviewing Large PRs:**\n\n1. Start with PR description\n2. Review structure first\n3. Look at test files\n4. Review implementation last\n5. Check consistency\n\n**Faster Reviews:**\n- Review in small batches (under 400 lines)\n- Use GitHub suggestions\n- Prioritize unblocking others\n- Set dedicated review time blocks\n\n**Automated Checks First:**\n- Linting passes\n- Type checking passes\n- Tests pass\n- Build succeeds\n- No security vulnerabilities\n\n**Turnaround Goals:**\n- Hotfixes: 1 hour\n- Regular PRs: 4 hours\n- Non-urgent: 24 hours\n\n**Key Takeaways:**\n1. Dedicate time for reviews\n2. Use automated checks first\n3. Aim for 4-hour turnaround' }
    ]
  },
  {
    id: 1022, slug: 'soft-mentoring', title: 'Mentoring Engineers',
    description: 'Develop effective mentoring skills - facilitate productive pair programming, share knowledge, and grow junior engineers.',
    level: 'advanced', duration: '35 min',
    objectives: ['Facilitate productive pair programming sessions', 'Create effective knowledge sharing practices', 'Guide junior engineers through challenging problems', 'Build a culture of continuous learning'],
    quiz: [
      { id: 1, question: 'What is the primary goal of pair programming?', options: ['Writing code faster', 'Sharing knowledge and solving problems collaboratively', 'Monitoring the other developer', 'Completing two tasks at once'], correctIndex: 1, explanation: 'Pair programming is about knowledge sharing and collaborative problem-solving.' },
      { id: 2, question: 'When mentoring, what is the best approach when they are stuck?', options: ['Give the answer immediately', 'Ask guiding questions to help them discover the solution', 'Wait for them to figure it out', 'Rewrite their code'], correctIndex: 1, explanation: 'Guiding questions help develop problem-solving skills.' },
      { id: 3, question: 'What makes an effective knowledge sharing session?', options: ['Presenting for 60+ minutes', 'Short, focused sessions with practical examples and Q&A', 'Sending a document to read', 'Only sharing new technology'], correctIndex: 1, explanation: 'Short, focused sessions with practical examples keep the audience engaged.' }
    ],
    topics: [
      { id: 'pair-programming', title: 'Pair Programming', content: '**Styles:**\n\n1. Driver-Navigator - One types, one guides\n2. Ping-Pong - Write test together, take turns\n3. Strong-Style - Idea goes through the other person\'s hands\n\n**Effective Session:**\n\nBefore:\n- Set a clear goal\n- Agree on style\n- Set time boundaries (25 min focus, 5 min break)\n\nDuring:\n- Switch roles every 15-25 minutes\n- Narrate your thought process\n- Ask questions instead of assumptions\n- Take short breaks\n\nAfter:\n- Summarize what was learned\n- Document decisions\n- Share with the team\n\n**When to Pair:**\n- Complex problems\n- Onboarding new members\n- Knowledge transfer\n- Debugging tricky issues\n\n**Key Takeaways:**\n1. Pair programming is for knowledge sharing\n2. Switch roles frequently\n3. Set clear goals and time boundaries' },
      { id: 'knowledge-sharing', title: 'Knowledge Sharing', content: '**Practices:**\n\n1. Tech Talks (15-30 min)\n- Problem/concept (5 min)\n- Solution/explanation (10 min)\n- Demo (10 min)\n- Q&A (5 min)\n\n2. Brown Bag Sessions\n- Informal lunch-and-learn\n- Rotating topic selection\n- Record for absent members\n\n3. Documentation as Code\n- ADRs\n- Team wiki\n- Onboarding processes\n- Runbooks\n\n**Reducing Bus Factor:**\n\nBus factor = minimum people needed before project is in trouble\n\nGoal: Every critical system has at least 2 people\n\nHow:\n- Rotate who works on different parts\n- Pair programming\n- Document tribal knowledge\n- Cross-train on critical systems\n\n**Key Takeaways:**\n1. Make knowledge sharing regular\n2. Target bus factor of 2+\n3. Document tribal knowledge' },
      { id: 'growing-juniors', title: 'Growing Junior Engineers', content: '**Mentoring Framework:**\n\n1. Observe - Watch how they approach problems\n2. Guide - Ask questions, do not give answers\n3. Challenge - Give progressively harder tasks\n4. Feedback - Regular, specific, actionable\n5. Celebrate - Acknowledge growth\n\n**Effective Feedback:**\n\nFrequency: Weekly 1-on-1s\n\nStructure:\n- What went well (specific examples)\n- What could improve (with guidance)\n- Focus for next week\n\nAvoid:\n- Vague feedback\n- Only negative feedback\n- No actionable next steps\n\n**Challenge Levels:**\n\n1. Bug fixes with clear reproduction\n2. Small features with clear requirements\n3. Features requiring design decisions\n4. Leading small projects end-to-end\n5. Mentoring another junior\n\n**Key Takeaways:**\n1. Give specific, actionable feedback\n2. Progressively increase challenge\n3. Watch for burnout and imposter syndrome' },
      { id: 'building-learning-culture', title: 'Building Learning Culture', content: '**Creating a Learning Environment:**\n\n1. Psychological Safety\n2. Curiosity\n3. Sharing\n4. Experimentation\n5. Reflection\n\n**Team Practices:**\n\n- Blameless Post-Mortems\n- Learning Fridays\n- Book Club\n- Hack Days\n- Conference Talks\n\n**Measuring:**\n\n- Tech talks per quarter\n- Documentation coverage\n- Onboarding time\n- Learning activity participation\n- Knowledge distribution\n\n**Key Takeaways:**\n1. Psychological safety is the foundation\n2. Dedicate regular time for learning\n3. Measure knowledge distribution' }
    ]
  },
  {
    id: 1023, slug: 'soft-decisions', title: 'Technical Decision Making',
    description: 'Make better technical decisions through structured trade-off analysis, ADRs, and systematic technology evaluation.',
    level: 'advanced', duration: '35 min',
    objectives: ['Conduct structured trade-off analysis', 'Write effective Architecture Decision Records', 'Evaluate technologies systematically', 'Document and communicate technical decisions'],
    quiz: [
      { id: 1, question: 'What is the purpose of an ADR?', options: ['Document meeting minutes', 'Record context, decision, and rationale for architectural choices', 'Track technical debt', 'Plan sprint work'], correctIndex: 1, explanation: 'ADRs capture context, decision, and reasoning behind architectural choices.' },
      { id: 2, question: 'Most important factor when evaluating new technology?', options: ['GitHub popularity', 'How well it solves your specific problem within constraints', 'Number of features', 'How new it is'], correctIndex: 1, explanation: 'The best technology solves your specific problem within your constraints.' },
      { id: 3, question: 'What is a trade-off?', options: ['A compromise making everyone unhappy', 'Accepting a disadvantage in one area for advantage in another', 'Choosing the cheapest option', 'Following what others do'], correctIndex: 1, explanation: 'Trade-offs involve recognizing that every choice has costs and benefits.' }
    ],
    topics: [
      { id: 'trade-off-analysis', title: 'Trade-Off Analysis', content: '**Framework:**\n\nFor each option evaluate:\n1. What do we gain?\n2. What do we give up?\n3. What are the risks?\n4. What are the costs?\n5. What is the reversibility?\n\n**Decision Matrix:**\n\nCriteria          | Weight | Option A | Option B\nLearning curve    |   3    |    2     |    4\nCommunity support |   2    |    5     |    3\nScalability       |   3    |    5     |    4\nDev tools         |   1    |    5     |    3\n\nWeighted Score:         37         34\n\n**Key Takeaways:**\n1. Every decision involves trade-offs\n2. Use weighted criteria for comparison\n3. Consider reversibility' },
      { id: 'adr-process', title: 'ADR Process', content: '**ADR Template:**\n\n# ADR-001: Use NgRx\n\n## Status\nAccepted\n## Context\nOur app has 50+ components with complex state.\n## Decision\nWe will use NgRx.\n## Rationale\n1. Mature ecosystem\n2. Predictable state updates\n3. Excellent dev tools\n## Consequences\n### Positive\n- Consistent pattern\n- Debug with Redux DevTools\n### Negative\n- Learning curve\n- Verbose for simple updates\n\n**Process:**\n1. Identify need for decision\n2. Draft ADR\n3. Share for feedback\n4. Discuss and reach consensus\n5. Record decision\n6. Set review date\n\n**Key Takeaways:**\n1. ADRs capture context and reasoning\n2. Include positive and negative consequences\n3. Set review dates' },
      { id: 'technology-evaluation', title: 'Technology Evaluation', content: '**Evaluation Criteria:**\n\n1. Problem Fit\n2. Team Fit\n3. Community and Ecosystem\n4. Technical Quality\n5. Operational Impact\n6. Long-term Viability\n\n**Proof of Concept Process:**\n\n1. Define success criteria\n2. Build minimal prototype (1-2 days)\n3. Test against real scenarios\n4. Document findings\n5. Present for go/no-go\n\n**Key Takeaways:**\n1. Define criteria before starting\n2. Build a proof of concept\n3. Consider long-term maintenance' },
      { id: 'communicating-decisions', title: 'Communicating Decisions', content: '**Framework:**\n\nFor every decision communicate:\n1. What we decided\n2. Why we decided this\n3. What we considered but rejected\n4. What this means for the team\n5. When we will revisit\n\n**Channels:**\n\nArchitecture -> ADR + team meeting\nLibrary choice -> RFC + async discussion\nProcess change -> Team meeting + doc\nCoding standards -> Linter config + wiki\n\n**Ensuring Buy-In:**\n- Involve stakeholders early\n- Present alternatives fairly\n- Acknowledge trade-offs\n- Give time for questions\n- Document the decision\n\n**Key Takeaways:**\n1. Communicate with context\n2. Use the right channel\n3. Involve stakeholders early' }
    ]
  },
  {
    id: 1024, slug: 'soft-incidents', title: 'Incident Response',
    description: 'Handle production incidents effectively with blameless post-mortems, root cause analysis, and continuous improvement.',
    level: 'advanced', duration: '30 min',
    objectives: ['Conduct effective blameless post-mortems', 'Perform root cause analysis using structured techniques', 'Build a blameless culture', 'Implement action items that prevent recurrence'],
    quiz: [
      { id: 1, question: 'What is the primary purpose of a blameless post-mortem?', options: ['Assign responsibility', 'Learn from the incident and improve systems', 'Punish those who caused the outage', 'Document for legal purposes'], correctIndex: 1, explanation: 'Blameless post-mortems focus on systemic improvements, not individual blame.' },
      { id: 2, question: 'What is the 5 Whys technique used for?', options: ['Counting affected users', 'Finding root cause by asking why repeatedly', 'Determining financial impact', 'Planning fix timeline'], correctIndex: 1, explanation: 'The 5 Whys technique peels back layers to reach the root cause.' },
      { id: 3, question: 'What makes incident response effective?', options: ['Fix as fast as possible', 'Clear communication, defined roles, systematic resolution', 'Work overtime until resolved', 'Only involve the person who caused it'], correctIndex: 1, explanation: 'Effective response requires clear communication, defined roles, and systematic approach.' }
    ],
    topics: [
      { id: 'post-mortem-process', title: 'Post-Mortem Process', content: '**Post-Mortem Template:**\n\n## Incident Summary\n- Date: 2024-01-15\n- Duration: 2 hours 15 minutes\n- Impact: 500 users affected\n- Severity: P1\n\n## Timeline\n- 14:00 - Alert fires\n- 14:05 - On-call acknowledges\n- 14:15 - Root cause identified\n- 14:30 - Fix deployed\n- 15:00 - Error rate normal\n\n## What Went Well\n- Alert fired quickly\n- Quick response\n- Clear communication\n\n## What Went Wrong\n- No monitoring\n- Not configurable\n- Outdated runbook\n\n## Root Cause\nConnection pool sized for normal traffic. Traffic spike exhausted pool.\n\n## Action Items\n- Add monitoring (Owner: Alice, Due: Jan 22)\n- Make configurable (Owner: Bob, Due: Jan 29)\n\n**Key Takeaways:**\n1. Focus on systemic issues\n2. Create actionable items with owners\n3. Review as a team' },
      { id: 'blameless-culture', title: 'Blameless Culture', content: '**Principles:**\n\n1. Everyone acts with good intentions\n2. Mistakes are opportunities\n3. Systems prevent human error\n4. Transparency is encouraged\n5. Learning is valued over perfection\n\n**Language Matters:**\n\nBlameful: Who deployed this broken code?\nBlameless: What about our process allowed this?\n\nBlameful: You should have tested this.\nBlameless: How can we improve our testing?\n\nBlameful: This was careless.\nBlameless: What conditions led to this mistake?\n\n**Building Culture:**\n\n- Leaders model blameless behavior\n- Celebrate incident reports\n- Share learnings across teams\n- Reward transparency\n- Focus on process improvements\n\n**Key Takeaways:**\n1. Language matters - focus on systems\n2. Leaders must model behavior\n3. Celebrate transparency' },
      { id: 'root-cause-analysis', title: 'Root Cause Analysis', content: '**5 Whys:**\n\nProblem: Application is slow.\n1. Why? DB queries are slow.\n2. Why? Too many queries per request.\n3. Why? N+1 query pattern.\n4. Why? ORM does not eager-load.\n5. Why? No ORM config review in code review.\n\nRoot Cause: No ORM review in code review process.\nSolution: Add ORM checks to review checklist.\n\n**Fishbone Categories:**\n\n- People: Training, knowledge\n- Process: Procedures, workflows\n- Technology: Tools, infrastructure\n- Environment: Load, network\n- Measurement: Monitoring, alerting\n\n**Key Takeaways:**\n1. Use 5 Whys to peel back layers\n2. Categorize contributing factors\n3. Root cause is usually systemic' },
      { id: 'action-items', title: 'Action Items and Follow-Up', content: '**Quality Action Items:**\n\nGood: Add connection pool monitoring, Owner: Alice, Due: Jan 22\nBad: Improve monitoring\n\n**Tracking:**\n\n1. Create tickets\n2. Link to post-mortem\n3. Review weekly\n4. Close when verified\n5. Report completion rate\n\n**Preventing Recurrence:**\n\n1. Fix the immediate issue\n2. Add monitoring\n3. Add automated tests\n4. Update runbooks\n5. Share learnings\n\n**Follow-Up:**\n\nSchedule: 2-4 weeks after\nPurpose: Verify effectiveness\nAttendees: Same team + stakeholders\n\n**Key Takeaways:**\n1. Specific, assigned, time-bound\n2. Track weekly\n3. Follow up to verify effectiveness' }
    ]
  },
  {
    id: 1025, slug: 'soft-leadership', title: 'Engineering Leadership',
    description: 'Develop engineering leadership skills - influence without authority, build technical strategy, and scale teams effectively.',
    level: 'advanced', duration: '35 min',
    objectives: ['Influence decisions without formal authority', 'Develop and communicate technical strategy', 'Scale engineering teams through hiring and culture', 'Balance technical debt with feature development'],
    quiz: [
      { id: 1, question: 'How do you influence without authority?', options: ['Tell people what to do', 'Build trust, provide data, demonstrate value', 'Escalate to management', 'Avoid disagreements'], correctIndex: 1, explanation: 'Influence comes from trust, evidence, and demonstrated results, not hierarchy.' },
      { id: 2, question: 'What is technical debt?', options: ['Money owed for infrastructure', 'Short-term trade-offs that increase future maintenance cost', 'Cost of running servers', 'Budget for technology'], correctIndex: 1, explanation: 'Technical debt is accumulated cost of shortcuts that make the codebase harder to modify.' },
      { id: 3, question: 'Most important factor in scaling a team?', options: ['Hire as fast as possible', 'Maintain culture and knowledge sharing', 'Use latest tools', 'Increase meetings'], correctIndex: 1, explanation: 'As teams grow, maintaining culture and knowledge sharing becomes critical.' }
    ],
    topics: [
      { id: 'influence-without-authority', title: 'Influence Without Authority', content: '**Sources of Influence:**\n\n1. Expertise\n2. Relationships\n3. Data\n4. Vision\n5. Results\n\n**Strategies:**\n\nRational Persuasion:\n- Present data and logical arguments\n- Show cost-benefit analysis\n\nCoalition Building:\n- Find allies\n- Build consensus before meetings\n\nExchange:\n- Find win-win solutions\n- Be willing to compromise\n\nInspiration:\n- Connect to team values\n- Paint compelling picture\n\n**Example - Proposing Refactor:**\n\nInstead: We need to refactor this module.\nTry: We spend 40% of sprint time on payment module issues. I have a proposal to reduce that to 10%, freeing 2 story points per sprint.\n\n**Key Takeaways:**\n1. Build trust through delivery\n2. Use data to support arguments\n3. Find allies and build consensus' },
      { id: 'technical-strategy', title: 'Technical Strategy', content: '**Framework:**\n\n1. Vision - Where are we going?\n2. Principles - What guides decisions?\n3. Priorities - What matters now?\n4. Roadmap - How do we get there?\n5. Metrics - How do we measure progress?\n\n**Balancing Tech Debt:**\n\n70% Features\n20% Tech debt\n10% Innovation\n\n**Roadmap Example:**\n\nQ1: Foundation\n- Migrate to signals\n- Establish design system\n- Set up monitoring\n\nQ2: Scale\n- Micro-frontends\n- E2E testing\n- Build times -50%\n\nQ3: Optimize\n- Bundle size -30%\n- Caching strategy\n- A/B testing\n\nQ4: Innovate\n- SSR evaluation\n- AI features prototype\n- Edge computing\n\n**Key Takeaways:**\n1. Align with business goals\n2. Allocate time for debt and innovation\n3. Use metrics to track progress' },
      { id: 'team-scaling', title: 'Team Scaling', content: '**Principles:**\n\n1. Hire slow, fire fast\n2. Maintain culture\n3. Invest in onboarding\n4. Document before hiring\n5. Preserve knowledge distribution\n\n**Onboarding:**\n\nWeek 1:\n- Dev environment\n- Codebase walkthrough\n- Meet the team\n- First small task\n\nWeek 2:\n- Deeper exploration\n- Attend ceremonies\n- Pair with team\n- Onboarding project\n\nMonth 1:\n- Own small feature\n- Participate in reviews\n- Understand deployment\n- First 1-on-1\n\n**Key Takeaways:**\n1. Invest heavily in onboarding\n2. Document before scaling\n3. Preserve knowledge distribution' },
      { id: 'balancing-debt-features', title: 'Balancing Debt and Features', content: '**Debt Classification:**\n\nType 1: Deliberate - We know it is a shortcut\nType 2: Accidental - We did not know better\nType 3: Bit Rot - Code that degraded\n\n**Prioritization:**\n\nHigh Business Value + High Debt -> Fix Now\nHigh Business Value + Low Debt -> Build Now\nLow Business Value + High Debt -> Consider\nLow Business Value + Low Debt -> Defer\n\n**Communicating to Leadership:**\n\nInstead: We need to refactor the codebase.\nTry: Deployment time increased from 5min to 45min. This costs 4 hours per week. A $20K refactoring investment saves $50K per year.\n\n**Key Takeaways:**\n1. Classify debt to prioritize\n2. Quantify cost in business terms\n3. Use impact matrix for decisions' }
    ]
  }
];
