import { Lesson } from '../models/lesson.model';

export const TESTING_LESSONS: Lesson[] = [
  {
    id: 801, slug: 'testing-fundamentals', title: 'Testing Fundamentals',
    description: 'Master the fundamentals of testing in Angular applications.',
    level: 'beginner', duration: '30 min',
    objectives: ['Understand testing pyramid', 'Set up testing environment', 'Write basic unit tests'],
    quiz: [
      { id: 1, question: 'What is the testing pyramid?', options: ['A testing framework', 'A model showing the ideal distribution of unit, integration, and e2e tests', 'A type of test', 'A testing tool'], correctIndex: 1, explanation: 'The testing pyramid suggests having many unit tests at the base, fewer integration tests in the middle, and few end-to-end tests at the top.' },
      { id: 2, question: 'What is unit testing?', options: ['Testing the entire application', 'Testing individual components or services in isolation', 'Testing user workflows', 'Testing database connections'], correctIndex: 1, explanation: 'Unit testing verifies that individual pieces of code (components, services, pipes) work correctly in isolation.' },
      { id: 3, question: 'What is TestBed used for?', options: ['Building applications', 'Creating a testing environment for Angular components', 'Running end-to-end tests', 'Managing test data'], correctIndex: 1, explanation: 'TestBed is Angular\'s primary API for configuring and initializing the environment for unit testing.' }
    ],
    topics: [
      {
        id: 'testing-pyramid', title: 'Testing Pyramid',
        content: 'The testing pyramid is a strategic framework for organizing your test suite. At the base are unit tests, which should make up about 70 percent of your tests. These test individual components, services, and pipes in isolation. They are fast to execute, easy to debug, and provide precise feedback about what broke. In the middle layer are integration tests, roughly 20 percent of your suite. These verify that multiple units work together correctly, such as a component communicating with its child components or a service calling another service. At the top are end-to-end tests, comprising about 10 percent. These simulate real user workflows through the entire application and are the slowest but most comprehensive. The key insight is that each layer serves a different purpose. Unit tests catch logic errors early and run quickly during development. Integration tests catch issues that emerge when components interact, such as incorrect dependency injection or data flow problems. E2E tests validate critical business workflows like login, checkout, and data submission. A well-balanced pyramid gives you fast feedback during development while still catching integration issues and validating user journeys. Avoid putting too many tests at the top of the pyramid, as E2E tests are expensive to maintain and slow to run.'
      },
      {
        id: 'setup', title: 'Testing Setup',
        content: 'Angular provides built-in testing support through the Angular CLI. When you generate a component, service, or module, Angular automatically creates a corresponding spec file. The testing framework uses Jasmine as the test runner and Karma as the test server. To run your tests, execute the ng test command which compiles your application, starts Karma, opens a browser, and runs all spec files. You can add the code-coverage flag to generate a coverage report showing which lines of code are exercised by your tests. The watch mode flag keeps the test runner active and re-runs tests whenever you save a file, providing rapid feedback during development. TestBed is the primary Angular API for testing. It creates a dynamic testing module that mimics an Angular module, configured specifically for your tests. You configure TestBed in the beforeEach block to set up the testing environment before each test runs. This includes declaring components, providing services, and importing necessary modules. After configuration, call compileComponents to process any asynchronous template and CSS compilation. Then create a component fixture using TestBed.createComponent, which returns a handle to the component and its template for testing.'
      },
      {
        id: 'basic-test', title: 'Writing Basic Tests',
        content: 'Every test in Jasmine follows the describe-it pattern. The describe block groups related tests under a descriptive name, typically the class or feature being tested. Inside describe, the it block defines an individual test case with a specific expectation. The beforeEach block runs before each it block to set up shared state, such as creating component instances or injecting services. The expect function is the assertion mechanism. It takes a value and chains it with a matcher. Common matchers include toBe for strict equality, toEqual for deep equality, toBeTruthy and toBeFalsy for boolean checks, toContain for substring or array membership, and toThrow for error verification. For Angular components, you create a TestBed configuration, build the component with TestBed.createComponent, and then test its behavior. The fixture object wraps the component and provides access to the component instance, the native element, and change detection. After setting inputs or triggering events, call fixture.detectChanges to trigger Angular change detection and update the DOM. For services, you inject them through TestBed.inject and call methods directly, verifying the return values with expect. This straightforward approach covers most testing scenarios in Angular applications.'
      }
    ]
  },
  {
    id: 802, slug: 'testing-components', title: 'Component Testing',
    description: 'Master testing Angular components with inputs, outputs, and dependencies.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Test component inputs/outputs', 'Mock dependencies', 'Test async operations'],
    quiz: [
      { id: 1, question: 'How do you test a component with inputs?', options: ['Set the input directly on the component instance', 'Use TestBed to create the component and set inputs', 'Both A and B', 'You cannot test inputs'], correctIndex: 2, explanation: 'You can set inputs directly on the component instance or use the componentRef.setInput() method.' },
      { id: 2, question: 'What is the purpose of SpyObj in Jasmine?', options: ['Create real objects', 'Create mock objects with spy methods', 'Create test data', 'Create HTML elements'], correctIndex: 1, explanation: 'SpyObj creates mock objects where you can spy on method calls and return specific values.' },
      { id: 3, question: 'How do you test async operations?', options: ['Use async/await', 'Use fakeAsync and tick()', 'Use done callback', 'All of the above'], correctIndex: 3, explanation: 'Angular provides multiple ways to test async operations: async/await, fakeAsync/tick, and the done callback.' }
    ],
    topics: [
      {
        id: 'input-output', title: 'Testing Inputs and Outputs',
        content: 'Testing component inputs involves setting values and verifying the component renders correctly. For signal-based inputs, use the signal setter directly on the component instance. Call fixture.detectChanges after setting an input to trigger change detection and update the template. Then query the rendered DOM to verify the output matches expectations. When testing input changes, set a new value and call detectChanges again to verify the component updates its display. For traditional decorator-based inputs, use fixture.componentRef.setInput which sets the value through Angular\'s input binding mechanism. Testing outputs requires spying on the EventEmitter. Use jasmine.spyOn to intercept the emit method, then trigger the action that should cause the emission, such as clicking a button or calling a method. After triggering, assert that emit was called with the expected payload using toHaveBeenCalledWith. For event bindings in templates, you can dispatch events on the native element and verify the output was emitted. This approach works for both signal-based and decorator-based outputs. Always verify both that the event was emitted and that it carries the correct data. Testing outputs in isolation gives you confidence that child components communicate correctly with their parents.'
      },
      {
        id: 'mocking', title: 'Mocking Dependencies',
        content: 'Mocking replaces real dependencies with controlled substitutes during testing. Jasmine provides jasmine.createSpyObj to create typed mock objects. Pass the class name and an array of method names, and Jasmine creates an object with spy methods that you can configure. Use and.returnValue to make a spy return a specific value, and.callFake to provide custom logic, and.returnValue with throwError to simulate errors. In Angular, provide mocks through the TestBed providers array. Use the provide key as the real service class and useValue or useClass for the mock. This ensures Angular\'s dependency injection gives your component or service the mock instead of the real implementation. When mocking HTTP calls, Angular provides HttpTestingController. Configure TestBed with provideHttpClient and provideHttpClientTesting, then inject HttpTestingController. Your tests call the service method, then use httpMock.expectOne to intercept the request. Verify the request method and URL, then flush a mock response or error. After each test, call httpMock.verify in an afterEach block to ensure no unexpected requests were made. This pattern keeps your tests fast, deterministic, and free from network dependencies.'
      },
      {
        id: 'async-testing', title: 'Testing Async Operations',
        content: 'Angular provides several utilities for testing asynchronous code. The fakeAsync zone combined with the tick function lets you control time programmatically. Wrap your test in fakeAsync, and when the code under test triggers a setTimeout or debounce, call tick with the appropriate milliseconds to advance the virtual clock. After tick completes, assert the expected state. This approach is deterministic and avoids real delays. For Observable-based code, the same fakeAsync pattern works with operators like debounceTime, delay, and switchMap. Subscribe to the observable, call tick to advance time, and verify the emitted values. For Promise-based code, use async and await syntax. Mark the test function as async, await the promise, and then assert. Angular also provides waitForAsync which handles zone.js integration for Promise-based tests. The done callback is a Jasmine feature for tests that cannot use Angular\'s zone-based utilities. Pass done as a parameter to the test function and call it when the asynchronous operation completes. However, prefer fakeAsync and async-await over done callbacks because they integrate better with Angular\'s change detection and provide clearer error messages when assertions fail.'
      }
    ]
  },
  {
    id: 803, slug: 'testing-services', title: 'Service Testing',
    description: 'Master testing Angular services with dependency injection and HTTP mocking.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Test service methods', 'Mock HTTP calls', 'Test error handling'],
    quiz: [
      { id: 1, question: 'How do you test a service that depends on HttpClient?', options: ['Make real HTTP calls', 'Use HttpTestingController to mock requests', 'Use fetch instead', 'Skip testing HTTP'], correctIndex: 1, explanation: 'HttpTestingController intercepts HTTP requests during tests, allowing you to mock responses without real network calls.' },
      { id: 2, question: 'What should you verify after each HTTP test?', options: ['That the service was created', 'That all expected HTTP requests were made', 'That the component rendered', 'That the test passed'], correctIndex: 1, explanation: 'Always call httpMock.verify() in afterEach to ensure no unexpected HTTP requests were made.' },
      { id: 3, question: 'How do you test error handling in a service?', options: ['Ignore errors', 'Use HttpTestingController to simulate errors', 'Test only happy paths', 'Use real network errors'], correctIndex: 1, explanation: 'Simulate errors by calling req.error() instead of req.flush() to test error handling logic.' }
    ],
    topics: [
      {
        id: 'basic-service', title: 'Basic Service Testing',
        content: 'Testing services begins with verifying they can be instantiated through dependency injection. Use TestBed.configureTestingModule with an empty providers array for services with no dependencies, then inject the service using TestBed.inject. Write a simple test that checks the service is truthy, confirming it was created successfully. Next, test each public method by calling it with known inputs and asserting the expected outputs using expect with appropriate matchers. For services that maintain state, test the initial state after creation, then perform operations and verify state changes. Test edge cases such as empty inputs, null values, boundary values, and error conditions. When a service depends on other services, you have two options. Provide real implementations if they are fast and deterministic, or create mock versions using jasmine.createSpyObj and provide them through the TestBed providers. Mocks give you full control over return values and let you verify that the service under test calls its dependencies correctly. Always test both the happy path where everything works and error paths where dependencies fail or return unexpected data. This approach ensures your service handles all scenarios gracefully.'
      },
      {
        id: 'http-testing', title: 'HTTP Service Testing',
        content: 'Angular\'s HttpClient testing utilities let you intercept and mock HTTP requests without making real network calls. Configure TestBed with provideHttpClient and provideHttpClientTesting to set up the testing HTTP backend. Inject HttpTestingController from TestBed to control intercepted requests. When testing a method that makes an HTTP call, invoke the method and subscribe to the observable. Then use httpMock.expectOne with the expected URL to intercept the pending request. Verify the request properties such as method, headers, and body. Call req.flush with mock data to simulate a successful response, or call req.error to simulate a failure. For POST and PUT requests, verify that req.request.body contains the expected payload. For requests with query parameters, use httpMock.expectOne with a predicate function that matches the URL pattern. After each test, call httpMock.verify in an afterEach block. This ensures all expected requests were made and no unexpected requests leaked through. Testing error responses is equally important. Flush an error response with a status code and status text, then subscribe to the error callback and verify the service handles it correctly. This pattern covers GET, POST, PUT, PATCH, and DELETE operations comprehensively.'
      },
      {
        id: 'mocking', title: 'Mocking Strategies',
        content: 'Mocking is the practice of replacing real dependencies with controlled substitutes. The goal is to isolate the code under test from external systems that are slow, non-deterministic, or unavailable in the test environment. There are several types of test doubles. A stub provides preset return values without tracking interactions. A spy wraps a real or fake object and records method calls for verification. A mock is a fully pre-programmed object with expectations about how it should be called. A fake is a working implementation optimized for testing, like an in-memory database. Jasmine.createSpyObj creates typed spy objects that integrate seamlessly with TypeScript. Pass the class name and method names, and get an object where every method is a spy. Configure return values with and.returnValue and and.callFake. Verify interactions with toHaveBeenCalledWith and toHaveBeenCalledTimes. When deciding what to mock, follow these guidelines. Always mock HTTP calls, file system access, timers, and third-party services. Prefer real objects for simple value objects, pure functions, and your own fast deterministic code. The key is to mock at system boundaries where your code interacts with the outside world, not internal implementation details that may change frequently.'
      }
    ]
  },
  {
    id: 804, slug: 'testing-e2e-playwright', title: 'End-to-End Testing with Playwright',
    description: 'Master end-to-end testing with Playwright for reliable Angular application testing.',
    level: 'advanced', duration: '45 min',
    objectives: ['Set up Playwright for Angular', 'Create page objects for test organization', 'Handle network mocking', 'Run tests in CI/CD'],
    quiz: [
      { id: 1, question: 'What is Playwright primarily used for?', options: ['Unit testing components', 'End-to-end browser testing across multiple browsers', 'Code compilation', 'Style checking'], correctIndex: 1, explanation: 'Playwright is a framework for end-to-end testing that allows you to test your Angular app in real browsers with automation.' },
      { id: 2, question: 'What is the Page Object Model pattern in Playwright?', options: ['A database model', 'A design pattern that encapsulates page interactions into reusable classes', 'A testing framework', 'A component architecture'], correctIndex: 1, explanation: 'The Page Object Model encapsulates page-specific locators and actions into classes, making tests more maintainable and readable.' },
      { id: 3, question: 'How do you mock API responses in Playwright?', options: ['Cannot mock API responses', 'Use page.route() to intercept and modify network requests', 'Only use real API calls', 'Use a separate mocking library'], correctIndex: 1, explanation: 'Playwright provides page.route() to intercept network requests and return custom responses without hitting real APIs.' }
    ],
    topics: [
      {
        id: 'playwright-setup', title: 'Playwright Setup',
        content: 'Playwright is installed as a development dependency and configured through a playwright.config.ts file. The configuration specifies the test directory, browser projects, and the web server to start before tests run. For Angular applications, point the webServer command to ng serve and set the port to 4200. The baseURL setting lets you navigate to pages using relative paths. The config supports multiple browser projects including Chromium, Firefox, and WebKit, allowing you to test cross-browser compatibility from a single test suite. Enable retries in CI environments to handle transient failures. Set fullyParallel to true to run test files concurrently for faster execution. Configure the reporter to generate HTML reports for debugging failed tests. Install Playwright browsers as a CI step using npx playwright install with deps flag for system dependencies. In your test files, import test and expect from @playwright/test. The test function defines individual test cases, and the page fixture provides a browser page instance. Use page.goto to navigate to your Angular application, and chain assertions with expect to verify page content, element visibility, and URL changes. The test.beforeEach hook sets up common state like navigating to a page before each test runs.'
      },
      {
        id: 'page-objects', title: 'Page Object Model',
        content: 'The Page Object Model encapsulates page-specific locators and actions into reusable classes. Each page or major component gets its own class that holds Locator properties for interactive elements and methods for user actions. Locators are defined in the constructor using page.locator with CSS selectors, data-testid attributes, or role-based selectors. Methods like login, search, or navigate encapsulate multi-step interactions into single calls. This abstraction serves two purposes. First, it eliminates locator duplication across tests. If a selector changes, you update it in one place instead of every test. Second, it makes tests read at a higher level of intent. A test reads like a sequence of user actions rather than a list of DOM queries. To use page objects in tests, instantiate them in the beforeEach hook with the page fixture. Call page object methods to perform actions, then use expect with locator assertions to verify results. Keep page object methods focused on actions without assertions, and let the test handle all verification. This separation makes page objects reusable across different test scenarios and easier to maintain as your application evolves.'
      },
      {
        id: 'network-mocking', title: 'Network Interception',
        content: 'Playwright intercepts network requests using page.route, which lets you modify or fulfill requests before they reach the server. Pass a URL pattern as a string or regex, and a handler function that receives the route object. Call route.fulfill to provide a custom response with a status code, content type, and body. This is useful for testing loading states, error handling, and edge cases that are difficult to reproduce with a real backend. You can also use route.continue to modify the request before forwarding it, or route.abort to simulate network failures. Network mocking enables deterministic tests that do not depend on backend availability or data state. Mock API responses with consistent data, and verify your UI renders correctly regardless of server conditions. For testing loading indicators, add a delay to the fulfilled response to simulate slow network conditions. Mock error responses by fulfilling with a 500 status code and error message, then verify your application displays appropriate error states. Combine network mocking with viewport configuration to test responsive behavior under different network conditions. Always clean up route handlers after tests to avoid intercepting requests in subsequent tests.'
      }
    ]
  },
  {
    id: 805, slug: 'testing-integration', title: 'Integration Testing Strategies',
    description: 'Master integration testing strategies for testing component and service interactions.',
    level: 'advanced', duration: '40 min',
    objectives: ['Write component integration tests', 'Test service interactions', 'Mock HTTP calls properly', 'Create reusable test utilities'],
    quiz: [
      { id: 1, question: 'What is the difference between unit and integration tests?', options: ['There is no difference', 'Unit tests isolate components while integration tests verify component interactions', 'Integration tests are faster', 'Unit tests use real dependencies'], correctIndex: 1, explanation: 'Unit tests verify individual components in isolation, while integration tests verify how multiple components and services work together.' },
      { id: 2, question: 'How should HTTP calls be mocked in integration tests?', options: ['Use HttpTestingController', 'Use a real HTTP server', 'Skip HTTP mocking', 'Only test non-HTTP code'], correctIndex: 0, explanation: 'HttpTestingController from Angular provides a clean way to intercept and mock HTTP requests in integration tests.' },
      { id: 3, question: 'What is a shared test utility?', options: ['A testing framework', 'Reusable helper functions and configurations for writing tests consistently', 'A test runner', 'A code coverage tool'], correctIndex: 1, explanation: 'Shared test utilities are helper functions, base configurations, and mock data that can be reused across multiple test files.' }
    ],
    topics: [
      {
        id: 'component-integration', title: 'Component Integration Tests',
        content: 'Component integration tests verify that multiple components work together correctly. Instead of testing a component in isolation with all dependencies mocked, you import its actual child components and test the real interactions. Configure TestBed with the parent component and its child components in the imports array. Provide real or mock services depending on what you want to verify. For example, a user list component that renders user card children can import both components and verify that the list passes data to each card correctly. Test that actions in child components propagate to the parent. When a user clicks delete on a card, verify the parent component receives the event and updates its list. Integration tests catch issues like mismatched input types, missing event bindings, and incorrect data transformations between components. They are slower than unit tests but provide higher confidence that your component tree works as a cohesive unit. Focus integration tests on critical user workflows and component boundaries where data flows between components. Use them to verify that your component composition is correct and that parent-child communication works as expected.'
      },
      {
        id: 'service-integration', title: 'Service Integration Tests',
        content: 'Service integration tests verify that multiple services collaborate correctly. Instead of testing each service in isolation, you provide real implementations and test the complete flow. For example, test that an order service correctly calls a payment service and then a notification service by providing all three real services in TestBed. Mock external dependencies like HTTP calls using HttpTestingController, but let internal service interactions run naturally. This approach catches issues in the orchestration logic that unit tests with mocked services would miss. Test data flows through the service pipeline by verifying that each service receives the expected input and produces the expected output. When testing service chains, verify both the final result and the intermediate calls. Check that each service was called with the correct arguments and in the correct order. Service integration tests are valuable for testing complex business workflows where multiple services coordinate to accomplish a task. They are faster than component integration tests because they do not involve template rendering or change detection, but slower than unit tests because they exercise more code. Use them to verify your service layer architecture is correct.'
      },
      {
        id: 'test-utilities', title: 'Shared Test Utilities',
        content: 'Shared test utilities reduce duplication and enforce consistency across your test suite. Create helper functions for common operations like creating component fixtures, querying DOM elements, and waiting for async operations. A createComponent helper can wrap the standard TestBed setup and return a configured fixture. DOM query helpers like getElement and getAllElements provide typed access to rendered elements without repetitive casting. Reusable mock data files define fixtures for common entities like users, products, or orders. Centralizing mock data ensures consistency across tests and makes it easy to update when the data model changes. Export constants for mock API responses, error objects, and configuration values. Create base TestBed configurations that include common providers like HTTP client, router, and animations. Spread these configurations into individual test modules to reduce boilerplate. For HTTP testing, create a helper that sets up HttpTestingController and provides functions for flushing mock responses. Document each utility with JSDoc comments explaining its purpose and parameters. Organize utilities by domain, placing component helpers in one file, service helpers in another, and shared mock data in a separate file. This organization makes utilities easy to discover and maintain as your test suite grows.'
      }
    ]
  },
  {
    id: 806, slug: 'testing-performance', title: 'Performance Testing',
    description: 'Master performance testing strategies for Angular applications.',
    level: 'advanced', duration: '40 min',
    objectives: ['Set up Lighthouse CI', 'Test Core Web Vitals', 'Detect memory leaks', 'Enforce performance budgets'],
    quiz: [
      { id: 1, question: 'What are Core Web Vitals?', options: ['A testing framework', 'Google metrics measuring loading, interactivity, and visual stability', 'Angular performance tools', 'Browser debugging features'], correctIndex: 1, explanation: 'Core Web Vitals are three metrics Google uses to measure user experience: LCP (loading), FID/INP (interactivity), and CLS (visual stability).' },
      { id: 2, question: 'What is Lighthouse CI?', options: ['A build tool', 'An automated tool for running Lighthouse audits in CI/CD pipelines', 'A testing framework', 'A code editor plugin'], correctIndex: 1, explanation: 'Lighthouse CI automates running Lighthouse audits on every build, tracking performance regressions over time.' },
      { id: 3, question: 'How do you detect memory leaks in tests?', options: ['Check bundle size', 'Monitor heap size before and after operations', 'Run Lighthouse', 'Check network requests'], correctIndex: 1, explanation: 'Memory leak detection involves monitoring heap allocations during test execution and comparing them against expected values.' }
    ],
    topics: [
      {
        id: 'lighthouse-ci', title: 'Lighthouse CI Setup',
        content: 'Lighthouse CI automates performance auditing in your continuous integration pipeline. Install it as a development dependency and create a configuration file that specifies which pages to audit and what score thresholds to enforce. The collect section configures how Lighthouse runs your application. Point startServerCommand to ng serve and set numberOfRuns to 3 for statistically meaningful results. Define the URLs to test, including your homepage and critical routes. The assert section defines performance budgets. Set minimum scores for performance, accessibility, best practices, and SEO categories. Configure numeric thresholds for specific metrics like First Contentful Paint under 2000 milliseconds, Largest Contentful Paint under 2500 milliseconds, and Cumulative Layout Shift under 0.1. The upload section sends results to a Lighthouse CI server for tracking over time. In GitHub Actions, add a step that runs npx lhci autorun after your build completes. Lighthouse CI will fail the build if any assertions fail, preventing performance regressions from reaching production. Track performance scores across builds to identify trends and catch gradual degradation. Review Lighthouse reports for specific recommendations like image optimization, code splitting, and render-blocking resources.'
      },
      {
        id: 'web-vitals', title: 'Web Vitals Testing',
        content: 'Core Web Vitals measure real-world user experience across three dimensions. Largest Contentful Paint measures loading performance and should be under 2500 milliseconds. Interaction to Next Paint measures responsiveness and should be under 200 milliseconds. Cumulative Layout Shift measures visual stability and should be under 0.1. Test these metrics using Playwright with the Performance Observer API. For LCP, create a PerformanceObserver that watches for largest-contentful-paint entries and records the final entry\'s start time. Navigate to the page, wait for the observer to fire, and assert the value is under your threshold. For CLS, observe layout-shift entries and accumulate their values, excluding shifts caused by user input. For INP, measure the time between user interactions and the next paint by observing event timing entries. These tests run in real browsers against your actual application, providing accurate measurements. Run them in your CI pipeline with consistent viewport sizes and network conditions for reproducible results. Compare metrics against historical baselines to detect performance regressions. Use Playwright\'s tracing feature to capture detailed performance profiles for debugging slow pages. Combine automated metrics testing with manual performance reviews using Chrome DevTools for comprehensive performance analysis.'
      },
      {
        id: 'memory-leaks', title: 'Memory Leak Detection',
        content: 'Memory leaks occur when components or services fail to clean up resources like subscriptions, event listeners, and timers. In Angular, the most common leaks come from unsubscribed Observables and forgotten event listeners. Test for memory leaks by creating and destroying components repeatedly while monitoring heap size. Use performance.memory.usedJSHeapSize to track memory allocation before and after the test. Create the component, trigger its initialization, destroy it, and force garbage collection. Repeat this cycle fifty times and compare the final heap size to the initial size. Allow a tolerance of a few megabytes for normal heap fluctuations. For subscription cleanup, verify that ngOnDestroy calls unsubscribe on all active subscriptions. Spy on the destroy method and check that subscription.closed is true after destruction. For event listeners, verify that removeEventListener is called for every addEventListener. Test that components using takeUntil or async pipe properly complete their Observables on destroy. Use RxJS TestScheduler to verify Observable completion without real timers. Regularly run memory leak tests as part of your CI suite to catch leaks early. Profile your application with Chrome DevTools Memory tab to identify specific leak sources when tests fail.'
      }
    ]
  },
  {
    id: 807, slug: 'testing-mocking', title: 'Mocking & Test Doubles',
    description: 'Master mocking techniques and test doubles for isolating code under test.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Understand test double types', 'Create effective mocks', 'Know when to mock vs use real objects'],
    quiz: [
      { id: 1, question: 'What is the difference between a mock and a stub?', options: ['They are the same thing', 'A stub returns preset data while a mock verifies interactions', 'A mock returns preset data while a stub verifies interactions', 'Neither verifies interactions'], correctIndex: 1, explanation: 'Stubs provide canned answers to calls made during the test, while mocks also record and verify that certain interactions occurred.' },
      { id: 2, question: 'When should you prefer NOT to mock a dependency?', options: ['When the dependency is complex', 'When testing pure business logic that depends on simple, fast, deterministic collaborators', 'When the dependency is a third-party library', 'Never, always mock everything'], correctIndex: 1, explanation: 'If the real object is fast, deterministic, and not a network or file system call, using the real implementation often gives more confidence than mocking.' },
      { id: 3, question: 'What problem does Jasmine.SpyObj solve?', options: ['It creates real service instances', 'It creates typed mock objects with spy methods for spying and stubbing', 'It replaces TestBed', 'It provides HTTP mocking'], correctIndex: 1, explanation: 'Jasmine.SpyObj creates an object with methods that are automatically spies, giving you type safety and the ability to stub return values and verify calls.' }
    ],
    topics: [
      {
        id: 'what-are-mocks', title: 'What Are Mocks?',
        content: 'Test doubles are objects that replace real dependencies during testing. Understanding the different types helps you choose the right one for each situation. Dummy objects fill parameter lists but are never actually used. They exist only to satisfy type requirements so the code compiles. Stubs provide hardcoded responses to method calls. When a test needs a service to return specific data, a stub returns that data without any logic. Stubs do not care how many times they are called or with what arguments. Spies record information about calls made to them. A spy tracks the call count, arguments, and return value. You can configure a spy to return specific values using and.returnValue. Mocks are pre-programmed objects with expectations. Unlike stubs, mocks verify behavior. If the code under test does not call the mock as expected, the test fails. Fakes are working implementations optimized for testing. A fake database might store data in memory instead of on disk. Use dummies when you need to fill a parameter. Use stubs when you need to control return values. Use spies when you need to verify calls happened. Use mocks when you need to set expectations before the test. Use fakes when you want realistic behavior without external systems. Each type serves a specific purpose in your testing toolkit.'
      },
      {
        id: 'creating-mocks', title: 'Creating Effective Mocks',
        content: 'Jasmine.createSpyObj is the primary tool for creating typed mock objects in Angular tests. Pass the class name as a string for error messages, an array of method names to create as spies, and optionally an array of property names. The resulting object has methods that are automatically Jasmine spies, giving you full type safety with TypeScript. Configure return values using and.returnValue for synchronous values and and.returnValue with of for Observables. Use and.callFake when you need custom logic in the mock, such as transforming input data before returning it. Use and.returnValue with throwError to simulate error conditions. Verify interactions using toHaveBeenCalled and toHaveBeenCalledWith. The toHaveBeenCalledTimes matcher checks the exact call count. Combine multiple matchers for thorough verification. For Observable-based mocks, create Subject or ReplaySubject instances that you control. Inject the mock Subject where the real Observable would be, and call next in your tests to emit values. This gives you precise control over when data arrives. Clean up mock subjects in afterEach to prevent test pollution. When creating mocks, focus on the public interface that the code under test uses. Do not mock private methods or internal implementation details that may change frequently.'
      },
      {
        id: 'when-to-mock', title: 'When to Mock',
        content: 'Deciding when to mock requires balancing test isolation against test realism. Always mock external systems that your code cannot control. HTTP calls should be mocked because network requests are slow, non-deterministic, and may fail for reasons unrelated to your code. File system operations should be mocked to avoid test pollution and platform dependencies. Third-party services like authentication providers, payment gateways, and analytics should be mocked to isolate your business logic. Time-dependent code should use fake timers instead of real delays. Prefer real objects when the dependency is fast, deterministic, and part of your own codebase. Simple value objects, pure transformation functions, and data structures do not need mocking. Using the real implementation gives you more confidence that the code works correctly with actual data. The key principle is to mock at system boundaries where your code interacts with the outside world. Mock the HTTP client, not the service that wraps it. Mock the file system, not the utility function that processes file content. Avoid mocking implementation details that change frequently, as this creates fragile tests that break when you refactor. Focus mocks on external contracts rather than internal mechanics. This approach produces tests that are both reliable and maintainable over time.'
      }
    ]
  },
  {
    id: 808, slug: 'testing-tdd', title: 'Test-Driven Development',
    description: 'Learn the Test-Driven Development methodology to write better code with confidence.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Apply the TDD cycle', 'Practice red-green-refactor', 'Understand TDD benefits and tradeoffs'],
    quiz: [
      { id: 1, question: 'What is the correct order of the TDD cycle?', options: ['Green-Red-Refactor', 'Refactor-Green-Red', 'Red-Green-Refactor', 'Code-Test-Refactor'], correctIndex: 2, explanation: 'The TDD cycle starts with a failing test (Red), writes the minimum code to pass (Green), then improves the code without changing behavior (Refactor).' },
      { id: 2, question: 'What does the Refactor step in TDD ensure?', options: ['Add new features', 'Improve code structure without changing external behavior', 'Fix failing tests', 'Write more tests'], correctIndex: 1, explanation: 'Refactoring improves the internal structure of code without altering its observable behavior, keeping tests green while improving design.' },
      { id: 3, question: 'Why write the test before the code in TDD?', options: ['It is faster', 'It forces clear thinking about requirements and produces testable design', 'The test framework requires it', 'It eliminates all bugs'], correctIndex: 1, explanation: 'Writing tests first forces you to think about what the code should do before how it does it, leading to cleaner interfaces and testable designs.' }
    ],
    topics: [
      {
        id: 'tdd-cycle', title: 'The TDD Cycle',
        content: 'Test-Driven Development follows a short, repeating cycle called Red-Green-Refactor. Each iteration produces working, tested, clean code. Step one is Red. Write a small test for the next piece of functionality. Since the feature does not exist yet, the test fails immediately. This failing test defines exactly what behavior you want. The red state is intentional because it confirms the test actually tests something. Step two is Green. Write the simplest possible code to make the test pass. Do not worry about elegance or optimization. The goal is to get to green as fast as possible. Sometimes this means returning a hardcoded value. That is fine because the next step cleans it up. Step three is Refactor. With a safety net of passing tests, improve the code structure. Remove duplication, extract methods, rename variables for clarity, and apply design patterns. Since all tests pass, you can refactor confidently knowing any breakage is caught immediately. The cycle is very short, typically lasting minutes. Start with a failing test to define requirements. Write minimal code to pass, then improve the design. Each cycle produces a small piece of working, tested, clean code. Over time, these small pieces accumulate into a well-tested, well-designed system.'
      },
      {
        id: 'red-green-refactor', title: 'Red-Green-Refactor Deep Dive',
        content: 'Going deeper into each phase of TDD reveals important nuances. In the Red phase, write a specific test that defines one behavior. Avoid vague tests like should work. Instead, write should return empty array when no items in cart. The test should fail for the right reason, meaning it fails because the behavior is not implemented, not because of syntax errors or setup issues. In the Green phase, resist the urge to write more than needed. If the test asks for a specific return value, return that value. If it asks for a calculation, implement just that calculation. Over-engineering at this stage defeats the purpose of TDD. The simplest implementation that passes the test is the correct one. In the Refactor phase, look for specific improvement opportunities. Extract repeated logic into shared methods. Break large functions into smaller named pieces. Rename variables for readability. Move code to the appropriate classes. Extract magic numbers into named constants. During refactoring, run tests after each change to ensure nothing breaks. If a change causes a test failure, revert it immediately and try a different approach. The Refactor phase is where design quality emerges. TDD does not guarantee perfect design, but the short feedback loop makes it easy to iterate toward better structure. Each Red-Green-Refactor cycle produces a small increment of working, tested, clean code.'
      },
      {
        id: 'tdd-benefits', title: 'TDD Benefits and Tradeoffs',
        content: 'TDD produces several significant benefits that compound over time. Better design emerges naturally because writing tests first forces you to think about the public API before implementing. This leads to cleaner interfaces, loosely coupled components, and highly cohesive classes. Confident refactoring becomes possible because the test suite catches breakage immediately. You can improve code structure at any time without fear of introducing regressions. Living documentation results from well-written tests that show how code is intended to be used. New developers can read the test suite to understand what each class does and what inputs it expects. Fewer defects reach production because the short feedback loop catches issues early when they are cheapest to fix. However, TDD has tradeoffs. Initial development is slower because writing tests before code takes more time upfront. This investment pays off through reduced debugging and easier maintenance later, but the benefits are not immediate. The learning curve is steep for developers accustomed to writing code first. TDD requires a different mindset and discipline that takes practice to develop. Not all code is easily testable. UI rendering, complex framework integrations, and code with heavy side effects may not benefit from TDD. TDD shines for complex business logic, long-lived code, APIs used by multiple consumers, and code where correctness is critical. It is less useful for prototypes, simple CRUD operations, and throwaway code.'
      }
    ]
  },
  {
    id: 809, slug: 'testing-visual-regression', title: 'Visual Regression Testing',
    description: 'Learn how to catch unintended visual changes in your Angular application UI.',
    level: 'advanced', duration: '35 min',
    objectives: ['Understand visual regression testing', 'Set up visual testing tools', 'Implement visual regression in CI/CD'],
    quiz: [
      { id: 1, question: 'What is visual regression testing?', options: ['Testing database performance', 'Comparing screenshots to detect unintended UI changes between builds', 'Testing JavaScript logic', 'Accessibility testing'], correctIndex: 1, explanation: 'Visual regression testing captures baseline screenshots and compares them against new screenshots to detect pixel-level differences in the UI.' },
      { id: 2, question: 'What is a common challenge with visual regression testing?', options: ['It is too slow', 'Flaky tests from font rendering, animations, and dynamic content', 'It cannot test Angular', 'It requires no configuration'], correctIndex: 1, explanation: 'Visual tests can be sensitive to platform differences, font rendering, animations, and dynamic content like timestamps, requiring careful configuration of thresholds and ignores.' },
      { id: 3, question: 'What tool is commonly used for visual regression testing with Playwright?', options: ['Jasmine', 'Playwright with built-in screenshot comparison or Percy', 'Karma', 'Jest'], correctIndex: 1, explanation: 'Playwright has built-in screenshot comparison capabilities, and tools like Percy extend this with cloud-based visual testing infrastructure.' }
    ],
    topics: [
      {
        id: 'what-is-vrt', title: 'What Is Visual Regression Testing?',
        content: 'Visual regression testing catches unintended visual changes by comparing screenshots across builds. It works by capturing a baseline screenshot of each page or component in a known good state. When code changes are made, new screenshots are captured under identical conditions. The tool compares baseline and new screenshots pixel by pixel or using sophisticated comparison algorithms. Any differences are flagged for human review. Visual regression testing matters because traditional tests verify code behavior but not visual appearance. A component might return correct data while displaying it incorrectly. CSS changes might break layouts without affecting functionality. Font changes, spacing adjustments, or color modifications might create accessibility issues that functional tests miss entirely. The process follows a clear flow. First, establish baselines by capturing screenshots in a controlled environment with fixed viewport sizes and consistent rendering. When code changes, capture new screenshots and compare against baselines. Review any differences to determine if they are intentional changes or bugs. If intentional, update the baselines. If bugs, fix the code. Types of visual testing include screenshot comparison for full pages or elements, DOM snapshot testing for structure and styles, layout testing for positioning, and responsive testing across viewport sizes. Common bugs caught include broken layouts, overlapping elements, missing images, color contrast issues, and content overflow.'
      },
      {
        id: 'tools-for-vrt', title: 'Tools for Visual Regression Testing',
        content: 'Several tools are available for visual regression testing, each with different strengths. Playwright provides native screenshot comparison through toHaveScreenshot. Configure maxDiffPixelRatio to allow a small percentage of pixel differences, threshold for per-pixel color tolerance, and animations setting to disable animations for consistency. Store baseline screenshots in a snapshots directory and review diffs when tests fail. Percy by BrowserStack provides cloud-based visual testing with cross-browser comparison and team review workflows. Install the Percy CLI and Playwright integration, then use percySnapshot to capture screenshots during tests. Percy handles cross-browser comparison and provides a web interface for reviewing visual changes. Chromatic is designed for Storybook-based component testing. It captures screenshots of every story and provides a visual review interface. This approach catches visual regressions at the component level before they reach integration. BackstopJS is a standalone visual testing tool that works with any framework. It uses Puppeteer for screenshot capture and provides a reference and test report interface. When choosing a tool, consider your team size, hosting preference, and existing workflow. Playwright is free and integrates into existing test suites. Percy adds team workflows and cross-browser support. Chromatic excels for component-driven development with Storybook. Most tools support threshold configuration to handle minor rendering differences between platforms.'
      },
      {
        id: 'implementing-vrt', title: 'Implementing Visual Regression Testing',
        content: 'Setting up visual regression testing with Playwright involves configuring screenshot comparison thresholds and handling dynamic content. Configure playwright.config.ts with a snapshot directory and comparison options. Set maxDiffPixelRatio to allow a small percentage of differences for anti-aliasing and font rendering variations. Set threshold for per-pixel color tolerance. Disable animations to ensure consistent screenshots. Dynamic content like timestamps, random IDs, and user avatars must be handled to avoid false positives. Before capturing screenshots, use page.evaluate to replace dynamic content with static placeholders. Remove random elements, replace background images, and normalize text content. This ensures screenshots are deterministic across runs. Responsive visual testing captures screenshots at multiple viewport sizes. Define an array of viewport configurations with names and dimensions, then loop through them creating a test for each. Name screenshots with the viewport to differentiate them. In CI, run visual tests on pull requests to catch unintended changes before they merge. Use GitHub Actions to run Playwright tests, upload screenshot artifacts for review, and fail the build if visual differences exceed thresholds. Review visual diffs in the PR to determine if changes are intentional. Update baselines when intentional visual changes are approved. This workflow ensures visual regressions are caught early and reviewed systematically.'
      }
    ]
  },
  {
    id: 810, slug: 'testing-test-architecture', title: 'Test Architecture & Strategy',
    description: 'Design effective testing strategies and maintainable test suites for large Angular applications.',
    level: 'advanced', duration: '45 min',
    objectives: ['Design a testing strategy', 'Categorize different test types', 'Maintain a healthy test suite over time'],
    quiz: [
      { id: 1, question: 'What is the testing pyramid?', options: ['A testing tool', 'A strategy recommending many unit tests, fewer integration tests, and few e2e tests', 'A way to organize test files', 'A code coverage metric'], correctIndex: 1, explanation: 'The testing pyramid advocates for a large base of fast unit tests, a smaller layer of integration tests, and a minimal top layer of end-to-end tests.' },
      { id: 2, question: 'What is a test smell?', options: ['Tests that run slowly', 'Anti-patterns in test code that indicate maintenance or design problems', 'Tests that always fail', 'Tests without assertions'], correctIndex: 1, explanation: 'Test smells are patterns in test code that suggest problems such as brittle tests, excessive mocking, test interdependence, or unclear test intent.' },
      { id: 3, question: 'How should flaky tests be handled?', options: ['Ignore them', 'Fix or remove them immediately as they erode confidence in the test suite', 'Mark them as skipped permanently', 'Run them multiple times until they pass'], correctIndex: 1, explanation: 'Flaky tests undermine trust in the test suite. They should be investigated, fixed, or removed rather than tolerated or re-run repeatedly.' }
    ],
    topics: [
      {
        id: 'testing-pyramid', title: 'Testing Pyramid and Beyond',
        content: 'The testing pyramid is a strategic framework for deciding what types of tests to write. The base consists of many fast, focused unit tests. The middle layer contains fewer integration tests. The top has minimal end-to-end tests. Unit tests at the base verify individual functions, components, and services in isolation. They run fast, are easy to debug, and provide precise feedback about what broke. Integration tests in the middle verify that multiple units work together correctly. They catch issues that unit tests miss, such as incorrect dependency injection or data flow problems. End-to-end tests at the top simulate real user workflows through the entire application. They are slow and expensive to maintain, so they should focus on critical business paths. An alternative model is the Testing Trophy by Kent C. Dodds, which emphasizes integration tests over unit tests. The trophy suggests that integration tests provide the best return on investment because they test real user interactions while still being relatively fast. Use the pyramid as a guideline, not a rigid rule. Pure business logic gets unit tests. Component interactions get integration tests. Critical user journeys get end-to-end tests. Cross-browser compatibility gets end-to-end tests. Performance and visual testing use specialized tools. The right proportion depends on your application, team size, and risk tolerance.'
      },
      {
        id: 'test-categories', title: 'Test Categories and Scope',
        content: 'Effective test architecture requires clear categories that define what each test verifies. Component tests verify that Angular components render correctly and respond to user interactions. They use TestBed to create the component with its template and verify DOM output, input and output bindings, and event handling. Service tests verify that services perform their business logic correctly. HTTP services use HttpTestingController to mock network calls. State services verify state transitions and side effects. Pipe tests verify that pipes transform data correctly. These are typically simple unit tests with multiple input cases. Directive tests verify that directives modify host element behavior correctly. Guard and resolver tests verify navigation logic and data resolution. Use consistent naming conventions across all categories. The pattern should describe expected behavior under specific conditions. For example, should return user token when credentials are valid, should throw error when credentials are invalid. Group related tests using nested describe blocks. The outer describe names the class or feature. Inner describe blocks name the method or scenario. This organization makes it easy to find and understand tests. Document test categories in your project README so new team members understand the testing strategy. Review test categories periodically to ensure they still align with your application architecture and team practices.'
      },
      {
        id: 'test-maintenance', title: 'Test Suite Maintenance',
        content: 'A test suite is a living asset that requires ongoing maintenance. Neglected tests become a liability rather than an asset. Identify and address test smells regularly. Brittle tests break when implementation details change even if behavior remains correct. Fix them by testing behavior instead of implementation. Slow tests reduce developer productivity. Fix them by using mocks for slow dependencies, parallelizing tests, and keeping end-to-end tests focused on critical paths. Flaky tests sometimes pass and sometimes fail without code changes. Often caused by timing issues, shared state, or external dependencies. Fix them by isolating tests, using fake timers, and avoiding shared mutable state. Excessive mocking creates tests that no longer verify realistic behavior. Fix them by using integration tests instead of deeply mocked unit tests. Test duplication wastes effort and creates maintenance burden. Remove redundant tests and focus on unique scenarios. Track test suite metrics over time. Monitor total test count, pass rate, average run time, flaky rate, code coverage, and mutation score. Set thresholds and alert when metrics degrade. Refactor test code just like production code. Extract common setup into shared fixtures, create helper functions for repetitive assertions, and organize tests to mirror production code structure. Review and update tests when the code they test changes. Stale tests that no longer match the code provide false confidence and should be removed or updated.'
      }
    ]
  },
  {
    id: 811, slug: 'testing-angular-service-tests', title: 'Angular Service Testing Patterns',
    description: 'Master patterns for testing Angular services including HTTP, stateful, and RxJS services.',
    level: 'intermediate', duration: '40 min',
    objectives: ['Test HTTP services with HttpTestingController', 'Test stateful services with complex state', 'Test services that use RxJS operators'],
    quiz: [
      { id: 1, question: 'How do you test a service that makes HTTP calls?', options: ['Use real HTTP requests', 'Use HttpTestingController to intercept and mock requests', 'Use fetch API', 'Skip HTTP testing'], correctIndex: 1, explanation: 'HttpTestingController from Angular allows you to intercept HTTP requests during tests and provide mock responses without making real network calls.' },
      { id: 2, question: 'What should you always do after HTTP tests?', options: ['Log to console', 'Call httpMock.verify() to ensure no unexpected requests were made', 'Reset TestBed', 'Clear local storage'], correctIndex: 1, explanation: 'Calling httpMock.verify() in afterEach ensures that all expected HTTP requests were made and no unexpected requests slipped through.' },
      { id: 3, question: 'How do you test a service using BehaviorSubject?', options: ['It cannot be tested', 'Subscribe to the observable and verify emitted values match expected state', 'Use setTimeout', 'Use async/await only'], correctIndex: 1, explanation: 'Subscribe to the BehaviorSubject and verify that the emitted values match the expected state changes after operations are performed.' }
    ],
    topics: [
      {
        id: 'testing-http-services', title: 'Testing HTTP Services',
        content: 'HTTP services are among the most common services in Angular applications. Testing them requires intercepting network calls and providing controlled responses. Configure TestBed with provideHttpClient and provideHttpClientTesting to set up the testing HTTP backend. Inject HttpTestingController to control intercepted requests. For GET requests, call the service method, subscribe to the observable, then use httpMock.expectOne with the expected URL. Verify the request method is GET, then flush mock data using req.flush. For POST requests, verify the request body contains the expected payload before flushing the response. For DELETE requests, verify the URL includes the correct resource ID. For requests with query parameters, use a predicate function in expectOne that matches the URL pattern. Test error responses by calling req.error with a status object instead of req.flush. Subscribe to the error callback and verify the service handles it correctly. Always call httpMock.verify in an afterEach block to ensure all expected requests were made. This pattern works for all HTTP methods and provides complete control over request and response handling. Test both successful responses and various error scenarios including network failures, timeouts, and server errors.'
      },
      {
        id: 'testing-stateful-services', title: 'Testing Stateful Services',
        content: 'Stateful services manage application state and expose methods that mutate that state. Testing them requires verifying state transitions and side effects. Start by testing the initial state. After creating the service, verify all properties are in their expected initial values. Then test each method that modifies state by calling it and asserting the new state. For services that manage collections, test adding items, updating items, removing items, and clearing all items. Verify that calculations like totals, counts, and filters produce correct results after each mutation. For services that expose state as Observables, subscribe to the state stream and verify emitted values match expectations. Collect emitted values in an array and assert against the expected sequence of states. Test concurrent operations by triggering multiple state changes rapidly and verifying the final state is correct. When services depend on other services, mock the dependencies and verify the service calls them correctly. Test that state changes trigger appropriate side effects like notifications or side effects. For services using signals, test that signal values update correctly after operations. Verify computed signals derive correct values from their dependencies. Test effects that respond to signal changes by checking their side effects.'
      },
      {
        id: 'testing-rxjs-services', title: 'Testing RxJS Services',
        content: 'Services that use RxJS operators require careful testing to verify that observable pipelines produce expected results. For debounced search, use fakeAsync and tick. Subscribe to the search results observable, trigger multiple search terms with tick calls between them, then verify only the final debounced result is emitted. For switchMap behavior, start a request, trigger a second request before the first completes, and verify only the second result is emitted. The first request should be cancelled. For combined observables, use the TestScheduler to create virtual time streams. Marble testing provides a visual way to describe observable sequences using dash and parenthesis notation. For error handling, use catchError and retry operators. Test that errors are caught and retried the expected number of times before being re-thrown. Verify that the observable completes or errors as expected. For async pipe integration, test that components using async pipe display data correctly by triggering the underlying observable and calling detectChanges. Test subscription cleanup by verifying that ngOnDestroy completes subscriptions. Use takeUntil with a destroy$ subject to automatically unsubscribe. Verify the destroy$ subject completes when the service or component is destroyed. This prevents memory leaks and ensures clean test execution.'
      }
    ]
  },
  {
    id: 812, slug: 'testing-angular-component-tests', title: 'Angular Component Testing Patterns',
    description: 'Master advanced patterns for testing Angular components including outputs, inputs, and host bindings.',
    level: 'advanced', duration: '40 min',
    objectives: ['Test component outputs with event emitters', 'Test component inputs with signals and properties', 'Test host bindings and dynamic components'],
    quiz: [
      { id: 1, question: 'How do you test a component output event emitter?', options: ['Check the DOM for the event', 'Spy on the emit method and verify it was called with correct arguments', 'Use console.log', 'Test the parent component only'], correctIndex: 1, explanation: 'Spy on the EventEmitter emit method and verify it was called with the expected payload when the triggering action occurs.' },
      { id: 2, question: 'How do you test Angular signal-based inputs?', options: ['Use component.input.set(value)', 'Signals cannot be tested', 'Use HTTP mocking', 'Use fixture.whenStable()'], correctIndex: 0, explanation: 'Signal inputs can be set directly using the signal setter or through fixture.componentRef.setInput() for the test.' },
      { id: 3, question: 'What is the benefit of using OnPush change detection in tests?', options: ['Tests run faster', 'It forces explicit testing of change detection behavior', 'It eliminates the need for fixture.detectChanges()', 'It prevents testing async operations'], correctIndex: 1, explanation: 'OnPush components require explicit change detection calls, making tests more predictable and revealing when state changes should trigger re-renders.' }
    ],
    topics: [
      {
        id: 'testing-component-output', title: 'Testing Component Outputs',
        content: 'Component outputs use EventEmitters to communicate with parent components. Testing outputs verifies that the correct events are emitted with the correct data at the right time. Start by spying on the EventEmitter using jasmine.spyOn. Pass the component instance and the output property name, then chain .and to access the spy configuration. Trigger the action that should cause the emission. This might be clicking a button, calling a method, or simulating a user interaction. After triggering, assert that the spy was called with the expected payload using toHaveBeenCalledWith. For multiple emissions, verify each call separately. Test that outputs are not emitted when they should not be. For example, if a delete button should be hidden in readonly mode, verify the output is not emitted when readonly is true. Test output timing with fakeAsync. If an output is emitted after an async operation, use tick to advance time and verify the emission happens at the correct moment. For outputs with complex payloads, verify the entire payload structure using toEqual. Test that outputs emit the correct references, not just correct values, especially when the output carries object references that should match specific instances. This ensures parent components receive the exact data they expect.'
      },
      {
        id: 'testing-component-input', title: 'Testing Component Inputs',
        content: 'Testing component inputs involves setting values and verifying the component renders correctly. For signal-based inputs, use the signal setter directly on the component instance. Call the signal as a function with the new value, then call fixture.detectChanges to trigger change detection. Query the rendered DOM to verify the output matches the expected display. For traditional decorator-based inputs, use fixture.componentRef.setInput which sets the value through Angular\'s input binding mechanism. Test input changes by setting a new value and calling detectChanges again. Verify the component updates its display to reflect the new input. This ensures the component reacts correctly to dynamic data. Test default values by creating the component without setting inputs and verifying the default display. Test edge cases like empty strings, null values, zero, and very long strings. Verify the component handles these gracefully without errors. For components with multiple inputs, test combinations. Set one input while keeping others at defaults, then change multiple inputs simultaneously. Verify the component renders correctly for each combination. Test that inputs are properly typed by passing values of the expected type. Verify computed properties derived from inputs produce correct values after input changes.'
      },
      {
        id: 'testing-host-bindings', title: 'Testing Host Bindings',
        content: 'Host bindings allow components to modify their host element attributes, classes, and styles. Testing these bindings ensures the component correctly interacts with its host element. To test host class bindings, set the controlling property and call fixture.detectChanges. Query the native element and check that the expected class is present or absent using classList.contains. For example, a highlight directive that adds a class when active should verify the class appears when active is true and disappears when active is false. For host style bindings, set the controlling property and verify the native element style has the expected value. Check backgroundColor, color, or other CSS properties that the component sets dynamically. For host attribute bindings, verify that attributes like aria-label, role, tabindex, and data attributes are set correctly. Use getAttribute to check attribute values and hasAttribute to verify presence or absence. Test host listeners by dispatching events on the native element. Create a KeyboardEvent for keydown, a MouseEvent for click, or a custom event. Spy on the component method that handles the event and verify it was called. Test that host bindings respond to property changes by updating the controlling property multiple times and verifying the host element updates accordingly. This ensures the component maintains its host element state correctly throughout its lifecycle.'
      }
    ]
  }
];
