import { Lesson } from '../models/lesson.model';

export const TOOLING_LESSONS: Lesson[] = [
  {
    id: 601, slug: 'tooling-module-systems', title: 'Module Systems (CommonJS/ESM/AMD)',
    description: 'Understand how JavaScript modules evolved from IIFEs to CommonJS, AMD, and modern ES Modules.',
    level: 'beginner', duration: '25 min',
    objectives: ['Explain the differences between CommonJS, AMD, and ES Modules', 'Understand how bundlers resolve module dependencies', 'Write ES Module import/export statements correctly', 'Identify the right module system for different environments'],
    quiz: [
      { id: 1, question: 'Which module system is natively supported by browsers?', options: ['CommonJS', 'AMD', 'ES Modules', 'UMD'], correctIndex: 2, explanation: 'ES Modules (import/export) are natively supported by modern browsers without a bundler.' },
      { id: 2, question: 'What does CommonJS use to export values?', options: ['export default', 'module.exports', 'define()', 'import'], correctIndex: 1, explanation: 'CommonJS uses module.exports (or exports) to export values, commonly used in Node.js.' },
      { id: 3, question: 'What is a key difference between CommonJS and ES Modules?', options: ['CommonJS is synchronous, ESM is asynchronous', 'CommonJS is for browsers, ESM is for Node', 'CommonJS supports tree-shaking, ESM does not', 'They are identical'], correctIndex: 0, explanation: 'CommonJS loads modules synchronously (require()), while ESM uses static imports that enable asynchronous loading and tree-shaking.' }
    ],
    topics: [
      { id: 'commonjs', title: 'CommonJS', content: '**What is CommonJS?**\n\nCommonJS is a module system designed for Node.js. It uses `require()` to import and `module.exports` to export.\n\n```javascript\n// math.js (CommonJS)\nconst PI = 3.14159;\nfunction add(a, b) { return a + b; }\nmodule.exports = { PI, add };\n\n// app.js (CommonJS)\nconst { PI, add } = require(\'./math\');\nconsole.log(add(PI, 2)); // 5.14159\n```\n\n**Why it matters:**\n- Dominant in Node.js ecosystem for years\n- Modules are loaded synchronously at runtime\n- Each file is wrapped in a function scope\n\n**Common Mistakes:**\n- Trying to use CommonJS in browser without a bundler\n- Using `require()` inside ES Modules\n- Mutating `exports` instead of using `module.exports`\n\n**Best Practices:**\n- Use CommonJS for Node.js scripts and CLI tools\n- Prefer ES Modules for new Node.js projects (v12+)\n- Use `.mjs` extension or `"type": "module"` in package.json for ESM in Node\n\n**Key Takeaways:**\n1. CommonJS uses `require()` and `module.exports`\n2. It loads modules synchronously — not suitable for browsers\n3. Node.js supports ESM natively since v12 with .mjs or package.json config' },
      { id: 'esm', title: 'ES Modules (ESM)', content: '**What are ES Modules?**\n\nES Modules (ESM) is the official standard module system for JavaScript, using static `import` and `export` syntax.\n\n```javascript\n// utils.js (ESM)\nexport const PI = 3.14159;\nexport function add(a, b) { return a + b; }\nexport default class Calculator { }\n\n// app.js (ESM)\nimport Calculator, { PI, add } from \'./utils.js\';\n```\n\n**Why ESM matters:**\n- **Static analysis**: Enables tree-shaking — unused exports are removed\n- **Browser native**: Runs directly in browsers without bundlers\n- **Asynchronous loading**: Modules load in parallel\n- **Strict mode by default**: Eliminates common errors\n\n**Key Differences from CommonJS:**\n```javascript\n// CommonJS (dynamic)\nconst module = require(\'./module\');\nmodule.default ? module.default : module;\n\n// ESM (static)\nimport module from \'./module.js\';\n```\n\n**Common Mistakes:**\n- Forgetting the `.js` extension in import paths\n- Mixing `require()` and `import` in the same file\n- Not setting `"type": "module"` in package.json for Node ESM\n\n**Key Takeaways:**\n1. ESM uses static `import`/`export` for better optimization\n2. Tree-shaking only works with ES Modules\n3. Native in browsers — no bundler needed for simple apps' },
      { id: 'amd', title: 'AMD & UMD', content: '**What is AMD (Asynchronous Module Definition)?**\n\nAMD was designed for browsers to load modules asynchronously. It is primarily used with RequireJS.\n\n```javascript\n// AMD (RequireJS)\ndefine([\'jquery\', \'lodash\'], function($, _) {\n  return {\n    init: function() { _.defaults(this, { name: \'World\' }); }\n  };\n});\n```\n\n**What is UMD (Universal Module Definition)?**\n\nUMD creates modules that work in both CommonJS and AMD environments, plus as global variables.\n\n```javascript\n// UMD wrapper pattern\n(function(root, factory) {\n  if (typeof define === \'function\' && define.amd) {\n    define([], factory);\n  } else if (typeof module === \'object\' && module.exports) {\n    module.exports = factory();\n  } else {\n    root.MyLib = factory();\n  }\n})(this, function() {\n  return { version: \'1.0.0\' };\n});\n```\n\n**Why it matters:**\n- AMD solved browser module loading before ESM existed\n- UMD provides universal compatibility for libraries\n- Both are largely replaced by ESM in modern development\n\n**Key Takeaways:**\n1. AMD loads modules asynchronously — designed for browsers\n2. UMD works across CommonJS, AMD, and global contexts\n3. Both are legacy patterns; prefer ESM for new projects' },
      { id: 'module-migration', title: 'Migrating Between Module Systems', content: '**Migration Strategies:**\n\nMoving from CommonJS to ESM requires understanding both systems:\n\n```javascript\n// Before (CommonJS)\nconst express = require(\'express\');\nmodule.exports = { app: express() };\n\n// After (ESM)\nimport express from \'express\';\nexport const app = express();\n```\n\n**Step-by-Step Migration:**\n1. Add `"type": "module"` to package.json\n2. Change `require()` to `import`\n3. Change `module.exports` to `export`\n4. Add `.js` extensions to relative imports\n5. Replace `__dirname` with `import.meta.url`\n\n```javascript\n// __dirname replacement in ESM\nimport { fileURLToPath } from \'url\';\nimport { dirname } from \'path\';\nconst __filename = fileURLToPath(import.meta.url);\nconst __dirname = dirname(__filename);\n```\n\n**Common Pitfalls:**\n- Dynamic `require()` must become `await import()`\n- Circular dependencies behave differently in ESM\n- Some npm packages may not support ESM yet\n\n**Key Takeaways:**\n1. ESM migration improves tree-shaking and performance\n2. Use `"type": "module"` in package.json to enable ESM\n3. Replace `__dirname`/`__filename` with `import.meta.url` utilities' }
    ]
  },
  {
    id: 602, slug: 'tooling-package-management', title: 'Package Management (npm/yarn/pnpm)',
    description: 'Master npm, Yarn, and pnpm — dependency resolution, lockfiles, workspaces, and choosing the right package manager.',
    level: 'beginner', duration: '25 min',
    objectives: ['Compare npm, Yarn, and pnpm in terms of features and performance', 'Understand dependency resolution and lockfiles', 'Use workspaces for monorepo dependency management', 'Configure and optimize package manager settings'],
    quiz: [
      { id: 1, question: 'Which package manager uses a content-addressable store to save disk space?', options: ['npm', 'Yarn Classic', 'pnpm', 'Bun'], correctIndex: 2, explanation: 'pnpm uses a content-addressable store with symlinks, saving significant disk space compared to npm/Yarn.' },
      { id: 2, question: 'What does a lockfile (package-lock.json / yarn.lock) do?', options: ['Lists dev dependencies only', 'Pins exact dependency versions for reproducible installs', 'Compiles TypeScript dependencies', 'Optimizes bundle size'], correctIndex: 1, explanation: 'Lockfiles pin exact versions of all dependencies, ensuring every install produces the same dependency tree.' },
      { id: 3, question: 'What is the purpose of npm workspaces?', options: ['To run multiple servers simultaneously', 'To manage multiple packages in a monorepo from a single root', 'To create parallel npm registries', 'To install packages faster'], correctIndex: 1, explanation: 'Workspaces allow you to manage multiple packages from a single repository, sharing dependencies and linking local packages.' }
    ],
    topics: [
      { id: 'npm', title: 'npm (Node Package Manager)', content: '**What is npm?**\n\nnpm is the default package manager for Node.js, managing JavaScript packages via the npm registry.\n\n```bash\n# Core commands\nnpm init -y                    # Initialize package.json\nnpm install express            # Install a dependency\nnpm install --save-dev jest    # Install a dev dependency\nnpm uninstall lodash           # Remove a package\nnpm update                     # Update packages\nnpm audit                      # Security audit\n```\n\n**package.json Structure:**\n```json\n{\n  "name": "my-app",\n  "version": "1.0.0",\n  "dependencies": { "express": "^4.18.0" },\n  "devDependencies": { "jest": "^29.0.0" },\n  "scripts": {\n    "start": "node server.js",\n    "test": "jest"\n  }\n}\n```\n\n**Common Mistakes:**\n- Committing node_modules to version control\n- Using `npm install` instead of `npm ci` in CI/CD\n- Ignoring `npm audit` warnings\n\n**Key Takeaways:**\n1. Use `npm ci` in CI/CD for reproducible, faster installs\n2. Always run `npm audit` to catch security vulnerabilities\n3. Keep dependencies minimal and up to date' },
      { id: 'yarn', title: 'Yarn', content: '**What is Yarn?**\n\nYarn is an alternative package manager focused on speed, security, and reliability. It comes in Classic (v1) and Modern (Berry/v2+) versions.\n\n```bash\n# Yarn commands\nyarn init -y\nyarn add express\nyarn add --dev jest\nyarn remove lodash\nyarn install\nyarn dlx create-react-app\n```\n\n**Yarn Berry (v2+) Features:**\n```yaml\n# .yarnrc.yml\nnodeLinker: node-modules\npackageManager: yarn@3.5.0\n```\n\n**Yarn Workspaces:**\n```json\n{\n  "workspaces": ["packages/*", "apps/*"]\n}\n```\n\n**Common Mistakes:**\n- Confusing Yarn Classic (v1) commands with Yarn Berry (v2+)\n- Not committing .yarnrc.yml to version control\n\n**Key Takeaways:**\n1. Yarn Berry offers Plug\'n\'Play for zero-install and faster builds\n2. Yarn workspaces simplify monorepo dependency management\n3. Use `yarn dlx` to run packages without installing them' },
      { id: 'pnpm', title: 'pnpm (Performant npm)', content: '**What is pnpm?**\n\npnpm is a fast, disk-efficient package manager that uses a content-addressable store and symlinks to avoid duplication.\n\n```bash\n# pnpm commands\npnpm init\npnpm add express\npnpm add -D jest\npnpm remove lodash\npnpm install\npnpm -r exec jest\n```\n\n**Why pnpm is Faster and More Efficient:**\n```\nnpm:     project-a/node_modules/express  (full copy)\n         project-b/node_modules/express  (another full copy)\n\npnpm:    node_modules/.pnpm/express@4.18/  (single copy)\n         project-a/node_modules/express -> symlink\n         project-b/node_modules/express -> symlink\n```\n\n**Strict Mode:**\n- pnpm is strict by default — undeclared dependencies are inaccessible\n- Prevents phantom dependencies\n- Results in more reliable builds\n\n**Key Takeaways:**\n1. pnpm saves disk space via content-addressable storage with symlinks\n2. Strict mode prevents phantom dependency bugs\n3. Fastest package manager in benchmarks — ideal for large monorepos' },
      { id: 'workspaces', title: 'Workspaces & Monorepo Dependencies', content: '**What are Workspaces?**\n\nWorkspaces let you manage multiple packages within a single repository, sharing dependencies and linking local packages.\n\n```json\n{\n  "name": "my-monorepo",\n  "private": true,\n  "workspaces": ["packages/*"]\n}\n```\n\n```\nmy-monorepo/\n  package.json\n  packages/\n    ui-components/\n      package.json\n    utils/\n      package.json\n    app/\n      package.json\n```\n\n**Installing and Linking:**\n```bash\n# From root - installs all workspace dependencies\npnpm install\n\n# Add shared dependency to specific workspace\npnpm add lodash --filter utils\n```\n\n**Common Mistakes:**\n- Not marking root package as `"private": true` for workspaces\n- Creating circular dependencies between workspace packages\n\n**Key Takeaways:**\n1. Workspaces eliminate duplicated dependencies across packages\n2. Local packages are automatically symlinked — no publishing needed\n3. Use `--filter` or `-r` flags to run commands across workspaces' }
    ]
  },
  {
    id: 603, slug: 'tooling-version-control', title: 'Version Control (Git Workflows)',
    description: 'Learn Git fundamentals and team workflows — branching strategies, rebasing, cherry-picking, and collaborative practices.',
    level: 'beginner', duration: '30 min',
    objectives: ['Understand Git branching strategies (Git Flow, Trunk-Based)', 'Use rebasing and cherry-picking effectively', 'Write meaningful commit messages', 'Handle merge conflicts confidently'],
    quiz: [
      { id: 1, question: 'What does "git rebase" do differently from "git merge"?', options: ['Rebase creates a merge commit, merge does not', 'Rebase replays commits on top of another branch, creating a linear history', 'Rebase deletes the feature branch', 'Rebase only works on remote branches'], correctIndex: 1, explanation: 'Rebase rewrites commit history by replaying your commits on top of the target branch, creating a clean linear history.' },
      { id: 2, question: 'Which branching strategy uses short-lived feature branches merged into main?', options: ['Git Flow', 'Trunk-Based Development', 'GitLab Flow', 'Feature Branch Workflow'], correctIndex: 1, explanation: 'Trunk-Based Development uses short-lived branches (often < 1 day) that are frequently merged into main/trunk.' },
      { id: 3, question: 'What is the purpose of "git cherry-pick"?', options: ['To delete specific commits', 'To apply a specific commit from one branch to another', 'To merge all commits from a branch', 'To undo a commit'], correctIndex: 1, explanation: 'Cherry-pick applies a specific commit from one branch onto another, useful for backporting fixes.' }
    ],
    topics: [
      { id: 'branching', title: 'Branching Strategies', content: '**Git Flow:**\n```\nmain (production)\n  \u2514\u2500\u2500 develop (integration)\n       \u251c\u2500\u2500 feature/login\n       \u251c\u2500\u2500 feature/dashboard\n       \u2514\u2500\u2500 release/v1.0\n            \u2514\u2500\u2500 hotfix/fix-bug\n```\n- `main` and `develop` are long-lived branches\n- Feature branches, release branches, and hotfix branches are short-lived\n- Best for projects with scheduled releases\n\n**Trunk-Based Development:**\n```\nmain (trunk)\n  \u251c\u2500\u2500 short-lived feature branch\n  \u251c\u2500\u2500 short-lived feature branch\n  \u2514\u2500\u2500 short-lived feature branch\n```\n- Short-lived branches (< 1-2 days)\n- Continuous integration into main\n- Feature flags for incomplete features\n- Preferred by high-performing teams\n\n**Key Takeaways:**\n1. Trunk-Based Development with short-lived branches is preferred for fast delivery\n2. Feature flags let you merge incomplete features safely\n3. Choose a strategy based on your release cadence and team size' },
      { id: 'rebase', title: 'Rebasing & Interactive Rebase', content: '**Basic Rebase:**\n```bash\n# Rebase feature branch onto main\ngit checkout feature\ngit rebase main\n```\n\n**Interactive Rebase (cleanup before merge):**\n```bash\n# Rebase last 3 commits interactively\ngit rebase -i HEAD~3\n\n# Editor opens:\npick abc1234 Add login form\npick def5678 Fix typo in login\npick ghi9012 Add form validation\n\n# Squash and reorder:\npick abc1234 Add login form\nfixup def5678 Fix typo in login\nsquash ghi9012 Add form validation\n```\n\n**Common Commands:**\n```bash\ngit rebase --continue    # Continue after resolving conflicts\ngit rebase --abort       # Cancel the rebase\n```\n\n**Rebase vs Merge:**\n- Rebase: Clean linear history, but rewrites commits\n- Merge: Preserves exact history, but adds merge commits\n\n**Key Takeaways:**\n1. Use interactive rebase to clean up commits before merging\n2. Never rebase commits that have been pushed/shared\n3. Rebase creates linear history; merge preserves full history' },
      { id: 'conventional-commits', title: 'Conventional Commits', content: '**What are Conventional Commits?**\n\nA standardized commit message format that makes history readable and enables automated tooling.\n\n```\n<type>(<scope>): <description>\n\n[optional body]\n\n[optional footer]\n```\n\n**Examples:**\n```\nfeat(auth): add OAuth2 login flow\nfix(api): handle null response from user endpoint\ndocs(readme): update installation instructions\nrefactor(ui): extract Button component\nperf(bundle): reduce main bundle size by 30%\ntest(auth): add unit tests for token refresh\nchore(deps): upgrade Angular to v17\n```\n\n**Common Types:**\n- `feat`: New feature (triggers minor version bump)\n- `fix`: Bug fix (triggers patch version bump)\n- `docs`, `style`, `refactor`, `perf`, `test`, `chore`\n\n**Why It Matters:**\n- Enables automated changelogs\n- Makes `git log` scannable and meaningful\n- Integrates with semantic-release for automated versioning\n\n**Key Takeaways:**\n1. Use `feat` for features and `fix` for bugs at minimum\n2. Keep the subject line under 72 characters\n3. Conventional Commits enable automated changelogs and versioning' },
      { id: 'merge-conflicts', title: 'Handling Merge Conflicts', content: '**What Causes Conflicts?**\n\nConflicts occur when two branches modify the same lines in a file.\n\n```\n<<<<<<< HEAD\nconst timeout = 5000;\n=======\nconst timeout = 3000;\n>>>>>>> feature\n```\n\n**Resolution Steps:**\n1. Identify conflicting files: `git status`\n2. Open each file and find conflict markers\n3. Choose the correct version (or combine both)\n4. Remove conflict markers\n5. Stage resolved files: `git add <file>`\n6. Continue: `git merge --continue` or `git rebase --continue`\n\n**Preventing Conflicts:**\n```bash\n# Pull with rebase to avoid unnecessary merge commits\ngit pull --rebase origin main\n\n# Use rerere to remember conflict resolutions\ngit config --global rerere.enabled true\n```\n\n**Common Mistakes:**\n- Leaving conflict markers in committed code\n- Resolving conflicts without understanding both changes\n- Not testing after resolving conflicts\n\n**Key Takeaways:**\n1. Use `git pull --rebase` to minimize merge commits\n2. Always verify your changes compile and tests pass after resolving conflicts\n3. `rerere` (reuse recorded resolution) helps with recurring conflicts' }
    ]
  },
  {
    id: 604, slug: 'tooling-command-line', title: 'Command Line Basics',
    description: 'Essential terminal and command-line skills for modern frontend development — navigation, scripting, and automation.',
    level: 'beginner', duration: '20 min',
    objectives: ['Navigate the filesystem using terminal commands', 'Chain commands with pipes and redirects', 'Write and run shell scripts', 'Use environment variables from the command line'],
    quiz: [
      { id: 1, question: 'What does the "pipe" operator (|) do in a shell command?', options: ['Runs two commands simultaneously', 'Redirects output of one command as input to another', 'Creates a new file', 'Deletes the output file'], correctIndex: 1, explanation: 'The pipe operator (|) takes the stdout of the left command and passes it as stdin to the right command.' },
      { id: 2, question: 'How do you set an environment variable for a single command on macOS/Linux?', options: ['Set VAR=value && command', 'VAR=value command', 'env VAR=value command', 'Both B and C'], correctIndex: 3, explanation: 'Both "VAR=value command" and "env VAR=value command" set env vars for a single command.' },
      { id: 3, question: 'What does "chmod +x script.sh" do?', options: ['Executes the script', 'Makes the script file executable', 'Encrypts the script', 'Moves the script to PATH'], correctIndex: 1, explanation: 'chmod +x adds execute permission to the file, allowing it to be run as a script.' }
    ],
    topics: [
      { id: 'navigation', title: 'Filesystem Navigation', content: '**Essential Navigation Commands:**\n```bash\npwd                         # Print working directory\nls -la                      # List all files with details\ncd /path/to/dir            # Change directory\ncd ..                       # Go up one directory\ncd ~                        # Go to home directory\nmkdir -p src/app/components # Create nested directories\nrmdir empty-dir             # Remove empty directory\nrm -rf dir                  # Remove directory and contents (careful!)\n```\n\n**File Operations:**\n```bash\ncp source.txt dest.txt      # Copy file\ncp -r src/ dest/            # Copy directory recursively\nmv old.txt new.txt          # Move/rename file\ntouch newfile.ts            # Create empty file\nfind . -name "*.ts" -type f # Find TypeScript files\n```\n\n**Common Mistakes:**\n- Using `rm -rf /` — destroys everything\n- Not quoting paths with spaces\n\n**Key Takeaways:**\n1. `ls -la` shows hidden files and permissions\n2. `find . -name "*.ext"` is essential for searching codebases\n3. Always double-check before using `rm -rf`' },
      { id: 'pipes', title: 'Pipes, Redirects & Chaining', content: '**Piping Output:**\n```bash\ncat package.json | grep "version" | head -1\nls -la | grep ".ts$"\ngit log --oneline | head -10\n```\n\n**Redirects:**\n```bash\ncommand > file.txt           # Write stdout to file (overwrite)\ncommand >> file.txt          # Append stdout to file\ncommand 2> errors.txt        # Redirect stderr to file\ncommand > out.txt 2>&1       # Redirect both stdout and stderr\n```\n\n**Command Chaining:**\n```bash\ncommand1 && command2         # Run command2 only if command1 succeeds\ncommand1 || command2         # Run command2 only if command1 fails\ncommand1 ; command2          # Run both regardless of success\n```\n\n**Practical Examples:**\n```bash\n# Kill process on port 3000\nlsof -ti:3000 | xargs kill -9\n\n# Count TypeScript files\nfind . -name "*.ts" | wc -l\n```\n\n**Key Takeaways:**\n1. `&&` chains commands conditionally; `;` runs them unconditionally\n2. Pipe (|) passes output between commands — powerful for text processing\n3. `2>&1` combines stderr with stdout for complete output capture' },
      { id: 'env-variables', title: 'Environment Variables', content: '**What are Environment Variables?**\n\nEnvironment variables store configuration values outside your code.\n\n```bash\n# View all environment variables\nenv\n\n# Set for current session\nexport API_URL=https://api.example.com\n\n# Set for a single command\nNODE_ENV=production npm run build\n```\n\n**Using in Node.js:**\n```javascript\nconst apiUrl = process.env.API_URL;\nconst nodeEnv = process.env.NODE_ENV || \'development\';\n```\n\n**.env Files (use with dotenv):**\n```bash\n# .env\nAPI_URL=https://api.example.com\nDB_HOST=localhost\nSECRET_KEY=abc123\n```\n\n**Common Mistakes:**\n- Committing .env files with secrets to version control\n- Not adding .env to .gitignore\n- Hardcoding secrets in source code\n\n**Key Takeaways:**\n1. Never commit secrets to version control — use .env files\n2. Always add .env to .gitignore\n3. Use env vars for environment-specific configuration' },
      { id: 'shell-scripts', title: 'Shell Scripting Basics', content: '**Writing Your First Script:**\n```bash\n#!/bin/bash\n# build.sh\n\nset -e  # Exit on error\n\necho "Starting build..."\nnpm run lint\nnpm run test\nnpm run build\necho "Build complete!"\n```\n\n**Variables and Conditionals:**\n```bash\n#!/bin/bash\nENV=${1:-development}\n\nif [ "$ENV" = "production" ]; then\n  echo "Building for production..."\n  npm run build:prod\nelse\n  echo "Building for development..."\n  npm run build:dev\nfi\n```\n\n**Making Scripts Executable:**\n```bash\nchmod +x build.sh\n./build.sh production\n```\n\n**Key Takeaways:**\n1. Always use `set -e` to exit on first error\n2. Use `${VAR:-default}` for default variable values\n3. Package.json scripts are preferred over shell scripts in JS projects' }
    ]
  },
  {
    id: 605, slug: 'tooling-ide-setup', title: 'IDE Setup & Productivity',
    description: 'Configure VS Code for maximum productivity — extensions, settings, debugging, and workspace configuration for Angular development.',
    level: 'beginner', duration: '25 min',
    objectives: ['Configure VS Code with essential Angular extensions', 'Set up debugging configurations', 'Use workspace-specific settings for team consistency', 'Leverage keyboard shortcuts and productivity features'],
    quiz: [
      { id: 1, question: 'What is the purpose of .vscode/settings.json in a project?', options: ['It defines the VS Code version to use', 'It shares team-wide editor settings that override user defaults', 'It stores API keys for extensions', 'It configures the TypeScript compiler'], correctIndex: 1, explanation: '.vscode/settings.json shares project-specific editor configurations, ensuring all team members use consistent settings.' },
      { id: 2, question: 'Which VS Code extension is essential for Angular development?', options: ['Prettier', 'Angular Language Service', 'ESLint', 'GitLens'], correctIndex: 1, explanation: 'Angular Language Service provides IntelliSense, error checking, and navigation for Angular templates and components.' },
      { id: 3, question: 'What does "editor.formatOnSave" do?', options: ['Saves the file automatically', 'Runs the formatter when you save', 'Formats on auto-save only', 'Enables auto-save'], correctIndex: 1, explanation: 'formatOnSave automatically runs the configured formatter (like Prettier) every time you save a file.' }
    ],
    topics: [
      { id: 'extensions', title: 'Essential Extensions', content: '**Angular Development Stack:**\n- **Angular Language Service** — IntelliSense, error checking, go-to-definition for templates\n- **ESLint** — Real-time linting feedback in the editor\n- **Prettier** — Automatic code formatting\n- **GitLens** — Enhanced Git integration (blame, history, diff)\n\n**Productivity Extensions:**\n- **Error Lens** — Inline error display next to code\n- **Import Cost** — Shows bundle size impact of imports\n- **REST Client** — Test APIs directly in VS Code\n\n**Recommended Settings (.vscode/extensions.json):**\n```json\n{\n  "recommendations": [\n    "angular.ng-template",\n    "dbaeumer.vscode-eslint",\n    "esbenp.prettier-vscode",\n    "eamodio.gitlens",\n    "usernamehw.errorlens"\n  ]\n}\n```\n\n**Key Takeaways:**\n1. Angular Language Service is the most important extension for Angular dev\n2. Use .vscode/extensions.json to recommend extensions to your team\n3. Error Lens makes debugging faster by showing errors inline' },
      { id: 'settings', title: 'Workspace Settings', content: '**.vscode/settings.json (Team Shared):**\n```json\n{\n  "editor.formatOnSave": true,\n  "editor.defaultFormatter": "esbenp.prettier-vscode",\n  "editor.codeActionsOnSave": {\n    "source.fixAll.eslint": "explicit"\n  },\n  "editor.tabSize": 2,\n  "editor.minimap.enabled": false,\n  "files.trimTrailingWhitespace": true,\n  "files.insertFinalNewline": true,\n  "typescript.tsdk": "node_modules/typescript/lib"\n}\n```\n\n**Key Settings Explained:**\n- `typescript.tsdk`: Points to project\'s TypeScript version (prevents version conflicts)\n- `editor.codeActionsOnSave`: Auto-fixes ESLint issues on save\n- `files.trimTrailingWhitespace`: Removes trailing spaces automatically\n\n**Key Takeaways:**\n1. Always set "typescript.tsdk" to the project\'s TypeScript version\n2. Commit .vscode/settings.json and .vscode/extensions.json to version control\n3. Keep personal preferences in user settings, not workspace settings' },
      { id: 'debugging', title: 'Debugging Configuration', content: '**launch.json for Angular Debugging:**\n```json\n{\n  "version": "0.2.0",\n  "configurations": [\n    {\n      "type": "chrome",\n      "request": "launch",\n      "name": "Launch Chrome",\n      "url": "http://localhost:4200",\n      "webRoot": "${workspaceFolder}"\n    },\n    {\n      "type": "node",\n      "request": "launch",\n      "name": "Debug Jest",\n      "program": "${workspaceFolder}/node_modules/.bin/jest",\n      "args": ["--runInBand", "--coverage", "${file}"],\n      "console": "integratedTerminal"\n    }\n  ]\n}\n```\n\n**Debugging Workflow:**\n1. Set breakpoints in VS Code by clicking the gutter\n2. Start the debugger with F5 or the Run panel\n3. Use the Debug Console to inspect variables\n\n**Key Takeaways:**\n1. Chrome debugging with sourcemaps lets you debug TypeScript directly\n2. Source map path overrides ensure breakpoints align correctly\n3. Jest debugging config allows stepping through test code' },
      { id: 'shortcuts', title: 'Keyboard Shortcuts & Snippets', content: '**Essential Angular Dev Shortcuts:**\n```\nCmd+Shift+P         Command Palette\nCmd+P               Quick file open\nCmd+Shift+F         Search across files\nCmd+.               Quick fix / code actions\nF12                 Go to definition\nAlt+F12             Peek definition\nShift+Alt+F         Format document\nCmd+/               Toggle line comment\nCmd+Shift+K         Delete line\nAlt+Up/Down         Move line up/down\nCmd+D               Select next occurrence\n```\n\n**Snippets (Angular):**\n```json\n{\n  "Angular Component": {\n    "prefix": "ng-comp",\n    "body": [\n      "import { Component } from \'@angular/core\';",\n      "",\n      "@Component({",\n      "  selector: \'app-$1\',",\n      "  templateUrl: \'./$1.component.html\'",\n      "})",\n      "export class ${1:ComponentName}Component {}"\n    ]\n  }\n}\n```\n\n**Key Takeaways:**\n1. Master Cmd+Shift+P (Command Palette) — access everything from there\n2. Cmd+D to select multiple occurrences for bulk editing\n3. Custom snippets dramatically speed up boilerplate creation' }
    ]
  },
  {
    id: 606, slug: 'tooling-vite-deep-dive', title: 'Vite Deep Dive',
    description: 'Understand Vite\'s architecture — ESM-powered dev server, Rollup-based builds, plugin system, and performance advantages.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Explain how Vite achieves near-instant dev server startup', 'Configure Vite for Angular and other frameworks', 'Understand the difference between dev and production builds', 'Write custom Vite plugins'],
    quiz: [
      { id: 1, question: 'Why is Vite faster than Webpack in development?', options: ['It uses a different JavaScript engine', 'It uses native ESM — no bundling needed during dev', 'It caches more aggressively', 'It uses Rust instead of JavaScript'], correctIndex: 1, explanation: 'Vite leverages native ES Modules in the browser during dev, avoiding the need to bundle the entire application before serving.' },
      { id: 2, question: 'What does Vite use for production builds?', options: ['esbuild only', 'Rollup', 'Webpack', 'SWC'], correctIndex: 1, explanation: 'Vite uses Rollup for production builds, providing optimized chunking, tree-shaking, and code splitting.' },
      { id: 3, question: 'How do you add a Vite plugin?', options: ['In angular.json', 'In vite.config.ts via the plugins array', 'In package.json scripts', 'Via a CLI flag only'], correctIndex: 1, explanation: 'Plugins are added to the plugins array in vite.config.ts.' }
    ],
    topics: [
      { id: 'vite-architecture', title: 'Vite Architecture', content: '**How Vite Works:**\n\nVite has two main parts:\n1. **Dev Server** — Uses native ESM, no bundling during development\n2. **Build** — Uses Rollup for optimized production builds\n\n```typescript\n// vite.config.ts\nimport { defineConfig } from \'vite\';\nimport angular from \'@analogjs/vite-plugin-angular\';\n\nexport default defineConfig({\n  plugins: [angular()],\n  server: {\n    port: 4200,\n    open: true\n  },\n  build: {\n    target: \'esnext\',\n    outDir: \'dist\'\n  }\n});\n```\n\n**Dev Server Flow:**\n```\nBrowser request -> Vite Dev Server -> Transform on-demand -> Native ESM\n(no bundling step)\n```\n\n**Why It\'s Fast:**\n- No bundling in dev — browsers load modules directly\n- esbuild for dependency pre-bundling (10-100x faster than JS-based tools)\n- On-demand transformation — only transform files the browser requests\n- HMR stays fast regardless of app size\n\n**Key Takeaways:**\n1. Vite skips bundling in dev — uses native ESM for instant startup\n2. Rollup handles production builds with optimization\n3. esbuild pre-bundles node_modules dependencies 10-100x faster' },
      { id: 'vite-plugins', title: 'Vite Plugin System', content: '**Plugin Hooks:**\n```typescript\nimport { Plugin } from \'vite\';\n\nexport default function myPlugin(): Plugin {\n  return {\n    name: \'my-plugin\',\n    transform(code, id) {\n      if (id.endsWith(\'.custom\')) {\n        return transformCustomFile(code);\n      }\n    },\n    transformIndexHtml(html) {\n      return html.replace(\'</body>\', \'<script>console.log("injected")</script></body>\');\n    },\n    configureServer(server) {\n      server.middlewares.use(\'/api\', (req, res) => {\n        res.end(JSON.stringify({ hello: \'world\' }));\n      });\n    }\n  };\n}\n```\n\n**Popular Plugins:**\n- `@vitejs/plugin-react` — React Fast Refresh\n- `vite-plugin-checker` — TypeScript/ESLint overlay\n- `vite-plugin-compression` — Gzip/Brotli compression\n\n**Key Takeaways:**\n1. Vite plugins use the Rollup plugin API with additional Vite hooks\n2. configureServer lets you add middleware to the dev server\n3. transformIndexHtml enables HTML injection and modification' },
      { id: 'vite-env', title: 'Environment Variables & Mode', content: '**Environment Variables in Vite:**\n```bash\n# .env              - Loaded in all cases\n# .env.local        - Loaded in all cases, ignored by git\n# .env.[mode]       - Only loaded in specified mode\n# .env.[mode].local  - Only loaded in mode, ignored by git\n```\n\n**Accessing Variables:**\n```typescript\n// Only VITE_ prefixed variables are exposed to client code\nconst apiUrl = import.meta.env.VITE_API_URL;\nconst mode = import.meta.env.MODE;\nconst isDev = import.meta.env.DEV;\nconst isProd = import.meta.env.PROD;\n```\n\n**HTML Environment Injection:**\n```html\n<script type="module">\n  console.log(import.meta.env.VITE_API_URL);\n</script>\n```\n\n**Key Takeaways:**\n1. Only variables prefixed with VITE_ are exposed to the browser\n2. Use .env.[mode] files for environment-specific configuration\n3. import.meta.env replaces process.env in Vite projects' },
      { id: 'vite-perf', title: 'Performance Optimization', content: '**Dependency Pre-Bundling:**\n```typescript\n// vite.config.ts\nexport default defineConfig({\n  optimizeDeps: {\n    include: [\'lodash-es\', \'moment\'],\n    exclude: [\'your-local-package\']\n  }\n});\n```\n\n**Code Splitting:**\n```typescript\n// Manual chunk splitting\nexport default defineConfig({\n  build: {\n    rollupOptions: {\n      output: {\n        manualChunks: {\n          vendor: [\'react\', \'react-dom\'],\n          utils: [\'lodash-es\', \'date-fns\']\n        }\n      }\n    }\n  }\n});\n```\n\n**Build Optimization Tips:**\n- Use `build.target` to specify browser support level\n- Enable CSS code splitting with `build.cssCodeSplit: true`\n- Use dynamic imports for route-based code splitting\n- Analyze bundle with `rollup-plugin-visualizer`\n\n**Common Mistakes:**\n- Setting target too low (e.g., es5) when modern browsers are the audience\n- Not analyzing bundle size before production\n- Including large dependencies in the main bundle\n\n**Key Takeaways:**\n1. Pre-bundle large dependencies for faster dev startup\n2. Use manualChunks to control code splitting in production\n3. Analyze bundles regularly to catch size regressions' }
    ]
  },
  {
    id: 607, slug: 'tooling-webpack', title: 'Webpack Configuration',
    description: 'Master Webpack configuration — loaders, plugins, code splitting, and migration strategies to modern alternatives.',
    level: 'intermediate', duration: '35 min',
    objectives: ['Configure loaders and plugins for a modern Angular/React project', 'Set up code splitting and dynamic imports', 'Optimize build performance with caching and parallelization', 'Plan a migration from Webpack to Vite'],
    quiz: [
      { id: 1, question: 'What is the difference between a loader and a plugin in Webpack?', options: ['Loaders transform files, plugins perform broader tasks on the build', 'They are the same thing', 'Plugins transform files, loaders perform build tasks', 'Loaders are for CSS, plugins are for JS'], correctIndex: 0, explanation: 'Loaders transform individual files (e.g., TypeScript to JS), while plugins hook into the build lifecycle for broader tasks.' },
      { id: 2, question: 'What does "tree-shaking" do in Webpack?', options: ['Removes unused exports from bundles', 'Shakes the dependency tree visualization', 'Optimizes image assets', 'Reduces CSS file size'], correctIndex: 0, explanation: 'Tree-shaking analyzes import/export usage and eliminates dead code that is never referenced in the final bundle.' },
      { id: 3, question: 'Which Webpack feature enables caching between builds?', options: ['cache', 'persistentCaching', 'filesystem cache', 'Both A and C'], correctIndex: 3, explanation: 'Webpack 5 supports both the "cache" option and filesystem caching for faster subsequent builds.' }
    ],
    topics: [
      { id: 'webpack-loaders', title: 'Loaders & Rules', content: '**What are Loaders?**\n\nLoaders transform non-JavaScript files into valid Webpack modules.\n\n```javascript\n// webpack.config.js\nmodule.exports = {\n  module: {\n    rules: [\n      {\n        test: /\\.tsx?$/,\n        use: \'ts-loader\',\n        exclude: /node_modules/\n      },\n      {\n        test: /\\.css$/,\n        use: [\'style-loader\', \'css-loader\']\n      },\n      {\n        test: /\\.scss$/,\n        use: [\'style-loader\', \'css-loader\', \'sass-loader\']\n      },\n      {\n        test: /\\.(png|jpg|gif)$/,\n        type: \'asset/resource\'\n      }\n    ]\n  }\n};\n```\n\n**Loader Execution Order:**\n- Loaders execute right-to-left: `sass-loader` -> `css-loader` -> `style-loader`\n\n**Key Takeaways:**\n1. Loaders transform files during the build process\n2. Execution order is right-to-left (last loader runs first)\n3. Webpack 5 uses asset modules instead of file-loader/raw-loader' },
      { id: 'webpack-plugins', title: 'Plugins', content: '**What are Plugins?**\n\nPlugins extend Webpack\'s functionality across the entire build lifecycle.\n\n```javascript\nconst HtmlWebpackPlugin = require(\'html-webpack-plugin\');\nconst MiniCssExtractPlugin = require(\'mini-css-extract-plugin\');\nconst { BundleAnalyzerPlugin } = require(\'webpack-bundle-analyzer\');\n\nmodule.exports = {\n  plugins: [\n    new HtmlWebpackPlugin({\n      template: \'./src/index.html\'\n    }),\n    new MiniCssExtractPlugin({\n      filename: \'[name].[contenthash].css\'\n    }),\n    new BundleAnalyzerPlugin()  // Visualize bundle size\n  ]\n};\n```\n\n**Common Plugins:**\n- `HtmlWebpackPlugin` — Generates HTML with injected script tags\n- `MiniCssExtractPlugin` — Extracts CSS into separate files\n- `TerserPlugin` — Minifies JavaScript\n- `DefinePlugin` — Defines global constants\n\n**Key Takeaways:**\n1. Plugins handle tasks that loaders cannot (HTML generation, CSS extraction)\n2. Use DefinePlugin to inject environment variables\n3. BundleAnalyzerPlugin is essential for bundle size analysis' },
      { id: 'webpack-caching', title: 'Build Caching & Performance', content: '**Webpack 5 Caching:**\n```javascript\nmodule.exports = {\n  cache: {\n    type: \'filesystem\',\n    buildDependencies: {\n      config: [__filename]\n    }\n  }\n};\n```\n\n**Performance Optimizations:**\n```javascript\nmodule.exports = {\n  optimization: {\n    splitChunks: {\n      chunks: \'all\',\n      cacheGroups: {\n        vendor: {\n          test: /[\\\\/]node_modules[\\\\/]/,\n          name: \'vendor\',\n          chunks: \'all\'\n        }\n      }\n    },\n    usedExports: true  // Enable tree-shaking\n  }\n};\n```\n\n**Build Speed Tips:**\n- Use `cache: { type: "filesystem" }` for faster rebuilds\n- Set `resolve.extensions` to limit file resolution\n- Use `include` in loader rules to reduce file scanning\n- Consider `thread-loader` for CPU-intensive tasks\n\n**Key Takeaways:**\n1. Filesystem caching dramatically speeds up subsequent builds\n2. splitChunks separates vendor code for better caching\n3. Limit loader scope with include/exclude to reduce build time' }
    ]
  },
  {
    id: 608, slug: 'tooling-swc-babel', title: 'SWC & Babel',
    description: 'Understand modern JavaScript transpilation — how Babel and SWC transform your code, and when to use each.',
    level: 'intermediate', duration: '25 min',
    objectives: ['Explain the role of transpilers in the JavaScript build pipeline', 'Configure SWC for faster compilation', 'Compare SWC and Babel performance and feature sets', 'Set up custom transforms for code transformation'],
    quiz: [
      { id: 1, question: 'Why is SWC significantly faster than Babel?', options: ['SWC uses a simpler plugin API', 'SWC is written in Rust, leveraging native performance', 'SWC only handles TypeScript, not JavaScript', 'SWC uses WebAssembly for speed'], correctIndex: 1, explanation: 'SWC is written in Rust, which gives it native performance advantages over Babel\'s JavaScript-based transpilation.' },
      { id: 2, question: 'What is the primary role of a transpiler like Babel or SWC?', options: ['Bundle multiple files into one', 'Transform modern syntax into compatible JavaScript', 'Minify code for production', 'Run tests on the codebase'], correctIndex: 1, explanation: 'Transpilers convert newer JavaScript/TypeScript syntax into older, more widely supported JavaScript.' },
      { id: 3, question: 'What is @swc/core primarily used for?', options: ['Runtime execution', 'Compile-time transformation of TypeScript and modern JavaScript', 'Package management', 'API mocking'], correctIndex: 1, explanation: '@swc/core provides fast compilation, minification, and bundling capabilities as a Babel alternative.' }
    ],
    topics: [
      { id: 'babel-overview', title: 'Babel Overview', content: '**What is Babel?**\n\nBabel is a JavaScript compiler that transforms modern syntax into backward-compatible JavaScript.\n\n```javascript\n// babel.config.json\n{\n  "presets": [\n    ["@babel/preset-env", {\n      "targets": "> 0.25%, not dead"\n    }],\n    "@babel/preset-typescript"\n  ],\n  "plugins": [\n    ["@babel/plugin-proposal-decorators", { "legacy": true }]\n  ]\n}\n```\n\n**How Babel Works:**\n1. **Parse** — Convert source code to AST (Abstract Syntax Tree)\n2. **Transform** — Apply plugins to modify the AST\n3. **Generate** — Convert modified AST back to code\n\n**Key Takeaways:**\n1. Babel parses, transforms, and generates JavaScript\n2. Presets bundle related plugins (e.g., @babel/preset-env)\n3. Plugins run in order — plugin ordering matters' },
      { id: 'swc-overview', title: 'SWC Overview', content: '**What is SWC?**\n\nSWC (Speedy Web Compiler) is a super-fast TypeScript/JavaScript compiler written in Rust.\n\n```json\n// .swcrc\n{\n  "jsc": {\n    "parser": {\n      "syntax": "typescript",\n      "decorators": true,\n      "tsx": true\n    },\n    "transform": {\n      "legacyDecorator": true,\n      "decoratorMetadata": true\n    },\n    "target": "es2022"\n  },\n  "minify": true\n}\n```\n\n**SWC Features:**\n- TypeScript/JSX/ECMAScript compilation\n- Built-in minification\n- Fast refresh for React\n- Decorator support (Angular compatible)\n\n**Why Choose SWC Over Babel:**\n- 20-70x faster compilation\n- Drop-in Babel replacement in many tools\n- Smaller bundle size\n- Native Rust performance\n\n**Key Takeaways:**\n1. SWC is 20-70x faster than Babel for the same tasks\n2. SWC supports TypeScript, JSX, and decorators natively\n3. Many tools (Next.js, Vite) now use SWC by default' },
      { id: 'swc-vs-babel', title: 'SWC vs Babel Comparison', content: '**Feature Comparison:**\n```\nFeature              | Babel           | SWC\n---------------------|-----------------|------------------\nLanguage             | JavaScript      | Rust\nSpeed                | Baseline        | 20-70x faster\nPlugin Ecosystem     | Huge (thousands)| Growing (Rust)\nTypeScript Support   | Via preset      | Native\nMinification         | Via Terser      | Built-in\nDecorators           | Via plugin      | Built-in\nConfiguration        | Complex         | Simple\n```\n\n**Migration Example (Webpack):**\n```javascript\n// Before: babel-loader\n{\n  test: /\\.tsx?$/,\n  use: \'babel-loader\'\n}\n\n// After: swc-loader\n{\n  test: /\\.tsx?$/,\n  use: \'swc-loader\'\n}\n```\n\n**When to Use Babel:**\n- Need very specific transforms not available in SWC\n- Custom Babel plugins are critical to your pipeline\n- Legacy browser support requires granular control\n\n**Key Takeaways:**\n1. SWC is the preferred choice for new projects (speed advantage)\n2. Babel is still valuable for its massive plugin ecosystem\n3. Migration from Babel to SWC is usually straightforward' }
    ]
  },
  {
    id: 609, slug: 'tooling-eslint-prettier', title: 'ESLint & Prettier',
    description: 'Set up and configure ESLint for code quality and Prettier for consistent formatting in Angular and JavaScript projects.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Configure ESLint with TypeScript and Angular rules', 'Set up Prettier for consistent code formatting', 'Integrate ESLint and Prettier to work together', 'Create custom rules and formatters for team needs'],
    quiz: [
      { id: 1, question: 'What is the main difference between ESLint and Prettier?', options: ['They do the same thing', 'ESLint finds and fixes code issues, Prettier formats code style', 'ESLint is for TypeScript, Prettier is for JavaScript', 'Prettier is faster than ESLint'], correctIndex: 1, explanation: 'ESLint focuses on code quality (catching bugs, enforcing patterns), while Prettier focuses solely on code formatting (indentation, spacing, line length).' },
      { id: 2, question: 'Which package prevents ESLint and Prettier from conflicting?', options: ['eslint-config-prettier', 'eslint-plugin-prettier', 'prettier-eslint', 'stylelint'], correctIndex: 0, explanation: 'eslint-config-prettier disables ESLint rules that conflict with Prettier, letting Prettier handle formatting.' },
      { id: 3, question: 'What does the "extends" field do in .eslintrc?', options: ['Adds new files to lint', 'Inherits configuration from shared configs or plugins', 'Extends the TypeScript compiler options', 'Adds new ESLint plugins'], correctIndex: 1, explanation: 'The "extends" field lets you inherit from shared configurations like @typescript-eslint/recommended or angular-eslint/recommended.' }
    ],
    topics: [
      { id: 'eslint-config', title: 'ESLint Configuration', content: '**Modern Flat Config (eslint.config.js):**\n```javascript\nimport js from "@eslint/js";\nimport tseslint from "typescript-eslint";\nimport angular from "angular-eslint";\n\nexport default tseslint.config(\n  js.configs.recommended,\n  ...tseslint.configs.recommended,\n  ...angular.configs.templateRecommended,\n  {\n    rules: {\n      "@typescript-eslint/no-explicit-any": "warn",\n      "@typescript-eslint/explicit-function-return-type": "off",\n      "no-console": ["warn", { allow: ["warn", "error"] }]\n    }\n  }\n);\n```\n\n**Key Rules to Configure:**\n- `@typescript-eslint/no-explicit-any` — Warn on `any` usage\n- `no-unused-vars` — Catch unused imports and variables\n- `eqeqeq` — Enforce strict equality\n- `no-console` — Prevent console.log in production\n\n**Key Takeaways:**\n1. Use flat config (eslint.config.js) for new projects\n2. Start with recommended configs and customize from there\n3. Use "warn" instead of "error" for rules you are gradually adopting' },
      { id: 'prettier-config', title: 'Prettier Configuration', content: '**.prettierrc Configuration:**\n```json\n{\n  "semi": true,\n  "trailingComma": "all",\n  "singleQuote": true,\n  "printWidth": 100,\n  "tabWidth": 2,\n  "useTabs": false,\n  "bracketSpacing": true,\n  "arrowParens": "always"\n}\n```\n\n**.prettierignore:**\n```\nnode_modules\ndist\nbuild\ncoverage\n*.min.js\n```\n\n**Editor Integration:**\n```json\n// .vscode/settings.json\n{\n  "editor.defaultFormatter": "esbenp.prettier-vscode",\n  "editor.formatOnSave": true\n}\n```\n\n**Key Takeaways:**\n1. Prettier is opinionated — configure once and stop debating style\n2. Use .prettierignore to exclude generated files\n3. Always pair with editor integration for auto-formatting on save' },
      { id: 'eslint-prettier-integration', title: 'ESLint + Prettier Integration', content: '**Why Integrate?**\n\nWithout integration, ESLint formatting rules and Prettier can conflict, causing confusing errors.\n\n**Setup:**\n```bash\nnpm install --save-dev eslint-config-prettier eslint-plugin-prettier\n```\n\n```javascript\n// eslint.config.js\nimport prettier from "eslint-config-prettier";\nimport prettierPlugin from "eslint-plugin-prettier";\n\nexport default [\n  // ... other configs\n  prettier,  // Disables conflicting ESLint rules\n  {\n    plugins: { prettier: prettierPlugin },\n    rules: {\n      "prettier/prettier": "error"\n    }\n  }\n];\n```\n\n**How It Works:**\n1. `eslint-config-prettier` turns off ESLint rules that conflict with Prettier\n2. `eslint-plugin-prettier` runs Prettier as an ESLint rule\n3. Formatting issues appear as ESLint errors in your editor\n\n**Best Approach:**\n- Run Prettier separately (format on save)\n- Use eslint-config-prettier only to disable conflicts\n- Do NOT use eslint-plugin-prettier (it slows down linting)\n\n**Key Takeaways:**\n1. Use eslint-config-prettier to disable conflicting rules\n2. Prefer running Prettier directly rather than as an ESLint plugin\n3. Format on save eliminates formatting discussions in code review' }
    ]
  },
  {
    id: 610, slug: 'tooling-module-federation', title: 'Module Federation',
    description: 'Learn about Module Federation — sharing code between independently deployed applications at runtime.',
    level: 'intermediate', duration: '30 min',
    objectives: ['Explain how Module Federation enables micro-frontends', 'Configure Module Federation in a Webpack or Vite project', 'Share dependencies between federated modules', 'Handle versioning and deployment of federated modules'],
    quiz: [
      { id: 1, question: 'What is Module Federation primarily used for?', options: ['File compression', 'Sharing code between independently deployed applications at runtime', 'Database connection pooling', 'CSS-in-JS styling'], correctIndex: 1, explanation: 'Module Federation allows multiple applications to share code at runtime, enabling micro-frontend architectures.' },
      { id: 2, question: 'What are "remotes" in Module Federation?', options: ['Remote servers', 'Applications that provide federated modules to other applications', 'External APIs', 'Cloud storage providers'], correctIndex: 1, explanation: 'Remotes are applications that expose modules (components, utilities) that other applications (hosts) can consume at runtime.' },
      { id: 3, question: 'What is a "host" in Module Federation?', options: ['The CI/CD server', 'The application that consumes federated modules from remotes', 'The database host', 'The production server'], correctIndex: 1, explanation: 'The host (or shell) is the application that loads and consumes modules from remote federated applications.' }
    ],
    topics: [
      { id: 'mf-concepts', title: 'Core Concepts', content: '**What is Module Federation?**\n\nModule Federation (by Webpack author Zack Jackson) allows multiple independently built and deployed applications to share code at runtime.\n\n**Key Terms:**\n- **Host (Shell)**: The application that consumes remote modules\n- **Remote**: The application that provides modules to the host\n- **Shared**: Dependencies used by both host and remotes (e.g., React, Angular)\n\n**Architecture:**\n```\nHost App (Port 3000)\n  \u251c\u2500\u2500 Loads Remote1 components (Port 3001)\n  \u251c\u2500\u2500 Loads Remote2 components (Port 3002)\n  \u2514\u2500\u2500 Shares React/Angular runtime\n```\n\n**Key Takeaways:**\n1. Module Federation enables micro-frontend architecture\n2. Hosts consume modules from remotes at runtime\n3. Shared dependencies are loaded once and reused across apps' },
      { id: 'mf-webpack', title: 'Webpack Configuration', content: '**Host Configuration:**\n```javascript\n// host/webpack.config.js\nconst { ModuleFederationPlugin } = require(\'webpack\').container;\n\nmodule.exports = {\n  plugins: [\n    new ModuleFederationPlugin({\n      name: \'host\',\n      remotes: {\n        dashboard: \'dashboard@http://localhost:3001/remoteEntry.js\'\n      },\n      shared: {\n        react: { singleton: true, requiredVersion: \'^18.0.0\' },\n        \'react-dom\': { singleton: true }\n      }\n    })\n  ]\n};\n```\n\n**Remote Configuration:**\n```javascript\n// remote/webpack.config.js\nconst { ModuleFederationPlugin } = require(\'webpack\').container;\n\nmodule.exports = {\n  plugins: [\n    new ModuleFederationPlugin({\n      name: \'dashboard\',\n      filename: \'remoteEntry.js\',\n      exposes: {\n        \'./Dashboard\': \'./src/components/Dashboard\'\n      },\n      shared: {\n        react: { singleton: true, requiredVersion: \'^18.0.0\' }\n      }\n    })\n  ]\n};\n```\n\n**Consuming Remote Modules:**\n```typescript\n// In host app\nconst Dashboard = React.lazy(() => import(\'dashboard/Dashboard\'));\n\nfunction App() {\n  return (\n    <Suspense fallback={<div>Loading...</div>}>\n      <Dashboard />\n    </Suspense>\n  );\n}\n```\n\n**Key Takeaways:**\n1. Hosts declare remotes and shared dependencies\n2. Remotes expose specific modules via the `exposes` config\n3. Use `singleton: true` for frameworks to avoid duplicate instances' },
      { id: 'mf-deployment', title: 'Deployment & Versioning', content: '**Deployment Strategy:**\n\nEach micro-frontend is independently deployed:\n```\n1. Deploy remote app (updates remoteEntry.js)\n2. Host app picks up changes on next page load\n3. No redeployment of host needed\n```\n\n**Version Management:**\n```javascript\nshared: {\n  react: {\n    singleton: true,\n    requiredVersion: \'^18.0.0\',  // Accept semver range\n    eager: false                   // Lazy load if not available\n  }\n}\n```\n\n**Common Challenges:**\n- Shared dependency version conflicts\n- Styling isolation between micro-frontends\n- Shared state management across apps\n- Error handling when remotes are unavailable\n\n**Best Practices:**\n- Use singleton mode for React/Angular to avoid multiple instances\n- Set requiredVersion to allow minor version flexibility\n- Implement fallback UI for when remotes fail to load\n- Use CSS scoping (Shadow DOM or naming conventions) for style isolation\n\n**Key Takeaways:**\n1. Each micro-frontend can be deployed independently\n2. Use singleton: true for framework dependencies\n3. Handle remote failures gracefully with fallback UIs' }
    ]
  },
  {
    id: 611, slug: 'tooling-custom-vite-plugins', title: 'Custom Vite Plugins',
    description: 'Build custom Vite plugins — hook into the build lifecycle, transform files, and extend dev server capabilities.',
    level: 'advanced', duration: '35 min',
    objectives: ['Understand the Vite plugin hook lifecycle', 'Write plugins that transform source files', 'Create plugins that modify the dev server', 'Debug and test custom Vite plugins'],
    quiz: [
      { id: 1, question: 'Which Vite plugin hook is called for every file during the build?', options: ['configureServer', 'transform', 'buildStart', 'closeBundle'], correctIndex: 1, explanation: 'The transform hook is called for every module that Vite processes, allowing you to modify its content.' },
      { id: 2, question: 'What does the "resolveId" hook do?', options: ['Transforms file content', 'Resolves a module ID to its file path', 'Generates HTML output', 'Cleans the build directory'], correctIndex: 1, explanation: 'resolveId lets you customize how module specifiers are resolved to file paths or virtual modules.' },
      { id: 3, question: 'How do you create a virtual module in a Vite plugin?', options: ['Use the "virtual" prefix in the file path', 'Return a path from resolveId and handle it in load', 'Create a temporary file on disk', 'Use the virtualModules option'], correctIndex: 1, explanation: 'Virtual modules are created by intercepting resolveId to return a virtual ID, then handling it in the load hook.' }
    ],
    topics: [
      { id: 'plugin-hooks', title: 'Plugin Hook Lifecycle', content: '**Vite Plugin Hooks:**\n```typescript\nimport { Plugin } from \'vite\';\n\nexport default function examplePlugin(): Plugin {\n  return {\n    name: \'example-plugin\',\n\n    // Config modification\n    config(config, { command }) {\n      return { define: { __APP_VERSION__: JSON.stringify(\'1.0\') } };\n    },\n\n    // Resolve module IDs\n    resolveId(source, importer) {\n      if (source === \'virtual:config\') {\n        return \'\\0virtual:config\';  // \\0 prefix marks virtual modules\n      }\n    },\n\n    // Load resolved modules\n    load(id) {\n      if (id === \'\\0virtual:config\') {\n        return `export default { env: \'${process.env.NODE_ENV}\' }`;\n      }\n    },\n\n    // Transform file content\n    transform(code, id) {\n      if (id.endsWith(\'.vue\')) {\n        return transformVueFile(code);\n      }\n    },\n\n    // Dev server only\n    configureServer(server) {\n      server.middlewares.use(\'/api/status\', (req, res) => {\n        res.end(JSON.stringify({ status: \'ok\' }));\n      });\n    }\n  };\n}\n```\n\n**Key Takeaways:**\n1. Hook execution follows a specific order: config -> resolveId -> load -> transform\n2. Virtual modules use the \\0 prefix convention\n3. configureServer only runs during development' },
      { id: 'plugin-transform', title: 'File Transformation', content: '**Custom File Transformation:**\n\n```typescript\nimport { Plugin } from \'vite\';\n\nexport default function yamlPlugin(): Plugin {\n  return {\n    name: \'vite-plugin-yaml\',\n    transform(code, id) {\n      if (!id.endsWith(\'.yaml\') && !id.endsWith(\'.yml\')) {\n        return null;  // Skip non-YAML files\n      }\n\n      const yaml = require(\'js-yaml\');\n      const parsed = yaml.load(code);\n\n      return {\n        code: `export default ${JSON.stringify(parsed)}`,\n        map: null  // Source map (optional)\n      };\n    }\n  };\n}\n```\n\n**Usage in vite.config.ts:**\n```typescript\nimport yamlPlugin from \'./plugins/vite-plugin-yaml\';\n\nexport default defineConfig({\n  plugins: [yamlPlugin()]\n});\n```\n\n**Now you can import YAML files:**\n```typescript\nimport config from \'./config.yaml\';\nconsole.log(config.database.host);\n```\n\n**Key Takeaways:**\n1. Return null from transform to skip files you don\'t handle\n2. Always return both code and source map from transform\n3. Use the \\0 prefix when creating virtual module IDs' },
      { id: 'plugin-testing', title: 'Testing & Debugging Plugins', content: '**Testing a Vite Plugin:**\n```typescript\nimport { describe, it, expect } from \'vitest\';\nimport yamlPlugin from \'./vite-plugin-yaml\';\n\ndescribe(\'yamlPlugin\', () => {\n  it(\'should transform YAML to JS module\', () => {\n    const plugin = yamlPlugin();\n    const yamlContent = \'name: test\\nversion: 1.0\';\n\n    const result = plugin.transform!(yamlContent, \'config.yaml\');\n\n    expect(result).not.toBeNull();\n    expect(result!.code).toContain(\'export default\');\n    expect(result!.code).toContain(\'name\');\n  });\n\n  it(\'should skip non-YAML files\', () => {\n    const plugin = yamlPlugin();\n    const result = plugin.transform!(\'const x = 1;\', \'app.ts\');\n    expect(result).toBeNull();\n  });\n});\n```\n\n**Debugging Tips:**\n- Use `console.log` in plugin hooks (output appears in terminal)\n- Enable `DEBUG=vite:*` environment variable for verbose logging\n- Use `vite build --debug` to see plugin execution details\n\n**Key Takeaways:**\n1. Test transform hooks by calling them directly with mock data\n2. Return null for files the plugin should not handle\n3. Use DEBUG=vite:* for verbose plugin logging' }
    ]
  },
  {
    id: 612, slug: 'tooling-build-optimization', title: 'Build Optimization',
    description: 'Optimize your production builds — minification, tree-shaking, code splitting, and bundle analysis techniques.',
    level: 'advanced', duration: '30 min',
    objectives: ['Analyze and reduce bundle size using visualization tools', 'Implement effective tree-shaking strategies', 'Configure code splitting for optimal loading performance', 'Apply advanced minification and compression techniques'],
    quiz: [
      { id: 1, question: 'What tool visualizes the contents of your JavaScript bundles?', options: ['webpack-bundle-analyzer', 'ESLint', 'Prettier', 'TypeScript Compiler'], correctIndex: 0, explanation: 'webpack-bundle-analyzer creates an interactive treemap visualization of your bundle contents, showing what takes up space.' },
      { id: 2, question: 'What is "tree-shaking" most effective with?', options: ['CommonJS require()', 'ES Module import/export', 'Dynamic imports', 'Global variables'], correctIndex: 1, explanation: 'Tree-shaking works with ES Modules because their static import/export structure allows bundlers to determine unused code at build time.' },
      { id: 3, question: 'Which technique splits code so users only download what they need for the current route?', options: ['Minification', 'Tree-shaking', 'Lazy loading / Code splitting', 'Source maps'], correctIndex: 2, explanation: 'Code splitting with lazy loading ensures users only download JavaScript needed for the current route or feature.' }
    ],
    topics: [
      { id: 'bundle-analysis', title: 'Bundle Analysis', content: '**Tools for Analyzing Bundles:**\n\n```bash\n# Webpack Bundle Analyzer\nnpm install --save-dev webpack-bundle-analyzer\n\n# For Vite\nnpm install --save-dev rollup-plugin-visualizer\n```\n\n**Vite Bundle Analysis:**\n```typescript\n// vite.config.ts\nimport { visualizer } from \'rollup-plugin-visualizer\';\n\nexport default defineConfig({\n  plugins: [\n    visualizer({\n      open: true,\n      filename: \'bundle-stats.html\',\n      gzipSize: true\n    })\n  ]\n});\n```\n\n**What to Look For:**\n- Large unexpected libraries (e.g., moment.js with all locales)\n- Duplicate packages (lodash + lodash-es)\n- Unused dependencies\n- Large assets (images, fonts)\n\n**Key Takeaways:**\n1. Run bundle analysis regularly to catch size regressions\n2. Look for duplicate packages and large unexpected dependencies\n3. Use gzip/brotli size in analysis for realistic comparisons' },
      { id: 'tree-shaking-advanced', title: 'Advanced Tree-Shaking', content: '**Tree-Shaking Best Practices:**\n\n```typescript\n// BAD - Imports entire library\nimport _ from \'lodash\';\n_.debounce(fn, 300);\n\n// GOOD - Import specific function\nimport debounce from \'lodash/debounce\';\ndebounce(fn, 300);\n\n// BEST - Use tree-shakeable library\nimport { debounce } from \'lodash-es\';\ndebounce(fn, 300);\n```\n\n**Side Effects Configuration:**\n```json\n// package.json\n{\n  "sideEffects": false\n}\n\n// Or specify files with side effects\n{\n  "sideEffects": ["*.css", "./src/polyfills.ts"]\n}\n```\n\n**Common Tree-Shaking Killers:**\n- Dynamic `require()` calls\n- Side effects in module scope\n- Using `/* @__PURE__ */` comments for side-effect-free functions\n\n**Key Takeaways:**\n1. Use named imports over default imports for better tree-shaking\n2. Set `sideEffects: false` in package.json to enable deeper optimization\n3. Prefer lodash-es over lodash for tree-shakeable imports' },
      { id: 'code-splitting-advanced', title: 'Advanced Code Splitting', content: '**Route-Based Splitting (Angular):**\n```typescript\n// app.routes.ts\nexport const routes: Routes = [\n  {\n    path: \'dashboard\',\n    loadComponent: () => import(\'./dashboard/dashboard.component\')\n      .then(m => m.DashboardComponent)\n  },\n  {\n    path: \'settings\',\n    loadComponent: () => import(\'./settings/settings.component\')\n      .then(m => m.SettingsComponent)\n  }\n];\n```\n\n**Vendor Chunk Splitting:**\n```javascript\n// Vite\nexport default defineConfig({\n  build: {\n    rollupOptions: {\n      output: {\n        manualChunks: {\n          vendor: [\'@angular/core\', \'@angular/common\'],\n          utils: [\'lodash-es\', \'date-fns\']\n        }\n      }\n    }\n  }\n});\n```\n\n**Preload & Prefetch Hints:**\n```html\n<!-- Preload critical chunks -->\n<link rel="modulepreload" href="/assets/dashboard.js">\n\n<!-- Prefetch non-critical chunks -->\n<link rel="prefetch" href="/assets/settings.js">\n```\n\n**Key Takeaways:**\n1. Use dynamic imports for route-based code splitting\n2. Manual chunk splitting improves caching across deploys\n3. Use preload for critical resources, prefetch for anticipated ones' }
    ]
  },
  {
    id: 613, slug: 'tooling-monorepo', title: 'Monorepo Tooling (Nx/Turborepo)',
    description: 'Master monorepo tooling with Nx and Turborepo — workspace configuration, task running, caching, and dependency management.',
    level: 'advanced', duration: '35 min',
    objectives: ['Set up a monorepo workspace with Nx or Turborepo', 'Configure task caching for faster builds', 'Manage dependencies between packages in a monorepo', 'Implement affected-based CI/CD for monorepos'],
    quiz: [
      { id: 1, question: 'What is the primary benefit of task caching in monorepo tools?', options: ['It compresses source files', 'It skips tasks that haven\'t changed based on inputs', 'It removes unused code', 'It generates documentation'], correctIndex: 1, explanation: 'Task caching stores the output of tasks and skips re-running them when inputs (source code, dependencies) haven\'t changed.' },
      { id: 2, question: 'What does "affected" analysis do in Nx?', options: ['Deletes unused packages', 'Identifies which packages were changed and what depends on them', 'Creates dependency graphs', 'Merges branches'], correctIndex: 1, explanation: 'Affected analysis determines which projects were modified and which other projects are impacted by those changes.' },
      { id: 3, question: 'How does Turborepo achieve parallel task execution?', options: ['It uses Web Workers', 'It runs independent tasks concurrently while respecting dependency order', 'It requires multiple CPUs', 'It compiles everything at once'], correctIndex: 1, explanation: 'Turborepo analyzes the task dependency graph and runs independent tasks in parallel, while sequentializing dependent tasks.' }
    ],
    topics: [
      { id: 'nx-overview', title: 'Nx Workspace', content: '**Setting Up Nx:**\n```bash\n# Create new Nx workspace\nnpx create-nx-workspace@latest my-monorepo\n\n# Add Angular plugin\nnx add @nx/angular\n\n# Generate a library\nnx generate @nx/angular:library shared-ui\n\n# Generate an application\nnx generate @nx/angular:application my-app\n```\n\n**nx.json Configuration:**\n```json\n{\n  "targetDefaults": {\n    "build": {\n      "dependsOn": ["^build"],\n      "cache": true\n    },\n    "test": {\n      "cache": true\n    },\n    "lint": {\n      "cache": true\n    }\n  },\n  "defaultBase": "main"\n}\n```\n\n**Project Structure:**\n```\nmy-monorepo/\n  apps/\n    my-app/\n    my-app-e2e/\n  libs/\n    shared-ui/\n    shared-utils/\n  tools/\n  nx.json\n  tsconfig.base.json\n```\n\n**Key Takeaways:**\n1. Nx provides a complete monorepo toolkit with code generation\n2. Target defaults in nx.json configure caching and dependencies\n3. Libs contain shared code; apps contain deployable applications' },
      { id: 'turborepo', title: 'Turborepo', content: '**Setting Up Turborepo:**\n```bash\n# Create new Turborepo\nnpx create-turbo@latest my-monorepo\n\n# Or add to existing monorepo\nnpm install turbo --save-dev\n```\n\n**turbo.json Configuration:**\n```json\n{\n  "$schema": "https://turbo.build/schema.json",\n  "tasks": {\n    "build": {\n      "dependsOn": ["^build"],\n      "outputs": ["dist/**"],\n      "cache": true\n    },\n    "test": {\n      "dependsOn": ["build"],\n      "cache": true\n    },\n    "lint": {\n      "cache": true\n    },\n    "dev": {\n      "cache": false,\n      "persistent": true\n    }\n  }\n}\n```\n\n**Running Tasks:**\n```bash\n# Run build for all packages\nnpx turbo run build\n\n# Run with cache\nnpx turbo run build --cache=local\n\n# Run only affected packages\nnpx turbo run build --filter=...[HEAD~1]\n```\n\n**Key Takeaways:**\n1. Turborepo is simpler to set up than Nx — focuses on task running and caching\n2. The `outputs` field tells Turborepo what to cache\n3. `dependsOn: ["^build"]` ensures dependencies build first' },
      { id: 'monorepo-caching', title: 'Caching Strategies', content: '**Local Caching:**\n```bash\n# Nx - local cache in .nx/cache\ncache: true  # in targetDefaults\n\n# Turborepo - local cache in node_modules/.cache/turbo\nnpx turbo run build --cache=local\n```\n\n**Remote Caching (Turborepo):**\n```json\n// turbo.json\n{\n  "remoteCache": {\n    "signature": true  // Verify cache integrity\n  }\n}\n```\n\n```bash\n# Enable remote caching\nnpx turbo login\nnpx turbo run build --cache=remote\n```\n\n**Remote Caching (Nx Cloud):**\n```bash\n# Connect to Nx Cloud\nnpx nx connect-to-nx-cloud\n\n# Run with remote caching\nnpx nx run-many --target=build --all\n```\n\n**Cache Invalidation:**\n- Source code changes invalidate task cache\n- Dependency changes invalidate downstream caches\n- Environment variable changes can invalidate cache\n\n**Key Takeaways:**\n1. Local caching speeds up repeated builds on the same machine\n2. Remote caching shares build artifacts across team and CI/CD\n3. Cache invalidation is based on inputs — source, dependencies, environment' },
      { id: 'monorepo-ci', title: 'CI/CD for Monorepos', content: '**Affected-Only CI Strategy:**\n```yaml\n# GitHub Actions example\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with:\n          fetch-depth: 0  # Full history for affected analysis\n\n      - name: Install dependencies\n        run: pnpm install --frozen-lockfile\n\n      - name: Build affected packages\n        run: npx nx run-many --target=build --affected\n\n      - name: Test affected packages\n        run: npx nx run-many --target=test --affected\n\n      - name: Deploy\n        run: npx nx affected --target=deploy --configuration=production\n```\n\n**Key CI/CD Principles:**\n1. Only build/test what changed (affected analysis)\n2. Use remote caching to share build artifacts\n3. Parallelize independent tasks\n4. Use task graphs to determine execution order\n\n**Common CI Mistakes:**\n- Building everything on every PR (wasteful)\n- Not using remote caching in CI\n- Missing `fetch-depth: 0` for git history analysis\n\n**Key Takeaways:**\n1. Use affected analysis to only build/test changed packages\n2. Enable remote caching in CI for dramatic speed improvements\n3. Set fetch-depth: 0 for proper change detection' }
    ]
  },
  {
    id: 614, slug: 'tooling-docker-frontend', title: 'Docker for Frontend',
    description: 'Containerize frontend applications with Docker — multi-stage builds, optimization, and development workflows.',
    level: 'advanced', duration: '30 min',
    objectives: ['Write optimized multi-stage Dockerfiles for frontend apps', 'Configure Docker Compose for local development', 'Implement caching strategies for faster builds', 'Debug and optimize Docker images for production'],
    quiz: [
      { id: 1, question: 'Why use multi-stage builds in Docker for frontend apps?', options: ['They make the image smaller by separating build and runtime', 'They run multiple containers simultaneously', 'They enable Docker Swarm', 'They add more CPU cores'], correctIndex: 0, explanation: 'Multi-stage builds keep build tools (node_modules, dev dependencies) out of the final image, reducing size significantly.' },
      { id: 2, question: 'Which Docker instruction copies package.json into the image?', options: ['COPY . .', 'COPY package*.json ./', 'ADD package.json', 'INSTALL package.json'], correctIndex: 1, explanation: 'COPY package*.json ./ copies both package.json and package-lock.json, enabling dependency caching before copying source code.' },
      { id: 3, question: 'What is the purpose of .dockerignore?', options: ['To ignore Docker errors', 'To exclude files from the Docker build context', 'To ignore container logs', 'To skip Docker Hub authentication'], correctIndex: 1, explanation: '.dockerignore excludes files like node_modules and .git from the build context, speeding up builds and reducing image size.' }
    ],
    topics: [
      { id: 'dockerfile', title: 'Dockerfile for Frontend', content: '**Multi-Stage Dockerfile:**\n```dockerfile\n# Stage 1: Build\nFROM node:20-alpine AS builder\nWORKDIR /app\n\n# Cache dependencies\nCOPY package*.json ./\nRUN npm ci --only=production\n\n# Copy source and build\nCOPY . .\nRUN npm run build\n\n# Stage 2: Serve\nFROM nginx:alpine\nCOPY --from=builder /app/dist/my-app /usr/share/nginx/html\nCOPY nginx.conf /etc/nginx/conf.d/default.conf\n\nEXPOSE 80\nCMD ["nginx", "-g", "daemon off;"]\n```\n\n**Why Multi-Stage:**\n- Final image is nginx (~25MB) instead of node (~300MB+)\n- No node_modules, source code, or dev tools in production\n- Better security — smaller attack surface\n\n**Key Takeaways:**\n1. Multi-stage builds reduce final image size by 80-90%\n2. Copy package.json first for better Docker layer caching\n3. Use alpine variants for smaller base images' },
      { id: 'docker-caching', title: 'Docker Layer Caching', content: '**Caching Strategy:**\n```dockerfile\n# Good: package.json copied before source code\nCOPY package*.json ./\nRUN npm ci          # Cached if package.json unchanged\n\nCOPY . .            # Only this layer rebuilds on code changes\nRUN npm run build\n```\n\n**Bad: Everything copied at once**\n```dockerfile\n# Bad: Any source change invalidates npm ci cache\nCOPY . .\nRUN npm ci && npm run build\n```\n\n**.dockerignore:**\n```\nnode_modules\n.git\ndist\ncoverage\n.env\n*.md\n.vscode\n```\n\n**Build with cache:**\n```bash\n# Use cache from previous builds\ndocker build --cache-from my-app:latest -t my-app:new .\n```\n\n**Key Takeaways:**\n1. Order Dockerfile instructions from least to most frequently changing\n2. Always use .dockerignore to exclude unnecessary files\n3. Use --cache-from to leverage caches from other builds' },
      { id: 'docker-compose', title: 'Docker Compose for Development', content: '**docker-compose.yml:**\n```yaml\nversion: \'3.8\'\nservices:\n  frontend:\n    build:\n      context: .\n      dockerfile: Dockerfile.dev\n    ports:\n      - "4200:4200"\n    volumes:\n      - .:/app\n      - /app/node_modules  # Anonymous volume (preserve node_modules)\n    environment:\n      - NODE_ENV=development\n      - API_URL=http://localhost:3000\n    command: npm start\n\n  api:\n    image: my-api:latest\n    ports:\n      - "3000:3000"\n```\n\n**Development Dockerfile:**\n```dockerfile\nFROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 4200\nCMD ["npm", "start"]\n```\n\n**Key Takeaways:**\n1. Use anonymous volumes to preserve node_modules during development\n2. Mount source code as a volume for hot reload\n3. docker-compose.yml defines the full development environment' }
    ]
  },
  {
    id: 615, slug: 'tooling-cicd-pipelines', title: 'CI/CD Pipelines',
    description: 'Build robust CI/CD pipelines for frontend applications — automated testing, building, deployment, and monitoring.',
    level: 'advanced', duration: '35 min',
    objectives: ['Design a complete CI/CD pipeline for a frontend application', 'Configure automated testing and quality gates', 'Implement deployment strategies (blue-green, canary)', 'Set up rollback and monitoring procedures'],
    quiz: [
      { id: 1, question: 'What is the difference between CI and CD?', options: ['CI builds code, CD compiles code', 'CI integrates code changes frequently, CD delivers to production', 'They are the same thing', 'CI is manual, CD is automatic'], correctIndex: 1, explanation: 'CI (Continuous Integration) involves frequently merging code changes with automated testing. CD (Continuous Delivery/Deployment) automates the release process.' },
      { id: 2, question: 'What is a "quality gate" in CI/CD?', options: ['A physical gate in the data center', 'A set of conditions that must be met before code is merged', 'A firewall rule', 'A Docker network configuration'], correctIndex: 1, explanation: 'Quality gates are automated checks (test coverage, lint, build success) that must pass before code can be merged or deployed.' },
      { id: 3, question: 'What is a blue-green deployment?', options: ['Deploying to two different cloud providers', 'Maintaining two identical environments and switching traffic between them', 'Using blue and green colors in the UI', 'Running tests on blue and green servers'], correctIndex: 1, explanation: 'Blue-green deployment maintains two production environments — current (blue) and new (green). Traffic switches to green after verification.' }
    ],
    topics: [
      { id: 'ci-pipeline', title: 'CI Pipeline Design', content: '**GitHub Actions CI Pipeline:**\n```yaml\nname: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm ci\n      - run: npm run lint\n      - run: npm run typecheck\n\n  test:\n    needs: lint\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm ci\n      - run: npm run test -- --coverage\n      - uses: codecov/codecov-action@v4\n        with:\n          file: ./coverage/lcov.info\n\n  build:\n    needs: test\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm ci\n      - run: npm run build\n      - uses: actions/upload-artifact@v4\n        with:\n          name: build-output\n          path: dist/\n```\n\n**Key Takeaways:**\n1. Run linting before tests for fast feedback\n2. Use caching (npm cache, node_modules) to speed up CI\n3. Upload build artifacts for deployment stages' },
      { id: 'cd-pipeline', title: 'CD Pipeline Design', content: '**Deployment Pipeline (GitHub Actions):**\n```yaml\n  deploy-staging:\n    needs: build\n    runs-on: ubuntu-latest\n    environment: staging\n    steps:\n      - uses: actions/download-artifact@v4\n        with:\n          name: build-output\n          path: dist/\n      - name: Deploy to Staging\n        run: |\n          firebase deploy --only hosting --project staging\n        env:\n          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}\n\n  e2e-staging:\n    needs: deploy-staging\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci\n      - run: npx playwright test --project=staging\n\n  deploy-production:\n    needs: e2e-staging\n    runs-on: ubuntu-latest\n    environment: production\n    steps:\n      - name: Deploy to Production\n        run: firebase deploy --only hosting --project production\n```\n\n**Deployment Strategies:**\n- **Rolling**: Gradually replace old instances with new ones\n- **Blue-Green**: Switch traffic between two identical environments\n- **Canary**: Roll out to a small percentage of users first\n\n**Key Takeaways:**\n1. Always run E2E tests against staging before production deploy\n2. Use GitHub environments for approval gates\n3. Canary deployments reduce risk of bad deploys' },
      { id: 'quality-gates', title: 'Quality Gates & Monitoring', content: '**Quality Gates Configuration:**\n```yaml\n# In your CI pipeline\nquality-gate:\n  steps:\n    - name: Check test coverage\n      run: |\n        COVERAGE=$(cat coverage/coverage-summary.json | jq \'.total.lines.pct\')\n        if (( $(echo "$COVERAGE < 80" | bc -l) )); then\n          echo "Coverage $COVERAGE% is below 80% threshold"\n          exit 1\n        fi\n\n    - name: Bundle size check\n      run: |\n        BUNDLE_SIZE=$(wc -c < dist/main.js)\n        if [ $BUNDLE_SIZE -gt 250000 ]; then\n          echo "Bundle size ${BUNDLE_SIZE} exceeds 250KB limit"\n          exit 1\n        fi\n\n    - name: Lighthouse audit\n      run: npx lhci autorun\n```\n\n**Post-Deploy Monitoring:**\n- **Real User Monitoring (RUM)**: Track Core Web Vitals in production\n- **Error Tracking**: Sentry, Datadog for runtime errors\n- **Uptime Monitoring**: Pingdom, UptimeRobot for availability\n\n**Rollback Procedures:**\n```bash\n# Quick rollback (revert to previous deployment)\nnpx firebase hosting:channel:rollback\n\n# Docker rollback\ndocker rollback <service-name>\n```\n\n**Key Takeaways:**\n1. Set minimum coverage thresholds (80%+) as quality gates\n2. Monitor bundle size to prevent bloat\n3. Have a documented rollback procedure for every deployment' }
    ]
  }
];
